from pathlib import Path
import json
R=Path(__file__).resolve().parent.parent;ps=json.loads((R/'prototype/page-manifest.json').read_text())
# Every row ties a page to a concrete screen contract and implementable work.
M={
'login':('subpackages/auth/pages/login/index','AuthStateMachine','BrandIntro / FormField / ConsentRow','MP01-T03-02 MP01-T03-03 MP01-T03-04','E auth/login、auth/refresh、auth/me；N auth/wechat/mini/login/bind','账号非空；密码不入日志；协议需主动阅读并确认；不要求手机号','匿名→微信认证→已绑定/待绑定→平台登录态；绑定证明两侧身份','code过期重新认证；账号冲突不自动合并；注册关闭说明原因'),
'workspace':('subpackages/auth/pages/workspace/index','WorkspaceSelection','WorkspaceCard / RadioIndicator / Notice','MP01-T03-04 MP01-T02-06','E auth/me、auth/switch-tenant、tenants、me/invitations','选项仅来自真实membership；role按服务端返回展示','单选→点击进入→冻结写入→切换成功→新scope首页','无空间引导创建/邀请；失败保留原空间；旧回包不能覆盖新空间'),
'home':('pages/home/index','HomeViewModel','IntentComposer / AgentCard / AttentionCard / RecentConversation','MP01-T01-05 MP03-T01-03','E 会话/Agent/商业API；N inbox；home聚合可选，不强制新增','任务意图先保存在当前scope草稿；点击后到助手确认，不直接发起','输入想法→选择助手→确认任务；待办→审批；会话→聊天','单卡请求失败独立降级；无运行能力仍可使用已开放知识问答'),
'agents':('subpackages/agents/pages/list/index','AgentCatalogViewModel','SearchField / SegmentedControl / AgentCard','MP01-T01-05 MP03-T01-04','E 共享Agent配置API；N launch-options；具体既有URL由MP00固定','关键词trim且长度有界；筛选与scope写入查询键','搜索/筛选→打开可用助手；不可用→说明原因','空结果与未安装/无权/目标离线分开；不让用户填写内部target'),
'agent':('subpackages/agents/pages/detail/index','LaunchStateMachine','AgentHero / TaskForm / ScopeSummary / BudgetInput','MP03-T02-01 MP03-T01-04 MP01-T02-07','E POST workbench/executions、GET executions/requests/:request_id；N launch-options','text非空；预算按服务器单位/步长/范围；target/workspace来自授权选项','编辑→校验→持久化意图→提交→接纳或原request_id对账','双击不重复；未知状态不换ID；选项失效重读并重新确认'),
'chat':('subpackages/chat/pages/thread/index','ChatViewModel','AssistantMessage / CitationCard / ChatComposer / AttachmentItem','MP02-T01-01 MP02-T01-02 MP02-T01-03','E sessions、messages、knowledge-chat/agent-chat、attachments','输入非空；附件限定当前session；Markdown转受控节点','用户发送→分片输出→完结格式化；引用→授权原文；停止→结束本地输出','断流显示未完成；权限撤销不读缓存；不当成durable任务重启'),
'tasks':('pages/tasks/index','TaskPageViewModel','TaskStats / StatusFilter / TaskCard','MP03-T01-02 MP03-T01-03 MP03-T02-04','N GET workbench/executions；N inbox；E 单run详情','状态筛选采用已确认enum；cursor与filter/scope匹配','首屏→游标分页→筛选重置；待确认→审批；新建→Agent','空/无权/未装配/离线缓存区分；不以本机记录当全量任务'),
'execution':('subpackages/execution/pages/detail/index','ExecutionViewModel','ExecutionHero / Timeline / ApprovalCard / CommandSheet','MP03-T02-03 MP03-T02-04 MP03-T02-06','E run/get、snapshot、events、interactions、commands','run来自授权资源；命令带expected_revision；步骤只包含安全摘要','进入先快照后事件；断线→同run恢复；steer/cancel二次确认','gap/过期游标/未知schema重同步；已终态不再执行危险命令'),
'approval':('subpackages/execution/pages/approval/index','DecisionViewModel','RiskIntro / ActionSummary / ParameterPreview / ConfirmSheet','MP03-T02-05','E 单run interactions；POST interactions/:id/decisions','目标、影响、参数脱敏；真实decision类型及当前版本；拒绝理由有界','待处理→二次确认→提交中→通过/拒绝；关闭弹窗不写入','过期/他端已处理/版本冲突刷新；无永久放行；预算不等于外部授权'),
'artifact':('subpackages/execution/pages/artifact/index','ArtifactViewModel','FileCover / SafeTextPreview / DownloadAction','MP03-T02-07 MP01-T02-04','E sessions/message artifacts及授权download，关联按实际schema','文件类型MIME和扩展联合校验；不运行HTML/JS','从任务→重新授权读产物→安全预览或系统下载','过期删除撤权显示原因；无长期公开地址；跨run映射不猜测'),
'knowledge':('pages/knowledge/index','KnowledgeListViewModel','KnowledgeSearch / KnowledgeCard / RecentDocument','MP02-T02-01','E 知识库共享API与domain筛选','筛选我的/空间/共享按真实权限；关键词加入scope查询键','选择库→文档列表；搜索→同范围结果；问答→指定授权库','共享只读库无导入；不存在/无权/空库区分'),
'kb':('subpackages/documents/pages/kb/index','KnowledgeDetailViewModel','KnowledgeHeader / DocumentRow / ProcessingBadge','MP02-T02-01 MP02-T02-03','E 库内文档与处理状态API','文档状态真实映射；上传按钮依赖该库写权限','基于此库提问→聊天；导入→目标已选；文档→授权详情','upload成功仍parsing；失败保留原因；权限变化刷新'),
'upload':('subpackages/documents/pages/import/index','UploadStateMachine','TargetCard / FilePicker / URLField / ProcessingCard','MP02-T02-02 MP02-T02-03 MP01-T02-04','E 知识upload/import；A Taro.uploadFile/native port','文件类型大小由服务端配置；URL只做初筛，后端最终防SSRF','选择→确认目标→上传→解析→ready；解析中允许离开','未知上传结果不重复创建；解析失败不显示成功；临时附件不自动入库'),
'document':('subpackages/documents/pages/detail/index','DocumentReferenceViewModel','DocumentMeta / HighlightQuote / SafePreview','MP02-T02-04','E 授权文档/preview与引用领域映射','来源位置仅用真实locator；显示更新和权限差异','从引用打开→定位片段→看上下文→基于文档提问','删除/撤权/版本变化说明；无位置不伪造页码；外部链接不直接跳'),
'me':('pages/me/index','ProfileViewModel','ProfileHeader / WorkspaceRow / UsageSummary / AccountMenu','MP04-T01-01 MP01-T03-05','E auth/me、commercial/summary、orders、me/invitations','用户和空间职责分开；用量字符串格式化；不从角色猜计费权','切空间→选择页；用量/订单/邀请→对应页；退出需确认','stale标统计时点；退出清凭证缓存和请求；不假称撤销服务端已完成'),
'usage':('subpackages/account/pages/usage/index','UsageAndPlansViewModel','UsageCard / UsageTrend / PlanCard / AvailabilityNotice','MP04-T01-01 MP04-T01-02','E summary/plans/usage/quotes；N 通道可用性','available/held/refund_locked独立；真实价格/单位不可硬编码','查看明细→选计划→服务端报价；无权仅只读','未核验通道说明原因；过期价格不下单；历史数据有as_of'),
'checkout':('subpackages/account/pages/checkout/index','CheckoutViewModel','PlanSummary / QuoteDetails / PurchaseAvailability / PayCTA','MP04-T01-02 MP04-T01-03 MP04-T01-04','E quotes/orders；N 严格typed channel checkout','quote_id有效且版本匹配；空间商品金额来自服务端','确认→幂等订单→获准收银→原订单查询；默认不可购买','报价过期重取；取消/未知不新建单；客户端不算价格和权益'),
'order':('subpackages/account/pages/order/index','OrderViewModel','PaymentStep / FulfillmentStep / OrderDetails','MP04-T01-04 MP04-T01-05','E commercial/orders/:id；OrderView.payment/fulfillment','order_id当前主体有权；付款和履约分别映射真实enum','待付款确认→已付款未履约→服务端fulfilled→返回用量','延迟/attention/退款按服务器结果；重查原订单不重复购买'),
'invitations':('subpackages/account/pages/invitations/index','InvitationsViewModel','InviteCard / RoleSummary / AcceptDecline','MP01-T03-05 MP04-T02-03','E me/invitations、accept/decline、accept-by-token','token只定位并验证邀请；真实受邀用户、角色、状态','匿名先登录；接受后刷新membership再选择空间；拒绝回列表','过期撤销不能接受；他人邀请不操作；接受不是全资源授权'),
'states':('subpackages/system/pages/state/index','AppStateViewModel','StateIllustration / ReasonText / RecoveryAction','MP01-T01-04 MP04-T03-03','E ApiError和capabilities；N完整原因码映射','错误不暴露堆栈或凭证；request_id可复制且不含机密','六类状态分别提供正确动作；重试仅对应幂等读取','不可把503/403当空；断流恢复不创建新run；登录回跳需白名单')}
out=['# 04｜20页详细设计与开发映射','', '本文件沿用上版20页信息架构。每页对应原型、Taro路由、ViewModel、组件、API、校验、状态和任务编号。', '', '## 全局页面合同','', '统一遵循03的tokens与触点；主Tab显示底栏，聊天/审批使用独立底部操作区；真实胶囊与键盘尺寸由平台层提供。服务端数据、UI状态和本地恢复记录分层；所有写动作先校验当前scope、权限与capability。', '', '| 页面 | Taro路由 | 主要任务 |','|---|---|---|']
for p in ps:
 m=M[p['id']];out.append(f"| P{p['n']} {p['name']} | `{m[0]}` | {m[3]} |")
for p in ps:
 route,vm,comp,task,api,fields,flow,edge=M[p['id']]
 out += ['',f"## P{p['n']}｜{p['name']}",'',f"**原型：**`prototype/pages/{p['file']}`；**Taro路由：**`{route}`。",f"\n**目标：**{p['goal']}",f"\n**布局：**{p['layout']}",f"\n**组件：**{comp}。",f"\n**状态模型：**{vm}。读取支持loading/ready/refreshing/empty/error；业务状态不能压缩成一个loading布尔值。",f"\n**字段与校验：**{fields}。",f"\n**接口合同：**{api}。N为新增；E/A按固定源码适配，不代表本轮后端已实现。",f"\n**交互顺序：**{flow}。",f"\n**异常与边界：**{edge}。",f"\n**权限：**{p['permission']}",f"\n**任务映射：**{task}。",'', '**独立验收：**','',f"1. 按“{flow}”完成正常路径，确认导航、文案和状态对应实际接口。",f"2. 注入“{edge}”，不发生隐式重复写、越权展示或误报成功。",'3. 验证320/375/390/430宽度、长文案、底部安全区、焦点/触点，以及切空间后的旧回包隔离。', '', '**原型与生产差异：**原型以本地状态示范流程；没有真实请求、权限、队列、计费和微信SDK。开发时替换feature数据源，不把demo开关/固定账号/价格/任务号带入生产。']
(R/'docs/04-页面详细设计.md').write_text('\n'.join(out)+'\n')
(R/'prototype/developer-mapping.json').write_text(json.dumps({p['id']:{'route':M[p['id']][0],'viewModel':M[p['id']][1],'components':M[p['id']][2],'tasks':M[p['id']][3].split(),'api':M[p['id']][4]} for p in ps},ensure_ascii=False,indent=2)+'\n')
print('20 page design specs generated')
