package types

import (
	"database/sql/driver"
	"encoding/json"
	"strings"
	"time"
)

// Query history visibility modes, stored on tenants.query_history_config.
const (
	// QueryHistoryModeNormal keeps full transcripts in workspace query history.
	QueryHistoryModeNormal = "normal"
	// QueryHistoryModeAnonymized strips identity before a turn enters history.
	QueryHistoryModeAnonymized = "anonymized"
	// QueryHistoryModeDisabled stops recording new turns into query history.
	QueryHistoryModeDisabled = "disabled"
)

// QueryHistoryExportJob lifecycle statuses.
const (
	QueryHistoryExportPending = "pending"
	QueryHistoryExportRunning = "running"
	QueryHistoryExportDone    = "done"
	QueryHistoryExportFailed  = "failed"
)

// QueryHistoryConfig is the workspace-level query history policy, stored in
// the tenants.query_history_config JSONB column. Nil means "not configured";
// callers normalizing a config they are about to enforce get Mode=normal.
type QueryHistoryConfig struct {
	// Mode is one of the QueryHistoryMode* constants. Empty or unrecognized
	// values normalize to QueryHistoryModeNormal so a corrupt row can never
	// silently disable or de-identify workspace history.
	Mode string `json:"mode" yaml:"mode"`
}

// NormalizeQueryHistoryMode returns the supported mode for the raw value,
// falling back to QueryHistoryModeNormal for empty/unknown input.
func NormalizeQueryHistoryMode(mode string) string {
	switch strings.TrimSpace(mode) {
	case QueryHistoryModeNormal, QueryHistoryModeAnonymized, QueryHistoryModeDisabled:
		return strings.TrimSpace(mode)
	default:
		return QueryHistoryModeNormal
	}
}

// Normalize canonicalizes the config's Mode in place. The nil receiver is a
// no-op so a nil config stays "unconfigured" rather than gaining a default.
func (c *QueryHistoryConfig) Normalize() {
	if c == nil {
		return
	}
	c.Mode = NormalizeQueryHistoryMode(c.Mode)
}

// Value implements the driver.Valuer interface, used to convert
// QueryHistoryConfig to database value.
func (c *QueryHistoryConfig) Value() (driver.Value, error) {
	if c == nil {
		return nil, nil
	}
	return json.Marshal(c)
}

// Scan implements the sql.Scanner interface, used to convert database value
// to QueryHistoryConfig.
func (c *QueryHistoryConfig) Scan(value interface{}) error {
	if value == nil {
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		return nil
	}
	return json.Unmarshal(b, c)
}

// QueryHistoryExportJob tracks one asynchronous query-history export. The
// worker claims pending jobs, streams the archive to FilePath, and leaves
// either done or failed with ErrorMessage set.
type QueryHistoryExportJob struct {
	// ID is generated by the database.
	ID uint64 `json:"id" gorm:"primaryKey;autoIncrement"`
	// TenantID scopes the export to one workspace.
	TenantID uint64 `json:"tenant_id" gorm:"index"`
	// RequestedBy is the principal that asked for the export.
	RequestedBy string `json:"requested_by" gorm:"type:varchar(512)"`
	// Status is one of the QueryHistoryExport* constants.
	Status string `json:"status" gorm:"type:varchar(16);not null;default:'pending'"`
	// FilePath is where the finished archive lives; empty until it exists.
	FilePath string `json:"file_path" gorm:"type:varchar(512);not null;default:''"`
	// ErrorMessage explains a failed export; empty otherwise.
	ErrorMessage string    `json:"error_message" gorm:"type:text;not null;default:''"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// TableName pins the GORM table name.
func (QueryHistoryExportJob) TableName() string { return "query_history_export_jobs" }
