export const designTokens = {
  color: {
    // Vue TDesign light theme primitives. Keep page separate from the React
    // canvas token: the Vue shell uses #eee while migrated surfaces commonly
    // use the lighter #f7f9fc canvas.
    page: '#eeeeee',
    sidebar: '#f9f9f9',
    container: '#ffffff',
    containerHover: '#f3f3f3',
    containerActive: '#e7e7e7',
    secondaryContainer: '#f3f3f3',
    secondaryContainerHover: '#eeeeee',
    secondaryContainerActive: '#dcdcdc',
    component: '#e7e7e7',
    componentHover: '#dcdcdc',
    componentActive: '#a6a6a6',
    componentDisabled: '#eeeeee',
    textPrimary: 'rgba(0, 0, 0, 0.9)',
    textSecondary: 'rgba(0, 0, 0, 0.6)',
    textPlaceholder: 'rgba(0, 0, 0, 0.4)',
    textDisabled: 'rgba(0, 0, 0, 0.26)',
    textAnti: '#ffffff',
    text: '#172033',
    muted: '#66758b',
    surface: '#ffffff',
    surfaceMuted: '#f3f3f3',
    canvas: '#f7f9fc',
    border: '#dce3ed',
    lineControl: '#dcdcdc',
    primary: '#2e6de6',
    danger: '#b42318',
    accent: '#07c05f',
    accentHover: '#08dd6e',
    accentActive: '#06b04d',
    accentDisabled: '#8ce0af',
    accentFocus: 'color-mix(in srgb, #07c05f 20%, transparent)',
    success: '#00a870',
    warning: '#e37318',
    dangerStrong: '#d54941',
    lineSoft: '#edf0f5',
    lineStrong: '#b8c5d6',
    lineNeutral: '#e7e7e7',
    placeholder: '#8a8a8a',
    disabledBg: '#eeeeee',
    overlay: 'rgb(0 0 0 / 50%)',
  },
  radius: {
    small: '2px',
    default: '3px',
    medium: '6px',
    largeTDesign: '9px',
    extraLarge: '12px',
    round: '999px',
    circle: '50%',
    field: '3px',
    control: '6px',
    card: '8px',
    large: '12px',
    dialog: '10px',
    pill: '999px',
  },
  space: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '3rem' },
  state: { focusRing: '3px solid rgb(46 109 230 / 35%)', disabledOpacity: 0.6 },
  typography: {
    body: { fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif', lineHeight: 1.5 },
    mono: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace' },
    heading: { weight: 700 },
    size: {
      bodySmall: '12px',
      bodyMedium: '14px',
      bodyLarge: '16px',
      titleSmall: '14px',
      titleMedium: '16px',
      titleLarge: '20px',
      headlineSmall: '24px',
      headlineMedium: '28px',
      headlineLarge: '36px',
    },
    lineHeight: {
      common: '8px',
      bodySmall: '20px',
      bodyMedium: '22px',
      bodyLarge: '24px',
      titleSmall: '22px',
      titleMedium: '24px',
      titleLarge: '28px',
      headlineSmall: '32px',
      headlineMedium: '36px',
      headlineLarge: '44px',
    },
  },
  shadow: {
    one: '0px 1px 10px rgba(0, 0, 0, 0.05), 0px 4px 5px rgba(0, 0, 0, 0.08), 0px 2px 4px -1px rgba(0, 0, 0, 0.12)',
    two: '0px 3px 14px 2px rgba(0, 0, 0, 0.05), 0px 8px 10px 1px rgba(0, 0, 0, 0.06), 0px 5px 5px -3px rgba(0, 0, 0, 0.1)',
    three: '0px 6px 30px 5px rgba(0, 0, 0, 0.05), 0px 16px 24px 2px rgba(0, 0, 0, 0.04), 0px 8px 10px -5px rgba(0, 0, 0, 0.08)',
  },
  // Tailwind v4 consumes these values through @theme; the names intentionally
  // mirror shadcn semantic slots while retaining Vue's green control accent.
  tailwind: {
    colors: {
      background: 'var(--color-page, var(--color-canvas))',
      foreground: 'var(--color-ink)',
      card: 'var(--color-surface)',
      cardForeground: 'var(--color-ink)',
      primary: 'var(--color-accent)',
      primaryForeground: 'var(--color-surface)',
      secondary: 'var(--color-surface-muted)',
      secondaryForeground: 'var(--color-ink)',
      muted: 'var(--color-surface-muted)',
      mutedForeground: 'var(--color-muted)',
      border: 'var(--color-line)',
      input: 'var(--color-line-input)',
      ring: 'var(--color-accent)',
      destructive: 'var(--color-danger)',
      destructiveForeground: 'var(--color-surface)',
    },
    borderRadius: {
      sm: 'var(--radius-field)',
      md: 'var(--radius-control)',
      lg: 'var(--radius-card)',
      xl: 'var(--radius-dialog)',
      full: 'var(--radius-pill)',
    },
    fontFamily: {
      sans: 'var(--font-sans)',
      mono: 'var(--font-mono)',
    },
    boxShadow: {
      sm: 'var(--shadow-one)',
      md: 'var(--shadow-two)',
      lg: 'var(--shadow-three)',
    },
  },
  // Component wrappers use these short semantic names instead of coupling
  // pages to either TDesign variables or shadcn's default palette.
  shadcn: {
    background: 'page',
    foreground: 'ink',
    card: 'surface',
    primary: 'accent',
    secondary: 'surfaceMuted',
    border: 'line',
    input: 'lineInput',
    ring: 'focus',
    destructive: 'danger',
  },
} as const;

export type DesignTokens = typeof designTokens;
