import { chromium } from 'playwright-core';
const WEB = 'http://localhost:5181';
const API = 'http://127.0.0.1:8080';
const loginRes = await fetch(API + '/api/v1/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: 'uimig@local.dev', password: 'Uimig-2026-Tailwind' }) });
const loginBody = await loginRes.json();
const token = loginBody.token;
const tenantId = String(loginBody.active_tenant?.id ?? loginBody.user?.tenant_id ?? '');
const storageState = { cookies: [], origins: [{ origin: WEB, localStorage: [ { name: 'weknora_token', value: token }, { name: 'weknora_refresh_token', value: loginBody.refresh_token ?? '' }, { name: 'weknora_selected_tenant_id', value: tenantId } ] }] };
const browser = await chromium.launch();
const ctx = await browser.newContext({ storageState, viewport: { width: 1440, height: 900 }, locale: 'zh-CN' });
const page = await ctx.newPage();
await page.goto(WEB + '/platform/creatChat', { waitUntil: 'networkidle', timeout: 20000 }).catch(() => {});
await page.waitForTimeout(2000);
const skip = page.getByText('跳过引导', { exact: true });
console.log('skip count:', await skip.count());
if (await skip.count()) { await skip.first().click().catch((e) => console.log('skip fail', String(e).slice(0, 100))); await page.waitForTimeout(800); }
const rows = page.getByText('视觉验证会话');
console.log('session rows:', await rows.count());
for (let i = 0; i < await rows.count(); i++) console.log('row', i, 'visible:', await rows.nth(i).isVisible().catch(() => 'err'));
const tourCount = await page.getByText('欢迎使用 WeKnora').count();
console.log('tour still present:', tourCount);
await page.screenshot({ path: 'artifacts/tailwind-shadcn/debug-state.png', fullPage: false });
await browser.close();
