#!/usr/bin/env bash
# Lifecycle and experiment runner for the T03 wallet-semantics evidence lab.
#
# Usage: ./deploy/lago-lab/wallet-semantics/lab.sh env|up|status|down|clean|run <experiment>|run-all
#
#   env       generate the worktree-local deploy/lago/.env for THIS lab
#             (project weknora-lago-75, loopback ports 48893/48894, first-run
#             seed values per the T01 README contract; refuses to overwrite)
#   up        start the stack via the shared, read-only deploy/lago/lago.sh
#   status    health snapshot JSON (delegates to deploy/lago/lago.sh status)
#   down      stop the stack; named volumes are preserved
#   clean     remove the whole weknora-lago-75 project including volumes and
#             the generated deploy/lago/.env (from-scratch re-run)
#   run       run one experiment (e1|e2|e3|e4|all) against the lab API; the
#             operator API key comes only from the caller environment
#   run-all   run e1 e2 e3 e4 in order
#
# This lab never modifies anything under deploy/lago/ except the git-ignored
# deploy/lago/.env, and never reads, logs, or stores the caller's API key.

set -euo pipefail

LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$LAB_DIR/../../.." && pwd)"
LAGO_DIR="$REPO_ROOT/deploy/lago"
ENV_FILE="$LAGO_DIR/.env"
COMPOSE_PROJECT="weknora-lago-75"
API_PORT=48893
FRONT_PORT=48894

# Official Lago sample defaults that generated secrets must never equal.
readonly SAMPLE_POSTGRES_PASSWORD="changeme"
readonly SAMPLE_SECRET_KEY_BASE="your-secret-key-base-hex-64"
readonly SAMPLE_ENCRYPTION_PRIMARY_KEY="your-encryption-primary-key"
readonly SAMPLE_ENCRYPTION_DETERMINISTIC_KEY="your-encryption-deterministic-key"
readonly SAMPLE_ENCRYPTION_KEY_DERIVATION_SALT="your-encryption-derivation-salt"

die() {
  echo "lab.sh: $*" >&2
  exit 1
}

usage() {
  sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 2
}

ensure_env() {
  [[ -f "$ENV_FILE" ]] || die "missing $ENV_FILE -- run ./deploy/lago-lab/wallet-semantics/lab.sh env first"
}

random_secret() {
  python3 -c "import secrets; print(secrets.token_urlsafe($1))"
}

random_hex_secret() {
  python3 -c "import secrets; print(secrets.token_hex($1))"
}

env_value() {
  local key="$1" line
  line="$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 || true)"
  line="${line#*=}"
  line="${line%\"}"
  printf '%s' "${line#\"}"
}

cmd_env() {
  if [[ -e "$ENV_FILE" ]]; then
    die "refusing to overwrite existing $ENV_FILE (delete it first to regenerate)"
  fi
  local rsa_key
  rsa_key="$(openssl genrsa 2048 2>/dev/null | openssl base64 -A)"
  [[ -n "$rsa_key" ]] || die "openssl failed to generate the Lago RSA private key"

  umask 077
  {
    echo "# Generated by deploy/lago-lab/wallet-semantics/lab.sh env -- local secrets, never commit."
    echo "# T03 wallet-semantics lab isolation (plan global constraints)."
    echo "COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT}"
    echo "LAGO_API_PORT=${API_PORT}"
    echo "LAGO_FRONT_PORT=${FRONT_PORT}"
    echo "LAGO_API_URL=http://127.0.0.1:${API_PORT}"
    echo "LAGO_FRONT_URL=http://127.0.0.1:${FRONT_PORT}"
    echo "# Random stack secrets (same contract as ./deploy/lago/lago.sh init)."
    echo "POSTGRES_PASSWORD=$(random_secret 24)"
    echo "SECRET_KEY_BASE=$(random_hex_secret 32)"
    echo "LAGO_ENCRYPTION_PRIMARY_KEY=$(random_secret 32)"
    echo "LAGO_ENCRYPTION_DETERMINISTIC_KEY=$(random_secret 32)"
    echo "LAGO_ENCRYPTION_KEY_DERIVATION_SALT=$(random_secret 16)"
    echo "LAGO_RSA_PRIVATE_KEY=\"${rsa_key}\""
    echo "# T03 first-run seed (T01 README contract): seeds org + operator user + API key."
    echo "LAGO_CREATE_ORG=true"
    echo "LAGO_ORG_USER_EMAIL=ops-t03@weknora.local"
    echo "LAGO_ORG_USER_PASSWORD=$(random_secret 16)"
    echo "LAGO_ORG_NAME=WeKnora T03"
    echo "LAGO_ORG_API_KEY=$(random_secret 32)"
  } > "$ENV_FILE"
  echo "wrote $ENV_FILE (mode 600) -- the lab operator API key is LAGO_ORG_API_KEY inside it"
}

cmd_up() {
  ensure_env
  "$LAGO_DIR/lago.sh" up
}

cmd_status() {
  ensure_env
  "$LAGO_DIR/lago.sh" status --json
}

cmd_down() {
  ensure_env
  "$LAGO_DIR/lago.sh" down
}

cmd_clean() {
  [[ -f "$ENV_FILE" ]] || die "nothing to clean (no $ENV_FILE)"
  (cd "$LAGO_DIR" && docker compose -p "$COMPOSE_PROJECT" down -v --remove-orphans)
  rm -f "$ENV_FILE"
  echo "removed project ${COMPOSE_PROJECT} including volumes and the worktree-local .env"
}

cmd_run() {
  local experiment="${1:-}"
  [[ -n "$experiment" ]] || usage
  ensure_env
  LAGO_API_PORT="$(env_value LAGO_API_PORT)" \
    exec python3 "$LAB_DIR/run_experiment.py" "$experiment"
}

cmd_run_all() {
  cmd_run all
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-}" in
    env) shift; cmd_env "$@" ;;
    up) shift; cmd_up "$@" ;;
    status) shift; cmd_status "$@" ;;
    down) shift; cmd_down "$@" ;;
    clean) shift; cmd_clean "$@" ;;
    run) shift; cmd_run "$@" ;;
    run-all) shift; cmd_run_all "$@" ;;
    -h|--help|help) usage ;;
    *) usage ;;
  esac
fi
