export { ChatComposer, createChatSubmission } from './chat/composer.tsx';
export type { ChatComposerProps, ChatSubmission } from './chat/composer.tsx';
export { MessageList, renderMessageHtml } from './chat/message-list.tsx';
export type { MessageListProps, PendingChatMessage } from './chat/message-list.tsx';
export { renderChatMarkdown } from './chat/markdown.ts';
export { ArtifactPreview, artifactPreviewModel } from './chat/artifact-preview.tsx';
export type { ArtifactPreviewKind, ArtifactPreviewModel, ArtifactPreviewPayload, ArtifactPreviewProps } from './chat/artifact-preview.tsx';
export { hydrateMermaidBlocks, hydrateMermaidBlocksWithBrowserDefaults, MERMAID_RENDER_CONFIG } from './chat/mermaid.ts';
export type { MermaidEngine } from './chat/mermaid.ts';
export { SessionSidebar } from './chat/session-sidebar.tsx';
export type { SessionGroupView, SessionSidebarProps, SessionSourceOption } from './chat/session-sidebar.tsx';
export { ChatPage } from './chat/page.tsx';
export type { ChatAgentOption, ChatOAuthApprovalPrompt, ChatPageProps, ChatStreamPresentation, ChatTerminalView, ChatToolApprovalPrompt, ChatToolCallView } from './chat/page.tsx';
export { ReferenceList, referenceSections } from './chat/reference-list.tsx';
export type { ReferenceListProps, ReferenceSection } from './chat/reference-list.tsx';
export { ToolResultView, toolResultPresentation } from './chat/tool-result.tsx';
export type { ToolResultPresentation, ToolResultViewInput } from './chat/tool-result.tsx';
export { SETTINGS_SECTIONS, roleAtLeast, settingsSection, settingsSectionsForRole } from './settings/registry.ts';
export type { SettingsSection, SettingsScope, SettingsRole, SettingsOperation } from './settings/registry.ts';
export { createEmbedBridgeGuard, EMBED_HOST_SOURCE, EMBED_MESSAGE_SOURCE } from './embed/bridge.ts';
export type { EmbedMessageEvent } from './embed/bridge.ts';
export { INTEGRATION_SECTIONS, integrationKeyFromQuery, integrationSection } from './integrations/registry.ts';
export type { IntegrationKey, IntegrationOperation, IntegrationSection } from './integrations/registry.ts';
export { IntegrationsPage } from './integrations/page.tsx';
export type { APIPrincipalConfig, IntegrationActions, IntegrationPrincipalToken, IntegrationResource, IntegrationsPageProps } from './integrations/page.tsx';
export { apiKeyAccessMode, apiKeyValueDisplay, isFreshKeyVisible } from './integrations/apiKeys.ts';
export type { ApiKeyRow } from './integrations/apiKeys.ts';
export { buildEmbedUpdatePayload } from './integrations/form.ts';
export type { EmbedResourceLike } from './integrations/form.ts';
export { integrationTabForSection, normalizeIntegrationSettingsSection, integrationSettingsQuery, selectSettingsQuery } from './integrations/settings-route.ts';
