import { parseActionSuccessResponse, type ActionSuccessResponse } from '@weknora/contracts';
import { array, booleanValue, dataArray, dataRecord, encoded, numberValue, optionalNumber, query, record, stringValue, success, withSignal, type IdentityRequest, type JsonRecord } from '../identity/common.ts';

export type TenantApiKeyCapability = string;
export interface ApiKey { id: number; name: string; api_key: string; scope_type?: 'tenant' | 'platform'; full_access: boolean; knowledge_base_ids: string[] | null; capabilities?: TenantApiKeyCapability[]; last_used_at?: string; expires_at?: string; created_at: string; token?: string }
export interface SystemAdminUser { id: string; username: string; email: string; is_active: boolean; is_system_admin: boolean; created_at: string; updated_at: string; [key: string]: unknown }
export interface SystemSetting { id: number; key: string; value: unknown; value_type: 'int' | 'string' | 'bool' | 'string_list'; category: string; description: string; is_secret: boolean; requires_restart: boolean; last_modified_by: string; created_at: string; updated_at: string; enum?: string[] }
export interface RuntimeTask { id: string; queue: string; type: string; state: string; allowed_actions: string[]; retried: number; max_retry: number; [key: string]: unknown }
export interface RuntimeQueues { available: boolean; upstream_concurrency: number; parse_concurrency: number; wiki_concurrency: number; pools: JsonRecord[]; queues: JsonRecord[]; model_limiter_available: boolean; models: JsonRecord[]; timestamp: number }
export interface AuditPage { items: JsonRecord[]; nextCursor: number }
export interface DeploymentCapabilities { edition: string; capabilities: Record<string, { supported: boolean; reason?: string }> }
export interface APIPrincipalConfig { mode: 'tenant' | 'direct_header' | 'signed_token'; direct_header_name: string; signed_token_header_name: string; require_direct_header: boolean; has_hmac_secret: boolean }

function parseApiKey(value: unknown, path: string): ApiKey { const row = record(value, path); const capabilities = row.capabilities === undefined ? undefined : array(row.capabilities, `${path}.capabilities`).map((item, index) => stringValue(item, `${path}.capabilities[${index}]`)); return { ...row, id: numberValue(row.id, `${path}.id`), name: stringValue(row.name, `${path}.name`), api_key: stringValue(row.api_key, `${path}.api_key`), full_access: booleanValue(row.full_access, `${path}.full_access`), knowledge_base_ids: row.knowledge_base_ids === null ? null : array(row.knowledge_base_ids, `${path}.knowledge_base_ids`).map((item, index) => stringValue(item, `${path}.knowledge_base_ids[${index}]`)), ...(capabilities === undefined ? {} : { capabilities }), created_at: stringValue(row.created_at, `${path}.created_at`) }; }
function parseAdmin(value: unknown, path: string): SystemAdminUser { const row = record(value, path); return { ...row, id: stringValue(row.id, `${path}.id`), username: stringValue(row.username, `${path}.username`), email: stringValue(row.email, `${path}.email`), is_active: booleanValue(row.is_active, `${path}.is_active`), is_system_admin: booleanValue(row.is_system_admin, `${path}.is_system_admin`), created_at: stringValue(row.created_at, `${path}.created_at`), updated_at: stringValue(row.updated_at, `${path}.updated_at`) }; }
function parseSetting(value: unknown, path: string): SystemSetting { const row = record(value, path); const valueType = stringValue(row.value_type, `${path}.value_type`); if (!['int', 'string', 'bool', 'string_list'].includes(valueType)) throw new Error(`${path}.value_type is unsupported`); return { ...row, id: numberValue(row.id, `${path}.id`), key: stringValue(row.key, `${path}.key`), value: row.value, value_type: valueType as SystemSetting['value_type'], category: stringValue(row.category, `${path}.category`), description: typeof row.description === 'string' ? row.description : '', is_secret: booleanValue(row.is_secret, `${path}.is_secret`), requires_restart: booleanValue(row.requires_restart, `${path}.requires_restart`), last_modified_by: stringValue(row.last_modified_by, `${path}.last_modified_by`), created_at: stringValue(row.created_at, `${path}.created_at`), updated_at: stringValue(row.updated_at, `${path}.updated_at`) }; }
function parseAudit(value: unknown, path: string): AuditPage { const root = success(value, path); return { items: array(root.data, `${path}.data`).map((item, index) => record(item, `${path}.data[${index}]`)), nextCursor: typeof root.next_cursor === 'number' ? numberValue(root.next_cursor, `${path}.next_cursor`) : 0 }; }
function action(value: unknown): ActionSuccessResponse { return parseActionSuccessResponse(value); }
function parsePrincipalConfig(value: unknown, path: string): APIPrincipalConfig { const root = record(value, path); const row = record(root.data, `${path}.data`); const mode = stringValue(row.mode, `${path}.data.mode`); if (!['tenant', 'direct_header', 'signed_token'].includes(mode)) throw new Error(`${path}.data.mode is unsupported`); return { mode: mode as APIPrincipalConfig['mode'], direct_header_name: stringValue(row.direct_header_name, `${path}.data.direct_header_name`), signed_token_header_name: stringValue(row.signed_token_header_name, `${path}.data.signed_token_header_name`), require_direct_header: booleanValue(row.require_direct_header, `${path}.data.require_direct_header`), has_hmac_secret: booleanValue(row.has_hmac_secret, `${path}.data.has_hmac_secret`) }; }

function parseRuntimeTasks(value: unknown, path: string): { available: boolean; tasks: RuntimeTask[]; pageSize: number; hasMore: boolean; nextCursor?: string } { const row = record(value, path); const raw = array(row.tasks, `${path}.tasks`); return { available: row.available === true, tasks: raw.map((item, index) => { const task = record(item, `${path}.tasks[${index}]`); return { ...task, id: stringValue(task.id, `${path}.tasks[${index}].id`), queue: stringValue(task.queue, `${path}.tasks[${index}].queue`), type: stringValue(task.type, `${path}.tasks[${index}].type`), state: stringValue(task.state, `${path}.tasks[${index}].state`), allowed_actions: array(task.allowed_actions, `${path}.tasks[${index}].allowed_actions`).map((v, actionIndex) => stringValue(v, `${path}.tasks[${index}].allowed_actions[${actionIndex}]`)), retried: numberValue(task.retried, `${path}.tasks[${index}].retried`), max_retry: numberValue(task.max_retry, `${path}.tasks[${index}].max_retry`) }; }), pageSize: numberValue(row.page_size, `${path}.page_size`), hasMore: row.has_more === true, ...(row.next_cursor === undefined ? {} : { nextCursor: stringValue(row.next_cursor, `${path}.next_cursor`) }) }; }
function parseRuntimeQueues(value: unknown, path: string): RuntimeQueues { const row = record(value, path); return { available: booleanValue(row.available, `${path}.available`), upstream_concurrency: numberValue(row.upstream_concurrency, `${path}.upstream_concurrency`), parse_concurrency: numberValue(row.parse_concurrency, `${path}.parse_concurrency`), wiki_concurrency: numberValue(row.wiki_concurrency, `${path}.wiki_concurrency`), pools: array(row.pools, `${path}.pools`).map((item, index) => record(item, `${path}.pools[${index}]`)), queues: array(row.queues, `${path}.queues`).map((item, index) => record(item, `${path}.queues[${index}]`)), model_limiter_available: booleanValue(row.model_limiter_available, `${path}.model_limiter_available`), models: array(row.models, `${path}.models`).map((item, index) => record(item, `${path}.models[${index}]`)), timestamp: numberValue(row.timestamp, `${path}.timestamp`) }; }

export function createAdministrationApi(request: IdentityRequest) {
  const tenantPath = (tenantId: number) => `/api/v1/tenants/${encoded(tenantId, 'tenantId')}/api-keys`;
  const adminAction = async (method: string, path: string, body?: unknown, signal?: AbortSignal) => action(await request(withSignal({ method, path, ...(body === undefined ? {} : { body }) }, signal)));
  return {
    apiKeys: {
      async list(signal?: AbortSignal): Promise<ApiKey[]> { return dataArray(await request(withSignal({ method: 'GET', path: '/api/v1/system/admin/api-keys' }, signal)), '/system/admin/api-keys').map((item, index) => parseApiKey(item, `/system/admin/api-keys.data[${index}]`)); },
      async create(input: { name: string; capabilities: TenantApiKeyCapability[]; expiresAtUnix?: number }, signal?: AbortSignal): Promise<ApiKey> { const data = dataRecord(await request(withSignal({ method: 'POST', path: '/api/v1/system/admin/api-keys', body: { name: input.name, capabilities: input.capabilities, ...(input.expiresAtUnix === undefined ? {} : { expires_at_unix: input.expiresAtUnix }) } }, signal)), '/system/admin/api-keys'); return parseApiKey(data, '/system/admin/api-keys.data'); },
      async revoke(keyId: number, signal?: AbortSignal): Promise<void> { await adminAction('DELETE', `/api/v1/system/admin/api-keys/${encoded(keyId, 'keyId')}`, undefined, signal); },
    },
    tenantApiKeys: {
      async list(tenantId: number, signal?: AbortSignal): Promise<ApiKey[]> { return dataArray(await request(withSignal({ method: 'GET', path: tenantPath(tenantId) }, signal)), '/tenants/api-keys').map((item, index) => parseApiKey(item, `/tenants/api-keys.data[${index}]`)); },
      async create(tenantId: number, input: Record<string, unknown>, signal?: AbortSignal): Promise<ApiKey> { const data = dataRecord(await request(withSignal({ method: 'POST', path: tenantPath(tenantId), body: input }, signal)), '/tenants/api-keys'); return parseApiKey(data, '/tenants/api-keys.data'); },
      async update(tenantId: number, keyId: number, input: Record<string, unknown>, signal?: AbortSignal): Promise<ApiKey> { const data = dataRecord(await request(withSignal({ method: 'PUT', path: `${tenantPath(tenantId)}/${encoded(keyId, 'keyId')}`, body: input }, signal)), '/tenants/api-keys'); return parseApiKey(data, '/tenants/api-keys.data'); },
      async revoke(tenantId: number, keyId: number, signal?: AbortSignal): Promise<void> { await adminAction('DELETE', `${tenantPath(tenantId)}/${encoded(keyId, 'keyId')}`, undefined, signal); },
      async principalConfig(tenantId: number, signal?: AbortSignal): Promise<APIPrincipalConfig> {
        return parsePrincipalConfig(await request(withSignal({ method: 'GET', path: `/api/v1/tenants/${encoded(tenantId, 'tenantId')}/api-principal-config` }, signal)), '/tenants/api-principal-config');
      },
      async updatePrincipalConfig(tenantId: number, input: { mode: APIPrincipalConfig['mode']; requireDirectHeader?: boolean; hmacSecret?: string }, signal?: AbortSignal): Promise<APIPrincipalConfig> {
        return parsePrincipalConfig(await request(withSignal({ method: 'PUT', path: `/api/v1/tenants/${encoded(tenantId, 'tenantId')}/api-principal-config`, body: { mode: input.mode, require_direct_header: input.requireDirectHeader === true, ...(input.hmacSecret?.trim() ? { hmac_secret: input.hmacSecret.trim() } : {}) } }, signal)), '/tenants/api-principal-config');
      },
      async createPrincipalTestToken(tenantId: number, externalUserId: string, expiresInSeconds = 900, signal?: AbortSignal): Promise<{ token: string; headerName: string; expiresInSeconds: number; externalUserId: string }> {
        const root = record(await request(withSignal({ method: 'POST', path: `/api/v1/tenants/${encoded(tenantId, 'tenantId')}/api-principal-test-token`, body: { external_user_id: externalUserId, expires_in_seconds: expiresInSeconds } }, signal)), '/tenants/api-principal-test-token');
        return { token: stringValue(root.token, '/tenants/api-principal-test-token.token'), headerName: stringValue(root.header_name, '/tenants/api-principal-test-token.header_name'), expiresInSeconds: numberValue(root.expires_in_seconds, '/tenants/api-principal-test-token.expires_in_seconds'), externalUserId: stringValue(root.external_user_id, '/tenants/api-principal-test-token.external_user_id') };
      },
    },
    admins: {
      async list(params: { offset?: number; limit?: number } = {}, signal?: AbortSignal) { const root = record(await request(withSignal({ method: 'GET', path: query('/api/v1/system/admin/list', [['offset', params.offset], ['limit', params.limit]]) }, signal)), '/system/admin/list'); const rows = array(root.admins, '/system/admin/list.admins'); return { items: rows.map((item, index) => parseAdmin(item, `/system/admin/list.admins[${index}]`)), total: numberValue(root.total, '/system/admin/list.total') }; },
      async promote(input: { userId?: string; email?: string }, signal?: AbortSignal) { return parseAdmin(await request(withSignal({ method: 'POST', path: '/api/v1/system/admin/promote', body: { ...(input.userId === undefined ? {} : { user_id: input.userId }), ...(input.email === undefined ? {} : { email: input.email }) } }, signal)), '/system/admin/promote'); },
      async revoke(userId: string, signal?: AbortSignal) { return parseAdmin(await request(withSignal({ method: 'POST', path: '/api/v1/system/admin/revoke', body: { user_id: userId } }, signal)), '/system/admin/revoke'); },
      async resetPassword(input: { email: string; new_password: string }, signal?: AbortSignal) { const root = record(await request(withSignal({ method: 'POST', path: '/api/v1/system/admin/users/reset-password', body: input }, signal)), '/system/admin/users/reset-password'); return { message: stringValue(root.message, '/system/admin/users/reset-password.message') }; },
      async createUser(input: { username: string; email: string; password?: string }, signal?: AbortSignal) { const root = record(await request(withSignal({ method: 'POST', path: '/api/v1/system/admin/users/create', body: input }, signal)), '/system/admin/users/create'); return { user: parseAdmin(root.user, '/system/admin/users/create.user'), ...(root.generated_password === undefined ? {} : { generatedPassword: stringValue(root.generated_password, '/system/admin/users/create.generated_password') }) }; },
    },
    settings: {
      async list(signal?: AbortSignal) { return array(await request(withSignal({ method: 'GET', path: '/api/v1/system/admin/settings' }, signal)), '/system/admin/settings').map((item, index) => parseSetting(item, `/system/admin/settings[${index}]`)); },
      async get(key: string, signal?: AbortSignal) { return parseSetting(await request(withSignal({ method: 'GET', path: `/api/v1/system/admin/settings/${encoded(key, 'key')}` }, signal)), '/system/admin/settings/:key'); },
      async update(key: string, value: unknown, signal?: AbortSignal) { return parseSetting(await request(withSignal({ method: 'PUT', path: `/api/v1/system/admin/settings/${encoded(key, 'key')}`, body: { value } }, signal)), '/system/admin/settings/:key'); },
      async reset(key: string, signal?: AbortSignal): Promise<void> { action(await request(withSignal({ method: 'DELETE', path: `/api/v1/system/admin/settings/${encoded(key, 'key')}` }, signal))); },
      async applyDefaultStorageQuota(signal?: AbortSignal) { const root = record(await request(withSignal({ method: 'POST', path: '/api/v1/system/admin/tenants/apply-default-storage-quota' }, signal)), '/system/admin/tenants/apply-default-storage-quota'); return { affected: numberValue(root.affected, 'affected'), quotaBytes: numberValue(root.quota_bytes, 'quota_bytes'), quotaGb: numberValue(root.quota_gb, 'quota_gb') }; },
    },
    auditLog: { async list(params: { afterId?: number; limit?: number; action?: string; outcome?: string; actor?: string } = {}, signal?: AbortSignal) { return parseAudit(await request(withSignal({ method: 'GET', path: query('/api/v1/system/admin/audit-log', [['after_id', params.afterId], ['limit', params.limit], ['action', params.action], ['outcome', params.outcome], ['actor', params.actor]]) }, signal)), '/system/admin/audit-log'); } },
    runtime: {
      async queues(signal?: AbortSignal): Promise<RuntimeQueues> { return parseRuntimeQueues(await request(withSignal({ method: 'GET', path: '/api/v1/system/admin/runtime/queues' }, signal)), '/system/admin/runtime/queues'); },
      tasks: { async list(queue: string, state: string, params: { cursor?: string; pageSize?: number } = {}, signal?: AbortSignal) { return parseRuntimeTasks(await request(withSignal({ method: 'GET', path: query(`/api/v1/system/admin/runtime/queues/${encoded(queue, 'queue')}/tasks`, [['state', state], ['cursor', params.cursor || undefined], ['page_size', params.pageSize]]) }, signal)), '/system/admin/runtime/tasks'); } },
      async mutateTask(queue: string, taskId: string, actionName: string, signal?: AbortSignal): Promise<void> { await adminAction('POST', `/api/v1/system/admin/runtime/queues/${encoded(queue, 'queue')}/tasks/${encoded(taskId, 'taskId')}/actions/${encoded(actionName, 'action')}`, undefined, signal); },
      async purgeArchived(queue: string, signal?: AbortSignal) { const root = record(await request(withSignal({ method: 'DELETE', path: `/api/v1/system/admin/runtime/queues/${encoded(queue, 'queue')}/archived` }, signal)), '/system/admin/runtime/queues/archived'); return { deleted: numberValue(root.deleted, 'deleted') }; },
    },
    async capabilities(signal?: AbortSignal): Promise<DeploymentCapabilities> { const root = record(await request(withSignal({ method: 'GET', path: '/api/v1/system/capabilities' }, signal)), '/system/capabilities'); if (root.code !== 0) throw new Error('/system/capabilities.code must be 0'); const data = record(root.data, '/system/capabilities.data'); const capabilities = record(data.capabilities, '/system/capabilities.data.capabilities'); return { edition: stringValue(data.edition, '/system/capabilities.data.edition'), capabilities: Object.fromEntries(Object.entries(capabilities).map(([key, value]) => { const row = record(value, `/system/capabilities.data.capabilities.${key}`); return [key, { supported: row.supported === true, ...(row.reason === undefined ? {} : { reason: stringValue(row.reason, `capabilities.${key}.reason`) }) }]; })) }; },
  };
}

export type AdministrationApi = ReturnType<typeof createAdministrationApi>;
