packages:
  - packages/contracts
  - packages/api-client
  - packages/domain
  - packages/ui
  - apps/web
  - apps/mobile
  - packages/happy-wire

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - '@more-tech/react-native-libsodium'

patchedDependencies:
  react-native-audio-api@0.8.4: patches/react-native-audio-api@0.8.4.patch
