import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import type { WeKnoraClient } from '@weknora/api-client';
import { Badge, Button, Card, Status, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@weknora/ui';
import { actionControls, appDigest, appErrorMessage, appRisk, appRows, appShort, appStatus, authorizationStatus, installationState, type AppRow } from './model.ts';

type AppMode = 'catalog' | 'connections' | 'authorization' | 'action';
type Props = { client: WeKnoraClient; mode: AppMode; id?: string; role?: string };
const copy = {
  catalog: { title: '应用目录', description: '查看当前工作空间可用的已审核应用动作与已安装版本。', empty: '暂无可用应用动作', installed: '已安装应用', installedEmpty: '暂无已安装应用' },
  connections: { title: '应用连接', description: '管理个人与工作空间级应用连接。', empty: '暂无应用连接' },
  authorization: { title: '应用授权', description: '本页面只轮询本次授权尝试状态；授权地址由连接流程提供。' },
  action: { title: '应用动作审批', description: '审批并执行一个绑定到当前快照的应用动作。' },
} as const;

function isAbortError(cause: unknown): boolean { const error = cause as { name?: string; code?: string }; return error?.name === 'AbortError' || error?.name === 'CanceledError' || error?.code === 'ERR_CANCELED'; }
function responseRecord(value: unknown): AppRow { const root = value && typeof value === 'object' ? value as AppRow : {}; const data = root.data; return data && typeof data === 'object' && !Array.isArray(data) ? data as AppRow : root; }

function PageFrame({ title, description, loading, onReload, children }: { title: string; description: string; loading: boolean; onReload: () => void; children: ReactNode }) {
  return <main className="wk-page flex h-full flex-col gap-5 overflow-y-auto p-6"><header className="flex items-start justify-between gap-4"><div><h1 className="m-0 text-xl font-semibold text-ink">{title}</h1><p className="m-0 mt-1 text-sm text-muted">{description}</p></div><Button size="small" onClick={onReload} loading={loading}>刷新</Button></header>{loading ? <div role="status"><Status>加载中…</Status></div> : null}{children}</main>;
}

function CatalogTable({ rows, empty }: { rows: AppRow[]; empty: string }) {
  const fields = [['action_id', '动作'], ['app_id', '应用'], ['app_version', '版本'], ['provider', '提供方'], ['risk', '风险'], ['required_scopes', '权限'], ['schema_digest', '摘要'], ['published', '发布']] as const;
  return <Table><TableHead><TableRow>{fields.map(([, title]) => <TableHeader key={title}>{title}</TableHeader>)}</TableRow></TableHead><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={fields.length}>{empty}</TableCell></TableRow> : rows.map((row, index) => <TableRow key={String(row.action_id ?? index)}>{fields.map(([field]) => { const value = row[field]; const content = field === 'required_scopes' && Array.isArray(value) ? value.join(', ') || '—' : field === 'risk' ? (() => { const risk = appRisk(value); return <Badge tone={risk.tone}>{risk.label}</Badge>; })() : field === 'schema_digest' ? appDigest(value) : field === 'published' ? <Badge tone={value ? 'success' : 'neutral'}>{value ? '已发布' : '未发布'}</Badge> : appShort(value); return <TableCell key={field} title={String(value ?? '')}>{content}</TableCell>; })}</TableRow>)}</TableBody></Table>;
}
function InstallationsTable({ rows, empty }: { rows: AppRow[]; empty: string }) {
  const fields = [['app_key', '应用'], ['version', '版本'], ['state', '状态'], ['scopes', '权限']] as const;
  return <Table><TableHead><TableRow>{fields.map(([, title]) => <TableHeader key={title}>{title}</TableHeader>)}</TableRow></TableHead><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={fields.length}>{empty}</TableCell></TableRow> : rows.map((row, index) => <TableRow key={String(row.id ?? index)}>{fields.map(([field]) => { const value = row[field]; const content = field === 'scopes' && Array.isArray(value) ? value.join(', ') || '—' : field === 'state' ? (() => { const state = installationState(value); return <Badge tone={state.tone}>{state.label}</Badge>; })() : appStatus(value); return <TableCell key={field}>{content}</TableCell>; })}</TableRow>)}</TableBody></Table>;
}

function CatalogPage({ client }: { client: WeKnoraClient }) {
  const [catalog, setCatalog] = useState<AppRow[]>([]); const [installed, setInstalled] = useState<AppRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const generation = useRef(0); const request = useRef<AbortController | null>(null);
  const load = async () => { request.current?.abort(); const run = ++generation.current; const controller = new AbortController(); request.current = controller; setLoading(true); setError(''); try { const [catalogResponse, installedResponse] = await Promise.all([client.request({ method: 'GET', path: '/api/v1/apps/catalog', signal: controller.signal }), client.request({ method: 'GET', path: '/api/v1/apps/installations', signal: controller.signal })]); if (run !== generation.current) return; setCatalog(appRows(catalogResponse)); setInstalled(appRows(installedResponse)); } catch (cause) { if (run === generation.current && !isAbortError(cause)) { setCatalog([]); setInstalled([]); setError(appErrorMessage(cause)); } } finally { if (run === generation.current) { setLoading(false); request.current = null; } } };
  useEffect(() => { void load(); return () => { generation.current += 1; request.current?.abort(); }; }, [client]);
  return <PageFrame title={copy.catalog.title} description={copy.catalog.description} loading={loading} onReload={() => void load()}>{error ? <Status tone="error">{error}</Status> : null}<Card><CatalogTable rows={catalog} empty={copy.catalog.empty} /></Card><Card><h2 className="m-0 mb-3 text-base font-semibold text-ink">{copy.catalog.installed}</h2><InstallationsTable rows={installed} empty={copy.catalog.installedEmpty} /></Card></PageFrame>;
}

function ConnectionsPage({ client, role }: { client: WeKnoraClient; role?: string }) {
  const [data, setData] = useState<AppRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const generation = useRef(0); const request = useRef<AbortController | null>(null); const canManage = role === 'owner' || role === 'admin';
  const load = async () => { request.current?.abort(); const run = ++generation.current; const controller = new AbortController(); request.current = controller; setLoading(true); setError(''); try { const value = await client.request({ method: 'GET', path: '/api/v1/apps/connections', signal: controller.signal }); if (run === generation.current) setData(appRows(value)); } catch (cause) { if (run === generation.current && !isAbortError(cause)) { setData([]); setError(appErrorMessage(cause)); } } finally { if (run === generation.current) { setLoading(false); request.current = null; } } };
  useEffect(() => { void load(); return () => { generation.current += 1; request.current?.abort(); }; }, [client]);
  const startAuthorization = async (row: AppRow) => { if (!canManage || busy) return; setBusy(String(row.id)); setError(''); try { const value = responseRecord(await client.request({ method: 'POST', path: `/api/v1/apps/connections/${encodeURIComponent(String(row.id))}/authorization-attempts`, body: {} })); const attemptId = String(value.attempt_id ?? ''); if (!attemptId) throw new Error('授权尝试未返回 ID'); window.location.assign('/platform/apps/authorization/' + encodeURIComponent(attemptId)); } catch (cause) { setError(appErrorMessage(cause)); } finally { setBusy(''); } };
  const revoke = async (row: AppRow) => { if (!canManage || busy || !window.confirm('确认撤销此应用连接？')) return; setBusy(String(row.id)); setError(''); try { await client.request({ method: 'POST', path: `/api/v1/apps/connections/${encodeURIComponent(String(row.id))}/revoke`, body: { expected_version: row.auth_version } }); await load(); } catch (cause) { setError(appErrorMessage(cause)); } finally { setBusy(''); } };
  return <PageFrame title={copy.connections.title} description={copy.connections.description} loading={loading} onReload={() => void load()}>{error ? <Status tone="error">{error}</Status> : null}{!canManage ? <Status>当前角色只能查看应用连接。</Status> : null}<Card><Table><TableHead><TableRow>{['连接 ID', '类型', '所有者', '状态', '操作'].map((header) => <TableHeader key={header}>{header}</TableHeader>)}</TableRow></TableHead><TableBody>{data.length === 0 ? <TableRow><TableCell colSpan={5}>{copy.connections.empty}</TableCell></TableRow> : data.map((row) => <TableRow key={String(row.id)}><TableCell title={String(row.id)}>{appShort(row.id)}</TableCell><TableCell>{row.kind === 'space' ? '工作空间' : appStatus(row.kind)}</TableCell><TableCell>{row.kind === 'space' ? '工作空间' : appShort(row.owner_id)}</TableCell><TableCell>{appStatus(row.state)}</TableCell><TableCell>{canManage && row.state === 'active' ? <><Button variant="text" size="small" loading={busy === String(row.id)} onClick={() => void startAuthorization(row)}>授权</Button><Button variant="text" size="small" loading={busy === String(row.id)} onClick={() => void revoke(row)}>撤销</Button></> : row.state === 'revoked' ? '远端清理中' : '—'}</TableCell></TableRow>)}</TableBody></Table></Card></PageFrame>;
}

function AuthorizationPage({ client, id }: { client: WeKnoraClient; id: string }) {
  const [attempt, setAttempt] = useState<AppRow>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); const generation = useRef(0); const request = useRef<AbortController | null>(null);
  const poll = async (showLoading = false) => { if (!id) return; if (timer.current) { clearTimeout(timer.current); timer.current = null; } request.current?.abort(); const run = ++generation.current; const controller = new AbortController(); request.current = controller; if (showLoading) setLoading(true); setError(''); try { const value = responseRecord(await client.request({ method: 'GET', path: `/api/v1/apps/authorization-attempts/${encodeURIComponent(id)}`, signal: controller.signal })); if (run !== generation.current) return; setAttempt(value); if (authorizationStatus(value.status).poll) timer.current = setTimeout(() => void poll(), 3000); } catch (cause) { if (run === generation.current && !isAbortError(cause)) setError(appErrorMessage(cause)); } finally { if (run === generation.current) { setLoading(false); request.current = null; } } };
  useEffect(() => { void poll(true); return () => { generation.current += 1; if (timer.current) clearTimeout(timer.current); request.current?.abort(); }; }, [client, id]);
  return <PageFrame title={copy.authorization.title} description={copy.authorization.description} loading={loading} onReload={() => void poll(true)}>{error ? <Status tone="error">{error}</Status> : null}<Status>授权地址不在此页面生成；此页面只显示本次授权尝试的本地状态。</Status><Card><dl className="grid gap-3 text-sm"><div><dt className="font-medium text-muted">尝试 ID</dt><dd className="m-0 font-mono">{id || '—'}</dd></div><div><dt className="font-medium text-muted">连接 ID</dt><dd className="m-0 font-mono">{appShort(attempt.connection_id)}</dd></div><div><dt className="font-medium text-muted">状态</dt><dd className="m-0">{appStatus(attempt.status)}</dd></div><div><dt className="font-medium text-muted">过期时间</dt><dd className="m-0">{appStatus(attempt.expires_at)}</dd></div></dl></Card><Button variant="text" onClick={() => window.location.assign('/platform/apps/connections')}>返回连接</Button></PageFrame>;
}

function ActionPage({ client, id, role }: { client: WeKnoraClient; id: string; role?: string }) {
  const [detail, setDetail] = useState<AppRow>({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const canDrive = role === 'owner' || role === 'admin'; const generation = useRef(0); const request = useRef<AbortController | null>(null);
  const load = async () => { if (!id) return; request.current?.abort(); const run = ++generation.current; const controller = new AbortController(); request.current = controller; setLoading(true); setError(''); try { const value = responseRecord(await client.request({ method: 'GET', path: `/api/v1/apps/actions/${encodeURIComponent(id)}`, signal: controller.signal })); if (run === generation.current) setDetail(value); } catch (cause) { if (run === generation.current && !isAbortError(cause)) { setDetail({}); setError(appErrorMessage(cause)); } } finally { if (run === generation.current) { setLoading(false); request.current = null; } } };
  useEffect(() => { void load(); return () => { generation.current += 1; request.current?.abort(); }; }, [client, id]);
  const action = detail.action && typeof detail.action === 'object' ? detail.action as AppRow : detail; const controls = actionControls(action.state, canDrive);
  const mutate = async (kind: 'approve' | 'execute') => { if (saving || !(kind === 'approve' ? controls.approve : controls.execute)) return; setSaving(true); setError(''); try { await client.request({ method: 'POST', path: `/api/v1/apps/actions/${encodeURIComponent(id)}/${kind}`, body: kind === 'approve' ? { digest: action.digest, expected_version: detail.expected_version } : {} }); await load(); } catch (cause) { setError(appErrorMessage(cause)); await load(); } finally { setSaving(false); } };
  const content = appStatus(action.content); let pretty = content; try { pretty = JSON.stringify(JSON.parse(content), null, 2); } catch { /* server content may be non-JSON legacy data */ }
  return <PageFrame title={copy.action.title} description={copy.action.description} loading={loading} onReload={() => void load()}>{error ? <Status tone="error">{error}</Status> : null}{!canDrive ? <Status>当前角色无权审批或执行应用动作。</Status> : null}<Card><dl className="grid gap-3 text-sm"><div><dt className="font-medium text-muted">动作 ID</dt><dd className="m-0 font-mono">{id || '—'}</dd></div><div><dt className="font-medium text-muted">账户</dt><dd className="m-0 font-mono">{appStatus(action.connection_name)}</dd></div><div><dt className="font-medium text-muted">目标</dt><dd className="m-0 font-mono">{appStatus(action.target)}</dd></div><div><dt className="font-medium text-muted">风险</dt><dd className="m-0">—</dd></div><div><dt className="font-medium text-muted">状态</dt><dd className="m-0">{appStatus(action.state)}</dd></div><div><dt className="font-medium text-muted">摘要</dt><dd className="m-0 font-mono">{appShort(action.digest)}</dd></div><div><dt className="font-medium text-muted">版本栅栏</dt><dd className="m-0 font-mono">{appStatus(detail.expected_version)}</dd></div><div><dt className="font-medium text-muted">参数</dt><dd className="m-0 whitespace-pre-wrap rounded-control bg-surface-muted p-3">{pretty}</dd></div></dl><div className="mt-4 flex gap-2">{controls.approve ? <Button loading={saving} onClick={() => void mutate('approve')}>批准</Button> : null}{controls.execute ? <Button loading={saving} onClick={() => void mutate('execute')}>执行</Button> : null}</div>{action.state === 'unknown' ? <Status>结果待核对；当前阶段不会提供重试发送。</Status> : null}</Card></PageFrame>;
}

export function AppsPage({ client, mode, id, role }: Props) { return mode === 'catalog' ? <CatalogPage client={client} /> : mode === 'connections' ? <ConnectionsPage client={client} role={role} /> : mode === 'authorization' ? <AuthorizationPage client={client} id={id ?? ''} /> : <ActionPage client={client} id={id ?? ''} role={role} />; }
