CREATE TABLE career_spaces (tenant_id BIGINT PRIMARY KEY, owner_user_id VARCHAR(512) NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE career_profiles (tenant_id BIGINT NOT NULL, user_id VARCHAR(512) NOT NULL, revision BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (tenant_id, user_id));
CREATE TABLE career_facts (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT NOT NULL, user_id VARCHAR(512) NOT NULL, key VARCHAR(128) NOT NULL, value TEXT NOT NULL, revision BIGINT NOT NULL, source TEXT NOT NULL, confirmation TEXT NOT NULL, request_id VARCHAR(128) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE (tenant_id, user_id, key));
CREATE TABLE career_fact_versions (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT NOT NULL, user_id VARCHAR(512) NOT NULL, key VARCHAR(128) NOT NULL, value TEXT NOT NULL, revision BIGINT NOT NULL, source TEXT NOT NULL, confirmation TEXT NOT NULL, proposal_id VARCHAR(36) NOT NULL DEFAULT '', request_id VARCHAR(128) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_career_fact_version_scope ON career_fact_versions (tenant_id, user_id, key, revision);
CREATE TABLE career_proposals (id BIGSERIAL PRIMARY KEY, public_id VARCHAR(36) NOT NULL UNIQUE, tenant_id BIGINT NOT NULL, user_id VARCHAR(512) NOT NULL, key VARCHAR(128) NOT NULL, value TEXT NOT NULL, source TEXT NOT NULL, status VARCHAR(16) NOT NULL, resolved_at TIMESTAMPTZ, resolved_revision BIGINT, confirmation TEXT NOT NULL DEFAULT '{}', resolution_source TEXT NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_career_proposal_scope ON career_proposals (tenant_id, user_id, status, created_at);
CREATE TABLE career_changes (id BIGSERIAL PRIMARY KEY, tenant_id BIGINT NOT NULL, user_id VARCHAR(512) NOT NULL, revision BIGINT NOT NULL, kind VARCHAR(32) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE (tenant_id, user_id, revision));
CREATE TABLE career_receipts (tenant_id BIGINT NOT NULL, user_id VARCHAR(512) NOT NULL, request_id VARCHAR(128) NOT NULL, fingerprint VARCHAR(64) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE (tenant_id, user_id, request_id));
