BEGIN;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM agent_chat_turn_claims) OR EXISTS(SELECT 1 FROM agent_runs WHERE security_agent_id IS NOT NULL) OR EXISTS(SELECT 1 FROM agent_release_revocations) OR EXISTS(SELECT 1 FROM agent_dependency_revocations) THEN RAISE EXCEPTION 'agent_security_history_prevents_down'; END IF; END $$;
DROP TRIGGER IF EXISTS trg_agent_adoption_variant_published_identity_immutable ON agent_adoption_variants;
DROP FUNCTION IF EXISTS reject_published_agent_variant_identity_update();
DROP TRIGGER IF EXISTS trg_agent_runs_marketplace_pin_required ON agent_runs;
DROP FUNCTION IF EXISTS reject_unpinned_marketplace_run_insert();
DROP TRIGGER IF EXISTS trg_agent_runs_security_pin_immutable ON agent_runs;
DROP FUNCTION IF EXISTS reject_agent_run_security_pin_update();
DROP INDEX IF EXISTS idx_agent_chat_turn_claims_active;
DROP INDEX IF EXISTS uq_agent_chat_turn_claim_session_user;
DROP INDEX IF EXISTS uq_agent_chat_turn_claim_session_assistant;
DROP INDEX IF EXISTS uq_agent_chat_turn_claim_request;
DROP INDEX IF EXISTS idx_agent_chat_turn_claim_source_state_release;
DROP INDEX IF EXISTS uq_agent_adoption_variant_local_agent;
DROP TABLE IF EXISTS agent_chat_turn_claims;
ALTER TABLE agent_runs DROP CONSTRAINT IF EXISTS ck_agent_runs_security_pin_complete;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS security_pin_source;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS security_release_id;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS security_local_agent_version_id;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS security_agent_id;
ALTER TABLE agent_dependency_revocations DROP COLUMN IF EXISTS run_cancellation_state;
ALTER TABLE agent_release_revocations DROP COLUMN IF EXISTS run_cancellation_state;
COMMIT;
