"""Browser-only checks for the OFFLINE prototype. Not Taro/WeChat/backend tests."""
from pathlib import Path
import json,sys,os,shutil
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[1]
manifest=json.loads((R/'prototype/page-manifest.json').read_text())
result={'scope':'Standalone HTML bytes loaded using Chromium set_content; no WeChat/backend','pages':[],'layouts':[],'flows':[],'script_errors':[]}
def check(name, condition,detail=''):
 ok=bool(condition);result['flows'].append({'case':name,'passed':ok,'detail':detail});assert ok,name+': '+detail
with sync_playwright() as pw:
 exe=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
 b=pw.chromium.launch(**({'executable_path':exe} if exe else {}),headless=True,args=['--no-sandbox'])
 for entry in manifest:
  p=b.new_page(viewport={'width':390,'height':844},device_scale_factor=1)
  errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
  p.set_content((R/'prototype/pages'/entry['file']).read_text(),wait_until='load')
  p.wait_for_timeout(60)
  actual=p.evaluate('current')
  overflow=p.evaluate("({body:document.body.scrollWidth>innerWidth+1,content:document.querySelector('.appcontent').scrollWidth>document.querySelector('.appcontent').clientWidth+1})")
  passed=actual==entry['id'] and not errors and not any(overflow.values())
  result['pages'].append({'page':entry['id'],'passed':passed,'current':actual,'overflow':overflow,'errors':errors})
  p.screenshot(path=str(R/'prototype/screenshots'/(entry['n']+'-'+entry['id']+'.png')))
  p.close()
 for width in [320,375,390,430]:
  p=b.new_page(viewport={'width':width,'height':844})
  p.on('pageerror',lambda e:result['script_errors'].append(str(e)))
  p.set_content((R/'prototype/index.html').read_text(),wait_until='load')
  for entry in manifest:
   p.evaluate('(id)=>window.__prototype.navigate(id)',entry['id'])
   o=p.evaluate("({body:document.body.scrollWidth>innerWidth+1,content:document.querySelector('.appcontent').scrollWidth>document.querySelector('.appcontent').clientWidth+1})")
   result['layouts'].append({'width':width,'page':entry['id'],'passed':not any(o.values()),'overflow':o})
  p.close()
 p=b.new_page(viewport={'width':390,'height':844},accept_downloads=True)
 p.on('pageerror',lambda e:result['script_errors'].append(str(e)))
 p.set_content((R/'prototype/index.html').read_text(),wait_until='load')
 def go(id):p.evaluate('(id)=>window.__prototype.navigate(id)',id)
 def state():return p.evaluate('window.__prototype.getState()')
 def click(a):p.locator(f'[data-act="{a}"]').first.click(timeout=4000)
 try:
  go('login');click('login-wx');check('未勾选协议不能登录',p.evaluate('current')=='login' and bool(p.locator('#login-error').inner_text()))
  p.locator('#consent').check();click('login-wx');check('微信模拟登录进入空间选择',p.evaluate('current')=='workspace')
  p.locator('[data-act="select-space"]').first.click();click('enter-space');check('显式进入个人空间',state()['tenant']=='我的个人空间')
  go('home');click('home-preset');check('首页示例意图可填入',bool(p.locator('#home-prompt').input_value()))
  click('home-start');check('首页不直接提交执行',p.evaluate('current')=='agent' and not state().get('launchCount'))
  click('task-start');check('确认后模拟创建一次任务',p.evaluate('current')=='execution' and state().get('launchCount')==1)
  rid=state()['requestId'];click('network');check('断网不把任务取消',state()['network']==False and state()['status']=='running')
  click('network');check('恢复不创建新意图',state()['requestId']==rid and state()['launchCount']==1)
  go('approval');click('approve');check('审批需要二次确认',p.locator('#modal').inner_text().find('确认')>=0 and state()['approval']=='pending')
  click('approve-confirm');check('仅本次审批成功',state()['approval']=='approved')
  go('approval');click('approval-stale');check('旧版本审批被阻断',state()['approval']=='stale' and not p.locator('[data-act="approve"]').count() and not p.locator('#modal [data-act="approve-confirm"]').count())
  go('execution');click('cancel-task');check('取消前状态未被修改',state()['status']!='canceled');click('cancel-confirm');check('确认取消后状态变化',state()['status']=='canceled')
  go('chat');p.locator('#chat-input').fill('把这些内容整理成待办清单');click('chat-send');p.wait_for_timeout(200);check('输入与中文增量回答',len(state()['userMessages'])==1 and bool(state()['assistantMessage']))
  click('chat-stop');before=state()['assistantMessage'];p.wait_for_timeout(200);check('停止输出停止本地增量',state()['assistantMessage']==before)
  go('agents');p.locator('#agent-search').fill('无匹配助手xyz');check('Agent搜索空结果',p.locator('#agent-cards').inner_text().find('没有找到')>=0)
  p.locator('#agent-search').fill('知识');check('Agent按关键词过滤',p.locator('#agent-cards .taskcard').count()==1)
  go('tasks');p.locator('[data-act="task-filter"][data-value="succeeded"]').click();check('任务完成筛选',p.locator('.hf-task-title').count()==1)
  go('knowledge');p.locator('[data-act="kb-filter"][data-value="shared"]').click();check('知识共享筛选',p.locator('#hf-kb-cards .taskcard').count()==1)
  go('upload');click('choose-file');click('upload-submit');check('上传与解析分离',state()['uploadStage']=='parsing' and p.locator('.appcontent').inner_text().find('正在解析')>=0)
  click('parse-complete');check('解析完成单独确认',state()['uploadStage']=='ready')
  go('checkout');check('默认购买通道关闭',p.locator('[data-act="pay"]').is_disabled())
  click('purchase-toggle');check('显式演示开关开启',not p.locator('[data-act="pay"]').is_disabled())
  click('quote-toggle');check('过期报价不能支付',p.locator('[data-act="pay"]').is_disabled())
  click('quote-toggle');click('pay');check('支付操作后只进入待确认',p.evaluate('current')=='order' and state()['orderPayment']=='pending' and state()['orderFulfillment']=='pending')
  check('未付款不能模拟发放权益',p.locator('[data-act="order-fulfilled"]').is_disabled())
  click('order-paid');check('已付款但未履约',state()['orderPayment']=='paid' and state()['orderFulfillment']!='fulfilled')
  click('order-fulfilled');check('履约独立完成',state()['orderFulfillment']=='fulfilled')
  go('artifact')
  with p.expect_download() as di:click('download')
  check('下载仅生成本地示例',di.value.suggested_filename.endswith('.md'))
  go('invitations');click('invite-accept');check('接受邀请刷新空间选项',p.evaluate('current')=='workspace' and '云杉创新项目' in p.locator('.appcontent').inner_text())
  go('states')
  for k in ['empty','offline','forbidden','unavailable','expired','syncing']:
   p.locator(f'[data-act="error-type"][data-value="{k}"]').click();check('异常状态-'+k,state()['errorType']==k and p.locator('.card.empty h2').count()==1)
  go('me');click('logout');click('logout-confirm');check('退出清理示例消息与意图',p.evaluate('current')=='login' and not state()['userMessages'] and not state().get('requestId'))
 except Exception as e:
  result['failure']=str(e);p.screenshot(path=str(R/'prototype/screenshots/flow-failure.png'))
 p.close()
 d=b.new_page(viewport={'width':1450,'height':1080},device_scale_factor=1)
 d.set_content((R/'prototype/index.html').read_text(),wait_until='load');d.wait_for_timeout(150)
 d.screenshot(path=str(R/'prototype/screenshots/review-studio.png'))
 d.close()
 g=b.new_page(viewport={'width':1440,'height':980},device_scale_factor=1)
 g.set_content((R/'design/components.html').read_text(),wait_until='load');g.wait_for_timeout(80)
 g.screenshot(path=str(R/'design/components-preview.png'))
 g.close();b.close()
result['summary']={k:sum(x['passed'] for x in result[k]) for k in ['pages','layouts','flows']}
result['summary'].update({k+'_total':len(result[k]) for k in ['pages','layouts','flows']})
(R/'tests/prototype-results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(result['summary'],ensure_ascii=False));print('failure:',result.get('failure'));print('page/layout errors:',[x for x in result['pages']+result['layouts'] if not x['passed']]);print('script errors:',result['script_errors'])
if result.get('failure') or any(not x['passed'] for x in result['pages']+result['layouts']+result['flows']) or result['script_errors']:sys.exit(1)
