// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCheckForUpdates() {
  return window['go']['main']['App']['AutoCheckForUpdates']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetAPIBaseURL() {
  return window['go']['main']['App']['GetAPIBaseURL']();
}

export function GetAPILanBaseURL() {
  return window['go']['main']['App']['GetAPILanBaseURL']();
}

export function GetApprovalMode() {
  return window['go']['main']['App']['GetApprovalMode']();
}

export function GetAutoSetupToken() {
  return window['go']['main']['App']['GetAutoSetupToken']();
}

export function GetDesktopHTTPBindPublicSetting() {
  return window['go']['main']['App']['GetDesktopHTTPBindPublicSetting']();
}

export function GetDesktopHTTPPortSetting() {
  return window['go']['main']['App']['GetDesktopHTTPPortSetting']();
}

export function GetDesktopListenPublicActive() {
  return window['go']['main']['App']['GetDesktopListenPublicActive']();
}

export function GetCredential(arg1) {
  return window['go']['main']['App']['GetCredential'](arg1);
}

export function SetCredential(arg1, arg2) {
  return window['go']['main']['App']['SetCredential'](arg1, arg2);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function GetPaseoURL() {
  return window['go']['main']['App']['GetPaseoURL']();
}

export function GetPaseoAllowedOrigins() {
  return window['go']['main']['App']['GetPaseoAllowedOrigins']();
export function GetProjectDirs() {
  return window['go']['main']['App']['GetProjectDirs']();
}

export function PickProjectDir() {
  return window['go']['main']['App']['PickProjectDir']();
}

export function RemoveProjectDir(arg1) {
  return window['go']['main']['App']['RemoveProjectDir'](arg1);
}

export function SetApprovalMode(arg1) {
  return window['go']['main']['App']['SetApprovalMode'](arg1);
}

export function SetDesktopHTTPBindPublicSetting(arg1) {
  return window['go']['main']['App']['SetDesktopHTTPBindPublicSetting'](arg1);
}

export function SetDesktopHTTPPortSetting(arg1) {
  return window['go']['main']['App']['SetDesktopHTTPPortSetting'](arg1);
}
