import { useEffect, useRef, useState, useCallback } from 'react';
import { View, Text } from '@tarojs/components';
import { useDidHide, useDidShow } from '@tarojs/taro';
import { Screen, Card, Action, Field, Notice, Section, ListRow, Badge, Empty, useData, DataBoundary, useAction, confirmAction } from '../../components/ui.tsx';
import { auth, client, executions } from '../../services/runtime.ts';
import { navigate, routeParam } from '../../platform/navigation.ts';
import { listTasks, pendingIntent, recentRuns, rememberRun, watchExecution, interactions, rejectInteraction } from '../../services/workbench.ts';
import { eventLabel, terminal, type RunProjection } from '../../core/execution.ts';
import { errorMessage } from '../../core/errors.ts';
import { formatBytes, formatTime } from '../../core/format.ts';
const labels:Record<string,string>={queued:'排队中',running:'运行中',waiting_user:'待你确认',reconciling:'核对状态中',succeeded:'已完成',failed:'失败',canceled:'已取消'};
export function TasksPage(){
 const [filter,setFilter]=useState(''),[cursor,setCursor]=useState(''),[lookupId,setLookupId]=useState('');const action=useAction();const query=useData(`tasks:${filter}:${cursor}`,()=>listTasks(cursor,filter));const pending=pendingIntent().current();
 return <Screen title='任务' tab><View className='wk-between'><Text className='wk-display'>工作正在向前。</Text><Action secondary onClick={()=>void navigate('agents')}>新任务</Action></View><View className='wk-filters'>{[['','全部'],['running','运行中'],['waiting_user','待确认'],['succeeded','已完成']].map(([id,name])=><Action key={id} secondary={filter!==id} onClick={()=>{setFilter(id);setCursor('')}}>{name}</Action>)}</View><DataBoundary state={query}>{page=><>{page.items.map(item=><Card key={item.runId}><ListRow title={item.title} subtitle={formatTime(item.updatedAt)} icon='tasks' onClick={()=>void navigate('execution',{id:item.runId})} suffix={<Badge tone={item.status==='waiting_user'?'warning':item.status==='succeeded'?'success':'neutral'}>{labels[item.status]??item.status}</Badge>}/></Card>)}{!page.items.length&&<Empty title='当前筛选下暂无任务'/>}{page.nextCursor&&<Action secondary onClick={()=>setCursor(page.nextCursor)}>下一页</Action>}{cursor&&<Action secondary onClick={()=>setCursor('')}>回到第一页</Action>}</>}</DataBoundary>{query.error&&<Notice>当前基线尚缺任务集合读模型。下面的“本机最近打开”只是恢复索引，不代表完整任务列表。</Notice>}{pending&&<Card tone='warning'><Text className='wk-h3'>有一项提交仍待核对</Text><Text className='wk-muted'>{pending.requestId}</Text><Action secondary loading={action.busy} onClick={()=>void action.run(async()=>{const result=await executions.lookup(pending.requestId);pendingIntent().reconcile(result);if(result.run_id&&result.state==='admitted'){rememberRun(result.run_id);pendingIntent().acknowledge();await navigate('execution',{id:result.run_id})}else query.reload()})}>查询原请求</Action></Card>}<Section title='本机最近打开'/>{recentRuns().map(id=><Card key={id}><ListRow title='继续查看执行' subtitle={id} icon='tasks' onClick={()=>void navigate('execution',{id})}/></Card>)}<Card><Field label='通过已有任务 ID 恢复' value={lookupId} onChange={setLookupId}/><Action secondary disabled={!lookupId.trim()} onClick={()=>void navigate('execution',{id:lookupId.trim()})}>读取任务状态</Action><Text className='wk-muted wk-small'>服务端仍会验证任务归属，不会因知道 ID 而获得访问权限。</Text></Card>{action.error&&<Notice tone='danger'>{action.error}</Notice>}</Screen>;
}
export function ExecutionPage(){
 const id=routeParam('id');const [projection,setProjection]=useState<RunProjection>(),[connection,setConnection]=useState('同步中'),[error,setError]=useState<string>(),[instruction,setInstruction]=useState('');const current=useRef<AbortController>();const interval=useRef<ReturnType<typeof setInterval>>();const action=useAction();
 const stop=()=>{current.current?.abort();if(interval.current)clearInterval(interval.current)};
 const reload=useCallback(()=>{
  stop();if(auth.snapshot().phase!=='ready')return;const stamp=auth.scope.capture(),controller=new AbortController();current.current=controller;setError(undefined);setConnection('同步中');
  void watchExecution(id,controller.signal,value=>{if(!controller.signal.aborted&&auth.scope.isCurrent(stamp)){setProjection(value);setConnection(terminal(value.execution.run_status)?'已同步':'已连接')}}).catch(e=>{if(!controller.signal.aborted&&auth.scope.isCurrent(stamp)){setError(errorMessage(e));setConnection('连接中断，可恢复')}});
  interval.current=setInterval(()=>{void executions.get(id,controller.signal).then(execution=>{if(!controller.signal.aborted&&auth.scope.isCurrent(stamp)){setProjection(p=>p?{...p,execution}:p);if(terminal(execution.run_status)){setConnection('已同步');stop()}}}).catch(()=>{/* The stream state stays visible; next explicit refresh retries. */})},5000);
 },[id]);
 useEffect(()=>{reload();return stop},[reload]);useDidShow(reload);useDidHide(()=>{stop();setConnection('已暂停订阅')});
 const execution=projection?.execution;
 return <Screen title='执行详情'>{execution&&projection?<><Card tone='mint'><View className='wk-between'><Badge tone={execution.run_status==='waiting_user'?'warning':execution.run_status==='succeeded'?'success':'info'}>{labels[execution.run_status]}</Badge><Text className='wk-muted wk-small'>{connection}</Text></View><Text className='wk-display'>每一步，都有迹可循。</Text><Text className='wk-mono'>{id}</Text><View className='wk-meta'><Text>执行：{execution.execution_status}</Text><Text>结算：{execution.settlement_status}</Text><Text>已接收事件：{projection.cursor}</Text></View></Card>{execution.run_status==='waiting_user'&&<Card tone='warning'><Text className='wk-h2'>任务需要你的确认</Text><Text className='wk-muted'>核对动作与影响后，再决定如何继续。</Text><Action onClick={()=>void navigate('approval',{id})}>查看待处理事项</Action></Card>}<Section title='执行时间线'/><View className='wk-timeline'>{projection.events.map(event=><View className='wk-step' key={event.seq}><Text className='wk-h3'>{eventLabel(event)}</Text><Text className='wk-muted wk-small'>{formatTime(event.occurred_at)} · #{event.seq}</Text></View>)}</View><Card><Field label='追加指令' value={instruction} onChange={setInstruction} multiline placeholder='补充要求，不会重建任务'/><Action loading={action.busy} disabled={!instruction.trim()||execution.capabilities.steer?.state!=='supported'||terminal(execution.run_status)} onClick={()=>void action.run(async()=>{await executions.command(id,{action:'steer',text:instruction.trim(),expected_revision:execution.revision});setInstruction('');reload()})}>提交追加指令</Action><Text className='wk-muted wk-small'>{execution.capabilities.steer?.reason||'仅在服务端明确允许时可追加。'}</Text></Card><View className='wk-grid'><Action secondary onClick={()=>void navigate('artifact',{session:execution.session_id,run:id})}>查看产物</Action><Action danger disabled={execution.capabilities.cancel?.state!=='supported'||terminal(execution.run_status)} loading={action.busy} onClick={()=>void action.run(async()=>{if(!await confirmAction('取消这个任务？','这会向服务端发送取消命令，已发生的消耗不会因此自动退还。'))return;await executions.command(id,{action:'cancel',expected_revision:execution.revision});reload()})}>取消任务</Action></View></>:<Empty title='正在读取服务端快照' body='不会为了恢复页面重新启动任务。'/>}{error&&<Notice tone='warning'>{error}</Notice>}{action.error&&<Notice tone='danger'>{action.error}</Notice>}<Action secondary onClick={reload}>重新同步快照</Action></Screen>;
}
export function ApprovalPage(){
 const id=routeParam('id');const query=useData(`interactions:${id}`,()=>interactions(id));const action=useAction();
 return <Screen title='审批确认'><Text className='wk-display'>先看清影响，{ '\n' }再作出决定。</Text><Notice tone='warning'>当前接口尚未提供动作名称、目标资源和风险摘要，不能只凭参数哈希批准外部写操作。请在 Web 核验完整动作；此版本仅支持安全拒绝。</Notice><DataBoundary state={query}>{items=><>{items.map(item=><Card key={item.id} tone={item.decisionId?'white':'warning'}><View className='wk-between'><Text className='wk-h3'>{item.kind==='tool_approval'?'工具操作确认':item.kind==='budget'?'预算扩展':'执行恢复'}</Text><Badge tone={item.decisionId?'success':'warning'}>{item.decisionId?'已处理':'待处理'}</Badge></View><Text className='wk-mono'>事项：{item.id}</Text><Text className='wk-muted wk-small'>版本：{item.revision} · 决策与参数哈希绑定</Text>{item.kind==='tool_approval'&&!item.decisionId&&<><Action disabled>缺少动作详情，暂不可批准</Action><Action secondary loading={action.busy} onClick={()=>void action.run(async()=>{if(!await confirmAction('拒绝本次操作？','仅拒绝当前这一项工具操作，不扩大其他授权。'))return;await rejectInteraction(item);query.reload()})}>拒绝本次操作</Action></>}</Card>)}{!items.length&&<Empty title='当前没有待处理事项'/>}</>}</DataBoundary>{action.error&&<Notice tone='danger'>{action.error}</Notice>}<Action secondary onClick={()=>void navigate('execution',{id})}>返回任务</Action></Screen>;
}
export function ArtifactPage(){
 const session=routeParam('session'),run=routeParam('run');const query=useData(`artifacts:${session}`,signal=>client.chat.artifacts.session(session,signal),!!session);
 return <Screen title='任务产物'><Text className='wk-display'>把完成的工作，{ '\n' }留在手边。</Text><DataBoundary state={query}>{items=><>{items.map(file=><Card key={`${file.index}:${file.fileName}`}><ListRow title={file.fileName} subtitle={`${file.fileType??'文件'} · ${formatBytes(file.fileSize??0)}`} suffix={<Badge>已保存</Badge>}/>{file.expiresAt&&<Text className='wk-muted'>有效期：{formatTime(file.expiresAt)}</Text>}</Card>)}{!items.length&&<Empty title='暂时没有产物' body='任务可能仍在进行，或者没有生成可下载文件。'/>}</>}</DataBoundary><Notice>会话级产物索引没有携带 message_id。本版不猜测下载地址；请在 Web 工作台下载。HTML、脚本和终端内容不会在小程序中执行。</Notice>{run&&<Action secondary onClick={()=>void navigate('execution',{id:run})}>返回任务</Action>}</Screen>;
}
