-- No-op counterpart: on fresh chains the columns come from 000018, whose own
-- down migration removes them. Rolling back this version on a deployed fork
-- database would have dropped columns still referenced by fork features, so
-- the original down was already effectively unusable there.
