-- No-op since the upstream merge: upstream's 000018_session_fork already adds
-- the same five statements on fresh chains (both files mirror the versioned
-- session_fork migration). Deployed fork databases already applied this
-- version with its original content, so emptying it only affects fresh
-- chains, which get the schema from 000018. Keeping the version occupied
-- preserves schema_migrations history. SQLite lacks ADD COLUMN IF NOT
-- EXISTS, so a no-op is the only duplicate-safe form here.
