CREATE TABLE career_spaces (tenant_id INTEGER PRIMARY KEY, owner_user_id TEXT NOT NULL UNIQUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE career_profiles (tenant_id INTEGER NOT NULL, user_id TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (tenant_id, user_id));
CREATE TABLE career_facts (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant_id INTEGER NOT NULL, user_id TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, revision INTEGER NOT NULL, source TEXT NOT NULL, confirmation TEXT NOT NULL, request_id TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (tenant_id, user_id, key));
CREATE TABLE career_fact_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant_id INTEGER NOT NULL, user_id TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, revision INTEGER NOT NULL, source TEXT NOT NULL, confirmation TEXT NOT NULL, proposal_id TEXT NOT NULL DEFAULT '', request_id TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_career_fact_version_scope ON career_fact_versions (tenant_id, user_id, key, revision);
CREATE TABLE career_proposals (id INTEGER PRIMARY KEY AUTOINCREMENT, public_id TEXT NOT NULL UNIQUE, tenant_id INTEGER NOT NULL, user_id TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL, resolved_at DATETIME, resolved_revision INTEGER, confirmation TEXT NOT NULL DEFAULT '{}', resolution_source TEXT NOT NULL DEFAULT '{}', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_career_proposal_scope ON career_proposals (tenant_id, user_id, status, created_at);
CREATE TABLE career_changes (id INTEGER PRIMARY KEY AUTOINCREMENT, tenant_id INTEGER NOT NULL, user_id TEXT NOT NULL, revision INTEGER NOT NULL, kind TEXT NOT NULL, body TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (tenant_id, user_id, revision));
CREATE TABLE career_receipts (tenant_id INTEGER NOT NULL, user_id TEXT NOT NULL, request_id TEXT NOT NULL, fingerprint VARCHAR(64) NOT NULL, body TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (tenant_id, user_id, request_id));
