// Ported verbatim from frontend/src/i18n/locales/*.ts -> agentEditor block.
// The generated packages/i18n set does not carry agentEditor.* yet; these
// literals back the agent editor modal until the keys land there.
export const agentEditorFallback: Record<string, Record<string, string>> = {
  "zh-CN": {
    'agentEditor.fileTypes.label': "支持的文件类型",
    'agentEditor.fileTypes.desc': "限制可选择的文件类型，留空表示支持所有类型",
    'agentEditor.fileTypes.allTypes': "全部类型",
    'agentEditor.fileTypes.pdf': "PDF 文档",
    'agentEditor.fileTypes.word': "Word 文档 (.docx/.doc)",
    'agentEditor.fileTypes.textLabel': "文本",
    'agentEditor.fileTypes.text': "纯文本文件 (.txt)",
    'agentEditor.fileTypes.markdown': "Markdown 文档",
    'agentEditor.fileTypes.csv': "逗号分隔值文件",
    'agentEditor.fileTypes.excel': "Excel 表格 (.xlsx/.xls)",
    'agentEditor.fileTypes.imageLabel': "图片",
    'agentEditor.fileTypes.image': "图片文件 (.jpg/.jpeg/.png)",
    // R485 D1/D2 — question suggestions / attachment upload / MCP services /
    // agent type blocks (zh-CN.ts 1014-1105, 1323-1367)
    'agentEditor.questionSuggestions.navLabel': "问题推荐",
    'agentEditor.questionSuggestions.title': "对话问题推荐",
    'agentEditor.questionSuggestions.description': "统一配置开场问题与回答后的上下文追问；渠道可关闭展示，但不能改写智能体策略。",
    'agentEditor.questionSuggestions.startersTitle': "开场推荐",
    'agentEditor.questionSuggestions.followUpsTitle': "回答后推荐",
    'agentEditor.questionSuggestions.enableStarters': "展示开场问题",
    'agentEditor.questionSuggestions.enableStartersDesc': "在用户首次提问前展示，可使用运营配置、知识库或混合来源。",
    'agentEditor.questionSuggestions.enableFollowUps': "生成回答后推荐",
    'agentEditor.questionSuggestions.enableFollowUpsDesc': "每次完整回答结束后异步生成，不阻塞主回答。启用后会产生额外模型调用。",
    'agentEditor.questionSuggestions.sourceMode': "内容来源",
    'agentEditor.questionSuggestions.count': "展示数量",
    'agentEditor.questionSuggestions.curatedItems': "运营配置问题",
    'agentEditor.questionSuggestions.curatedItemsDesc': "用于开场推荐；混合模式下优先展示。",
    'agentEditor.questionSuggestions.addItem': "添加问题",
    'agentEditor.questionSuggestions.model': "生成模型",
    'agentEditor.questionSuggestions.modelDesc': "留空时使用本轮对话模型。",
    'agentEditor.questionSuggestions.advancedSettings': "高级生成设置",
    'agentEditor.questionSuggestions.displayRules': "展示与兜底规则",
    'agentEditor.questionSuggestions.contextTurns': "上下文轮数",
    'agentEditor.questionSuggestions.categories': "问题类型",
    'agentEditor.questionSuggestions.instruction': "附加生成要求",
    'agentEditor.questionSuggestions.instructionPlaceholder': "例如：优先推荐能帮助用户落地执行的问题，避免宽泛问题或重复当前回答…",
    'agentEditor.questionSuggestions.suppressFallback': "兜底回答后不展示",
    'agentEditor.questionSuggestions.suppressQuestion': "回答本身以提问结尾时不展示",
    'agentEditor.questionSuggestions.knowledgeFallback': "模型生成失败时使用知识库候选",
    'agentEditor.questionSuggestions.allowRegenerate': "允许用户换一批",
    'agentEditor.questionSuggestions.modeCurated': "运营配置",
    'agentEditor.questionSuggestions.modeKnowledge': "知识库",
    'agentEditor.questionSuggestions.modeGenerated': "模型生成",
    'agentEditor.questionSuggestions.modeHybrid': "混合",
    'agentEditor.questionSuggestions.categoryClarify': "澄清",
    'agentEditor.questionSuggestions.categoryDeepen': "深入",
    'agentEditor.questionSuggestions.categoryAction': "下一步",
    'agentEditor.imageUpload.navLabel': "附件上传",
    'agentEditor.imageUpload.sectionTitle': "附件上传",
    'agentEditor.imageUpload.sectionDesc': "配置对话中图片、文档、音频等附件的上传、解析及对应模型",
    'agentEditor.imageUpload.label': "图片上传",
    'agentEditor.imageUpload.desc': "启用后用户可在对话中上传图片并由 VLM 理解",
    'agentEditor.imageUpload.vlmModel': "VLM 模型",
    'agentEditor.imageUpload.vlmModelDesc': "用于图片分析的视觉语言模型",
    'agentEditor.imageUpload.vlmModelPlaceholder': "请选择 VLM 模型",
    'agentEditor.imageUpload.imageUnderstandingLabel': "附件图片理解 / 扫描件 OCR",
    'agentEditor.imageUpload.imageUnderstandingDesc': "对图片型 PDF/PPT 等扫描件，当解析不出文字时用 VLM 进行 OCR 识别。开启会增加解析耗时，默认关闭。",
    'agentEditor.imageUpload.ocrMaxPagesLabel': "扫描件 OCR 最大页数",
    'agentEditor.imageUpload.ocrMaxPagesDesc': "扫描件送入 VLM 做 OCR 的最大页数，越多覆盖越全但越慢、越贵。0 表示使用全局默认。",
    'agentEditor.imageUpload.useGlobalDefault': "0 = 全局默认",
    'agentEditor.imageUpload.storageProvider': "图片存储",
    'agentEditor.imageUpload.storageProviderDesc': "选择图片文件的存储引擎，留空则使用系统默认",
    'agentEditor.imageUpload.storageProviderPlaceholder': "选择存储引擎",
    'agentEditor.imageUpload.storageDefault': "系统默认",
    'agentEditor.imageUpload.notConfigured': "未配置",
    'agentEditor.imageUpload.goStorageSettings': "去存储设置中配置",
    'agentEditor.audioUpload.label': "语音上传",
    'agentEditor.audioUpload.desc': "启用后用户可在对话中上传音频文件，系统将使用 ASR 模型自动转录为文字",
    'agentEditor.audioUpload.asrModel': "ASR 模型",
    'agentEditor.audioUpload.asrModelDesc': "用于音频转录的语音识别模型，未配置时音频文件将以占位符形式传递",
    'agentEditor.audioUpload.asrModelPlaceholder': "请选择 ASR 模型",
    'agentEditor.chatParser.label': "聊天附件解析策略",
    'agentEditor.chatParser.desc': "为不同文件类型指定解析引擎，仅对当前智能体的聊天附件生效",
    'agentEditor.chatParser.waitTimeoutLabel': "附件解析等待超时（秒）",
    'agentEditor.chatParser.waitTimeoutDesc': "单轮问答等待附件解析完成的最长时间，超时后未完成的附件会被跳过。大文件 / 扫描件可调大。0 表示使用全局默认。",
    'agentEditor.imageUpload.engineLocal': "Local（本地）",
    'agentEditor.imageUpload.engineCos': "腾讯云 COS",
    'agentEditor.imageUpload.engineTos': "火山引擎 TOS",
    'agentEditor.imageUpload.engineOss': "阿里云 OSS",
    'agentEditor.mcp.label': "MCP 服务",
    'agentEditor.mcp.desc': "选择 Agent 可以调用的 MCP 服务",
    'agentEditor.mcp.selectLabel': "选择 MCP 服务",
    'agentEditor.mcp.selectDesc': "选择要启用的 MCP 服务",
    'agentEditor.mcp.selectPlaceholder': "选择 MCP 服务",
    'agentEditor.mcp.authWaitTimeout': "授权等待超时（秒）",
    'agentEditor.mcp.authWaitTimeoutDesc': "对话中触发 OAuth 授权时，等待你完成授权的最长秒数，超时后自动跳过授权提示（仅对使用 OAuth 的 MCP 服务生效）。",
    'agentEditor.mcp.authWaitTimeoutPlaceholder': "默认 600 秒",
    'agentEditor.mcp.unavailableService': "不可用服务",
    'mcpSettings.disabled': "已禁用",
    'agentEditor.agentType.label': "智能体类型",
    'agentEditor.agentType.desc': "选择一个预设会自动填充系统提示词、工具列表和推荐的知识库范围。",
    'agentEditor.agentType.defaultNamePattern': "我的{label}",
    'agentEditor.agentType.kbIncompatibleWarn': "已选的 {count} 个知识库不适用于当前类型，请手动调整",
    'agentEditor.agentType.kbMismatch.ragQa': "未启用 RAG 检索",
    'agentEditor.agentType.kbMismatch.wikiQa': "未启用 Wiki",
    'agentEditor.agentType.kbMismatch.hybridRagWiki': "未启用任何检索能力",
    'agentEditor.agentType.kbMismatch.dataAnalysis': "需启用 RAG（不支持 FAQ）",
    'agentEditor.agentType.kbMismatch.quickAnswer': "快速问答模式需启用 RAG 检索",
    'agentEditor.agentType.kbMismatch.generic': "不适用于当前类型",
    'agentEditor.llmCallTimeout.label': 'LLM 调用超时',
    'agentEditor.llmCallTimeout.desc': '单次 LLM 调用的最大等待时间（秒），超过此时间后调用将被中止',
    'agentEditor.llmCallTimeout.hint': '留空或填 0 表示使用默认值（120 秒）',
    'agentEditor.llmCallTimeout.placeholder': '输入秒数，建议范围 60-1800',
    'agentEditor.desc.maxTokens': '模型生成回复的最大 Token 数。选「默认」时为 2048；选「自定义」后按你填的数保存。',
    'agentEditor.desc.maxTokensAgent': '每一轮推理的最大生成 Token（含工具调用 JSON）。选「默认」时，未绑沙箱为 4096，绑了沙箱（可写/改文件）为 24576。选「自定义」后按你填的数保存，不再自动改。',
    'agentEditor.desc.conversationSection': '配置多轮对话开关与问题改写开关（改写提示词见「提示词」）',
    'agentEditor.desc.conversationSectionAgent': '配置每轮携带多少历史对话。智能推理始终为多轮模式。',
    'agentEditor.desc.retainRetrievalHistory': '保留此前轮次的知识库检索结果。关闭时每轮重新检索',
    'agentEditor.navGroups.basic': '基础',
    'agentEditor.navGroups.knowledge': '知识检索',
    'agentEditor.navGroups.capability': '能力扩展',
    'agentEditor.navGroups.integration': '发布集成',
    'agentEditor.fallback.fixed': '固定回复',
    'agentEditor.fallback.model': '模型生成',
    'agentEditor.selection.all': '全部',
    'agentEditor.selection.selected': '指定',
    'agentEditor.selection.disabled': '禁用',
    'agentEditor.placeholders.available': '可用变量：',
    'agentEditor.placeholders.hint': '（点击插入，或输入 {{ 唤起列表）',
    // R486 D4 — PromptTemplateSelector controls (frontend zh-CN.ts 2043-2052)
    'agentEditor.placeholders.clickToInsert': '（点击插入）',
    'promptTemplate.resetDefault': '恢复默认',
    'promptTemplate.useTemplate': '使用模板',
    'promptTemplate.selectTemplate': '选择模板',
    'promptTemplate.noTemplates': '暂无模板',
    'promptTemplate.default': '默认',
    'agentEditor.builtinHint': '这是内置智能体，名称和描述不可修改，但可以调整配置参数',
    'agentEditor.tools.groupBase': '基础',
    'agentEditor.tools.groupRag': '知识库检索（RAG）',
    'agentEditor.tools.groupWikiRead': 'Wiki 读取',
    'agentEditor.tools.groupWikiEdit': 'Wiki 编辑',
    'agentEditor.tools.groupWikiIssue': 'Wiki 巡检',
    'agentEditor.tools.groupData': '数据分析',
    'agentEditor.tools.thinking': '思考',
    'agentEditor.tools.thinkingDesc': '动态和反思性的问题解决思考工具',
    'agentEditor.tools.todoWrite': '制定计划',
    'agentEditor.tools.todoWriteDesc': '创建结构化的研究计划',
    'agentEditor.tools.grepChunks': '关键词搜索',
    'agentEditor.tools.grepChunksDesc': '快速定位包含特定关键词的文档和分块',
    'agentEditor.tools.knowledgeSearch': '语义搜索',
    'agentEditor.tools.knowledgeSearchDesc': '理解问题并查找语义相关内容',
    'agentEditor.tools.listChunks': '查看文档分块',
    'agentEditor.tools.listChunksDesc': '获取文档完整分块内容',
    'agentEditor.tools.queryGraph': '查询知识图谱',
    'agentEditor.tools.queryGraphDesc': '从知识图谱中查询关系',
    'agentEditor.tools.getDocInfo': '获取文档信息',
    'agentEditor.tools.getDocInfoDesc': '查看文档元数据',
    'agentEditor.tools.dbQuery': '查询数据库',
    'agentEditor.tools.dbQueryDesc': '查询数据库中的信息',
    'agentEditor.tools.dataAnalysis': '数据分析',
    'agentEditor.tools.dataAnalysisDesc': '理解数据文件并进行数据分析',
    'agentEditor.tools.dataSchema': '查看数据元信息',
    'agentEditor.tools.dataSchemaDesc': '获取表格文件的元信息',
    'agentEditor.tools.wikiSearch': '搜索 Wiki',
    'agentEditor.tools.wikiSearchDesc': '在 Wiki 知识库中按关键词/语义搜索页面',
    'agentEditor.tools.wikiReadPage': '阅读 Wiki 页面',
    'agentEditor.tools.wikiReadPageDesc': '读取指定 Wiki 页面的完整内容',
    'agentEditor.tools.wikiReadSourceDoc': '精读源文档',
    'agentEditor.tools.wikiReadSourceDocDesc': '通过知识点深入阅读 Wiki 页面背后的原始文档',
    'agentEditor.tools.wikiFlagIssue': '标记 Wiki 问题',
    'agentEditor.tools.wikiFlagIssueDesc': '标记页面中存在的事实错误或合并冲突问题',
    'agentEditor.tools.wikiWritePage': '创建/覆盖 Wiki',
    'agentEditor.tools.wikiWritePageDesc': '创建新页面或完全覆盖已有 Wiki 页面',
    'agentEditor.tools.wikiReplaceText': '局部替换 Wiki',
    'agentEditor.tools.wikiReplaceTextDesc': '替换 Wiki 页面中的特定文本',
    'agentEditor.tools.wikiRenamePage': '重命名 Wiki',
    'agentEditor.tools.wikiRenamePageDesc': '重命名 Wiki 页面并自动更新关联链接',
    'agentEditor.tools.wikiDeletePage': '删除 Wiki',
    'agentEditor.tools.wikiDeletePageDesc': '删除 Wiki 页面并自动清理关联死链',
    'agentEditor.tools.wikiReadIssue': '查看 Wiki 问题',
    'agentEditor.tools.wikiReadIssueDesc': '查看特定 Wiki 页面的巡检问题详情',
    'agentEditor.tools.wikiUpdateIssue': '更新 Wiki 问题',
    'agentEditor.tools.wikiUpdateIssueDesc': '更新 Wiki 页面问题的处理状态',
    'agentEditor.tools.webSearch': '网络搜索',
    'agentEditor.tools.webFetch': '网页抓取',
    'agentEditor.tools.requiresKb': '（需要配置知识库）',
    'agentEditor.tools.requiresWikiKb': '（需要关联启用 Wiki 能力的知识库）',
    'agentEditor.tools.requiresRagKb': '（需要关联启用向量/关键词索引的知识库）',
    'agentEditor.tools.dangerTag': '可写',
    'agentEditor.tools.writeWarning': '会修改 Wiki 内容',
    'agentEditor.tools.statusNoKb': '当前未关联任何知识库',
    'agentEditor.tools.kbMetricRag': 'RAG 知识库',
    'agentEditor.tools.kbMetricWiki': 'Wiki 知识库',
    'agentEditor.tools.statusInactive': '有 {count} 个已勾选工具在当前配置下无法生效',
    'agentEditor.tools.effectiveLabel': '最终启用的工具',
    'agentEditor.tools.effectiveDesc': '根据当前配置计算，这是智能体保存后实际能调用的工具集合',
    'agentEditor.tools.effectiveEmpty': '当前没有可用工具，智能体将退化为纯模型问答',
    'agentEditor.desc.name': '为智能体设置一个易于识别的名称',
    'agentEditor.desc.description': '简要描述智能体的用途和特点',
    'agentEditor.desc.systemPrompt': '自定义系统提示词，定义智能体的行为和角色',
    'agentEditor.desc.leaveEmptyDefault': '（留空则使用系统默认）',
    'agentEditor.desc.contextTemplate': '定义如何将检索到的内容格式化后传递给模型',
    'agentEditor.desc.model': '选择智能体使用的大语言模型',
    'agentEditor.desc.temperature': '控制输出的随机性，0 最确定，1 最随机',
    'agentEditor.desc.thinking': '启用模型的扩展思考能力（需要模型支持）',
    'agentEditor.desc.multiTurn': '开启后将保留历史对话上下文',
    'agentEditor.desc.historyRounds': '保留最近几轮对话作为上下文',
    'agentEditor.desc.rewrite': '多轮对话时自动改写用户问题，消解指代和补全省略',
    'agentEditor.desc.memoryEnabled': '允许该智能体读取并补充你的长期记忆。关闭后，与它的对话既不会读取记忆，也不会新增记忆。空间或个人设置关闭时，这里开启也不会生效',
    'agentEditor.desc.queryUnderstandModel': '用于问题理解（改写与意图识别）的模型，留空则复用主对话模型',
    'agentEditor.desc.selectTools': '选择 Agent 可以使用的工具',
    'agentEditor.desc.maxIterations': '限制 Agent 单次任务的推理步数。选「不限制」时会一直跑到模型自然结束或你手动停止。',
    'agentEditor.desc.kbScope': '选择智能体可访问的知识库范围',
    'agentEditor.desc.webSearch': '启用后智能体可以搜索互联网获取信息',
    'agentEditor.desc.webSearchProvider': '为此智能体指定搜索引擎，留空则使用默认搜索引擎',
    'agentEditor.desc.webSearchMaxResults': '每次搜索返回的最大结果数量',
    'agentEditor.desc.webFetchEnabled': 'Rerank 后自动抓取排名靠前的网页完整内容，提升回答质量',
    'agentEditor.desc.webFetchTopN': 'Rerank 后最多抓取几个网页的完整内容',
    'agentEditor.desc.retrievalSection': '配置知识库检索召回、排序与 FAQ 优先策略（ReRank 模型见「模型配置」）',
    'agentEditor.desc.queryExpansion': '自动扩展查询词以提高召回率',
    'agentEditor.desc.embeddingTopK': '向量检索返回的最大结果数量',
    'agentEditor.desc.keywordThreshold': '关键词检索的最低相关性分数',
    'agentEditor.desc.vectorThreshold': '向量检索的最低相似度分数',
    'agentEditor.desc.rerankTopK': '重排序后保留的最大结果数量',
    'agentEditor.desc.rerankThreshold': '重排序的最低相关性分数',
    'agentEditor.desc.fallbackStrategy': '当无法从知识库找到相关内容时的处理方式',
    'agentEditor.desc.fallbackResponse': '当无法回答时返回的固定文本',
    'agentEditor.desc.fallbackPrompt': '当无法从知识库找到答案时，引导模型生成回复的提示词',
    'agentEditor.desc.rewriteSystemPrompt': '用于问题改写的系统提示词（留空使用默认）',
    'agentEditor.desc.rewriteUserPrompt': '用于问题改写的用户提示词模板（留空使用默认）',
    'agentEditor.faq.enableLabel': '启用 FAQ 优先',
    'agentEditor.faq.enableDesc': 'FAQ 答案将优先于普通文档被引用，提高回答准确性',
    'agentEditor.faq.thresholdLabel': '直接回答阈值',
    'agentEditor.faq.thresholdDesc': '当问题与 FAQ 相似度超过此值时，直接使用 FAQ 答案',
    'agentEditor.faq.boostLabel': 'FAQ 分数加权',
    'agentEditor.faq.boostDesc': 'FAQ 结果的相关性分数乘以此系数，使其排序更靠前',
    'agentEditor.personalization.title': '个性化',
    'agentEditor.personalization.desc': '为智能体选择 MBTI 人格类型并补充表达风格，塑造其回复的语气与性格',
    'agentEditor.personalization.mbtiLabel': '人格类型',
    'agentEditor.personalization.mbtiDesc': '选择一种 16 型人格，选「无」则保持默认回复风格',
    'agentEditor.personalization.noneLabel': '无',
    'agentEditor.personalization.noneDesc': '不设置人格，保持默认回复风格',
    'agentEditor.personalization.dimensionsLabel': '维度倾向',
    'agentEditor.personalization.styleLabel': '补充风格',
    'agentEditor.personalization.styleDesc': '可选。补充语气、口头禅等要求，与所选人格一起生效',
    'agentEditor.personalization.stylePlaceholder': '例如：语气轻松一些，多用类比解释复杂概念',
    'agentEditor.personalization.takeTest': '做个测试',
    'agentEditor.personalization.takeTestHint': '测试功能即将开放',
    'agentEditor.personalization.loadFailed': '人格类型加载失败',
    'agentEditor.personalization.unknownType': '当前保存的类型 {code} 不在类型列表中',
    'agentEditor.personalization.testTitle': 'MBTI 人格测试',
    'agentEditor.personalization.testIntroDesc': '共 28 道二选一题目，约需 3 分钟。答案没有对错之分，凭第一直觉作答即可。',
    'agentEditor.personalization.testDisclaimer': '测试结果仅供娱乐参考',
    'agentEditor.personalization.testStart': '开始测试',
    'agentEditor.personalization.testProgress': '已答 {answered} / {total}',
    'agentEditor.personalization.testSubmit': '查看结果',
    'agentEditor.personalization.testLoadFailed': '题目加载失败',
    'agentEditor.personalization.testSubmitError': '提交失败，请重试',
    'agentEditor.personalization.testResultTitle': '测试结果',
    'agentEditor.personalization.testApply': '应用到该 Agent',
    'agentEditor.subagents.title': '子智能体',
    'agentEditor.subagents.desc': '为智能体安装内置子智能体角色；主智能体可将任务委派给已安装的角色，未安装任何角色时委派关闭',
    'agentEditor.subagents.installedLabel': '已安装角色',
    'agentEditor.subagents.delegationOff': '尚未安装任何子智能体，委派能力处于关闭状态',
    'agentEditor.subagents.catalogLabel': '角色目录',
    'agentEditor.subagents.needSave': '新建的智能体需先保存，才能安装子智能体',
    'agentEditor.subagents.allDivisions': '全部',
    'agentEditor.subagents.searchPlaceholder': '搜索角色（名称或标识）',
    'agentEditor.subagents.emptyCatalog': '角色目录为空',
    'agentEditor.subagents.noMatch': '没有匹配的角色',
    'agentEditor.subagents.loadFailed': '角色目录加载失败',
    'agentEditor.subagents.actionFailed': '操作失败，请重试',
    'agentEditor.subagents.install': '安装',
    'agentEditor.subagents.remove': '移除',
    'agentEditor.subagents.installedTag': '已安装',
    'agentEditor.subagents.detailFailed': '角色详情加载失败',
  },
  "en-US": {
    'agentEditor.fileTypes.label': "Supported File Types",
    'agentEditor.fileTypes.desc': "Restrict selectable file types, leave empty to support all types",
    'agentEditor.fileTypes.allTypes': "All Types",
    'agentEditor.fileTypes.pdf': "PDF Documents",
    'agentEditor.fileTypes.word': "Word Documents (.docx/.doc)",
    'agentEditor.fileTypes.textLabel': "Text",
    'agentEditor.fileTypes.text': "Plain Text Files (.txt)",
    'agentEditor.fileTypes.markdown': "Markdown Documents",
    'agentEditor.fileTypes.csv': "Comma-Separated Value Files",
    'agentEditor.fileTypes.excel': "Excel Spreadsheets (.xlsx/.xls)",
    'agentEditor.fileTypes.imageLabel': "Images",
    'agentEditor.fileTypes.image': "Image Files (.jpg/.jpeg/.png)",
    // R485 D1/D2 — three-section + agent-type keys (en-US.ts 5917-5959, 6184-6252)
    'agentEditor.questionSuggestions.navLabel': "Question suggestions",
    'agentEditor.questionSuggestions.title': "Conversation question suggestions",
    'agentEditor.questionSuggestions.description': "Configure starters and contextual follow-ups in one agent-owned policy. Channels may hide them but cannot override the policy.",
    'agentEditor.questionSuggestions.startersTitle': "Conversation starters",
    'agentEditor.questionSuggestions.followUpsTitle': "After-answer follow-ups",
    'agentEditor.questionSuggestions.enableStarters': "Show starter questions",
    'agentEditor.questionSuggestions.enableStartersDesc': "Shown before the first user message from curated, knowledge, or mixed sources.",
    'agentEditor.questionSuggestions.enableFollowUps': "Generate follow-up questions",
    'agentEditor.questionSuggestions.enableFollowUpsDesc': "Generated asynchronously after every completed answer. Enabling this adds model usage.",
    'agentEditor.questionSuggestions.sourceMode': "Source mode",
    'agentEditor.questionSuggestions.count': "Question count",
    'agentEditor.questionSuggestions.curatedItems': "Curated questions",
    'agentEditor.questionSuggestions.curatedItemsDesc': "Used for starters and prioritized in hybrid mode.",
    'agentEditor.questionSuggestions.addItem': "Add question",
    'agentEditor.questionSuggestions.model': "Generation model",
    'agentEditor.questionSuggestions.modelDesc': "Uses the model from the completed turn when empty.",
    'agentEditor.questionSuggestions.advancedSettings': "Advanced generation settings",
    'agentEditor.questionSuggestions.displayRules': "Display and fallback rules",
    'agentEditor.questionSuggestions.contextTurns': "Context turns",
    'agentEditor.questionSuggestions.categories': "Question types",
    'agentEditor.questionSuggestions.instruction': "Additional instruction",
    'agentEditor.questionSuggestions.instructionPlaceholder': "For example: prioritize practical next-step questions and avoid broad questions or repeating the answer…",
    'agentEditor.questionSuggestions.suppressFallback': "Hide after fallback answers",
    'agentEditor.questionSuggestions.suppressQuestion': "Hide when the answer ends with a question",
    'agentEditor.questionSuggestions.knowledgeFallback': "Use knowledge candidates if generation fails",
    'agentEditor.questionSuggestions.allowRegenerate': "Allow users to regenerate",
    'agentEditor.questionSuggestions.modeCurated': "Curated",
    'agentEditor.questionSuggestions.modeKnowledge': "Knowledge",
    'agentEditor.questionSuggestions.modeGenerated': "Generated",
    'agentEditor.questionSuggestions.modeHybrid': "Hybrid",
    'agentEditor.questionSuggestions.categoryClarify': "Clarify",
    'agentEditor.questionSuggestions.categoryDeepen': "Deepen",
    'agentEditor.questionSuggestions.categoryAction': "Next step",
    'agentEditor.imageUpload.navLabel': "Attachment Upload",
    'agentEditor.imageUpload.sectionTitle': "Attachment Upload",
    'agentEditor.imageUpload.sectionDesc': "Configure image, document, and audio attachments in chat, plus parse rules and related models",
    'agentEditor.imageUpload.label': "Image Upload",
    'agentEditor.imageUpload.desc': "Allow users to upload images in chat for VLM understanding",
    'agentEditor.imageUpload.vlmModel': "VLM Model",
    'agentEditor.imageUpload.vlmModelDesc': "Vision language model for image analysis",
    'agentEditor.imageUpload.vlmModelPlaceholder': "Select VLM model",
    'agentEditor.imageUpload.imageUnderstandingLabel': "Attachment Image Understanding / Scanned OCR",
    'agentEditor.imageUpload.imageUnderstandingDesc': "For image-only PDFs/PPTs (scanned documents), run VLM OCR when no text can be extracted. Increases parse latency; off by default.",
    'agentEditor.imageUpload.ocrMaxPagesLabel': "Scanned OCR Max Pages",
    'agentEditor.imageUpload.ocrMaxPagesDesc': "Max pages of a scanned document sent to the VLM for OCR. More pages means better coverage but slower and costlier parsing. 0 uses the global default.",
    'agentEditor.imageUpload.useGlobalDefault': "0 = global default",
    'agentEditor.imageUpload.storageProvider': "Image Storage",
    'agentEditor.imageUpload.storageProviderDesc': "Storage engine for uploaded images. Leave empty to use system default",
    'agentEditor.imageUpload.storageProviderPlaceholder': "Select storage engine",
    'agentEditor.imageUpload.storageDefault': "System Default",
    'agentEditor.imageUpload.notConfigured': "Not Configured",
    'agentEditor.imageUpload.goStorageSettings': "Go to Storage Settings",
    'agentEditor.audioUpload.label': "Audio Upload",
    'agentEditor.audioUpload.desc': "When enabled, users can upload audio files in conversations. The system will automatically transcribe them using the ASR model.",
    'agentEditor.audioUpload.asrModel': "ASR Model",
    'agentEditor.audioUpload.asrModelDesc': "Speech recognition model for audio transcription. If not configured, audio files will be passed as placeholders.",
    'agentEditor.audioUpload.asrModelPlaceholder': "Select ASR Model",
    'agentEditor.chatParser.label': "Chat Attachment Parsing Policy",
    'agentEditor.chatParser.desc': "Choose a parser engine per file type for this agent's chat attachments.",
    'agentEditor.chatParser.waitTimeoutLabel': "Attachment Parse Wait Timeout (s)",
    'agentEditor.chatParser.waitTimeoutDesc': "How long a chat turn waits for still-parsing attachments before proceeding with only the finished ones. Raise for large / scanned files. 0 uses the global default.",
    'agentEditor.imageUpload.engineLocal': "Local",
    'agentEditor.imageUpload.engineCos': "Tencent Cloud COS",
    'agentEditor.imageUpload.engineTos': "Volcengine TOS",
    'agentEditor.imageUpload.engineOss': "Alibaba Cloud OSS",
    'agentEditor.mcp.label': "MCP Services",
    'agentEditor.mcp.desc': "Select MCP services available to the Agent",
    'agentEditor.mcp.selectLabel': "Select MCP Services",
    'agentEditor.mcp.selectDesc': "Select MCP services to enable",
    'agentEditor.mcp.selectPlaceholder': "Select MCP services",
    'agentEditor.mcp.authWaitTimeout': "Authentication Wait Timeout (s)",
    'agentEditor.mcp.authWaitTimeoutDesc': "Maximum seconds to wait for you to complete OAuth authentication when prompted during a conversation; the prompt is skipped after it elapses (only affects OAuth MCP services).",
    'agentEditor.mcp.authWaitTimeoutPlaceholder': "Default 600 seconds",
    'agentEditor.mcp.unavailableService': "Unavailable service",
    'mcpSettings.disabled': "Disabled",
    'agentEditor.agentType.label': "Agent Type",
    'agentEditor.agentType.desc': "Picking a preset auto-fills the system prompt, tool list and recommended KB scope.",
    'agentEditor.agentType.defaultNamePattern': "My {label}",
    'agentEditor.agentType.kbIncompatibleWarn': "{count} selected KB(s) are not compatible with this type, please adjust manually.",
    'agentEditor.agentType.kbMismatch.ragQa': "RAG retrieval not enabled",
    'agentEditor.agentType.kbMismatch.wikiQa': "Wiki not enabled",
    'agentEditor.agentType.kbMismatch.hybridRagWiki': "No retrieval surface enabled",
    'agentEditor.agentType.kbMismatch.dataAnalysis': "Requires RAG (FAQ not supported)",
    'agentEditor.agentType.kbMismatch.quickAnswer': "Quick Answer mode requires RAG retrieval",
    'agentEditor.agentType.kbMismatch.generic': "Not compatible with current type",
    'agentEditor.llmCallTimeout.label': 'LLM Call Timeout',
    'agentEditor.llmCallTimeout.desc': 'Maximum waiting time for a single LLM call (seconds). Call will be terminated if this time is exceeded',
    'agentEditor.llmCallTimeout.hint': 'Leave empty or 0 to use the default (120 seconds)',
    'agentEditor.llmCallTimeout.placeholder': 'Enter seconds, recommended range 60-1800',
    'agentEditor.desc.maxTokens': 'Maximum tokens for the model reply. Default is 2048. Custom values are saved as entered.',
    'agentEditor.desc.maxTokensAgent': 'Maximum tokens generated in each reasoning round, including tool-call JSON. Default is 4096 without a sandbox, or 24576 when a sandbox can write or edit files. A custom value is saved as entered and is not changed later.',
    'agentEditor.desc.conversationSection': 'Configure multi-turn conversation and query rewriting parameters',
    'agentEditor.desc.conversationSectionAgent': 'How much earlier conversation each turn carries. Smart reasoning is always multi-turn',
    'agentEditor.desc.retainRetrievalHistory': 'Keep knowledge base results from earlier turns. When off, each turn searches again',
    'agentEditor.navGroups.basic': 'Basics',
    'agentEditor.navGroups.knowledge': 'Knowledge & Retrieval',
    'agentEditor.navGroups.capability': 'Extensions',
    'agentEditor.navGroups.integration': 'Publish & Integrations',
    'agentEditor.fallback.fixed': 'Fixed Response',
    'agentEditor.fallback.model': 'Model Generated',
    'agentEditor.selection.all': 'All',
    'agentEditor.selection.selected': 'Selected',
    'agentEditor.selection.disabled': 'Disabled',
    'agentEditor.placeholders.available': 'Available variables: ',
    'agentEditor.placeholders.hint': '(click to insert, or type {{ to show list)',
    // R486 D4 — PromptTemplateSelector controls (frontend en-US.ts 5222-5230)
    'agentEditor.placeholders.clickToInsert': '(click to insert)',
    'promptTemplate.resetDefault': 'Reset Default',
    'promptTemplate.useTemplate': 'Use Template',
    'promptTemplate.selectTemplate': 'Select Template',
    'promptTemplate.noTemplates': 'No templates available',
    'promptTemplate.default': 'Default',
    'agentEditor.builtinHint': 'This is a built-in agent. Name and description cannot be modified, but configuration parameters can be adjusted.',
    'agentEditor.tools.groupBase': 'Basic',
    'agentEditor.tools.groupRag': 'Knowledge Retrieval (RAG)',
    'agentEditor.tools.groupWikiRead': 'Wiki Read',
    'agentEditor.tools.groupWikiEdit': 'Wiki Edit',
    'agentEditor.tools.groupWikiIssue': 'Wiki Review',
    'agentEditor.tools.groupData': 'Data Analysis',
    'agentEditor.tools.thinking': 'Thinking',
    'agentEditor.tools.thinkingDesc': 'Dynamic and reflective problem-solving thinking tool',
    'agentEditor.tools.todoWrite': 'Plan',
    'agentEditor.tools.todoWriteDesc': 'Create structured research plans',
    'agentEditor.tools.grepChunks': 'Keyword Search',
    'agentEditor.tools.grepChunksDesc': 'Quickly locate documents and chunks containing specific keywords',
    'agentEditor.tools.knowledgeSearch': 'Semantic Search',
    'agentEditor.tools.knowledgeSearchDesc': 'Understand questions and find semantically relevant content',
    'agentEditor.tools.listChunks': 'View Document Chunks',
    'agentEditor.tools.listChunksDesc': 'Get complete chunk content of a document',
    'agentEditor.tools.queryGraph': 'Query Knowledge Graph',
    'agentEditor.tools.queryGraphDesc': 'Query relationships from knowledge graph',
    'agentEditor.tools.getDocInfo': 'Get Document Info',
    'agentEditor.tools.getDocInfoDesc': 'View document metadata',
    'agentEditor.tools.dbQuery': 'Query Database',
    'agentEditor.tools.dbQueryDesc': 'Query information from the database',
    'agentEditor.tools.dataAnalysis': 'Data Analysis',
    'agentEditor.tools.dataAnalysisDesc': 'Understand data files and perform data analysis',
    'agentEditor.tools.dataSchema': 'View Data Schema',
    'agentEditor.tools.dataSchemaDesc': 'Get metadata of tabular files',
    'agentEditor.tools.wikiSearch': 'Search Wiki',
    'agentEditor.tools.wikiSearchDesc': 'Keyword / semantic search over Wiki pages',
    'agentEditor.tools.wikiReadPage': 'Read Wiki Page',
    'agentEditor.tools.wikiReadPageDesc': 'Read the full content of a specific Wiki page',
    'agentEditor.tools.wikiReadSourceDoc': 'Deep-read Source Doc',
    'agentEditor.tools.wikiReadSourceDocDesc': 'Dive into the original documents that a Wiki page is built from',
    'agentEditor.tools.wikiFlagIssue': 'Flag Wiki Issue',
    'agentEditor.tools.wikiFlagIssueDesc': 'Flag factual errors or merge conflicts on a Wiki page',
    'agentEditor.tools.wikiWritePage': 'Create / Overwrite Wiki',
    'agentEditor.tools.wikiWritePageDesc': 'Create a new page or fully overwrite an existing one',
    'agentEditor.tools.wikiReplaceText': 'Replace Text in Wiki',
    'agentEditor.tools.wikiReplaceTextDesc': 'Replace specific text in a Wiki page',
    'agentEditor.tools.wikiRenamePage': 'Rename Wiki Page',
    'agentEditor.tools.wikiRenamePageDesc': 'Rename a Wiki page and auto-update cross-links',
    'agentEditor.tools.wikiDeletePage': 'Delete Wiki Page',
    'agentEditor.tools.wikiDeletePageDesc': 'Delete a Wiki page and clean up dead links',
    'agentEditor.tools.wikiReadIssue': 'View Wiki Issue',
    'agentEditor.tools.wikiReadIssueDesc': 'View details of a Wiki page issue',
    'agentEditor.tools.wikiUpdateIssue': 'Update Wiki Issue',
    'agentEditor.tools.wikiUpdateIssueDesc': 'Update the status of a Wiki page issue',
    'agentEditor.tools.webSearch': 'Web Search',
    'agentEditor.tools.webFetch': 'Web Fetch',
    'agentEditor.tools.requiresKb': '(requires knowledge base configuration)',
    'agentEditor.tools.requiresWikiKb': '(requires a Wiki-enabled knowledge base)',
    'agentEditor.tools.requiresRagKb': '(requires a KB with vector/keyword indexing enabled)',
    'agentEditor.tools.dangerTag': 'Write',
    'agentEditor.tools.writeWarning': 'Mutates Wiki content',
    'agentEditor.tools.statusNoKb': 'No knowledge base is linked',
    'agentEditor.tools.kbMetricRag': 'RAG KBs',
    'agentEditor.tools.kbMetricWiki': 'Wiki KBs',
    'agentEditor.tools.statusInactive': '{count} ticked tool(s) cannot take effect with the current config',
    'agentEditor.tools.effectiveLabel': 'Effective Tools',
    'agentEditor.tools.effectiveDesc': 'Computed from the current config — these are the tools the agent will actually be able to call',
    'agentEditor.tools.effectiveEmpty': 'No tool available — the agent will fall back to plain model chat',
    'agentEditor.desc.name': 'Set an easily identifiable name for the agent',
    'agentEditor.desc.description': 'Briefly describe the purpose and features of the agent',
    'agentEditor.desc.systemPrompt': 'Custom system prompt to define the agent behavior and role',
    'agentEditor.desc.leaveEmptyDefault': '(leave empty to use system default)',
    'agentEditor.desc.contextTemplate': 'Define how retrieved content is formatted before passing to the model',
    'agentEditor.desc.model': 'Select the LLM used by the agent',
    'agentEditor.desc.temperature': 'Control output randomness, 0 is most deterministic, 1 is most random',
    'agentEditor.desc.thinking': 'Enable extended thinking capability (requires model support)',
    'agentEditor.desc.multiTurn': 'When enabled, historical conversation context will be preserved',
    'agentEditor.desc.historyRounds': 'Number of recent conversation rounds to keep as context',
    'agentEditor.desc.rewrite': 'Automatically rewrite user questions in multi-turn conversations to resolve references and omissions',
    'agentEditor.desc.memoryEnabled': 'Let this agent read and add to your long-term memory. When off, conversations with it neither read your memories nor add new ones. Turning it on here has no effect while the workspace or personal switch is off',
    'agentEditor.desc.queryUnderstandModel': 'Model used for query understanding (rewriting and intent detection). Leave empty to reuse the main chat model.',
    'agentEditor.desc.selectTools': 'Select tools available to the Agent',
    'agentEditor.desc.maxIterations': 'Caps how many reasoning steps one task may take. Unlimited keeps going until the model stops on its own or you stop it.',
    'agentEditor.desc.kbScope': 'Select the scope of knowledge bases accessible to the agent',
    'agentEditor.desc.webSearch': 'When enabled, the agent can search the internet for information',
    'agentEditor.desc.webSearchProvider': 'Specify a search engine for this agent. Leave empty to use the default.',
    'agentEditor.desc.webSearchMaxResults': 'Maximum number of results returned per search',
    'agentEditor.desc.webFetchEnabled': 'After reranking, auto-fetch full page content from top web results for better answers',
    'agentEditor.desc.webFetchTopN': 'Maximum number of web pages to fetch after reranking',
    'agentEditor.desc.retrievalSection': 'Configure knowledge base retrieval, ranking, and FAQ priority strategy',
    'agentEditor.desc.queryExpansion': 'Automatically expand query terms to improve recall',
    'agentEditor.desc.embeddingTopK': 'Maximum number of results from vector retrieval',
    'agentEditor.desc.keywordThreshold': 'Minimum relevance score for keyword retrieval',
    'agentEditor.desc.vectorThreshold': 'Minimum similarity score for vector retrieval',
    'agentEditor.desc.rerankTopK': 'Maximum number of results retained after reranking',
    'agentEditor.desc.rerankThreshold': 'Minimum relevance score for reranking',
    'agentEditor.desc.fallbackStrategy': 'How to handle when no relevant content is found in the knowledge base',
    'agentEditor.desc.fallbackResponse': 'Fixed text returned when unable to answer',
    'agentEditor.desc.fallbackPrompt': 'Prompt to guide model response when no answer is found in knowledge base',
    'agentEditor.desc.rewriteSystemPrompt': 'System prompt for question rewriting (leave empty for default)',
    'agentEditor.desc.rewriteUserPrompt': 'User prompt template for question rewriting (leave empty for default)',
    'agentEditor.faq.enableLabel': 'Enable FAQ Priority',
    'agentEditor.faq.enableDesc': 'FAQ answers will be prioritized over regular documents, improving response accuracy',
    'agentEditor.faq.thresholdLabel': 'Direct Answer Threshold',
    'agentEditor.faq.thresholdDesc': 'When the similarity between the question and FAQ exceeds this value, use the FAQ answer directly',
    'agentEditor.faq.boostLabel': 'FAQ Score Boost',
    'agentEditor.faq.boostDesc': 'Multiply FAQ relevance scores by this factor to rank them higher',
    'agentEditor.personalization.title': 'Personalization',
    'agentEditor.personalization.desc': 'Pick an MBTI persona and add style notes to shape how the agent speaks',
    'agentEditor.personalization.mbtiLabel': 'Persona type',
    'agentEditor.personalization.mbtiDesc': 'Choose one of the 16 types, or None to keep the default reply style',
    'agentEditor.personalization.noneLabel': 'None',
    'agentEditor.personalization.noneDesc': 'No persona; keep the default reply style',
    'agentEditor.personalization.dimensionsLabel': 'Dimension tendencies',
    'agentEditor.personalization.styleLabel': 'Style notes',
    'agentEditor.personalization.styleDesc': 'Optional. Extra tone or wording requirements applied along with the selected persona',
    'agentEditor.personalization.stylePlaceholder': 'e.g. Keep a relaxed tone and use analogies for complex ideas',
    'agentEditor.personalization.takeTest': 'Take the test',
    'agentEditor.personalization.takeTestHint': 'The test is coming soon',
    'agentEditor.personalization.loadFailed': 'Failed to load persona types',
    'agentEditor.personalization.unknownType': 'Saved type {code} is not in the catalog',
    'agentEditor.personalization.testTitle': 'MBTI Persona Test',
    'agentEditor.personalization.testIntroDesc': '28 either-or questions, about 3 minutes. There are no right answers — go with your first instinct.',
    'agentEditor.personalization.testDisclaimer': 'Results are for entertainment purposes only',
    'agentEditor.personalization.testStart': 'Start the test',
    'agentEditor.personalization.testProgress': '{answered} of {total} answered',
    'agentEditor.personalization.testSubmit': 'See my result',
    'agentEditor.personalization.testLoadFailed': 'Failed to load the questions',
    'agentEditor.personalization.testSubmitError': 'Failed to submit, please try again',
    'agentEditor.personalization.testResultTitle': 'Your result',
    'agentEditor.personalization.testApply': 'Apply to this agent',
    'agentEditor.subagents.title': 'Sub-agents',
    'agentEditor.subagents.desc': 'Install builtin sub-agent roles on this agent so it can delegate tasks to them; delegation is off while no role is installed',
    'agentEditor.subagents.installedLabel': 'Installed roles',
    'agentEditor.subagents.delegationOff': 'No sub-agents installed yet — delegation is off',
    'agentEditor.subagents.catalogLabel': 'Role catalog',
    'agentEditor.subagents.needSave': 'Save the new agent first to install sub-agents',
    'agentEditor.subagents.allDivisions': 'All',
    'agentEditor.subagents.searchPlaceholder': 'Search roles by name or slug',
    'agentEditor.subagents.emptyCatalog': 'The role catalog is empty',
    'agentEditor.subagents.noMatch': 'No roles match the filter',
    'agentEditor.subagents.loadFailed': 'Failed to load the role catalog',
    'agentEditor.subagents.actionFailed': 'The action failed, please retry',
    'agentEditor.subagents.install': 'Install',
    'agentEditor.subagents.remove': 'Remove',
    'agentEditor.subagents.installedTag': 'Installed',
    'agentEditor.subagents.detailFailed': 'Failed to load the role details',
  },
  "ja-JP": {
    'agentEditor.fileTypes.label': "対応ファイル形式",
    'agentEditor.fileTypes.desc': "選択できるファイル形式を制限します。空欄の場合はすべての形式に対応します",
    'agentEditor.fileTypes.allTypes': "すべての形式",
    'agentEditor.fileTypes.pdf': "PDFドキュメント",
    'agentEditor.fileTypes.word': "Wordドキュメント（.docx/.doc）",
    'agentEditor.fileTypes.textLabel': "テキスト",
    'agentEditor.fileTypes.text': "プレーンテキストファイル（.txt）",
    'agentEditor.fileTypes.markdown': "Markdownドキュメント",
    'agentEditor.fileTypes.csv': "カンマ区切りファイル",
    'agentEditor.fileTypes.excel': "Excelスプレッドシート（.xlsx/.xls）",
    'agentEditor.fileTypes.imageLabel': "画像",
    'agentEditor.fileTypes.image': "画像ファイル（.jpg/.jpeg/.png）",
    'agentEditor.llmCallTimeout.label': 'LLM呼び出しタイムアウト',
    'agentEditor.llmCallTimeout.desc': 'LLMの1回の呼び出しの最大待機時間（秒）。この時間を超えると呼び出しは中止されます',
    'agentEditor.llmCallTimeout.hint': '空欄または0でデフォルト（120秒）を使用します',
    'agentEditor.llmCallTimeout.placeholder': '秒数を入力してください。推奨範囲は60〜1800',
    'agentEditor.desc.maxTokens': 'モデルの応答の最大トークン数。デフォルトは2048です。カスタム値は入力したとおりに保存されます。',
    'agentEditor.desc.maxTokensAgent': '推論の各ラウンドで生成される最大トークン数（ツール呼び出しのJSONを含む）。デフォルトは、サンドボックスなしの場合4096、サンドボックスがファイルの書き込みや編集を行える場合は24576です。カスタム値は入力したとおりに保存され、以降変更されません。',
    'agentEditor.desc.conversationSection': 'マルチターン会話とクエリのリライトに関するパラメータを設定します',
    'agentEditor.desc.conversationSectionAgent': '各ターンで引き継ぐ過去の会話の量。スマート推論は常にマルチターンです',
    'agentEditor.desc.retainRetrievalHistory': '過去のターンのナレッジベース検索結果を保持します。無効にすると、ターンごとに再検索します',
    'agentEditor.navGroups.basic': '基本',
    'agentEditor.navGroups.knowledge': 'ナレッジと検索',
    'agentEditor.navGroups.capability': '拡張機能',
    'agentEditor.navGroups.integration': '公開と連携',
    'agentEditor.fallback.fixed': '固定応答',
    'agentEditor.fallback.model': 'モデル生成',
    'agentEditor.selection.all': 'すべて',
    'agentEditor.selection.selected': '選択済み',
    'agentEditor.selection.disabled': '無効',
    'agentEditor.placeholders.available': '使用可能な変数: ',
    'agentEditor.placeholders.hint': '（クリックで挿入、または{{を入力して一覧を表示）',
    'agentEditor.builtinHint': 'これは組み込みエージェントです。名前と説明は変更できませんが、設定パラメータは調整できます。',
    'agentEditor.tools.groupBase': '基本',
    'agentEditor.tools.groupRag': 'ナレッジベース検索（RAG）',
    'agentEditor.tools.groupWikiRead': 'Wiki読み取り',
    'agentEditor.tools.groupWikiEdit': 'Wiki編集',
    'agentEditor.tools.groupWikiIssue': 'Wikiレビュー',
    'agentEditor.tools.groupData': 'データ分析',
    'agentEditor.tools.thinking': '思考',
    'agentEditor.tools.thinkingDesc': '動的かつ内省的に問題を解決する思考ツール',
    'agentEditor.tools.todoWrite': '計画',
    'agentEditor.tools.todoWriteDesc': '構造化された調査計画を作成します',
    'agentEditor.tools.grepChunks': 'キーワード検索',
    'agentEditor.tools.grepChunksDesc': '特定のキーワードを含むドキュメントとチャンクを素早く特定します',
    'agentEditor.tools.knowledgeSearch': 'セマンティック検索',
    'agentEditor.tools.knowledgeSearchDesc': '質問を理解し、意味的に関連する内容を見つけます',
    'agentEditor.tools.listChunks': 'ドキュメントのチャンクを表示',
    'agentEditor.tools.listChunksDesc': 'ドキュメントの全チャンク内容を取得します',
    'agentEditor.tools.queryGraph': 'ナレッジグラフを照会',
    'agentEditor.tools.queryGraphDesc': 'ナレッジグラフからリレーションを照会します',
    'agentEditor.tools.getDocInfo': 'ドキュメント情報を取得',
    'agentEditor.tools.getDocInfoDesc': 'ドキュメントのメタデータを表示します',
    'agentEditor.tools.dbQuery': 'データベースを照会',
    'agentEditor.tools.dbQueryDesc': 'データベースから情報を照会します',
    'agentEditor.tools.dataAnalysis': 'データ分析',
    'agentEditor.tools.dataAnalysisDesc': 'データファイルを理解し、データ分析を実行します',
    'agentEditor.tools.dataSchema': 'データスキーマを表示',
    'agentEditor.tools.dataSchemaDesc': '表形式ファイルのメタデータを取得します',
    'agentEditor.tools.wikiSearch': 'Wikiを検索',
    'agentEditor.tools.wikiSearchDesc': 'Wikiページをキーワード/セマンティック検索します',
    'agentEditor.tools.wikiReadPage': 'Wikiページを読み取り',
    'agentEditor.tools.wikiReadPageDesc': '特定のWikiページの全文を読み取ります',
    'agentEditor.tools.wikiReadSourceDoc': 'ソースドキュメントを精読',
    'agentEditor.tools.wikiReadSourceDocDesc': 'Wikiページの元になった原文ドキュメントを詳しく読み込みます',
    'agentEditor.tools.wikiFlagIssue': 'Wikiの問題を報告',
    'agentEditor.tools.wikiFlagIssueDesc': 'Wikiページの事実誤認やマージ競合を報告します',
    'agentEditor.tools.wikiWritePage': 'Wikiを作成/上書き',
    'agentEditor.tools.wikiWritePageDesc': '新しいページを作成、または既存のページを全面的に上書きします',
    'agentEditor.tools.wikiReplaceText': 'Wikiのテキストを置換',
    'agentEditor.tools.wikiReplaceTextDesc': 'Wikiページ内の特定のテキストを置換します',
    'agentEditor.tools.wikiRenamePage': 'Wikiページ名を変更',
    'agentEditor.tools.wikiRenamePageDesc': 'Wikiページの名前を変更し、相互リンクを自動更新します',
    'agentEditor.tools.wikiDeletePage': 'Wikiページを削除',
    'agentEditor.tools.wikiDeletePageDesc': 'Wikiページを削除し、リンク切れを整理します',
    'agentEditor.tools.wikiReadIssue': 'Wikiの問題を表示',
    'agentEditor.tools.wikiReadIssueDesc': 'Wikiページの問題の詳細を表示します',
    'agentEditor.tools.wikiUpdateIssue': 'Wikiの問題を更新',
    'agentEditor.tools.wikiUpdateIssueDesc': 'Wikiページの問題のステータスを更新します',
    'agentEditor.tools.webSearch': 'Web検索',
    'agentEditor.tools.webFetch': 'Webページ取得',
    'agentEditor.tools.requiresKb': '（ナレッジベースの設定が必要）',
    'agentEditor.tools.requiresWikiKb': '（Wikiが有効なナレッジベースが必要）',
    'agentEditor.tools.requiresRagKb': '（ベクトル/キーワードインデックスが有効なナレッジベースが必要）',
    'agentEditor.tools.dangerTag': '書き込み',
    'agentEditor.tools.writeWarning': 'Wikiの内容を変更します',
    'agentEditor.tools.statusNoKb': 'ナレッジベースが紐付けられていません',
    'agentEditor.tools.kbMetricRag': 'RAGナレッジベース',
    'agentEditor.tools.kbMetricWiki': 'Wikiナレッジベース',
    'agentEditor.tools.statusInactive': '選択済みの{count}個のツールは、現在の設定では有効になりません',
    'agentEditor.tools.effectiveLabel': '有効なツール',
    'agentEditor.tools.effectiveDesc': '現在の設定から算出された、エージェントが実際に呼び出せるツールです',
    'agentEditor.tools.effectiveEmpty': '利用可能なツールがありません。エージェントは通常のモデル対話にフォールバックします',
    'agentEditor.desc.name': 'エージェントを識別しやすい名前を設定します',
    'agentEditor.desc.description': 'エージェントの目的と特徴を簡潔に説明します',
    'agentEditor.desc.systemPrompt': 'エージェントの動作と役割を定義するカスタムシステムプロンプト',
    'agentEditor.desc.leaveEmptyDefault': '（空欄の場合はシステムのデフォルトを使用）',
    'agentEditor.desc.contextTemplate': '検索した内容をモデルに渡す前の整形方法を定義します',
    'agentEditor.desc.model': 'エージェントが使用するLLMを選択します',
    'agentEditor.desc.temperature': '出力のランダム性を制御します。0が最も決定的、1が最もランダムです',
    'agentEditor.desc.thinking': '拡張思考機能を有効にします（モデルの対応が必要）',
    'agentEditor.desc.multiTurn': '有効にすると、過去の会話のコンテキストが保持されます',
    'agentEditor.desc.historyRounds': 'コンテキストとして保持する直近の会話ラウンド数',
    'agentEditor.desc.rewrite': 'マルチターン会話でユーザの質問を自動的にリライトし、指示語や省略を補完します',
    'agentEditor.desc.memoryEnabled': 'このエージェントが長期メモリを読み取り、追記できるようにします。無効にすると、このエージェントとの会話はメモリを読み取らず、新しいメモリも追加しません。ワークスペースまたは個人の設定が無効の場合、ここで有効にしても反映されません',
    'agentEditor.desc.queryUnderstandModel': 'クエリ理解（リライトとインテント判定）に使用するモデル。空欄の場合はメインのチャットモデルを使用します。',
    'agentEditor.desc.selectTools': 'エージェントが使用できるツールを選択します',
    'agentEditor.desc.maxIterations': '1つのタスクで実行できる推論ステップ数の上限。無制限にすると、モデルが自ら停止するか手動で停止するまで続行します。',
    'agentEditor.desc.kbScope': 'エージェントがアクセスできるナレッジベースの範囲を選択します',
    'agentEditor.desc.webSearch': '有効にすると、エージェントがインターネットで情報を検索できます',
    'agentEditor.desc.webSearchProvider': 'このエージェントで使用する検索エンジンを指定します。空欄の場合はデフォルトを使用します。',
    'agentEditor.desc.webSearchMaxResults': '1回の検索で返される結果の最大数',
    'agentEditor.desc.webFetchEnabled': 'リランク後、上位のWeb検索結果からページ全文を自動取得し、回答精度を高めます',
    'agentEditor.desc.webFetchTopN': 'リランク後に取得するWebページの最大数',
    'agentEditor.desc.retrievalSection': 'ナレッジベースの検索、ランキング、FAQ優先戦略を設定します',
    'agentEditor.desc.queryExpansion': 'クエリの語句を自動的に拡張してリコールを向上させます',
    'agentEditor.desc.embeddingTopK': 'ベクトル検索から取得する結果の最大数',
    'agentEditor.desc.keywordThreshold': 'キーワード検索の最小関連スコア',
    'agentEditor.desc.vectorThreshold': 'ベクトル検索の最小類似度スコア',
    'agentEditor.desc.rerankTopK': 'リランク後に保持する結果の最大数',
    'agentEditor.desc.rerankThreshold': 'リランクの最小関連スコア',
    'agentEditor.desc.fallbackStrategy': 'ナレッジベースで関連する内容が見つからない場合の処理方法',
    'agentEditor.desc.fallbackResponse': '回答できない場合に返す固定テキスト',
    'agentEditor.desc.fallbackPrompt': 'ナレッジベースで回答が見つからない場合に、モデルの応答を導くプロンプト',
    'agentEditor.desc.rewriteSystemPrompt': '質問リライト用のシステムプロンプト（空欄でデフォルト）',
    'agentEditor.desc.rewriteUserPrompt': '質問リライト用のユーザプロンプトテンプレート（空欄でデフォルト）',
    'agentEditor.faq.enableLabel': 'FAQ優先を有効化',
    'agentEditor.faq.enableDesc': 'FAQの回答が通常のドキュメントより優先され、応答の正確性が向上します',
    'agentEditor.faq.thresholdLabel': '直接回答のしきい値',
    'agentEditor.faq.thresholdDesc': '質問とFAQの類似度がこの値を超えた場合、FAQの回答をそのまま使用します',
    'agentEditor.faq.boostLabel': 'FAQスコアブースト',
    'agentEditor.faq.boostDesc': 'FAQの関連スコアにこの係数を掛けて、上位に表示します',
  },
  "ko-KR": {
    'agentEditor.fileTypes.label': "지원 파일 유형",
    'agentEditor.fileTypes.desc': "선택 가능한 파일 유형을 제한합니다. 비워두면 모든 유형을 지원합니다.",
    'agentEditor.fileTypes.allTypes': "전체 유형",
    'agentEditor.fileTypes.pdf': "PDF 문서",
    'agentEditor.fileTypes.word': "Word 문서 (.docx/.doc)",
    'agentEditor.fileTypes.textLabel': "텍스트",
    'agentEditor.fileTypes.text': "일반 텍스트 파일 (.txt)",
    'agentEditor.fileTypes.markdown': "Markdown 문서",
    'agentEditor.fileTypes.csv': "쉼표로 구분된 값 파일",
    'agentEditor.fileTypes.excel': "Excel 스프레드시트 (.xlsx/.xls)",
    'agentEditor.fileTypes.imageLabel': "이미지",
    'agentEditor.fileTypes.image': "이미지 파일 (.jpg/.jpeg/.png)",
    'agentEditor.llmCallTimeout.label': 'LLM 호출 타임아웃',
    'agentEditor.llmCallTimeout.desc': '단일 LLM 호출의 최대 대기 시간(초)입니다. 이 시간을 초과하면 호출이 중단됩니다',
    'agentEditor.llmCallTimeout.hint': '비워두거나 0이면 기본값(120초)을 사용합니다',
    'agentEditor.llmCallTimeout.placeholder': '초 단위로 입력하세요. 권장 범위 60-1800',
    'agentEditor.desc.maxTokens': '모델 응답의 최대 토큰 수. 「기본값」은 2048입니다. 「사용자 지정」은 입력한 값을 그대로 저장합니다.',
    'agentEditor.desc.maxTokensAgent': '각 추론 라운드에서 생성할 최대 토큰 수(도구 호출 JSON 포함). 「기본값」은 샌드박스 없으면 4096, 파일 쓰기/편집이 가능하면 24576입니다. 「사용자 지정」은 입력한 값을 그대로 저장합니다.',
    'agentEditor.desc.conversationSection': '다중 턴 대화 및 질문 재작성 관련 매개변수 설정',
    'agentEditor.desc.conversationSectionAgent': '매 턴에 실어 보낼 이전 대화 분량 설정 (스마트 추론은 항상 다중 턴)',
    'agentEditor.desc.retainRetrievalHistory': '이전 턴의 지식베이스 검색 결과를 유지합니다. 끄면 매 턴 새로 검색합니다',
    'agentEditor.navGroups.basic': '기본',
    'agentEditor.navGroups.knowledge': '지식 검색',
    'agentEditor.navGroups.capability': '기능 확장',
    'agentEditor.navGroups.integration': '게시 및 통합',
    'agentEditor.fallback.fixed': '고정 응답',
    'agentEditor.fallback.model': '모델 생성',
    'agentEditor.selection.all': '전체',
    'agentEditor.selection.selected': '지정',
    'agentEditor.selection.disabled': '비활성화',
    'agentEditor.placeholders.available': '사용 가능한 변수: ',
    'agentEditor.placeholders.hint': '(클릭하여 삽입, 또는 {{ 입력으로 목록 표시)',
    'agentEditor.builtinHint': '내장 에이전트입니다. 이름과 설명은 수정할 수 없지만, 설정 매개변수는 조정할 수 있습니다.',
    'agentEditor.tools.groupBase': '기본',
    'agentEditor.tools.groupRag': '지식베이스 검색 (RAG)',
    'agentEditor.tools.groupWikiRead': 'Wiki 읽기',
    'agentEditor.tools.groupWikiEdit': 'Wiki 편집',
    'agentEditor.tools.groupWikiIssue': 'Wiki 점검',
    'agentEditor.tools.groupData': '데이터 분석',
    'agentEditor.tools.thinking': '사고',
    'agentEditor.tools.thinkingDesc': '동적이고 반성적인 문제 해결 사고 도구',
    'agentEditor.tools.todoWrite': '계획 수립',
    'agentEditor.tools.todoWriteDesc': '구조화된 연구 계획 생성',
    'agentEditor.tools.grepChunks': '키워드 검색',
    'agentEditor.tools.grepChunksDesc': '특정 키워드를 포함하는 문서와 청크를 빠르게 찾기',
    'agentEditor.tools.knowledgeSearch': '의미 검색',
    'agentEditor.tools.knowledgeSearchDesc': '질문을 이해하고 의미적으로 관련된 콘텐츠 찾기',
    'agentEditor.tools.listChunks': '문서 청크 보기',
    'agentEditor.tools.listChunksDesc': '문서의 전체 청크 내용 조회',
    'agentEditor.tools.queryGraph': '지식 그래프 쿼리',
    'agentEditor.tools.queryGraphDesc': '지식 그래프에서 관계 조회',
    'agentEditor.tools.getDocInfo': '문서 정보 조회',
    'agentEditor.tools.getDocInfoDesc': '문서 메타데이터 보기',
    'agentEditor.tools.dbQuery': '데이터베이스 쿼리',
    'agentEditor.tools.dbQueryDesc': '데이터베이스에서 정보 조회',
    'agentEditor.tools.dataAnalysis': '데이터 분석',
    'agentEditor.tools.dataAnalysisDesc': '데이터 파일을 이해하고 데이터 분석 수행',
    'agentEditor.tools.dataSchema': '데이터 스키마 보기',
    'agentEditor.tools.dataSchemaDesc': '테이블 파일의 메타 정보 조회',
    'agentEditor.tools.wikiSearch': 'Wiki 검색',
    'agentEditor.tools.wikiSearchDesc': 'Wiki 지식베이스에서 키워드/의미 기반 검색',
    'agentEditor.tools.wikiReadPage': 'Wiki 페이지 읽기',
    'agentEditor.tools.wikiReadPageDesc': '지정한 Wiki 페이지의 전체 내용을 읽습니다',
    'agentEditor.tools.wikiReadSourceDoc': '원본 문서 읽기',
    'agentEditor.tools.wikiReadSourceDocDesc': 'Wiki 페이지의 기반이 된 원본 문서를 깊이 있게 읽습니다',
    'agentEditor.tools.wikiFlagIssue': 'Wiki 문제 표시',
    'agentEditor.tools.wikiFlagIssueDesc': '사실 오류나 병합 충돌을 표시합니다',
    'agentEditor.tools.wikiWritePage': 'Wiki 생성/덮어쓰기',
    'agentEditor.tools.wikiWritePageDesc': '새 페이지 생성 또는 기존 페이지 완전 덮어쓰기',
    'agentEditor.tools.wikiReplaceText': 'Wiki 텍스트 교체',
    'agentEditor.tools.wikiReplaceTextDesc': 'Wiki 페이지의 특정 텍스트 교체',
    'agentEditor.tools.wikiRenamePage': 'Wiki 이름 변경',
    'agentEditor.tools.wikiRenamePageDesc': 'Wiki 페이지 이름을 변경하고 연결된 링크를 자동 갱신',
    'agentEditor.tools.wikiDeletePage': 'Wiki 삭제',
    'agentEditor.tools.wikiDeletePageDesc': 'Wiki 페이지를 삭제하고 끊어진 링크를 자동 정리',
    'agentEditor.tools.wikiReadIssue': 'Wiki 문제 보기',
    'agentEditor.tools.wikiReadIssueDesc': '특정 Wiki 페이지 문제의 상세 조회',
    'agentEditor.tools.wikiUpdateIssue': 'Wiki 문제 업데이트',
    'agentEditor.tools.wikiUpdateIssueDesc': 'Wiki 페이지 문제의 처리 상태 업데이트',
    'agentEditor.tools.webSearch': '웹 검색',
    'agentEditor.tools.webFetch': '웹 페이지 가져오기',
    'agentEditor.tools.requiresKb': '(지식베이스 설정 필요)',
    'agentEditor.tools.requiresWikiKb': '(Wiki 기능이 활성화된 지식베이스가 필요합니다)',
    'agentEditor.tools.requiresRagKb': '(벡터/키워드 인덱싱이 활성화된 지식베이스가 필요합니다)',
    'agentEditor.tools.dangerTag': '쓰기',
    'agentEditor.tools.writeWarning': 'Wiki 내용을 변경합니다',
    'agentEditor.tools.statusNoKb': '연결된 지식베이스가 없습니다',
    'agentEditor.tools.kbMetricRag': 'RAG 지식베이스',
    'agentEditor.tools.kbMetricWiki': 'Wiki 지식베이스',
    'agentEditor.tools.statusInactive': '{count}개의 체크된 도구가 현재 설정에서는 작동하지 않습니다',
    'agentEditor.tools.effectiveLabel': '최종 활성 도구',
    'agentEditor.tools.effectiveDesc': '현재 설정 기준 저장 시 에이전트가 실제 호출할 수 있는 도구 집합',
    'agentEditor.tools.effectiveEmpty': '사용 가능한 도구가 없어 일반 모델 대화로 동작합니다',
    'agentEditor.desc.name': '에이전트를 쉽게 식별할 수 있는 이름을 설정하세요',
    'agentEditor.desc.description': '에이전트의 용도와 특징을 간단히 설명하세요',
    'agentEditor.desc.systemPrompt': '에이전트의 동작과 역할을 정의하는 사용자 정의 시스템 프롬프트',
    'agentEditor.desc.leaveEmptyDefault': '(비워두면 시스템 기본값 사용)',
    'agentEditor.desc.contextTemplate': '검색된 콘텐츠를 모델에 전달하기 전에 형식을 정의합니다',
    'agentEditor.desc.model': '에이전트가 사용할 대규모 언어 모델을 선택하세요',
    'agentEditor.desc.temperature': '출력의 무작위성을 제어합니다. 0이 가장 확정적, 1이 가장 무작위',
    'agentEditor.desc.thinking': '모델의 확장 사고 기능 활성화 (모델 지원 필요)',
    'agentEditor.desc.multiTurn': '활성화하면 대화 기록 컨텍스트가 유지됩니다',
    'agentEditor.desc.historyRounds': '컨텍스트로 유지할 최근 대화 라운드 수',
    'agentEditor.desc.rewrite': '다중 턴 대화에서 사용자 질문을 자동으로 재작성하여 지시대명사 해소 및 생략 보완',
    'agentEditor.desc.memoryEnabled': '이 에이전트가 장기 기억을 읽고 추가하도록 허용합니다. 끄면 이 에이전트와의 대화에서 기억을 읽지도, 새로 추가하지도 않습니다. 공간 또는 개인 설정이 꺼져 있으면 여기서 켜도 적용되지 않습니다',
    'agentEditor.desc.queryUnderstandModel': '질문 이해(재작성과 의도 분류)에 사용할 모델입니다. 비워 두면 기본 대화 모델을 사용합니다.',
    'agentEditor.desc.selectTools': 'Agent가 사용할 수 있는 도구를 선택하세요',
    'agentEditor.desc.maxIterations': 'Agent가 한 작업에서 수행할 최대 추론 단계 수입니다. 「제한 없음」을 선택하면 모델이 스스로 끝나거나 직접 중지할 때까지 계속 실행됩니다.',
    'agentEditor.desc.kbScope': '에이전트가 접근할 수 있는 지식베이스 범위를 선택하세요',
    'agentEditor.desc.webSearch': '활성화하면 에이전트가 인터넷에서 정보를 검색할 수 있습니다',
    'agentEditor.desc.webSearchProvider': '이 에이전트의 검색 엔진을 지정합니다. 비워두면 기본 검색 엔진을 사용합니다',
    'agentEditor.desc.webSearchMaxResults': '검색당 반환되는 최대 결과 수',
    'agentEditor.desc.webFetchEnabled': 'Rerank 후 상위 웹 페이지의 전체 콘텐츠를 자동으로 가져와 답변 품질을 향상시킵니다',
    'agentEditor.desc.webFetchTopN': 'Rerank 후 전체 콘텐츠를 가져올 최대 웹 페이지 수',
    'agentEditor.desc.retrievalSection': '지식베이스 검색·순위 및 FAQ 우선 전략 설정',
    'agentEditor.desc.queryExpansion': '쿼리 용어를 자동으로 확장하여 재현율 향상',
    'agentEditor.desc.embeddingTopK': '벡터 검색에서 반환되는 최대 결과 수',
    'agentEditor.desc.keywordThreshold': '키워드 검색의 최소 관련성 점수',
    'agentEditor.desc.vectorThreshold': '벡터 검색의 최소 유사도 점수',
    'agentEditor.desc.rerankTopK': '재순위 후 유지되는 최대 결과 수',
    'agentEditor.desc.rerankThreshold': '재순위의 최소 관련성 점수',
    'agentEditor.desc.fallbackStrategy': '지식베이스에서 관련 콘텐츠를 찾을 수 없을 때 처리 방식',
    'agentEditor.desc.fallbackResponse': '응답할 수 없을 때 반환할 고정 텍스트',
    'agentEditor.desc.fallbackPrompt': '지식베이스에서 답변을 찾을 수 없을 때 모델 응답을 유도하는 프롬프트',
    'agentEditor.desc.rewriteSystemPrompt': '질문 재작성용 시스템 프롬프트 (비워두면 기본값 사용)',
    'agentEditor.desc.rewriteUserPrompt': '질문 재작성용 사용자 프롬프트 템플릿 (비워두면 기본값 사용)',
    'agentEditor.faq.enableLabel': 'FAQ 우선 활성화',
    'agentEditor.faq.enableDesc': 'FAQ 답변이 일반 문서보다 우선되어 응답 정확도가 향상됩니다',
    'agentEditor.faq.thresholdLabel': '직접 답변 임계값',
    'agentEditor.faq.thresholdDesc': '질문과 FAQ의 유사도가 이 값을 초과하면 FAQ 답변을 직접 사용합니다',
    'agentEditor.faq.boostLabel': 'FAQ 점수 가중치',
    'agentEditor.faq.boostDesc': 'FAQ 관련성 점수에 이 계수를 곱하여 순위를 높입니다',
  },
  "ru-RU": {
    'agentEditor.fileTypes.label': "Поддерживаемые типы файлов",
    'agentEditor.fileTypes.desc': "Ограничение выбираемых типов файлов. Пустое поле — все типы поддерживаются.",
    'agentEditor.fileTypes.allTypes': "Все типы",
    'agentEditor.fileTypes.pdf': "PDF-документы",
    'agentEditor.fileTypes.word': "Документы Word (.docx/.doc)",
    'agentEditor.fileTypes.textLabel': "Текст",
    'agentEditor.fileTypes.text': "Текстовые файлы (.txt)",
    'agentEditor.fileTypes.markdown': "Документы Markdown",
    'agentEditor.fileTypes.csv': "Файлы CSV",
    'agentEditor.fileTypes.excel': "Таблицы Excel (.xlsx/.xls)",
    'agentEditor.fileTypes.imageLabel': "Изображения",
    'agentEditor.fileTypes.image': "Изображения (.jpg/.jpeg/.png)",
    'agentEditor.llmCallTimeout.label': 'Таймаут вызова LLM',
    'agentEditor.llmCallTimeout.desc': 'Максимальное время ожидания одного вызова LLM (в секундах). По истечении этого времени вызов прерывается',
    'agentEditor.llmCallTimeout.hint': 'Оставьте пустым или 0, чтобы использовать значение по умолчанию (120 секунд)',
    'agentEditor.llmCallTimeout.placeholder': 'Введите количество секунд, рекомендуемый диапазон 60-1800',
    'agentEditor.desc.maxTokens': 'Максимум токенов в ответе. «По умолчанию» — 2048. «Своё» сохраняет введённое число.',
    'agentEditor.desc.maxTokensAgent': 'Максимум токенов за один раунд рассуждения, включая JSON вызовов инструментов. «По умолчанию»: 4096 без песочницы, 24576 с записью/правкой файлов. «Своё» сохраняет введённое число и больше не меняется.',
    'agentEditor.desc.conversationSection': 'Настройка параметров многооборотного диалога и перефразирования вопросов',
    'agentEditor.desc.conversationSectionAgent': 'Объём предыдущего диалога в каждом ходе. Умные рассуждения всегда многооборотные',
    'agentEditor.desc.retainRetrievalHistory': 'Сохранять результаты поиска из прошлых ходов. При отключении каждый ход ищет заново',
    'agentEditor.navGroups.basic': 'Основное',
    'agentEditor.navGroups.knowledge': 'Знания и поиск',
    'agentEditor.navGroups.capability': 'Расширения',
    'agentEditor.navGroups.integration': 'Публикация и интеграция',
    'agentEditor.fallback.fixed': 'Фиксированный ответ',
    'agentEditor.fallback.model': 'Генерация моделью',
    'agentEditor.selection.all': 'Все',
    'agentEditor.selection.selected': 'Выбранные',
    'agentEditor.selection.disabled': 'Отключено',
    'agentEditor.placeholders.available': 'Доступные переменные: ',
    'agentEditor.placeholders.hint': '(нажмите для вставки или введите {{ для списка)',
    'agentEditor.builtinHint': 'Это встроенный агент. Имя и описание нельзя изменить, но можно настроить параметры конфигурации.',
    'agentEditor.tools.groupBase': 'Базовые',
    'agentEditor.tools.groupRag': 'Поиск в базе знаний (RAG)',
    'agentEditor.tools.groupWikiRead': 'Чтение Wiki',
    'agentEditor.tools.groupWikiEdit': 'Редактирование Wiki',
    'agentEditor.tools.groupWikiIssue': 'Проверка Wiki',
    'agentEditor.tools.groupData': 'Анализ данных',
    'agentEditor.tools.thinking': 'Размышление',
    'agentEditor.tools.thinkingDesc': 'Динамический инструмент рефлексивного решения проблем',
    'agentEditor.tools.todoWrite': 'Планирование',
    'agentEditor.tools.todoWriteDesc': 'Создание структурированных исследовательских планов',
    'agentEditor.tools.grepChunks': 'Поиск по ключевым словам',
    'agentEditor.tools.grepChunksDesc': 'Быстрый поиск документов и фрагментов с определёнными ключевыми словами',
    'agentEditor.tools.knowledgeSearch': 'Семантический поиск',
    'agentEditor.tools.knowledgeSearchDesc': 'Понимание вопросов и поиск семантически связанного контента',
    'agentEditor.tools.listChunks': 'Просмотр фрагментов документа',
    'agentEditor.tools.listChunksDesc': 'Получение полного содержимого фрагментов документа',
    'agentEditor.tools.queryGraph': 'Запрос графа знаний',
    'agentEditor.tools.queryGraphDesc': 'Запрос связей из графа знаний',
    'agentEditor.tools.getDocInfo': 'Информация о документе',
    'agentEditor.tools.getDocInfoDesc': 'Просмотр метаданных документа',
    'agentEditor.tools.dbQuery': 'Запрос к базе данных',
    'agentEditor.tools.dbQueryDesc': 'Запрос информации из базы данных',
    'agentEditor.tools.dataAnalysis': 'Анализ данных',
    'agentEditor.tools.dataAnalysisDesc': 'Понимание файлов данных и проведение анализа',
    'agentEditor.tools.dataSchema': 'Схема данных',
    'agentEditor.tools.dataSchemaDesc': 'Получение метаинформации табличных файлов',
    'agentEditor.tools.wikiSearch': 'Поиск по Wiki',
    'agentEditor.tools.wikiSearchDesc': 'Поиск страниц Wiki по ключевым словам / семантике',
    'agentEditor.tools.wikiReadPage': 'Читать страницу Wiki',
    'agentEditor.tools.wikiReadPageDesc': 'Прочитать полное содержимое указанной Wiki-страницы',
    'agentEditor.tools.wikiReadSourceDoc': 'Читать исходный документ',
    'agentEditor.tools.wikiReadSourceDocDesc': 'Глубокое чтение исходных документов, на которых построена Wiki-страница',
    'agentEditor.tools.wikiFlagIssue': 'Отметить проблему в Wiki',
    'agentEditor.tools.wikiFlagIssueDesc': 'Отметить фактические ошибки или конфликты слияния',
    'agentEditor.tools.wikiWritePage': 'Создать/перезаписать Wiki',
    'agentEditor.tools.wikiWritePageDesc': 'Создать новую или полностью перезаписать существующую страницу',
    'agentEditor.tools.wikiReplaceText': 'Заменить текст в Wiki',
    'agentEditor.tools.wikiReplaceTextDesc': 'Заменить конкретный текст на Wiki-странице',
    'agentEditor.tools.wikiRenamePage': 'Переименовать Wiki',
    'agentEditor.tools.wikiRenamePageDesc': 'Переименовать страницу Wiki и автоматически обновить перекрёстные ссылки',
    'agentEditor.tools.wikiDeletePage': 'Удалить Wiki',
    'agentEditor.tools.wikiDeletePageDesc': 'Удалить страницу Wiki и автоматически очистить битые ссылки',
    'agentEditor.tools.wikiReadIssue': 'Просмотр проблемы Wiki',
    'agentEditor.tools.wikiReadIssueDesc': 'Просмотр деталей конкретной проблемы страницы Wiki',
    'agentEditor.tools.wikiUpdateIssue': 'Обновить проблему Wiki',
    'agentEditor.tools.wikiUpdateIssueDesc': 'Обновить статус проблемы страницы Wiki',
    'agentEditor.tools.webSearch': 'Поиск в сети',
    'agentEditor.tools.webFetch': 'Загрузка веб-страницы',
    'agentEditor.tools.requiresKb': '(требуется настройка базы знаний)',
    'agentEditor.tools.requiresWikiKb': '(требуется база знаний с включённой Wiki)',
    'agentEditor.tools.requiresRagKb': '(требуется база знаний с включённым векторным/ключевым индексом)',
    'agentEditor.tools.dangerTag': 'Запись',
    'agentEditor.tools.writeWarning': 'Изменяет содержимое Wiki',
    'agentEditor.tools.statusNoKb': 'База знаний не подключена',
    'agentEditor.tools.kbMetricRag': 'RAG баз',
    'agentEditor.tools.kbMetricWiki': 'Wiki баз',
    'agentEditor.tools.statusInactive': '{count} отмеченных инструментов не смогут работать при текущей конфигурации',
    'agentEditor.tools.effectiveLabel': 'Итоговые активные инструменты',
    'agentEditor.tools.effectiveDesc': 'Рассчитано на основе текущей конфигурации — это набор инструментов, которые агент сможет вызывать после сохранения',
    'agentEditor.tools.effectiveEmpty': 'Нет доступных инструментов — агент перейдёт к простому чату с моделью',
    'agentEditor.desc.name': 'Задайте легко узнаваемое имя для агента',
    'agentEditor.desc.description': 'Кратко опишите назначение и особенности агента',
    'agentEditor.desc.systemPrompt': 'Пользовательский системный промпт для определения поведения и роли агента',
    'agentEditor.desc.leaveEmptyDefault': '(оставьте пустым для системного значения по умолчанию)',
    'agentEditor.desc.contextTemplate': 'Определите формат передачи найденного контента модели',
    'agentEditor.desc.model': 'Выберите LLM, используемую агентом',
    'agentEditor.desc.temperature': 'Контроль случайности выхода: 0 — наиболее детерминированный, 1 — наиболее случайный',
    'agentEditor.desc.thinking': 'Включить расширенное мышление модели (требуется поддержка модели)',
    'agentEditor.desc.multiTurn': 'При включении сохраняется контекст истории диалога',
    'agentEditor.desc.historyRounds': 'Количество последних раундов диалога для сохранения в контексте',
    'agentEditor.desc.rewrite': 'Автоматическое перефразирование вопросов в многооборотном диалоге для разрешения ссылок и дополнения',
    'agentEditor.desc.memoryEnabled': 'Разрешить этому агенту читать и пополнять вашу долговременную память. При выключении разговоры с ним не читают ваши записи и не добавляют новые. Если память выключена в настройках пространства или в личных настройках, включение здесь не подействует',
    'agentEditor.desc.queryUnderstandModel': 'Модель для понимания запроса (перефразирование и распознавание намерения). Пустое значение — использовать основную модель чата.',
    'agentEditor.desc.selectTools': 'Выберите инструменты, доступные агенту',
    'agentEditor.desc.maxIterations': 'Ограничивает число шагов рассуждения за одну задачу. «Без ограничения» — цикл идёт, пока модель не остановится сама или вы не остановите её.',
    'agentEditor.desc.kbScope': 'Выберите область баз знаний, доступных агенту',
    'agentEditor.desc.webSearch': 'При включении агент может искать информацию в интернете',
    'agentEditor.desc.webSearchProvider': 'Укажите поисковый движок для этого агента. Если оставить пустым, будет использоваться движок по умолчанию',
    'agentEditor.desc.webSearchMaxResults': 'Максимальное количество результатов на один поиск',
    'agentEditor.desc.webFetchEnabled': 'Автоматически загружать полное содержимое лучших страниц после Rerank для повышения качества ответов',
    'agentEditor.desc.webFetchTopN': 'Максимальное количество страниц для загрузки полного содержимого после Rerank',
    'agentEditor.desc.retrievalSection': 'Настройка поиска, ранжирования и стратегии приоритета FAQ',
    'agentEditor.desc.queryExpansion': 'Автоматическое расширение поисковых запросов для улучшения полноты',
    'agentEditor.desc.embeddingTopK': 'Максимальное количество результатов векторного поиска',
    'agentEditor.desc.keywordThreshold': 'Минимальная оценка релевантности для поиска по ключевым словам',
    'agentEditor.desc.vectorThreshold': 'Минимальная оценка сходства для векторного поиска',
    'agentEditor.desc.rerankTopK': 'Максимальное количество результатов после переранжирования',
    'agentEditor.desc.rerankThreshold': 'Минимальная оценка релевантности для переранжирования',
    'agentEditor.desc.fallbackStrategy': 'Действие при отсутствии релевантного контента в базе знаний',
    'agentEditor.desc.fallbackResponse': 'Фиксированный текст при невозможности ответить',
    'agentEditor.desc.fallbackPrompt': 'Промпт для генерации ответа модели, когда ответ не найден в базе знаний',
    'agentEditor.desc.rewriteSystemPrompt': 'Системный промпт для перефразирования вопросов (пустое = по умолчанию)',
    'agentEditor.desc.rewriteUserPrompt': 'Шаблон пользовательского промпта для перефразирования (пустое = по умолчанию)',
    'agentEditor.faq.enableLabel': 'Включить приоритет FAQ',
    'agentEditor.faq.enableDesc': 'Ответы FAQ будут приоритетнее обычных документов, повышая точность ответов',
    'agentEditor.faq.thresholdLabel': 'Порог прямого ответа',
    'agentEditor.faq.thresholdDesc': 'Если сходство вопроса с FAQ превышает это значение, ответ FAQ используется напрямую',
    'agentEditor.faq.boostLabel': 'Коэффициент FAQ',
    'agentEditor.faq.boostDesc': 'Умножение оценки релевантности FAQ на этот коэффициент для повышения ранга',
  },
} as const;
