import { useEffect, useMemo, useState } from 'react';
import type { WeKnoraClient } from '@weknora/api-client';
import { Button, Card, Dialog, Input, Status } from '@weknora/ui';
import { loadAgents, saveAgent, type AgentInput } from './api.ts';
import { buildAgentPath, parseAgentRoute, type AgentEditorSection } from './route.ts';
import { canEditAgent, canManageAgent, classifyAgent, initialEditorState, type Agent, type AgentPermissions } from './state.ts';
import './agents.css';

export interface AgentsPageProps { client: WeKnoraClient; pathname: string; permissions: AgentPermissions; onNavigate: (path: string) => void }

export function AgentsPage({ client, pathname, permissions, onNavigate }: AgentsPageProps) {
  const route = parseAgentRoute(pathname);
  const [state, setState] = useState<Awaited<ReturnType<typeof loadAgents>> | null>(null);
  const [reload, setReload] = useState(0);
  const [editor, setEditor] = useState<{ agent: Agent | null; section: AgentEditorSection } | null>(null);
  const [filter, setFilter] = useState<'all' | 'mine' | 'shared'>('all');
  useEffect(() => { let active = true; setState(null); void loadAgents(client).then((next) => { if (active) setState(next); }); return () => { active = false; }; }, [client, reload]);
  useEffect(() => { if (!route?.editId || !state || state.status !== 'success') return; const agent = state.items.find((item) => item.id === route.editId); if (agent) setEditor({ agent, section: route.section }); }, [route?.editId, route?.section, state]);
  const visible = useMemo(() => state?.status === 'success' ? state.items.filter((agent) => filter === 'all' || (filter === 'mine' ? !agent.permission && agent.created_by === permissions.userId : !!agent.permission)) : [], [state, filter, permissions.userId]);
  const openEditor = (agent: Agent | null, section: AgentEditorSection = 'basic') => { setEditor({ agent, section }); if (agent) onNavigate(buildAgentPath(agent.id, section, agent.source_tenant_id ? String(agent.source_tenant_id) : undefined)); };
  return <main className="wk-page agents-page"><header className="wk-header"><div><p className="wk-eyebrow">Agent workspace</p><h1>Agents</h1><p className="wk-muted">Create, configure, and use workspace agents.</p></div>{permissions.roles.includes('contributor') ? <Button variant="primary" onClick={() => openEditor(null)}>Create agent</Button> : null}</header>
    <Card><nav className="agents-filters" aria-label="Agent list filter">{(['all', 'mine', 'shared'] as const).map((value) => <button key={value} type="button" aria-pressed={filter === value} onClick={() => setFilter(value)}>{value === 'all' ? 'All' : value === 'mine' ? 'Created by me' : 'Shared with me'}</button>)}</nav>
      {!state ? <Status>Loading agents…</Status> : state.status === 'error' ? <div><Status tone="error">{state.message}</Status><Button type="button" onClick={() => setReload((value) => value + 1)}>Try again</Button></div> : visible.length === 0 ? <div className="agents-empty"><Status>No agents found.</Status>{permissions.roles.includes('contributor') && filter !== 'shared' ? <Button type="button" onClick={() => openEditor(null)}>Create agent</Button> : null}</div> : <div className="agents-grid">{visible.map((agent) => <article className="agent-card" key={`${agent.source_tenant_id ?? 'local'}:${agent.id}`}><div><span className="agent-avatar">{agent.avatar || agent.name.trim().slice(0, 1).toUpperCase() || '?'}</span><h2>{agent.name}</h2></div><p>{agent.description || 'No description'}</p><small>{classifyAgent(agent, permissions.userId).replace('-', ' ')}</small><div className="agent-actions"><Button type="button" onClick={() => openEditor(agent)}>{canManageAgent(agent, permissions) || canEditAgent(agent) ? 'Edit' : 'View'}</Button></div></article>)}</div>}
    </Card><AgentEditor client={client} value={editor} permissions={permissions} onSectionChange={(section) => { if (!editor) return; setEditor({ ...editor, section }); if (editor.agent) onNavigate(buildAgentPath(editor.agent.id, section, editor.agent.source_tenant_id ? String(editor.agent.source_tenant_id) : undefined)); }} onClose={() => { setEditor(null); onNavigate('/platform/agents'); }} onSaved={() => { setEditor(null); setReload((value) => value + 1); onNavigate('/platform/agents'); }} /></main>;
}

function AgentEditor({ client, value, permissions, onSectionChange, onClose, onSaved }: { client: WeKnoraClient; value: { agent: Agent | null; section: AgentEditorSection } | null; permissions: AgentPermissions; onSectionChange: (section: AgentEditorSection) => void; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const agent = value?.agent ?? null; const editable = !agent ? permissions.roles.includes('contributor') : canManageAgent(agent, permissions) || canEditAgent(agent); const initial = value ? initialEditorState(agent, value.section) : null;
  useEffect(() => { if (!value) return; setName(agent?.name ?? ''); setDescription(agent?.description ?? ''); setError(null); setSaving(false); }, [value, agent]);
  if (!value) return null;
  const submit = async () => { if (saving || !editable || !name.trim()) { if (!name.trim()) setError('Name is required.'); return; } setSaving(true); setError(null); const result = await saveAgent(client, agent?.id ?? null, { name: name.trim(), description: description.trim(), config: agent?.config }, undefined); if (result.status === 'success') onSaved(); else { setError(result.message); setSaving(false); } };
  return <Dialog open title={agent ? `Edit ${agent.name}` : 'Create agent'} onOpenChange={(open) => { if (!open && !saving) onClose(); }}><div className="agent-editor"><nav aria-label="Agent editor sections" className="agent-editor-nav">{(['basic', 'model', 'prompts', 'tools', 'knowledge', 'suggestions'] as const).map((section) => <button key={section} type="button" aria-current={value.section === section ? 'page' : undefined} onClick={() => onSectionChange(section)}>{section}</button>)}</nav><section><p className="wk-eyebrow">{initial?.section}</p>{value.section === 'basic' ? <><label htmlFor="agent-name">Name</label><Input id="agent-name" value={name} disabled={!editable || saving} onChange={(event) => setName(event.target.value)} /><label htmlFor="agent-description">Description</label><textarea id="agent-description" value={description} disabled={!editable || saving} onChange={(event) => setDescription(event.target.value)} /></> : <Status>Configuration for {value.section} is preserved by the existing Agent API contract.</Status>}{!editable ? <Status>You do not have permission to edit this agent.</Status> : null}{error ? <Status tone="error">{error}</Status> : null}<div className="agent-editor-actions"><Button type="button" onClick={onClose} disabled={saving}>Cancel</Button>{editable ? <Button type="button" variant="primary" loading={saving} onClick={() => void submit()}>Save</Button> : null}</div></section></div></Dialog>;
}
