/*
 * Chat copy for the React rendering layer, keyed by the active UI locale.
 *
 * Values are ported byte-exact from the authoritative Vue locales
 * (frontend/src/i18n/locales/{zh-CN,en-US,ja-JP,ko-KR,ru-RU}.ts) for every key
 * that exists there — the Vue source path is annotated on each zh-CN entry.
 * Keys the Vue locale files do not define (React-side affordances with no Vue
 * counterpart) keep their zh-CN string in all locales and are annotated
 * zh-only; they are recorded as a gap in
 * docs/migrations/react/evidence/vue-react-parity/2026-09-13-i18n-backfill.md.
 *
 * The chat-domain subset of these values is also generated into
 * @weknora/i18n (packages/i18n/src/generated/chat.ts). packages/views cannot
 * depend on @weknora/i18n (see integrations/messages.ts), so this local table
 * mirrors it byte-exact. Components resolve a table with resolveChatCopy()
 * (or take the resolved table via the copy prop); CHAT_COPY remains the
 * zh-CN default so existing consumers keep working.
 */

export const CHAT_COPY_LOCALES = ['zh-CN', 'en-US', 'ja-JP', 'ko-KR', 'ru-RU'] as const;

export type ChatCopyLocale = (typeof CHAT_COPY_LOCALES)[number];

/** The zh-CN table doubles as the key inventory for the other locales. */
const CHAT_COPY_ZH = {
/** chat.suggestedQuestions */
suggestedQuestions: '你可以这样问我',
/** chat.refreshSuggestedQuestions */
refreshSuggestedQuestions: '换一批',
/** chat.followUpQuestions */
followUpQuestions: '继续问',
/** chat.followUpQuestionsLoading */
followUpQuestionsLoading: '加载推荐问题',
/** chat.thinkingAlt */
thinkingAlt: '正在思考',
/** chat.fallbackHint */
fallbackHint: '未从知识库中检索到相关内容，以上为模型直接回答',
/** createChat.title */
createChatTitle: 'Hi，我是 WeKnora，让你的知识触手可及',
/** menu.newSession */
newSession: '新会话',
/** menu.myChats */
sidebarTitle: '我的对话',
sessionInProgress: '会话进行中',
/** menu.newChat */
newChat: '新对话',
/** menu.search */
searchSessions: '搜索',
/** knowledgeBase.columnSource */
sourceLabel: '来源',
/** embed.unknownLink */
unknownLink: '未知链接',
/** error.invalidImageLink — botmsg.vue invalid-image placeholder paragraph */
invalidImageLink: '无效的图片链接',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
groupLabel: '分组',
/** common.all */
groupAll: '全部',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
groupByDate: '按日期',
/** common.loading */
loadingSessions: '加载中...',
/** common.loading */
loadingMessages: '加载中...',
/** common.loading */
loadingHistory: '加载中...',
/** common.loadMore */
loadOlder: '加载更多',
/** menu.newSession */
untitledChat: '新会话',
/** input.send */
send: '发送',
/** input.stopGeneration */
stopGeneration: '停止生成',
/** input.placeholder */
composerPlaceholder: '直接向模型提问',
/** input.normalMode */
quickAnswer: '快速问答',
/** agent.selectAgent */
selectAgent: '选择智能体',
/** agent.manageAgents / builtinAgents / customAgents / noAgents / noDescription */
agentManageAgents: '管理',
agentBuiltinGroup: '内置智能体',
agentCustomGroup: '自定义智能体',
agentNoAgents: '暂无智能体',
agentNoDescription: '暂无描述',
/** agent.selector.* */
agentSelectorCurrent: '当前',
agentNotReadyStatus: '待配置',
agentNotReadyHint: '尚未就绪，还需配置：{items}',
agentConfigureAction: '去配置',
agentGoToSettings: '设置',
agentCapabilitiesSection: '能力',
agentCapWebSearch: '网络搜索',
agentCapImageUpload: '图片上传',
agentCapOn: '开启',
agentCapOff: '关闭',
agentCapUnset: '未配置',
agentCapSupported: '支持',
agentCapUnsupported: '不支持',
/** agent.type.* / capabilities.* */
agentModeTagQuick: '快速问答',
agentModeTagReasoning: '智能推理',
agentKbAll: '可访问全部知识库',
agentKbCount: '指定 {count} 个知识库',
agentMultiTurn: '多轮对话',
/** input.agentSwitchedOn/Off */
agentSwitchedOn: '已切换到智能推理',
agentSwitchedOff: '已切换到快速问答',
/** input.agentMissing*Model（内置与自定义文案一致，共用） */
agentMissingChatModel: '对话模型',
agentMissingRerankModel: '重排模型',
/** chat fork entries — upstream usermsg.vue:146 / botmsg.vue:224 hardcode zh tooltips;
 *  index.vue toasts 请等本轮回答结束后再分叉 / 分叉失败，请重试. */
forkFromUserTooltip: '从这里分叉出新会话',
forkFromAssistantTooltip: '从这条回答继续分叉',
forkBusyToast: '请等本轮回答结束后再分叉',
forkFailedToast: '分叉失败，请重试',
forkBadgeTooltip: '由其他会话分叉而来',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
uploadAttachment: '上传附件',
/** R472-A2 dedicated image upload button — Vue chat.imageUploadTooltip base
 *  label; the paste/drop suffix is dropped until the composer wires those. */
uploadImage: '上传图片',
/** input.knowledgeBase */
mentionKnowledge: '知识库',
mentionNoResults: '暂无匹配知识库',
mentionNoAvailable: '暂无可用知识库',
/** chat.noRelatedChunks */
noRelatedChunks: '没有找到相关片段',
/** chat.knowledgeBaseCount */
knowledgeBaseCount: '共 {count} 个知识库',
artifactPreviewBack: '返回列表',
artifactPreviewDownload: '下载',
artifactPreviewLoading: '加载预览中…',
artifactPreviewDownloadOnly: '下载后查看',
artifactPreviewPdf: 'PDF 预览',
artifactPreviewImage: '图片预览',
artifactPreviewMarkdown: 'Markdown 预览',
artifactPreviewText: '文本预览',
referencesTitle: '引用来源',
referenceWebSources: '网页来源',
referenceDocuments: '文档',
referenceToolResults: '工具结果',
referenceChunks: '引用片段',
approvalTitle: '工具调用需审批',
approvalViewArgs: '查看参数',
approvalApprove: '同意',
approvalReject: '拒绝',
approvalResolved: '已处理',
approvalInvalidJson: 'JSON 格式无效',
approvalArgsObject: '参数必须是 JSON 对象',
/** agentStream.toolApproval.argsModified */
approvalArgsModified: '已修改',
/** agentStream.toolApproval.userRejected */
approvalRejectedReason: '用户拒绝',
/** agentStream.toolApproval.countdownShort */
approvalCountdownShort: '{seconds}s',
oauthTitle: 'MCP 授权',
oauthTool: '工具',
oauthAuthorize: '去授权',
oauthCancel: '取消',
oauthAuthorized: '已授权',
chatActionsTitle: '操作',
toolCallsTitle: '工具调用',
metadataLabel: '元数据',
idLabel: 'ID',
/** input.agentMissingSummaryModel */
modelChip: '对话模型',
attachmentProcessing: '解析中',
steerAttachmentsBlocked: '请先移除附件，再补充当前任务',
/** time.today */
today: '今天',
/** time.yesterday */
yesterday: '昨天',
/** chat.conversationTime.today */
conversationTimeToday: '今天 {time}',
/** chat.conversationTime.yesterday */
conversationTimeYesterday: '昨天 {time}',
/** chat.conversationTime.thisYear */
conversationTimeThisYear: '{month}月{day}日 {time}',
/** chat.conversationTime.otherYear */
conversationTimeOtherYear: '{year}年{month}月{day}日 {time}',
/** chatHeader.moreActions */
moreActions: '更多对话操作',
/** menu.pin */
pin: '置顶',
/** menu.unpin */
unpin: '取消置顶',
/** menu.renameSession */
renameSession: '修改标题',
renameTitle: '修改标题',
renameTitlePlaceholder: '输入会话标题',
renameConfirm: '保存',
renameCancel: '取消',
renameSaving: '保存中…',
renameTitleRequired: '标题不能为空',
renameTitleFailed: '修改标题失败',
/** menu.clearMessages */
clearMessages: '清空消息',
/** upload.deleteRecord (Vue menu.vue session-row delete option) */
deleteRecord: '删除记录',
/** chatHeader.deleteSession */
deleteSession: '删除对话',
clearConfirmTitle: '确认清空消息',
clearConfirmBody: '确认清空当前对话的所有消息？此操作无法撤销。',
clearConfirmAction: '清空',
deleteConfirmTitle: '确认删除对话',
deleteConfirmAction: '删除',
/** chatHeader.deleteConfirmBody */
deleteConfirmBody: '确认删除当前对话？删除后将无法恢复。',
/** knowledgeList.loadFailed */
knowledgeBasesLoadFailed: '加载知识库失败',
operationFailed: '操作失败',
/** error.streamFailed (Vue streame.ts onerror prefix) */
streamFailed: '流式连接失败',
/** agent.copy */
copy: '复制',
/** common.copied */
copied: '已复制',
/** agent.addToKnowledgeBase */
addToKnowledgeBase: '添加到知识库',
/** chat.requestInfoTitle */
requestInfo: '请求信息',
/** chat.thinking */
thinking: '思考中...',
/** chat.deepThoughtCompleted */
deepThoughtCompleted: '已深度思考',
/** chat.deepThoughtAlt */
deepThoughtAlt: '深度思考完成',
/** common.finish */
finish: '完成',
/** chat.rawOutputLabel */
rawOutputLabel: '原始输出',
/** chat.sandbox.tabArtifacts */
artifacts: '产物',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
artifactsPending: '产物生成中…',
/** agent.artifactDrawer.preview */
preview: '预览',
/** common.download */
download: '下载',
/** settings.storage.available */
available: '可用',
/** tenantInvitation.status.expired */
expired: '已过期',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
sending: '发送中…',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
sendFailed: '发送失败',
/** common.retry */
retry: '重试',
/** input.steerCurrent */
steerCurrent: '补充当前任务',
/** input.steerAfter */
steerQueued: '完成后发送',
/** input.steerQueueSendNow */
steerQueueSendNow: '补充当前任务',
/** input.steerQueueWaiting */
steerQueueWaiting: '当前回答结束后发送',
/** input.steerRetry */
steerRetry: '重试发送',
/** common.remove */
remove: '移除',
/** chat.sandbox.panelTitle */
sandboxPanelTitle: '沙箱可视化',
/** chatHeader.toggleSandboxPanel */
openSandboxPanel: '沙箱终端',
/** common.close */
close: '关闭',
/** chat.sandbox.start */
startTerminal: '启动终端',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
terminalInput: '终端输入',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
sendInput: '发送输入',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
closeTerminal: '断开终端',
/** zh-only (no Vue locale source; see 2026-09-13-i18n-backfill.md) */
thinkingAndTools: '思考与工具',
/** knowledgeBase.columnStatus */
streamStatus: '状态',
/** agentStream.grepResults.titleMatch */
grepTitleMatch: '标题匹配',
/** agentStream.grepResults.faqEntry */
grepFaqEntry: 'FAQ 条目',
  toolNoResults: '暂无结果',
  toolNoRecords: '暂无记录',
  toolNoMatches: '未找到匹配项',
  toolEmptyOutput: '（无输出）',
  toolBinarySuppressed: '二进制输出已隐藏',
  toolWorkDir: '工作目录',
  toolExitCode: '退出码',
  toolStdout: '标准输出',
  toolStderr: '标准错误',
  toolUntitled: '未命名文档',
  toolTitleSearchResults: '搜索结果',
  toolTitleChunkDetail: '片段详情',
  toolTitleRelatedChunks: '相关片段',
  toolTitleKnowledgeBaseList: '知识库列表',
  toolTitleDocumentInfo: '文档信息',
  toolTitleGraphQueryResults: '图谱结果',
  toolTitleThinking: '思考',
  toolTitlePlan: '计划',
  toolTitleDatabaseQuery: '数据库查询',
  toolTitleWebSearchResults: '网页搜索结果',
  toolTitleWebFetchResults: '网页抓取结果',
  toolTitleGrepResults: '文件搜索',
  toolTitleKnowledgeChunksList: '知识片段',
  toolTitleWikiEdit: 'Wiki 更新',
  toolTitleShellExec: 'Shell 命令',
  toolTitleSandboxFiles: '沙箱文件',
  toolTitleSandboxFileWrite: '沙箱文件更新',
  toolTitleReadSkill: '读取技能',
  toolTitleMcpDiscovery: 'MCP 工具',
  toolTitleMcpCall: 'MCP 结果',
  toolTitlePlainText: '工具结果',
  toolChunkHits: '{count} 个片段命中',
  toolKeywordHits: '{count} 个关键词命中',
  toolKilled: '已终止',
  toolTruncated: '内容已截断',
  toolScore: '评分',
  toolChunks: '片段',
  toolFaqId: 'FAQ ID',
  toolDocumentId: '文档 ID',
  toolAnswers: '答案',
  toolDescription: '描述',
  toolSource: '来源',
  toolFile: '文件',
  toolUrl: 'URL',
  toolErrorCode: '错误码',
  chatScrollBottom: '滚动到底部',
  chatPreviewFailed: '加载产物预览失败',
/** chat.chunkIdLabel */
chunkIdLabel: '片段ID:',
/** chat.documentIdLabel */
documentIdLabel: '文档ID:',
/** chat.positionLabel */
positionLabel: '位置:',
/** agentStream.mcp.status.unavailable */
disabledAgentSuffix: '不可用',
/** chat.rawTextLabel */
rawTextLabel: '原始文本',
/** chat.webFetchPartialContent */
webFetchPartialContent: '部分页面内容',
/** chat.webFetchSummaryFailed */
webFetchSummaryFailed: '摘要失败',
/** chat.summaryLabel */
summaryLabel: '总结',
/** chat.fullContentLabel */
fullContentLabel: '完整内容',
/** chat.contentLengthLabelSimple */
contentLengthLabelSimple: '内容长度:',
/** chat.lengthChars */
lengthChars: '{value} 字',
/** chat.refreshSuggestedQuestions */
suggestedRefresh: '换一批',
/** common.collapse */
dismiss: '收起',
/** time.pinned */
groupPinned: '已置顶',
/** time.today */
groupToday: '今天',
/** time.yesterday */
groupYesterday: '昨天',
/** time.last7Days */
groupLast7Days: '近7天',
/** time.last30Days */
groupLast30Days: '近30天',
/** time.earlier */
groupOlder: '更早',
/** @weknora/i18n common.* bundle (no Vue key) */
previous: '上一页',
/** @weknora/i18n common.* bundle (no Vue key) */
next: '下一步',
/** @weknora/i18n common.* bundle (no Vue key) */
pageOf: '第 {page} 页 / 共 {total} 页',
batchManage: '批量管理',
batchCancel: '取消',
batchSelectAll: '全选会话',
batchDelete: '删除所选 ({count})',
batchDeleteConfirm: '确认删除选中的 {count} 个会话？删除后将无法恢复。',
batchDeleteError: '批量删除失败：{message}',
batchRetry: '重试',
batchDeleteBusy: '删除中…',
batchSelectSession: '选择会话 {title}',
sourceSelectLabel: '会话来源',
messagesLabel: '消息',
conversationPagesLabel: '会话分页',
};

export type ChatCopyKey = keyof typeof CHAT_COPY_ZH;

export type ChatCopyTable = Record<ChatCopyKey, string>;

/** All five locale tables; key sets are identical by construction. */
const CHAT_COPY_TABLES: Record<ChatCopyLocale, ChatCopyTable> = {
  'zh-CN': CHAT_COPY_ZH,
  'en-US': {
  suggestedQuestions: 'You can ask me',
  refreshSuggestedQuestions: 'More',
  followUpQuestions: 'Keep asking',
  followUpQuestionsLoading: 'Loading suggested questions',
  thinkingAlt: 'Thinking in progress',
  fallbackHint: 'No relevant content found in knowledge base. Above is a direct response from the model.',
  createChatTitle: 'Hi, I am WeKnora — your knowledge, within reach',
  newSession: 'New Chat',
  sidebarTitle: 'My chats',
  sessionInProgress: 'Conversation in progress',
  newChat: 'New Chat',
  searchSessions: 'Search',
  sourceLabel: 'Source',
  unknownLink: 'Unknown link',
  invalidImageLink: 'Invalid image link',
  groupLabel: '分组',
  groupAll: 'All',
  groupByDate: '按日期',
  loadingSessions: 'Loading...',
  loadingMessages: 'Loading...',
  loadingHistory: 'Loading...',
  loadOlder: 'Load more',
  untitledChat: 'New Chat',
  send: 'Send',
  stopGeneration: 'Stop Generation',
  composerPlaceholder: 'Ask questions directly to the model',
  quickAnswer: 'Quick Answer',
  selectAgent: 'Select Agent',
  agentManageAgents: 'Manage',
  agentBuiltinGroup: 'Built-in Agents',
  agentCustomGroup: 'Custom Agents',
  agentNoAgents: 'No agents',
  agentNoDescription: 'No description',
  agentSelectorCurrent: 'Current',
  agentNotReadyStatus: 'Setup needed',
  agentNotReadyHint: 'Not ready. Configure: {items}',
  agentConfigureAction: 'Configure',
  agentGoToSettings: 'Settings',
  agentCapabilitiesSection: 'Capabilities',
  agentCapWebSearch: 'Web search',
  agentCapImageUpload: 'Image upload',
  agentCapOn: 'On',
  agentCapOff: 'Off',
  agentCapUnset: 'Not set',
  agentCapSupported: 'Supported',
  agentCapUnsupported: 'Unsupported',
  agentModeTagQuick: 'Quick Answer',
  agentModeTagReasoning: 'Smart Reasoning',
  agentKbAll: 'Access to all knowledge bases',
  agentKbCount: '{count} knowledge base(s) specified',
  agentMultiTurn: 'Multi-turn conversation',
  agentSwitchedOn: 'Switched to Intelligent Reasoning',
  agentSwitchedOff: 'Switched to Quick Q&A',
  agentMissingChatModel: 'Chat model',
  agentMissingRerankModel: 'Rerank model',
  forkFromUserTooltip: '从这里分叉出新会话',
  forkFromAssistantTooltip: '从这条回答继续分叉',
  forkBusyToast: '请等本轮回答结束后再分叉',
  forkFailedToast: '分叉失败，请重试',
  forkBadgeTooltip: '由其他会话分叉而来',
  uploadAttachment: '上传附件',
  uploadImage: 'Upload image',
  mentionKnowledge: 'Knowledge Base',
  mentionNoResults: 'No matching knowledge bases',
  mentionNoAvailable: 'No knowledge bases available',
  noRelatedChunks: 'No related chunks found',
  knowledgeBaseCount: '{count} knowledge bases',
  artifactPreviewBack: 'Back to list',
  artifactPreviewDownload: 'Download',
  artifactPreviewLoading: 'Loading preview…',
  artifactPreviewDownloadOnly: 'Download to view',
  artifactPreviewPdf: 'PDF preview',
  artifactPreviewImage: 'Image preview',
  artifactPreviewMarkdown: 'Markdown preview',
  artifactPreviewText: 'Text preview',
  referencesTitle: 'References',
  referenceWebSources: 'Web sources',
  referenceDocuments: 'Documents',
  referenceToolResults: 'Tool results',
  referenceChunks: 'Reference chunks',
  approvalTitle: 'Tool approval required',
  approvalViewArgs: 'View arguments',
  approvalApprove: 'Approve',
  approvalReject: 'Reject',
  approvalResolved: 'Resolved',
  approvalInvalidJson: 'Invalid JSON',
  approvalArgsObject: 'Arguments must be a JSON object',
  /** agentStream.toolApproval.argsModified */
  approvalArgsModified: 'Modified',
  /** agentStream.toolApproval.userRejected */
  approvalRejectedReason: 'User rejected',
  /** agentStream.toolApproval.countdownShort */
  approvalCountdownShort: '{seconds}s',
  oauthTitle: 'MCP authorization',
  oauthTool: 'Tool',
  oauthAuthorize: 'Authorize',
  oauthCancel: 'Cancel',
  oauthAuthorized: 'Authorized',
  chatActionsTitle: 'Actions',
  toolCallsTitle: 'Tool calls',
  metadataLabel: 'Metadata',
  idLabel: 'ID',
  modelChip: 'Chat model',
  attachmentProcessing: 'Parsing…',
  steerAttachmentsBlocked: 'Remove attachments before steering the current task.',
  today: 'Today',
  yesterday: 'Yesterday',
  conversationTimeToday: 'Today {time}',
  conversationTimeYesterday: 'Yesterday {time}',
  conversationTimeThisYear: '{month}/{day} {time}',
  conversationTimeOtherYear: '{month}/{day}/{year} {time}',
  moreActions: 'More conversation actions',
  pin: 'Pin',
  unpin: 'Unpin',
  renameSession: 'Rename',
renameTitle: 'Rename conversation',
renameTitlePlaceholder: 'Enter a conversation title',
renameConfirm: 'Save',
renameCancel: 'Cancel',
renameSaving: 'Saving…',
renameTitleRequired: 'Title is required',
renameTitleFailed: 'Unable to rename conversation',
  clearMessages: 'Clear Messages',
  deleteRecord: 'Delete Record',
  deleteSession: 'Delete Conversation',
  clearConfirmTitle: 'Clear messages?',
  clearConfirmBody: 'Clear all messages in this conversation? This cannot be undone.',
  clearConfirmAction: 'Clear',
  deleteConfirmTitle: 'Delete conversation?',
  deleteConfirmAction: 'Delete',
  deleteConfirmBody: 'Delete this conversation? This cannot be undone.',
  knowledgeBasesLoadFailed: 'Failed to load knowledge bases',
operationFailed: 'Operation failed',
/** error.streamFailed */
streamFailed: 'Stream connection failed',
  copy: 'Copy',
  copied: 'Copied',
  addToKnowledgeBase: 'Add to Knowledge Base',
  requestInfo: 'Request info',
  thinking: 'Thinking...',
  deepThoughtCompleted: 'Deep thinking completed',
  deepThoughtAlt: 'Deep thinking finished',
  finish: 'Finish',
  rawOutputLabel: 'Raw output',
  artifacts: 'Files',
  artifactsPending: '产物生成中…',
  preview: 'Preview',
  download: 'Download',
  available: 'Available',
  expired: 'Expired',
  sending: '发送中…',
  sendFailed: '发送失败',
  retry: 'Retry',
  steerCurrent: 'Supplement current task',
  steerQueued: 'Send after completion',
  steerQueueSendNow: 'Supplement current task',
  steerQueueWaiting: 'Will send after the current answer finishes',
  steerRetry: 'Retry sending',
  remove: 'Remove',
  sandboxPanelTitle: 'Sandbox',
  openSandboxPanel: 'Sandbox terminal',
  close: 'Close',
  startTerminal: 'Start terminal',
  terminalInput: '终端输入',
  sendInput: '发送输入',
  closeTerminal: '断开终端',
  thinkingAndTools: '思考与工具',
  streamStatus: 'Status',
  grepTitleMatch: 'title',
  grepFaqEntry: 'FAQ entry',
  toolNoResults: 'No results',
  toolNoRecords: 'No records returned',
  toolNoMatches: 'No matches found',
  toolEmptyOutput: '(no output)',
  toolBinarySuppressed: 'Binary output suppressed',
  toolWorkDir: 'work dir',
  toolExitCode: 'exit code',
  toolStdout: 'stdout',
  toolStderr: 'stderr',
  toolUntitled: 'Untitled document',
  toolTitleSearchResults: 'Search results',
  toolTitleChunkDetail: 'Chunk detail',
  toolTitleRelatedChunks: 'Related chunks',
  toolTitleKnowledgeBaseList: 'Knowledge bases',
  toolTitleDocumentInfo: 'Document info',
  toolTitleGraphQueryResults: 'Graph results',
  toolTitleThinking: 'Thinking',
  toolTitlePlan: 'Plan',
  toolTitleDatabaseQuery: 'Database query',
  toolTitleWebSearchResults: 'Web search results',
  toolTitleWebFetchResults: 'Fetched page',
  toolTitleGrepResults: 'Search in files',
  toolTitleKnowledgeChunksList: 'Knowledge chunks',
  toolTitleWikiEdit: 'Wiki update',
  toolTitleShellExec: 'Shell command',
  toolTitleSandboxFiles: 'Sandbox files',
  toolTitleSandboxFileWrite: 'Sandbox file update',
  toolTitleReadSkill: 'Read skill',
  toolTitleMcpDiscovery: 'MCP tools',
  toolTitleMcpCall: 'MCP result',
  toolTitlePlainText: 'Tool result',
  toolChunkHits: '{count} chunk hits',
  toolKeywordHits: '{count} keyword hits',
  toolKilled: 'killed',
  toolTruncated: 'truncated',
  toolScore: 'score',
  toolChunks: 'chunks',
  toolFaqId: 'FAQ ID',
  toolDocumentId: 'Document ID',
  toolAnswers: 'Answers',
  toolDescription: 'Description',
  toolSource: 'Source',
  toolFile: 'File',
  toolUrl: 'URL',
  toolErrorCode: 'Error code',
  chatScrollBottom: 'Scroll to bottom',
  chatPreviewFailed: 'Unable to load artifact preview',
  chunkIdLabel: 'Chunk ID:',
  documentIdLabel: 'Document ID:',
  positionLabel: 'Position:',
  disabledAgentSuffix: 'Unavailable',
  rawTextLabel: 'Raw text',
  webFetchPartialContent: 'Partial page',
  webFetchSummaryFailed: 'Summary failed',
  summaryLabel: 'Summary',
  fullContentLabel: 'Full content',
  contentLengthLabelSimple: 'Content length:',
  lengthChars: '{value} characters',
  suggestedRefresh: 'More',
  dismiss: 'Collapse',
  groupPinned: 'Pinned',
  groupToday: 'Today',
  groupYesterday: 'Yesterday',
  groupLast7Days: 'Last 7 Days',
  groupLast30Days: 'Last 30 Days',
  groupOlder: 'Earlier',
  previous: 'Previous',
  next: 'Next',
  pageOf: 'Page {page} of {total}',
  batchManage: 'Batch manage',
  batchCancel: 'Cancel',
  batchSelectAll: 'Select all chats',
  batchDelete: 'Delete selected ({count})',
  batchDeleteConfirm: 'Delete the selected {count} chats? This cannot be undone.',
  batchDeleteError: 'Batch delete failed: {message}',
  batchRetry: 'Retry',
  batchDeleteBusy: 'Deleting…',
  batchSelectSession: 'Select chat {title}',
  sourceSelectLabel: 'Chat source',
  messagesLabel: 'Messages',
  conversationPagesLabel: 'Conversation pages',
  },
  'ja-JP': {
  suggestedQuestions: 'こんな質問ができます',
  refreshSuggestedQuestions: '別の候補',
  followUpQuestions: '続けて質問',
  followUpQuestionsLoading: '質問候補を読み込み中',
  thinkingAlt: '思考中',
  fallbackHint: 'ナレッジベースから関連する内容が見つかりませんでした。上記はモデルの直接回答です。',
  createChatTitle: 'こんにちは、WeKnoraです。あなたのナレッジを、すぐそばに',
  newSession: '新しいチャット',
  sidebarTitle: 'マイチャット',
  sessionInProgress: '会話中',
  newChat: '新しいチャット',
  searchSessions: '検索',
  sourceLabel: '取得元',
  unknownLink: '不明なリンク',
  invalidImageLink: '無効な画像リンクです',
  groupLabel: '分组',
  groupAll: 'すべて',
  groupByDate: '按日期',
  loadingSessions: '読み込み中...',
  loadingMessages: '読み込み中...',
  loadingHistory: '読み込み中...',
  loadOlder: 'さらに読み込む',
  untitledChat: '新しいチャット',
  send: '送信',
  stopGeneration: '生成を停止',
  composerPlaceholder: 'モデルに直接質問できます',
  quickAnswer: 'クイック回答',
  selectAgent: 'エージェントを選択',
  agentManageAgents: '管理',
  agentBuiltinGroup: '組み込みエージェント',
  agentCustomGroup: 'カスタムエージェント',
  agentNoAgents: 'エージェントがありません',
  agentNoDescription: '説明なし',
  agentSelectorCurrent: '現在',
  agentNotReadyStatus: '設定が必要',
  agentNotReadyHint: '準備ができていません。設定が必要な項目: {items}',
  agentConfigureAction: '設定を開く',
  agentGoToSettings: '設定',
  agentCapabilitiesSection: '機能',
  agentCapWebSearch: 'Web検索',
  agentCapImageUpload: '画像アップロード',
  agentCapOn: 'オン',
  agentCapOff: 'オフ',
  agentCapUnset: '未設定',
  agentCapSupported: '対応',
  agentCapUnsupported: '非対応',
  agentModeTagQuick: 'クイック回答',
  agentModeTagReasoning: 'スマート推論',
  agentKbAll: 'すべてのナレッジベースにアクセス可能',
  agentKbCount: 'ナレッジベース{count}件を指定',
  agentMultiTurn: 'マルチターン会話',
  agentSwitchedOn: 'スマート推論に切り替えました',
  agentSwitchedOff: 'クイック回答に切り替えました',
  agentMissingChatModel: 'チャットモデル',
  agentMissingRerankModel: 'リランクモデル',
  forkFromUserTooltip: 'ここから新しいセッションを分岐',
  forkFromAssistantTooltip: 'この回答から分岐を継続',
  forkBusyToast: 'この回答が終わってから分岐してください',
  forkFailedToast: '分岐に失敗しました。再試行してください',
  forkBadgeTooltip: '他のセッションから分岐されました',
  uploadAttachment: '上传附件',
  uploadImage: '画像をアップロード',
  mentionKnowledge: 'ナレッジベース',
  mentionNoResults: '一致するナレッジベースがありません',
  mentionNoAvailable: '利用可能なナレッジベースがありません',
  noRelatedChunks: '関連するチャンクが見つかりません',
  knowledgeBaseCount: '{count}件のナレッジベース',
  artifactPreviewBack: 'リストに戻る',
  artifactPreviewDownload: 'ダウンロード',
  artifactPreviewLoading: 'プレビューを読み込み中…',
  artifactPreviewDownloadOnly: 'ダウンロードして表示',
  artifactPreviewPdf: 'PDFプレビュー',
  artifactPreviewImage: '画像プレビュー',
  artifactPreviewMarkdown: 'Markdownプレビュー',
  artifactPreviewText: 'テキストプレビュー',
  referencesTitle: '引用元',
  referenceWebSources: 'ウェブソース',
  referenceDocuments: 'ドキュメント',
  referenceToolResults: 'ツール結果',
  referenceChunks: '引用チャンク',
  approvalTitle: 'ツール呼び出しの承認',
  approvalViewArgs: '引数を表示',
  approvalApprove: '承認',
  approvalReject: '拒否',
  approvalResolved: '処理済み',
  approvalInvalidJson: 'JSON が無効です',
  approvalArgsObject: '引数は JSON オブジェクトである必要があります',
  /** agentStream.toolApproval.argsModified */
  approvalArgsModified: '変更あり',
  /** agentStream.toolApproval.userRejected */
  approvalRejectedReason: 'ユーザが拒否しました',
  /** agentStream.toolApproval.countdownShort */
  approvalCountdownShort: '{seconds}秒',
  oauthTitle: 'MCP 認証',
  oauthTool: 'ツール',
  oauthAuthorize: '認証する',
  oauthCancel: 'キャンセル',
  oauthAuthorized: '認証済み',
  chatActionsTitle: '操作',
  toolCallsTitle: 'ツール呼び出し',
  metadataLabel: 'メタデータ',
  idLabel: 'ID',
  modelChip: 'チャットモデル',
  attachmentProcessing: '解析中…',
  steerAttachmentsBlocked: '添付ファイルを削除してから、現在のタスクを補足してください。',
  today: '今日',
  yesterday: '昨日',
  conversationTimeToday: '今日{time}',
  conversationTimeYesterday: '昨日{time}',
  conversationTimeThisYear: '{month}/{day} {time}',
  conversationTimeOtherYear: '{year}/{month}/{day} {time}',
  moreActions: 'その他の会話操作',
  pin: 'ピン留め',
  unpin: 'ピン留めを解除',
  renameSession: 'タイトルを変更',
renameTitle: '会話のタイトルを変更',
renameTitlePlaceholder: '会話のタイトルを入力',
renameConfirm: '保存',
renameCancel: 'キャンセル',
renameSaving: '保存中…',
renameTitleRequired: 'タイトルを入力してください',
renameTitleFailed: 'タイトルを変更できません',
  clearMessages: 'メッセージをクリア',
  deleteRecord: '記録を削除',
  deleteSession: '会話を削除',
  clearConfirmTitle: 'メッセージを削除しますか？',
  clearConfirmBody: 'この会話のすべてのメッセージを削除しますか？元に戻せません。',
  clearConfirmAction: '削除',
  deleteConfirmTitle: '会話を削除しますか？',
  deleteConfirmAction: '削除',
  deleteConfirmBody: 'この会話を削除しますか？この操作は取り消せません。',
  knowledgeBasesLoadFailed: 'ナレッジベースの読み込みに失敗しました',
operationFailed: '操作に失敗しました',
/** error.streamFailed */
streamFailed: 'ストリーム接続に失敗しました',
  copy: 'コピー',
  copied: 'コピーしました',
  addToKnowledgeBase: 'ナレッジベースに追加',
  requestInfo: 'リクエスト情報',
  thinking: '思考中...',
  deepThoughtCompleted: '深い思考が完了しました',
  deepThoughtAlt: '深い思考が完了',
  finish: '完了',
  rawOutputLabel: '生の出力',
  artifacts: 'ファイル',
  artifactsPending: '产物生成中…',
  preview: 'プレビュー',
  download: 'ダウンロード',
  available: '利用可能',
  expired: '期限切れ',
  sending: '发送中…',
  sendFailed: '发送失败',
  retry: '再試行',
  steerCurrent: '現在のタスクに追加',
  steerQueued: '完了後に送信',
  steerQueueSendNow: '現在のタスクに追加',
  steerQueueWaiting: '現在の回答が終わってから送信されます',
  steerRetry: '再送信',
  remove: '削除',
  sandboxPanelTitle: 'サンドボックス',
  openSandboxPanel: 'サンドボックスターミナル',
  close: '閉じる',
  startTerminal: 'ターミナルを起動',
  terminalInput: '终端输入',
  sendInput: '发送输入',
  closeTerminal: '断开终端',
  thinkingAndTools: '思考与工具',
  streamStatus: 'ステータス',
  grepTitleMatch: 'タイトル一致',
  grepFaqEntry: 'FAQ項目',
  toolNoResults: '結果なし',
  toolNoRecords: '返された記録はありません',
  toolNoMatches: '一致する項目がありません',
  toolEmptyOutput: '（出力なし）',
  toolBinarySuppressed: 'バイナリ出力は非表示です',
  toolWorkDir: '作業ディレクトリ',
  toolExitCode: '終了コード',
  toolStdout: '標準出力',
  toolStderr: '標準エラー',
  toolUntitled: '無題のドキュメント',
  toolTitleSearchResults: '検索結果',
  toolTitleChunkDetail: 'チャンク詳細',
  toolTitleRelatedChunks: '関連チャンク',
  toolTitleKnowledgeBaseList: 'ナレッジベース',
  toolTitleDocumentInfo: 'ドキュメント情報',
  toolTitleGraphQueryResults: 'グラフ結果',
  toolTitleThinking: '思考',
  toolTitlePlan: 'プラン',
  toolTitleDatabaseQuery: 'データベースクエリ',
  toolTitleWebSearchResults: 'ウェブ検索結果',
  toolTitleWebFetchResults: '取得したページ',
  toolTitleGrepResults: 'ファイル内検索',
  toolTitleKnowledgeChunksList: 'ナレッジチャンク',
  toolTitleWikiEdit: 'Wiki 更新',
  toolTitleShellExec: 'Shell コマンド',
  toolTitleSandboxFiles: 'サンドボックスファイル',
  toolTitleSandboxFileWrite: 'サンドボックスファイル更新',
  toolTitleReadSkill: 'スキルを読む',
  toolTitleMcpDiscovery: 'MCP ツール',
  toolTitleMcpCall: 'MCP 結果',
  toolTitlePlainText: 'ツール結果',
  toolChunkHits: '{count} 件のチャンクヒット',
  toolKeywordHits: '{count} 件のキーワードヒット',
  toolKilled: '終了',
  toolTruncated: '省略',
  toolScore: 'スコア',
  toolChunks: 'チャンク',
  toolFaqId: 'FAQ ID',
  toolDocumentId: 'ドキュメントID',
  toolAnswers: '回答',
  toolDescription: '説明',
  toolSource: 'ソース',
  toolFile: 'ファイル',
  toolUrl: 'URL',
  toolErrorCode: 'エラーコード',
  chatScrollBottom: '最下部へスクロール',
  chatPreviewFailed: 'アーティファクトのプレビューを読み込めません',
  chunkIdLabel: 'チャンクID:',
  documentIdLabel: 'ドキュメントID:',
  positionLabel: '位置:',
  disabledAgentSuffix: '利用不可',
  rawTextLabel: '元テキスト',
  webFetchPartialContent: 'ページの一部',
  webFetchSummaryFailed: '要約失敗',
  summaryLabel: '要約',
  fullContentLabel: '全文',
  contentLengthLabelSimple: 'コンテンツ長:',
  lengthChars: '{value}文字',
  suggestedRefresh: '別の候補',
  dismiss: '折りたたむ',
  groupPinned: 'ピン留め',
  groupToday: '今日',
  groupYesterday: '昨日',
  groupLast7Days: '過去7日間',
  groupLast30Days: '過去30日間',
  groupOlder: 'それ以前',
  previous: '前へ',
  next: '次へ',
  pageOf: '{total} ページ中 {page} ページ目',
  batchManage: '一括管理',
  batchCancel: 'キャンセル',
  batchSelectAll: '会話をすべて選択',
  batchDelete: '選択を削除 ({count})',
  batchDeleteConfirm: '選択した {count} 件の会話を削除しますか？元に戻せません。',
  batchDeleteError: '一括削除に失敗しました：{message}',
  batchRetry: '再試行',
  batchDeleteBusy: '削除中…',
  batchSelectSession: '会話 {title} を選択',
  sourceSelectLabel: '会話のソース',
  messagesLabel: 'メッセージ',
  conversationPagesLabel: '会話ページ',
  },
  'ko-KR': {
  suggestedQuestions: '이렇게 물어보세요',
  refreshSuggestedQuestions: '다른 질문',
  followUpQuestions: '이어서 질문',
  followUpQuestionsLoading: '추천 질문 로딩 중',
  thinkingAlt: '생각 중',
  fallbackHint: '지식 베이스에서 관련 내용을 찾지 못했습니다. 위는 모델의 직접 응답입니다.',
  createChatTitle: '안녕하세요, WeKnora입니다 — 당신의 지식을 손끝에',
  newSession: '새 세션',
  sidebarTitle: '내 대화',
  sessionInProgress: '대화 진행 중',
  newChat: '새 대화',
  searchSessions: '검색',
  sourceLabel: '소스',
  unknownLink: '알 수 없는 링크',
  invalidImageLink: '유효하지 않은 이미지 링크',
  groupLabel: '分组',
  groupAll: '전체',
  groupByDate: '按日期',
  loadingSessions: '로딩 중...',
  loadingMessages: '로딩 중...',
  loadingHistory: '로딩 중...',
  loadOlder: '더 보기',
  untitledChat: '새 세션',
  send: '전송',
  stopGeneration: '생성 중지',
  composerPlaceholder: '모델에 직접 질문',
  quickAnswer: '일반 모드',
  selectAgent: '에이전트 선택',
  agentManageAgents: '관리',
  agentBuiltinGroup: '내장된 인텔리전스',
  agentCustomGroup: '맞춤형 에이전트',
  agentNoAgents: '아직 에이전트가 없습니다.',
  agentNoDescription: '아직 설명이 없습니다',
  agentSelectorCurrent: '현재 선택',
  agentNotReadyStatus: '구성 필요',
  agentNotReadyHint: '아직 구성 필요: {items}',
  agentConfigureAction: '구성',
  agentGoToSettings: '설정',
  agentCapabilitiesSection: '능력',
  agentCapWebSearch: '웹 검색',
  agentCapImageUpload: '이미지 업로드',
  agentCapOn: '켜짐',
  agentCapOff: '꺼짐',
  agentCapUnset: '미구성',
  agentCapSupported: '지원',
  agentCapUnsupported: '미지원',
  agentModeTagQuick: '빠른 Q&A',
  agentModeTagReasoning: '에이전트 추론',
  agentKbAll: '전체 지식베이스에 액세스',
  agentKbCount: '{count} 지식베이스 지정',
  agentMultiTurn: '여러 라운드의 대화',
  agentSwitchedOn: 'Agent 모드로 전환되었습니다',
  agentSwitchedOff: '일반 모드로 전환되었습니다',
  agentMissingChatModel: '대화 모델',
  agentMissingRerankModel: '재정렬 모델',
  forkFromUserTooltip: '여기서 새 세션 분기',
  forkFromAssistantTooltip: '이 답변에서 분기 계속',
  forkBusyToast: '이번 답변이 끝난 후 분기하세요',
  forkFailedToast: '분기에 실패했습니다. 다시 시도하세요',
  forkBadgeTooltip: '다른 세션에서 분기됨',
  uploadAttachment: '上传附件',
  uploadImage: '이미지 업로드',
  mentionKnowledge: '지식베이스',
  mentionNoResults: '일치하는 지식베이스가 없습니다',
  mentionNoAvailable: '사용 가능한 지식베이스가 없습니다',
  noRelatedChunks: '관련 청크를 찾을 수 없습니다',
  knowledgeBaseCount: '총 {count}개 지식베이스',
  artifactPreviewBack: '목록으로 돌아가기',
  artifactPreviewDownload: '다운로드',
  artifactPreviewLoading: '미리보기 로드 중…',
  artifactPreviewDownloadOnly: '다운로드하여 보기',
  artifactPreviewPdf: 'PDF 미리보기',
  artifactPreviewImage: '이미지 미리보기',
  artifactPreviewMarkdown: 'Markdown 미리보기',
  artifactPreviewText: '텍스트 미리보기',
  referencesTitle: '참조 출처',
  referenceWebSources: '웹 소스',
  referenceDocuments: '문서',
  referenceToolResults: '도구 결과',
  referenceChunks: '참조 청크',
  approvalTitle: '도구 호출 승인 필요',
  approvalViewArgs: '매개변수 보기',
  approvalApprove: '승인',
  approvalReject: '거부',
  approvalResolved: '처리됨',
  approvalInvalidJson: '잘못된 JSON',
  approvalArgsObject: '인수는 JSON 객체여야 합니다',
  /** agentStream.toolApproval.argsModified */
  approvalArgsModified: '수정됨',
  /** agentStream.toolApproval.userRejected */
  approvalRejectedReason: '사용자 거부',
  /** agentStream.toolApproval.countdownShort */
  approvalCountdownShort: '{seconds}초',
  oauthTitle: 'MCP 인증',
  oauthTool: '도구',
  oauthAuthorize: '승인하기',
  oauthCancel: '취소',
  oauthAuthorized: '인증됨',
  chatActionsTitle: '작업',
  toolCallsTitle: '도구 호출',
  metadataLabel: '메타데이터',
  idLabel: 'ID',
  modelChip: '대화 모델',
  attachmentProcessing: '분석 중…',
  steerAttachmentsBlocked: '첨부 파일을 제거한 후 현재 작업을 보완하세요.',
  today: '오늘',
  yesterday: '어제',
  conversationTimeToday: '오늘 {time}',
  conversationTimeYesterday: '어제 {time}',
  conversationTimeThisYear: '{month}월 {day}일 {time}',
  conversationTimeOtherYear: '{year}년 {month}월 {day}일 {time}',
  moreActions: '대화 추가 작업',
  pin: '고정',
  unpin: '고정 해제',
  renameSession: '제목 수정',
renameTitle: '대화 제목 수정',
renameTitlePlaceholder: '대화 제목 입력',
renameConfirm: '저장',
renameCancel: '취소',
renameSaving: '저장 중…',
renameTitleRequired: '제목을 입력하세요',
renameTitleFailed: '대화 제목을 수정할 수 없습니다',
  clearMessages: '메시지 지우기',
  deleteRecord: '기록 삭제',
  deleteSession: '대화 삭제',
  clearConfirmTitle: '메시지를 지울까요?',
  clearConfirmBody: '이 대화의 모든 메시지를 지울까요? 되돌릴 수 없습니다.',
  clearConfirmAction: '지우기',
  deleteConfirmTitle: '대화를 삭제할까요?',
  deleteConfirmAction: '삭제',
  deleteConfirmBody: '현재 대화를 삭제할까요? 삭제 후에는 복구할 수 없습니다.',
  knowledgeBasesLoadFailed: '지식베이스 로드 실패',
operationFailed: '작업에 실패했습니다',
/** error.streamFailed */
streamFailed: '스트림 연결 실패',
  copy: '복사',
  copied: '복사됨',
  addToKnowledgeBase: '지식 베이스에 추가',
  requestInfo: 'Request info',
  thinking: '생각 중...',
  deepThoughtCompleted: '심층 분석 완료',
  deepThoughtAlt: '심층 분석 완료',
  finish: '완료',
  rawOutputLabel: '원시 출력',
  artifacts: '파일',
  artifactsPending: '产物生成中…',
  preview: '미리보기',
  download: '다운로드',
  available: '사용 가능',
  expired: '만료됨',
  sending: '发送中…',
  sendFailed: '发送失败',
  retry: '재시도',
  steerCurrent: '현재 작업에 추가',
  steerQueued: '완료 후 보내기',
  steerQueueSendNow: '현재 작업에 추가',
  steerQueueWaiting: '현재 답변이 끝난 뒤에 전송됩니다',
  steerRetry: '다시 보내기',
  remove: '제거',
  sandboxPanelTitle: '샌드박스',
  openSandboxPanel: '샌드박스 터미널',
  close: '닫기',
  startTerminal: '터미널 시작',
  terminalInput: '终端输入',
  sendInput: '发送输入',
  closeTerminal: '断开终端',
  thinkingAndTools: '思考与工具',
  streamStatus: '상태',
  grepTitleMatch: '제목',
  grepFaqEntry: 'FAQ entry',
  toolNoResults: '결과 없음',
  toolNoRecords: '반환된 레코드 없음',
  toolNoMatches: '일치하는 항목을 찾을 수 없음',
  toolEmptyOutput: '(출력 없음)',
  toolBinarySuppressed: '바이너리 출력이 숨겨짐',
  toolWorkDir: '작업 디렉터리',
  toolExitCode: '종료 코드',
  toolStdout: '표준 출력',
  toolStderr: '표준 오류',
  toolUntitled: '제목 없는 문서',
  toolTitleSearchResults: '검색 결과',
  toolTitleChunkDetail: '청크 상세',
  toolTitleRelatedChunks: '관련 청크',
  toolTitleKnowledgeBaseList: '지식 베이스',
  toolTitleDocumentInfo: '문서 정보',
  toolTitleGraphQueryResults: '그래프 결과',
  toolTitleThinking: '생각',
  toolTitlePlan: '계획',
  toolTitleDatabaseQuery: '데이터베이스 쿼리',
  toolTitleWebSearchResults: '웹 검색 결과',
  toolTitleWebFetchResults: '가져온 페이지',
  toolTitleGrepResults: '파일 검색',
  toolTitleKnowledgeChunksList: '지식 청크',
  toolTitleWikiEdit: 'Wiki 업데이트',
  toolTitleShellExec: 'Shell 명령',
  toolTitleSandboxFiles: '샌드박스 파일',
  toolTitleSandboxFileWrite: '샌드박스 파일 업데이트',
  toolTitleReadSkill: '스킬 읽기',
  toolTitleMcpDiscovery: 'MCP 도구',
  toolTitleMcpCall: 'MCP 결과',
  toolTitlePlainText: '도구 결과',
  toolChunkHits: '{count}개 청크 일치',
  toolKeywordHits: '{count}개 키워드 일치',
  toolKilled: '종료됨',
  toolTruncated: '잘림',
  toolScore: '점수',
  toolChunks: '청크',
  toolFaqId: 'FAQ ID',
  toolDocumentId: '문서 ID',
  toolAnswers: '답변',
  toolDescription: '설명',
  toolSource: '소스',
  toolFile: '파일',
  toolUrl: 'URL',
  toolErrorCode: '오류 코드',
  chatScrollBottom: '맨 아래로 스크롤',
  chatPreviewFailed: '아티팩트 미리보기를 불러올 수 없음',
  chunkIdLabel: '청크 ID:',
  documentIdLabel: '문서 ID:',
  positionLabel: '위치:',
  disabledAgentSuffix: '사용 불가',
  rawTextLabel: '원본 텍스트',
  webFetchPartialContent: '페이지 일부',
  webFetchSummaryFailed: '요약 실패',
  summaryLabel: '요약',
  fullContentLabel: '전체 내용',
  contentLengthLabelSimple: '내용 길이:',
  lengthChars: '{value}자',
  suggestedRefresh: '다른 질문',
  dismiss: '접기',
  groupPinned: '고정됨',
  groupToday: '오늘',
  groupYesterday: '어제',
  groupLast7Days: '최근 7일',
  groupLast30Days: '최근 30일',
  groupOlder: '이전',
  previous: '이전',
  next: '다음',
  pageOf: '{total} 페이지 중 {page} 페이지',
  batchManage: '일괄 관리',
  batchCancel: '취소',
  batchSelectAll: '대화 모두 선택',
  batchDelete: '선택 삭제 ({count})',
  batchDeleteConfirm: '선택한 {count}개의 대화를 삭제할까요? 되돌릴 수 없습니다.',
  batchDeleteError: '일괄 삭제 실패: {message}',
  batchRetry: '재시도',
  batchDeleteBusy: '삭제 중…',
  batchSelectSession: '대화 {title} 선택',
  sourceSelectLabel: '대화 출처',
  messagesLabel: '메시지',
  conversationPagesLabel: '대화 페이지',
  },
  'ru-RU': {
  suggestedQuestions: 'Вы можете спросить меня',
  refreshSuggestedQuestions: 'Ещё',
  followUpQuestions: 'Спрашивайте дальше',
  followUpQuestionsLoading: 'Загрузка рекомендуемых вопросов',
  thinkingAlt: 'Обдумывание...',
  fallbackHint: 'В базе знаний не найдено релевантного содержимого. Выше представлен прямой ответ модели.',
  createChatTitle: 'Привет, я WeKnora — ваши знания всегда под рукой',
  newSession: 'Новый диалог',
  sidebarTitle: 'Мои чаты',
  sessionInProgress: 'Диалог выполняется',
  newChat: 'Новый диалог',
  searchSessions: 'Поиск',
  sourceLabel: 'Источник',
  unknownLink: 'Неизвестная ссылка',
  invalidImageLink: 'Invalid image link',
  groupLabel: '分组',
  groupAll: 'Все',
  groupByDate: '按日期',
  loadingSessions: 'Загрузка...',
  loadingMessages: 'Загрузка...',
  loadingHistory: 'Загрузка...',
  loadOlder: 'Загрузить ещё',
  untitledChat: 'Новый диалог',
  send: 'Отправить',
  stopGeneration: 'Остановить генерацию',
  composerPlaceholder: 'Задайте вопрос напрямую модели',
  quickAnswer: 'Быстрый ответ',
  selectAgent: 'Select Agent',
  agentManageAgents: 'Manage',
  agentBuiltinGroup: 'Built-in Agents',
  agentCustomGroup: 'Custom Agents',
  agentNoAgents: 'No agents',
  agentNoDescription: 'No description',
  agentSelectorCurrent: 'Current',
  agentNotReadyStatus: 'Setup needed',
  agentNotReadyHint: 'Still needs: {items}',
  agentConfigureAction: 'Configure',
  agentGoToSettings: 'Settings',
  agentCapabilitiesSection: 'Возможности',
  agentCapWebSearch: 'Web search',
  agentCapImageUpload: 'Image upload',
  agentCapOn: 'On',
  agentCapOff: 'Off',
  agentCapUnset: 'Not set',
  agentCapSupported: 'Supported',
  agentCapUnsupported: 'Unsupported',
  agentModeTagQuick: 'Quick Answer',
  agentModeTagReasoning: 'Smart Reasoning',
  agentKbAll: 'Access to all knowledge bases',
  agentKbCount: '{count} knowledge base(s) specified',
  agentMultiTurn: 'Multi-turn conversation',
  agentSwitchedOn: 'Переключено в Agent режим',
  agentSwitchedOff: 'Переключено в обычный режим',
  agentMissingChatModel: 'Модель беседы',
  agentMissingRerankModel: 'Модель переранжирования',
  forkFromUserTooltip: 'Ответвить новый сеанс отсюда',
  forkFromAssistantTooltip: 'Продолжить ветвление от этого ответа',
  forkBusyToast: 'Дождитесь окончания ответа, затем ответвляйте',
  forkFailedToast: 'Не удалось ответвить. Повторите попытку',
  forkBadgeTooltip: 'Ответвлено от другого сеанса',
  uploadAttachment: '上传附件',
  uploadImage: 'Загрузить изображение',
  mentionKnowledge: 'База знаний',
  mentionNoResults: 'Подходящих баз знаний нет',
  mentionNoAvailable: 'Нет доступных баз знаний',
  noRelatedChunks: 'Связанные фрагменты не найдены',
  knowledgeBaseCount: '{count} баз знаний',
  artifactPreviewBack: 'Вернуться к списку',
  artifactPreviewDownload: 'Скачать',
  artifactPreviewLoading: 'Загрузка предпросмотра…',
  artifactPreviewDownloadOnly: 'Скачайте для просмотра',
  artifactPreviewPdf: 'Предпросмотр PDF',
  artifactPreviewImage: 'Предпросмотр изображения',
  artifactPreviewMarkdown: 'Предпросмотр Markdown',
  artifactPreviewText: 'Предпросмотр текста',
  referencesTitle: 'Источники',
  referenceWebSources: 'Веб-источники',
  referenceDocuments: 'Документы',
  referenceToolResults: 'Результаты инструментов',
  referenceChunks: 'Фрагменты источников',
  approvalTitle: 'Требуется подтверждение инструмента',
  approvalViewArgs: 'Показать аргументы',
  approvalApprove: 'Разрешить',
  approvalReject: 'Отклонить',
  approvalResolved: 'Обработано',
  approvalInvalidJson: 'Недопустимый JSON',
  approvalArgsObject: 'Аргументы должны быть объектом JSON',
  /** agentStream.toolApproval.argsModified */
  approvalArgsModified: 'Изменено',
  /** agentStream.toolApproval.userRejected */
  approvalRejectedReason: 'Отклонено пользователем',
  /** agentStream.toolApproval.countdownShort */
  approvalCountdownShort: '{seconds} с',
  oauthTitle: 'Авторизация MCP',
  oauthTool: 'Инструмент',
  oauthAuthorize: 'Авторизовать',
  oauthCancel: 'Отмена',
  oauthAuthorized: 'Авторизовано',
  chatActionsTitle: 'Действия',
  toolCallsTitle: 'Вызовы инструментов',
  metadataLabel: 'Метаданные',
  idLabel: 'ID',
  modelChip: 'Модель беседы',
  attachmentProcessing: 'Обработка…',
  steerAttachmentsBlocked: 'Удалите вложения перед дополнением текущей задачи.',
  today: 'Сегодня',
  yesterday: 'Вчера',
  conversationTimeToday: 'Сегодня {time}',
  conversationTimeYesterday: 'Вчера {time}',
  conversationTimeThisYear: '{day}.{month} {time}',
  conversationTimeOtherYear: '{day}.{month}.{year} {time}',
  moreActions: 'Другие действия с диалогом',
  pin: 'Закрепить',
  unpin: 'Открепить',
  renameSession: 'Переименовать',
renameTitle: 'Переименовать диалог',
renameTitlePlaceholder: 'Введите название диалога',
renameConfirm: 'Сохранить',
renameCancel: 'Отмена',
renameSaving: 'Сохранение…',
renameTitleRequired: 'Введите название',
renameTitleFailed: 'Не удалось переименовать диалог',
  clearMessages: 'Очистить сообщения',
  deleteRecord: 'Удалить запись',
  deleteSession: 'Удалить диалог',
  clearConfirmTitle: 'Очистить сообщения?',
  clearConfirmBody: 'Очистить все сообщения в этом диалоге? Это действие нельзя отменить.',
  clearConfirmAction: 'Очистить',
  deleteConfirmTitle: 'Удалить диалог?',
  deleteConfirmAction: 'Удалить',
  deleteConfirmBody: 'Удалить этот диалог? Это действие нельзя отменить.',
  knowledgeBasesLoadFailed: 'Не удалось загрузить базы знаний',
operationFailed: 'Не удалось выполнить операцию',
/** error.streamFailed */
streamFailed: 'Ошибка потокового соединения',
  copy: 'Копировать',
  copied: 'Скопировано',
  addToKnowledgeBase: 'Добавить в базу знаний',
  requestInfo: 'Request info',
  thinking: 'Думаю...',
  deepThoughtCompleted: 'Глубокий анализ завершён',
  deepThoughtAlt: 'Глубокий анализ',
  finish: 'Завершить',
  rawOutputLabel: 'Исходный вывод',
  artifacts: 'Файлы',
  artifactsPending: '产物生成中…',
  preview: 'Предпросмотр',
  download: 'Скачать',
  available: 'Доступно',
  expired: 'Expired',
  sending: '发送中…',
  sendFailed: '发送失败',
  retry: 'Повторить',
  steerCurrent: 'Дополнить текущую задачу',
  steerQueued: 'Отправить после завершения',
  steerQueueSendNow: 'Дополнить текущую задачу',
  steerQueueWaiting: 'Отправится после завершения текущего ответа',
  steerRetry: 'Повторить отправку',
  remove: 'Удалить',
  sandboxPanelTitle: 'Песочница',
  openSandboxPanel: 'Терминал песочницы',
  close: 'Закрыть',
  startTerminal: 'Запустить терминал',
  terminalInput: '终端输入',
  sendInput: '发送输入',
  closeTerminal: '断开终端',
  thinkingAndTools: '思考与工具',
  streamStatus: 'Статус',
  grepTitleMatch: 'заголовок',
  grepFaqEntry: 'FAQ entry',
  toolNoResults: 'Нет результатов',
  toolNoRecords: 'Записи не возвращены',
  toolNoMatches: 'Совпадений не найдено',
  toolEmptyOutput: '(нет вывода)',
  toolBinarySuppressed: 'Двоичный вывод скрыт',
  toolWorkDir: 'рабочий каталог',
  toolExitCode: 'код выхода',
  toolStdout: 'стандартный вывод',
  toolStderr: 'стандартная ошибка',
  toolUntitled: 'Документ без названия',
  toolTitleSearchResults: 'Результаты поиска',
  toolTitleChunkDetail: 'Детали фрагмента',
  toolTitleRelatedChunks: 'Связанные фрагменты',
  toolTitleKnowledgeBaseList: 'Базы знаний',
  toolTitleDocumentInfo: 'Информация о документе',
  toolTitleGraphQueryResults: 'Результаты графа',
  toolTitleThinking: 'Рассуждение',
  toolTitlePlan: 'План',
  toolTitleDatabaseQuery: 'Запрос к базе данных',
  toolTitleWebSearchResults: 'Результаты веб-поиска',
  toolTitleWebFetchResults: 'Полученная страница',
  toolTitleGrepResults: 'Поиск в файлах',
  toolTitleKnowledgeChunksList: 'Фрагменты знаний',
  toolTitleWikiEdit: 'Обновление Wiki',
  toolTitleShellExec: 'Команда Shell',
  toolTitleSandboxFiles: 'Файлы песочницы',
  toolTitleSandboxFileWrite: 'Обновление файла песочницы',
  toolTitleReadSkill: 'Чтение навыка',
  toolTitleMcpDiscovery: 'Инструменты MCP',
  toolTitleMcpCall: 'Результат MCP',
  toolTitlePlainText: 'Результат инструмента',
  toolChunkHits: 'Совпадений фрагментов: {count}',
  toolKeywordHits: 'Совпадений ключевых слов: {count}',
  toolKilled: 'завершено принудительно',
  toolTruncated: 'обрезано',
  toolScore: 'оценка',
  toolChunks: 'фрагменты',
  toolFaqId: 'ID FAQ',
  toolDocumentId: 'ID документа',
  toolAnswers: 'Ответы',
  toolDescription: 'Описание',
  toolSource: 'Источник',
  toolFile: 'Файл',
  toolUrl: 'URL',
  toolErrorCode: 'Код ошибки',
  chatScrollBottom: 'Прокрутить вниз',
  chatPreviewFailed: 'Не удалось загрузить предпросмотр артефакта',
  chunkIdLabel: 'ID фрагмента:',
  documentIdLabel: 'ID документа:',
  positionLabel: 'Позиция:',
  disabledAgentSuffix: 'Недоступно',
  rawTextLabel: 'Исходный текст',
  webFetchPartialContent: 'Часть страницы',
  webFetchSummaryFailed: 'Summary failed',
  summaryLabel: 'Сводка',
  fullContentLabel: 'Полный текст',
  contentLengthLabelSimple: 'Длина содержимого:',
  lengthChars: '{value} символов',
  suggestedRefresh: 'Ещё',
  dismiss: 'Свернуть',
  groupPinned: 'Закреплено',
  groupToday: 'Сегодня',
  groupYesterday: 'Вчера',
  groupLast7Days: 'Последние 7 дней',
  groupLast30Days: 'Последние 30 дней',
  groupOlder: 'Ранее',
  previous: 'Назад',
  next: 'Далее',
  pageOf: 'Страница {page} из {total}',
  batchManage: 'Массовое управление',
  batchCancel: 'Отмена',
  batchSelectAll: 'Выбрать все чаты',
  batchDelete: 'Удалить выбранные ({count})',
  batchDeleteConfirm: 'Удалить выбранные чаты ({count})? Отменить действие нельзя.',
  batchDeleteError: 'Ошибка массового удаления: {message}',
  batchRetry: 'Повторить',
  batchDeleteBusy: 'Удаление…',
  batchSelectSession: 'Выбрать чат {title}',
  sourceSelectLabel: 'Источник чатов',
  messagesLabel: 'Сообщения',
  conversationPagesLabel: 'Страницы диалогов',
  },
};

/** zh-CN table kept as the default for consumers that have no locale yet. */
export const CHAT_COPY: ChatCopyTable = CHAT_COPY_ZH;

export function isChatCopyLocale(value: string | null | undefined): value is ChatCopyLocale {
  return value != null && (CHAT_COPY_LOCALES as readonly string[]).includes(value);
}

/** Resolved chat copy for a locale; unknown locales fall back to zh-CN. */
export function resolveChatCopy(locale?: string | null): ChatCopyTable {
  return isChatCopyLocale(locale) ? CHAT_COPY_TABLES[locale] : CHAT_COPY_ZH;
}

/**
 * App locale convention: the language switch stores localStorage['locale']
 * (GeneralPreferencesPanel), otherwise the deployment default applies — the
 * same resolution as upstream i18n/index.ts (localStorage || BUILT_IN_DEFAULT)
 * and apps/web readStoredLocale(). The browser language is deliberately NOT
 * sniffed: an English browser must still see the Chinese deployment default,
 * matching the Vue app and keeping the chat view in the same locale as the
 * rest of this app.
 */
export function resolveChatLocale(): ChatCopyLocale {
  try {
    const stored = typeof window !== 'undefined' ? window.localStorage?.getItem('locale') : null;
    if (isChatCopyLocale(stored)) return stored;
  } catch {
    // Storage can be unavailable (sandboxed iframes); the deployment default
    // applies.
  }
  return 'zh-CN';
}

/** formatMessage-style {name} interpolation against a resolved table. */
export function formatChatCopy(table: ChatCopyTable, key: ChatCopyKey, values: Record<string, string | number> = {}): string {
  return table[key].replace(/\{(\w+)\}/g, (_match, name: string) => String(values[name] ?? `{${name}}`));
}

/** zh-CN-bound interpolation kept for the legacy module-level consumers. */
export function chatCopy(key: ChatCopyKey, values: Record<string, string | number> = {}): string {
  return formatChatCopy(CHAT_COPY, key, values);
}

/** Sidebar session group label for the keys produced by sessionGroups(). */
export function sessionGroupLabel(copy: ChatCopyTable, key: string): string {
  switch (key) {
    case 'pinned': return copy.groupPinned;
    case 'today': return copy.groupToday;
    case 'yesterday': return copy.groupYesterday;
    case 'last7Days': return copy.groupLast7Days;
    case 'last30Days': return copy.groupLast30Days;
    case 'older': return copy.groupOlder;
    default: return key;
  }
}

/**
 * Conversation date separator labels (chat.conversationTime.*) for
 * formatConversationTimestampLabel: the {time} placeholder is handled by the
 * caller, so the thisYear/otherYear formatters strip it from the template.
 */
export function conversationTimeLabels(copy: ChatCopyTable) {
  const dayLabel = (template: ChatCopyKey, model: { year: number; month: number; day: number }): string =>
    formatChatCopy(copy, template, { ...model, time: '' }).trim();
  return {
    today: copy.today,
    yesterday: copy.yesterday,
    thisYear: (model: { year: number; month: number; day: number }): string => dayLabel('conversationTimeThisYear', model),
    otherYear: (model: { year: number; month: number; day: number }): string => dayLabel('conversationTimeOtherYear', model),
  };
}

/** zh-CN conversation labels kept for the legacy module-level consumers. */
export const CONVERSATION_TIME_LABELS = conversationTimeLabels(CHAT_COPY);
