from pathlib import Path
import json,re
R=Path(__file__).resolve().parent.parent
pages=json.loads((R/'fixtures/pages.json').read_text());tokens=json.loads((R/'tokens/tokens.json').read_text())
css=(R/'tokens/tokens.css').read_text()+'\n'+(R/'prototype-src/style.css').read_text()
js=(R/'prototype-src/model.cjs').read_text()+'\n'+(R/'prototype-src/app.js').read_text().replace('PAGE_DEFINITIONS',json.dumps(pages,ensure_ascii=False)).replace('DESIGN_TOKENS', 'DESIGN_TOKENS')
js='const DESIGN_TOKENS='+json.dumps(tokens,ensure_ascii=False)+';\n'+js
shell='''<!doctype html><html lang="zh-CN" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><title>WeKnora · 移动工作台高保真设计</title><style>__CSS__</style></head><body data-start-page="__PAGE__"><header class="topbar"><div class="brandlock"><div class="brandmark"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3L12 3"/></svg></div><span class="logoname">WeKnora</span><div class="eyebrow">MOBILE WORKBENCH<br>PRODUCT DESIGN / 02</div></div><select id="mobile-pages" class="mobile-page-select" aria-label="切换页面"></select><div class="tools"><span class="version">18 个页面 · 本地演示</span><select id="scenario" class="studio-btn" aria-label="异常场景"><option value="normal">正常场景</option><option value="offline">离线</option><option value="conflict">审批冲突</option><option value="forbidden">无权限</option><option value="unknown">启动未知</option><option value="loading">加载中</option><option value="empty">空状态</option><option value="error">网络错误</option></select><button id="theme-button" class="studio-btn" data-act="theme" aria-label="切换深色主题">外观</button><button id="text-button" class="studio-btn desktop-tool" data-act="large" aria-label="切换大字体">Aa</button><button id="gallery-button" class="studio-btn desktop-tool" data-act="gallery">全部页面</button><button id="guide-button" class="studio-btn desktop-tool" data-act="guide">设计系统</button><button class="studio-btn desktop-tool" data-act="reset">重置</button></div></header><div class="studio-layout" id="studio-layout"><aside class="side"><nav id="sidenav" aria-label="设计页面导航"></nav><div class="side-foot">Quiet Workbench<br>暖白 × 深青绿 × 清晰层次<br>交付基线 · 2026.09.17<br><br>源码基线继承 12737238…<br>本原型不连接真实服务</div></aside><section class="preview"><div class="screen-label"><b id="screen-title">M03 / 工作台</b><span class="muted">390 × 844</span></div><div class="phone" id="phone"></div><p class="footnote">可体验完整流程与异常场景。任务、账户和费用为模拟数据；下载仅生成本地示例文件。</p></section><aside id="inspector" class="inspector" aria-label="设计说明"></aside></div><section class="gallery" id="gallery" hidden></section><section id="guide" hidden></section><script>__JS__</script></body></html>'''
base=shell.replace('__CSS__',css).replace('__JS__',js.replace('</script','<\\/script'))
(R/'index.html').write_text(base.replace('__PAGE__','home'))
(R/'design-system.html').write_text(base.replace('__PAGE__','home').replace("let state=WorkbenchModel.initial(),", "let state=WorkbenchModel.initial(),").replace("mode='preview', returnFocus=''", "mode='guide', returnFocus=''"))
(R/'pages').mkdir(exist_ok=True)
for p in pages:(R/'pages'/f'{p["no"]}-{p["id"]}.html').write_text(base.replace('__PAGE__',p['id']))
(R/'prototype-src/shell.html').write_text(shell)
print('Generated standalone index, design-system and',len(pages),'individual pages. bytes=',(R/'index.html').stat().st_size)
