package repository

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"net/url"
	"strings"
	"time"

	"github.com/Tencent/WeKnora/internal/agent/nativecontract"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// NativeOAuthBinding is resolved by server authority. The service must enforce
// its redirect allowlist before Create; the repository freezes that exact URI.
// Expiry must use microsecond precision, the common SQLite/PostgreSQL contract.
type NativeOAuthBinding struct {
	Key                                                    nativecontract.PendingKey
	Principal                                              nativecontract.Principal
	SessionOwnerID, ServiceID, InstallationID, RedirectURI string
	PendingRevision                                        int64
	ExpiresAt                                              time.Time
}

// NativeOAuthAttempt is an internal write command, not a response DTO. StateHash
// is the SHA-256 digest of a high-entropy state generated by the future adapter.
type NativeOAuthAttempt struct {
	Binding   NativeOAuthBinding
	AttemptID string
	StateHash string `json:"-"`
}

// NativeOAuthMetadata intentionally omits both state and receipt digests. A
// consumed record is callback evidence only, never permission for tool dispatch.
type NativeOAuthMetadata struct {
	Binding    NativeOAuthBinding
	AttemptID  string
	Revision   int64
	ConsumedAt *time.Time
}

// NativeOAuthRepository persists OAuth attempts without provider I/O, token
// storage, or pending resolution. No production adapter is registered here.
type NativeOAuthRepository struct {
	db  *gorm.DB
	now func() time.Time
}

func NewNativeOAuthRepository(db *gorm.DB, now func() time.Time) *NativeOAuthRepository {
	if now == nil {
		now = time.Now
	}
	return &NativeOAuthRepository{db: db, now: now}
}

type nativeOAuthRow struct {
	TenantID                                                                                                            uint64
	RunID, PendingID, AttemptID, SessionID, OwnerID, PrincipalType, PrincipalID, ServiceID, InstallationID, RedirectURI string
	PendingRevision, Revision                                                                                           int64
	ExpiresAt                                                                                                           time.Time
	ConsumedAt                                                                                                          *time.Time
	BindingHash, StateHash, ReceiptHash                                                                                 string
}

func nativeOAuthDigest(value string) bool {
	decoded, err := hex.DecodeString(value)
	return err == nil && len(decoded) == sha256.Size && value == strings.ToLower(value)
}

func nativeOAuthBindingHash(b NativeOAuthBinding) string {
	b.ExpiresAt = b.ExpiresAt.UTC().Truncate(time.Microsecond)
	data, _ := json.Marshal(b)
	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:])
}

func nativeOAuthRowFor(a NativeOAuthAttempt) nativeOAuthRow {
	b := a.Binding
	return nativeOAuthRow{TenantID: b.Key.Run.TenantID, RunID: b.Key.Run.RunID, PendingID: b.Key.PendingID, AttemptID: a.AttemptID,
		SessionID: b.Key.Run.SessionID, OwnerID: b.SessionOwnerID, PrincipalType: b.Principal.Type, PrincipalID: b.Principal.ID,
		ServiceID: b.ServiceID, InstallationID: b.InstallationID, RedirectURI: b.RedirectURI, PendingRevision: b.PendingRevision,
		ExpiresAt: b.ExpiresAt.UTC().Truncate(time.Microsecond), BindingHash: nativeOAuthBindingHash(b), StateHash: a.StateHash, Revision: 1}
}

func (row nativeOAuthRow) metadata() NativeOAuthMetadata {
	if row.ConsumedAt != nil {
		normalized := row.ConsumedAt.UTC()
		row.ConsumedAt = &normalized
	}
	return NativeOAuthMetadata{Binding: NativeOAuthBinding{Key: nativecontract.PendingKey{Run: nativecontract.RunIdentity{TenantID: row.TenantID, RunID: row.RunID, SessionID: row.SessionID}, PendingID: row.PendingID},
		Principal: nativecontract.Principal{Type: row.PrincipalType, ID: row.PrincipalID}, SessionOwnerID: row.OwnerID, ServiceID: row.ServiceID, InstallationID: row.InstallationID, RedirectURI: row.RedirectURI,
		PendingRevision: row.PendingRevision, ExpiresAt: row.ExpiresAt.UTC()}, AttemptID: row.AttemptID, Revision: row.Revision, ConsumedAt: row.ConsumedAt}
}

func (r *NativeOAuthRepository) validate(scope nativecontract.Scope, a NativeOAuthAttempt) error {
	if r == nil || r.db == nil || r.now == nil {
		return nativePendingFailure(nativecontract.ErrStore, "OAuth attempt store is unavailable")
	}
	b := a.Binding
	if !validNativePendingKey(b.Key) || scope.TenantID != b.Key.Run.TenantID || scope.SessionOwnerID == "" || b.SessionOwnerID != scope.SessionOwnerID || scope.Principal.Type == "" || scope.Principal.ID == "" || b.Principal != scope.Principal {
		return nativePendingFailure(nativecontract.ErrNotFound, "OAuth attempt was not found")
	}
	u, err := url.Parse(b.RedirectURI)
	if b.ServiceID == "" || b.PendingRevision < 1 || b.ExpiresAt.IsZero() || !b.ExpiresAt.Equal(b.ExpiresAt.Truncate(time.Microsecond)) || a.AttemptID == "" || !nativeOAuthDigest(a.StateHash) || err != nil || u.Scheme != "https" || u.Host == "" || u.User != nil || u.Fragment != "" {
		return nativePendingFailure(nativecontract.ErrInvalid, "OAuth attempt binding is invalid")
	}
	return nil
}

// lockRun follows the pending repository's run-first lock order. Its first
// statement is a write, avoiding SQLite deferred read-to-write upgrade races.
func (r *NativeOAuthRepository) lockRun(tx *gorm.DB, scope nativecontract.Scope, b NativeOAuthBinding) error {
	locked := tx.Table("native_agent_runs").Where("tenant_id=? AND run_id=? AND session_id=? AND owner_id=?", b.Key.Run.TenantID, b.Key.Run.RunID, b.Key.Run.SessionID, scope.SessionOwnerID).UpdateColumn("revision", gorm.Expr("revision"))
	if locked.Error != nil {
		return nativePendingFailure(nativecontract.ErrStore, "OAuth authority lock failed")
	}
	if locked.RowsAffected != 1 {
		return nativePendingFailure(nativecontract.ErrNotFound, "OAuth pending was not found")
	}
	return nil
}

// validatePending requires the caller to hold the run lock. Only creation and
// first consumption need a live pending decision; a committed replay is a read.
func (r *NativeOAuthRepository) validatePending(tx *gorm.DB, scope nativecontract.Scope, b NativeOAuthBinding) error {
	p := NewNativePendingDecisionRepository(tx)
	run, err := p.scopedRun(tx, scope, b.Key.Run)
	if err != nil {
		return err
	}
	row, err := p.load(tx, b.Key)
	if err != nil {
		return err
	}
	detail, err := nativePendingDetailFromRow(row, run)
	if err != nil {
		return err
	}
	now := r.now()
	if row.Revision != b.PendingRevision || detail.Status != nativecontract.PendingOpen || detail.WaitKind != nativecontract.WaitOAuth || detail.RunStatus != nativecontract.RunWaiting || detail.Service.ServiceID != b.ServiceID || detail.Service.InstallationID != b.InstallationID || detail.OAuth == nil || detail.OAuth.ServiceID != b.ServiceID || !detail.ExpiresAt.After(now) || !b.ExpiresAt.After(now) || b.ExpiresAt.After(detail.ExpiresAt) {
		return nativePendingFailure(nativecontract.ErrConflict, "OAuth pending binding is stale or expired")
	}
	return nil
}

func (r *NativeOAuthRepository) Create(ctx context.Context, scope nativecontract.Scope, a NativeOAuthAttempt) error {
	if err := r.validate(scope, a); err != nil {
		return err
	}
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := r.lockRun(tx, scope, a.Binding); err != nil {
			return err
		}
		if err := r.validatePending(tx, scope, a.Binding); err != nil {
			return err
		}
		row := nativeOAuthRowFor(a)
		created := tx.Table("native_agent_oauth_attempts").Clauses(clause.OnConflict{DoNothing: true}).Create(&row)
		if created.Error != nil {
			return nativePendingFailure(nativecontract.ErrStore, "OAuth attempt creation failed")
		}
		if created.RowsAffected == 1 {
			return nil
		}
		var stored nativeOAuthRow
		err := tx.Table("native_agent_oauth_attempts").Where("tenant_id=? AND attempt_id=?", row.TenantID, row.AttemptID).Take(&stored).Error
		if err == nil && stored.BindingHash == row.BindingHash && stored.StateHash == row.StateHash && stored.Revision == 1 {
			return nil
		}
		return nativePendingFailure(nativecontract.ErrConflict, "OAuth attempt or state already exists")
	})
}

func (r *NativeOAuthRepository) Get(ctx context.Context, scope nativecontract.Scope, key nativecontract.PendingKey, attemptID string) (NativeOAuthMetadata, error) {
	if r == nil || r.db == nil {
		return NativeOAuthMetadata{}, nativePendingFailure(nativecontract.ErrStore, "OAuth attempt store is unavailable")
	}
	if !validNativePendingKey(key) || scope.TenantID != key.Run.TenantID || scope.SessionOwnerID == "" || scope.Principal.Type == "" || scope.Principal.ID == "" {
		return NativeOAuthMetadata{}, nativePendingFailure(nativecontract.ErrNotFound, "OAuth attempt was not found")
	}
	var row nativeOAuthRow
	err := r.db.WithContext(ctx).Table("native_agent_oauth_attempts AS a").Select("a.*").Joins("JOIN native_agent_runs AS r ON r.tenant_id=a.tenant_id AND r.run_id=a.run_id AND r.session_id=a.session_id AND r.owner_id=a.owner_id").
		Where("a.tenant_id=? AND a.run_id=? AND a.pending_id=? AND a.session_id=? AND a.owner_id=? AND a.principal_type=? AND a.principal_id=? AND a.attempt_id=?", scope.TenantID, key.Run.RunID, key.PendingID, key.Run.SessionID, scope.SessionOwnerID, scope.Principal.Type, scope.Principal.ID, attemptID).Take(&row).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return NativeOAuthMetadata{}, nativePendingFailure(nativecontract.ErrNotFound, "OAuth attempt was not found")
	}
	if err != nil {
		return NativeOAuthMetadata{}, nativePendingFailure(nativecontract.ErrStore, "OAuth attempt read failed")
	}
	return row.metadata(), nil
}

// Consume accepts only a receipt hash already verified by the service adapter.
// It cannot verify provider proof itself. The first receipt wins; an identical
// receipt replays that committed result even after expiry, while any other
// receipt conflicts. A replay never renews expiry or authorizes new consumption.
func (r *NativeOAuthRepository) Consume(ctx context.Context, scope nativecontract.Scope, a NativeOAuthAttempt, verifiedReceiptHash string) (NativeOAuthMetadata, error) {
	if err := r.validate(scope, a); err != nil {
		return NativeOAuthMetadata{}, err
	}
	if !nativeOAuthDigest(verifiedReceiptHash) {
		return NativeOAuthMetadata{}, nativePendingFailure(nativecontract.ErrInvalid, "verified OAuth receipt hash is required")
	}
	var result NativeOAuthMetadata
	err := r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := r.lockRun(tx, scope, a.Binding); err != nil {
			return err
		}
		var row nativeOAuthRow
		err := tx.Table("native_agent_oauth_attempts").Where("tenant_id=? AND attempt_id=?", scope.TenantID, a.AttemptID).Take(&row).Error
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nativePendingFailure(nativecontract.ErrConflict, "OAuth callback binding does not match")
		}
		if err != nil {
			return nativePendingFailure(nativecontract.ErrStore, "OAuth attempt read failed")
		}
		if row.BindingHash != nativeOAuthBindingHash(a.Binding) || row.StateHash != a.StateHash {
			return nativePendingFailure(nativecontract.ErrConflict, "OAuth callback binding is invalid")
		}
		if row.Revision == 2 {
			if row.ReceiptHash != verifiedReceiptHash {
				return nativePendingFailure(nativecontract.ErrConflict, "OAuth callback was already consumed")
			}
			result = row.metadata()
			return nil
		}
		if err := r.validatePending(tx, scope, a.Binding); err != nil {
			return err
		}
		now := r.now().UTC().Truncate(time.Microsecond)
		updated := tx.Table("native_agent_oauth_attempts").Where("tenant_id=? AND attempt_id=? AND revision=1 AND expires_at > ? AND binding_hash=? AND state_hash=?", scope.TenantID, a.AttemptID, now, row.BindingHash, a.StateHash).
			Updates(map[string]any{"revision": 2, "receipt_hash": verifiedReceiptHash, "consumed_at": now})
		if updated.Error != nil {
			return nativePendingFailure(nativecontract.ErrStore, "OAuth receipt consumption failed")
		}
		if updated.RowsAffected != 1 {
			return nativePendingFailure(nativecontract.ErrConflict, "OAuth callback changed or expired")
		}
		row.Revision, row.ReceiptHash, row.ConsumedAt = 2, verifiedReceiptHash, &now
		result = row.metadata()
		return nil
	})
	if err != nil {
		return NativeOAuthMetadata{}, err
	}
	return result, nil
}
