package repository

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/Tencent/WeKnora/internal/types"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// openQueryHistoryTestDB keeps the migration dialect explicit, mirroring the
// native-schema smoke tests: SQLite is the always-on fast path and PostgreSQL
// runs the full versioned chain when TRPC_TEST_POSTGRES_DSN is provided.
func openQueryHistoryTestDB(t *testing.T, dialect string) *gorm.DB {
	t.Helper()
	switch dialect {
	case "sqlite":
		return openRunTestDB(t)
	case "postgres":
		if os.Getenv("TRPC_TEST_POSTGRES_DSN") == "" {
			t.Skip("TRPC_TEST_POSTGRES_DSN unset: query-history PostgreSQL evidence blocked-env")
		}
		_, filename, _, ok := runtime.Caller(0)
		require.True(t, ok)
		root := filepath.Clean(filepath.Join(filepath.Dir(filename), "../../.."))
		return openPostgresRunTestDB(t, root)
	default:
		t.Fatalf("unsupported query history test dialect %q", dialect)
		return nil
	}
}

// TestQueryHistoryShareTokenPartialUniqueIndex pins the share_token contract:
// a non-NULL token is globally unique across all sessions, while any number of
// sessions may keep a NULL token (the partial index skips them).
func TestQueryHistoryShareTokenPartialUniqueIndex(t *testing.T) {
	for _, dialect := range []string{"sqlite", "postgres"} {
		t.Run(dialect, func(t *testing.T) {
			db := openQueryHistoryTestDB(t, dialect)
			insert := func(id, shareToken string) error {
				return db.Exec(
					`INSERT INTO sessions (id, tenant_id, title, user_id, engine_type, share_token)
					 VALUES (?, 1, ?, 'u1', 'builtin', ?)`, id, id, shareToken,
				).Error
			}
			insertNull := func(id string) error {
				return db.Exec(
					`INSERT INTO sessions (id, tenant_id, title, user_id, engine_type)
					 VALUES (?, 1, ?, 'u1', 'builtin')`, id, id,
				).Error
			}

			require.NoError(t, insert("share-a", "tok-alpha"), "first non-NULL share_token must insert")
			require.Error(t, insert("share-b", "tok-alpha"),
				"a second session reusing a non-NULL share_token must violate the partial unique index")
			require.NoError(t, insert("share-c", "tok-beta"), "a different share_token must insert")

			// NULL tokens are excluded from the partial index: many sessions can
			// hold no token at once, and unshare/expire paths rely on that.
			// (An empty string would NOT be NULL, so NULL rows omit the column.)
			require.NoError(t, insertNull("share-null-1"))
			require.NoError(t, insertNull("share-null-2"))

			var shared int64
			require.NoError(t, db.Raw(
				`SELECT COUNT(*) FROM sessions WHERE share_token IS NOT NULL`,
			).Scan(&shared).Error)
			require.EqualValues(t, 2, shared, "expected exactly the two distinct non-NULL tokens")
		})
	}
}

// TestQueryHistoryExportJobsTableSmoke verifies the export-job table created
// by the migration round-trips through the GORM model with its defaults.
func TestQueryHistoryExportJobsTableSmoke(t *testing.T) {
	for _, dialect := range []string{"sqlite", "postgres"} {
		t.Run(dialect, func(t *testing.T) {
			db := openQueryHistoryTestDB(t, dialect)

			job := types.QueryHistoryExportJob{
				TenantID:    1,
				RequestedBy: "u1",
				Status:      types.QueryHistoryExportPending,
			}
			require.NoError(t, db.Create(&job).Error)
			require.NotZero(t, job.ID, "export job id must be generated by the database")

			var got types.QueryHistoryExportJob
			require.NoError(t, db.Where("tenant_id = ?", 1).First(&got).Error)
			require.Equal(t, types.QueryHistoryExportPending, got.Status)
			require.Equal(t, "u1", got.RequestedBy)
			require.Empty(t, got.FilePath, "file_path must default to empty until the export lands")
			require.Empty(t, got.ErrorMessage)
			require.False(t, got.CreatedAt.IsZero(), "created_at must default at insert time")
			require.False(t, got.UpdatedAt.IsZero(), "updated_at must default at insert time")

			require.NoError(t, db.Model(&got).Updates(map[string]interface{}{
				"status":        types.QueryHistoryExportFailed,
				"error_message": "boom",
			}).Error)
			var failed types.QueryHistoryExportJob
			require.NoError(t, db.Where("id = ?", got.ID).First(&failed).Error)
			require.Equal(t, types.QueryHistoryExportFailed, failed.Status)
			require.Equal(t, "boom", failed.ErrorMessage)

			require.Equal(t, "query_history_export_jobs", (&types.QueryHistoryExportJob{}).TableName())
		})
	}
}

// TestTenantQueryHistoryConfigRoundTrip verifies the tenants.query_history_config
// JSONB column persists and reloads the workspace-level config.
func TestTenantQueryHistoryConfigRoundTrip(t *testing.T) {
	for _, dialect := range []string{"sqlite", "postgres"} {
		t.Run(dialect, func(t *testing.T) {
			db := openQueryHistoryTestDB(t, dialect)

			// Baseline: the column exists and reads as unconfigured.
			var before types.Tenant
			require.NoError(t, db.Where("id = ?", 1).First(&before).Error)
			require.Nil(t, before.QueryHistoryConfig, "a tenant migrated without config must read as nil")

			cfg := &types.QueryHistoryConfig{Mode: types.QueryHistoryModeAnonymized}
			cfg.Normalize()
			require.NoError(t, db.Model(&types.Tenant{}).Where("id = ?", 1).
				Update("query_history_config", cfg).Error)

			var after types.Tenant
			require.NoError(t, db.Where("id = ?", 1).First(&after).Error)
			require.NotNil(t, after.QueryHistoryConfig)
			require.Equal(t, types.QueryHistoryModeAnonymized, after.QueryHistoryConfig.Mode)
		})
	}
}
