import { useEffect, useRef, useState } from 'react';
import type { WeKnoraClient } from '@weknora/api-client';
import { createScopeController } from '@weknora/domain/scope';
import { Button as TButton } from 'tdesign-react';
import { WkCard as Card, WkStatus as Status } from '../shared/wk-legacy.tsx';
import { appsApi, type AuthorizationAttempt } from './api.ts';
import { nextAuthorizationPoll, shouldContinueAuthorizationPolling } from './polling.ts';

export function AuthorizationPage({ client, scopeController, attemptId, onNavigate }: { client: WeKnoraClient; scopeController: ReturnType<typeof createScopeController>; attemptId: string; onNavigate: (path: string) => void }) {
  const [attempt, setAttempt] = useState<AuthorizationAttempt | null>(null); const attemptRef = useRef<AuthorizationAttempt | null>(null); const [error, setError] = useState(''); const failures = useRef(0); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); const inFlight = useRef<AbortController | null>(null);
  useEffect(() => { const scope = scopeController.current(); let active = true; attemptRef.current = null; setAttempt(null); const poll = async () => { if (!active) return; inFlight.current?.abort(); const controller = new AbortController(); inFlight.current = controller; try { const next = await appsApi(client).getAuthorization(attemptId, controller.signal); if (!active || !scopeController.isCurrent(scope.scope)) return; attemptRef.current = next; setAttempt(next); setError(''); failures.current = 0; if (shouldContinueAuthorizationPolling(next.status, next.expires_at, Date.now())) timer.current = setTimeout(poll, nextAuthorizationPoll(0)); } catch (e) { if (!active || controller.signal.aborted || !scopeController.isCurrent(scope.scope)) return; failures.current += 1; setError(e instanceof Error ? e.message : 'Unable to read authorization status'); const previous = attemptRef.current; if (previous === null || shouldContinueAuthorizationPolling(previous.status, previous.expires_at, Date.now())) timer.current = setTimeout(poll, nextAuthorizationPoll(failures.current)); } finally { if (inFlight.current === controller) inFlight.current = null; } }; void poll(); return () => { active = false; inFlight.current?.abort(); if (timer.current) clearTimeout(timer.current); }; }, [attemptId, client, scopeController]);
  return <main className="wk-page"><header className="wk-header"><div><p className="wk-eyebrow">Apps</p><h1>授权状态</h1><p className="wk-muted">此端点只查询本地授权 attempt 状态，不生成或伪造授权 URL。</p></div><TButton type="button" onClick={() => window.location.reload()}>刷新</TButton></header><Card>{error ? <Status tone="error">{error}</Status> : null}<p>Attempt：{attemptId}</p><p>连接：{attempt?.connection_id ?? '—'}</p><p>状态：{attempt?.status ?? '加载中…'}</p><p>过期时间：{attempt?.expires_at ?? '—'}</p>{attempt && !shouldContinueAuthorizationPolling(attempt.status, attempt.expires_at, Date.now()) ? <Status tone={attempt.status === 'active' ? 'success' : 'neutral'}>{attempt.status === 'active' ? '授权完成。' : '授权流程已结束。'}</Status> : null}<TButton type="button" onClick={() => onNavigate('/platform/apps/connections')}>返回连接</TButton></Card></main>;
}
