import { useEffect, useState } from 'react';
import type { WeKnoraClient } from '@weknora/api-client';
import { createScopeController } from '@weknora/domain/scope';
import { Button as TButton } from 'tdesign-react';
import { WkCard as Card, WkStatus as Status } from '../shared/wk-legacy.tsx';
import { appsApi, type ConnectionEntry } from './api.ts';
import { connectionStateLabel, connectionStateTone, revokeFailureKind } from './connection-state.ts';

export function ConnectionsPage({ client, scopeController, role, onNavigate }: { client: WeKnoraClient; scopeController: ReturnType<typeof createScopeController>; role?: string; onNavigate: (path: string) => void }) {
  const [rows, setRows] = useState<ConnectionEntry[]>([]); const [error, setError] = useState(''); const [conflict, setConflict] = useState(''); const [busy, setBusy] = useState(''); const [reload, setReload] = useState(0); const canManage = role === 'owner' || role === 'admin';
  const load = () => { const scope = scopeController.current(); setError(''); setConflict(''); void appsApi(client).listConnections(scope.signal).then((next) => { if (scopeController.isCurrent(scope.scope)) setRows(next); }).catch((e) => { if (!scope.signal.aborted && scopeController.isCurrent(scope.scope)) setError(e instanceof Error ? e.message : 'Unable to load connections'); }); };
  useEffect(load, [client, reload, scopeController]);
  const revoke = async (row: ConnectionEntry) => { if (!canManage || busy) return; setBusy(row.id); try { await appsApi(client).revokeConnection(row.id, row.auth_version); load(); } catch (e) { if (!scopeController.isCurrent(scopeController.current().scope)) return; if (revokeFailureKind(e) === 'conflict') { // 409/VERSION_CONFLICT: the CAS refused a stale auth_version — surface a re-read prompt and reload, never a fabricated success (Vue revokeConflict contract).
 setConflict('连接授权版本已变化，请刷新后重试'); load(); } else { setError(e instanceof Error ? e.message : 'Unable to revoke connection'); } } finally { setBusy(''); } };
  const authorize = async (row: ConnectionEntry) => { if (!canManage || busy) return; setBusy(row.id); try { const attempt = await appsApi(client).beginAuthorization(row.id); onNavigate('/platform/apps/authorization/' + encodeURIComponent(attempt.attempt_id)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to start authorization'); } finally { setBusy(''); } };
  return <main className="wk-page"><header className="wk-header"><div><p className="wk-eyebrow">Apps</p><h1>连接</h1><p className="wk-muted">个人连接和空间连接；凭据永不展示。</p></div><TButton type="button" onClick={() => setReload((value) => value + 1)}>刷新</TButton></header><Card>{!canManage ? <Status>当前成员不能管理连接。</Status> : null}{error ? <Status tone="error">{error}</Status> : null}{conflict ? <Status tone="warning">{conflict}</Status> : null}{rows.length === 0 ? <Status>暂无连接。</Status> : <ul className="wk-list">{rows.map((row) => <li key={row.id}><strong>{row.kind === 'space' ? '空间连接' : '个人连接'} · {row.id}</strong><span><Status tone={connectionStateTone(row.state)}>{connectionStateLabel(row.state)}</Status> · {row.kind === 'space' ? '空间账号' : row.owner_id ?? '账号未知'}</span>{canManage && row.state === 'active' ? <span><TButton type="button" disabled={busy !== ''} onClick={() => void authorize(row)}>重新授权</TButton> <TButton type="button" disabled={busy !== ''} onClick={() => void revoke(row)}>撤销</TButton></span> : null}{row.state === 'revoked' ? <small>本地连接已撤销，远端清理异步进行。</small> : null}</li>)}</ul>}</Card></main>;
}
