import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Button, Card, Status } from '@weknora/ui';
import { createAuthApi, persistLogin, type AuthApi } from './api.ts';
import { defaultAuthTranslator, type AuthTranslator } from './messages.ts';
import { getOnboardingPresentation, validateLoginForm, validateRegisterForm } from './auth-state.ts';
import type { WeKnoraClient } from '@weknora/api-client';
import './auth.css';

export interface AuthNavigation { replace(path: string): void; }
export interface AuthPageProps { api: AuthApi; navigation?: AuthNavigation; t?: AuthTranslator; }

function navigate(navigation: AuthNavigation | undefined, path: string) { navigation?.replace(path); if (!navigation) window.history.pushState({}, '', path); }

function Field({ label, name, type = 'text', value, onChange, error, disabled, placeholder }: { label: string; name: string; type?: string; value: string; onChange(value: string): void; error?: string; disabled: boolean; placeholder: string }) {
  return <label className="auth-field"><span>{label}</span><input name={name} type={type} value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled} placeholder={placeholder} autoComplete={name === 'password' ? 'current-password' : name === 'confirmPassword' ? 'new-password' : name} aria-invalid={error ? true : undefined} />{error ? <small role="alert">{error}</small> : null}</label>;
}

export function LoginPage({ api, navigation, t = defaultAuthTranslator }: AuthPageProps) {
  const [form, setForm] = useState({ email: '', password: '' }); const [errors, setErrors] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [registrationEnabled, setRegistrationEnabled] = useState(true);
  useEffect(() => { void api.authConfig().then((config) => setRegistrationEnabled(config.registration_mode !== 'invite_only')).catch(() => setRegistrationEnabled(true)); }, [api]);
  const submit = async () => { const next = validateLoginForm(form); setErrors(next); if (Object.keys(next).length) return; setLoading(true); setMessage(''); try { const session = await api.login(form.email, form.password); persistLogin(session); navigate(navigation, session.tenantId ? '/platform/knowledge-bases' : '/onboarding/workspace'); } catch (error) { setMessage(error instanceof Error ? error.message : t('auth.loginError')); } finally { setLoading(false); } };
  return <AuthShell><Card className="auth-card"><div className="auth-header"><p className="auth-eyebrow">WeKnora</p><h1>{t('auth.login')}</h1><p>{t('auth.subtitle')}</p><p className="auth-hint">{registrationEnabled ? t('auth.loginHint') : t('auth.inviteOnlyDescription')}</p></div>{message ? <Status tone="error">{message}</Status> : null}<form onSubmit={(event) => { event.preventDefault(); void submit(); }}><Field label={t('auth.email')} name="email" value={form.email} onChange={(email) => setForm({ ...form, email })} error={errors.email ? t(errors.email) : undefined} disabled={loading} placeholder={t('auth.emailPlaceholder')} /><Field label={t('auth.password')} name="password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} error={errors.password ? t(errors.password) : undefined} disabled={loading} placeholder={t('auth.passwordPlaceholder')} /><Button type="submit" disabled={loading}>{loading ? t('auth.loggingIn') : t('auth.login')}</Button></form>{registrationEnabled ? <div className="auth-links"><Button type="button" onClick={() => navigate(navigation, '/register')} disabled={loading}>{t('auth.createAccount')}</Button></div> : null}</Card></AuthShell>;
}

export function RegisterPage({ api, navigation, t = defaultAuthTranslator }: AuthPageProps) {
  const [form, setForm] = useState({ username: '', email: '', password: '', confirmPassword: '' }); const [errors, setErrors] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [complex, setComplex] = useState(false);
  useEffect(() => { void api.authConfig().then((config) => setComplex(config.complex_password_enabled)).catch(() => undefined); }, [api]);
  const submit = async () => { const next = validateRegisterForm(form, complex); setErrors(next); if (Object.keys(next).length) return; setLoading(true); setMessage(''); try { const result = await api.register({ username: form.username, email: form.email, password: form.password }); if (!result.success) throw new Error(result.message || t('auth.registerFailed')); setMessage(t('auth.registerSuccess')); navigate(navigation, '/login'); } catch (error) { setMessage(error instanceof Error ? error.message : t('auth.registerFailed')); } finally { setLoading(false); } };
  return <AuthShell><Card className="auth-card"><div className="auth-header"><p className="auth-eyebrow">WeKnora</p><h1>{t('auth.createAccount')}</h1><p>{t('auth.subtitle')}</p></div>{message ? <Status tone={message === t('auth.registerSuccess') ? 'success' : 'error'}>{message}</Status> : null}<form onSubmit={(event) => { event.preventDefault(); void submit(); }}><Field label={t('auth.username')} name="username" value={form.username} onChange={(username) => setForm({ ...form, username })} error={errors.username ? t(errors.username) : undefined} disabled={loading} placeholder={t('auth.usernamePlaceholder')} /><Field label={t('auth.email')} name="email" value={form.email} onChange={(email) => setForm({ ...form, email })} error={errors.email ? t(errors.email) : undefined} disabled={loading} placeholder={t('auth.emailPlaceholder')} /><Field label={t('auth.password')} name="password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} error={errors.password ? t(errors.password) : undefined} disabled={loading} placeholder={t('auth.passwordPlaceholder')} /><Field label={t('auth.confirmPassword')} name="confirmPassword" type="password" value={form.confirmPassword} onChange={(confirmPassword) => setForm({ ...form, confirmPassword })} error={errors.confirmPassword ? t(errors.confirmPassword) : undefined} disabled={loading} placeholder={t('auth.confirmPasswordPlaceholder')} /><Button type="submit" disabled={loading}>{loading ? t('auth.registering') : t('auth.register')}</Button></form><div className="auth-links"><Button type="button" onClick={() => navigate(navigation, '/login')} disabled={loading}>{t('auth.backToLogin')}</Button></div></Card></AuthShell>;
}

export function WorkspaceOnboardingPage({ api, navigation, t = defaultAuthTranslator }: AuthPageProps) {
  const [status, setStatus] = useState<'loading' | 'error' | 'ready'>('loading'); const [canCreate, setCanCreate] = useState(false); const [pending, setPending] = useState(0);
  const load = async () => { setStatus('loading'); try { const current = await api.currentUser(); if (!current.success) throw new Error(current.message || 'policy'); setCanCreate(current.capabilities?.can_create_tenant === true); setPending(await api.pendingInvitations()); setStatus('ready'); } catch { setStatus('error'); } };
  useEffect(() => { void load(); }, []);
  const view = useMemo(() => getOnboardingPresentation({ status, canCreateTenant: canCreate, pendingInvitationCount: pending }), [status, canCreate, pending]);
  return <main className="onboarding-page"><Card className="workspace-card"><div className="workspace-mark" aria-hidden="true">∑</div><h1>{view.kind === 'invite-only' ? t('auth.workspaceInviteOnlyTitle') : t('auth.workspaceTitle')}</h1><p className="auth-description">{view.kind === 'invite-only' ? t('auth.workspaceInviteOnlyDescription') : t('auth.workspaceDescription')}</p>{view.kind === 'loading' ? <Status>{t('auth.loadingPolicy')}</Status> : null}{view.kind === 'error' ? <div className="auth-error"><Status tone="error">{t('auth.policyLoadFailed')}</Status><Button type="button" onClick={() => void load()}>{t('auth.retry')}</Button></div> : null}{view.kind === 'invite-only' ? <Status>{t('auth.inviteOnlyNotice')}</Status> : null}{view.kind === 'create-and-invite' ? <div className="workspace-actions"><Button type="button" onClick={() => navigate(navigation, '/platform/tenants/new')}>{t('auth.createWorkspace')}</Button><Button type="button" onClick={() => navigate(navigation, '/platform/invitations')}>{t('auth.viewInvitations')}{view.pendingInvitationCount ? ` (${view.pendingInvitationCount})` : ''}</Button></div> : null}{view.kind === 'invite-only' ? <Button type="button" onClick={() => navigate(navigation, '/platform/invitations')}>{t('auth.viewInvitations')}{view.pendingInvitationCount ? ` (${view.pendingInvitationCount})` : ''}</Button> : null}<p className="auth-description">{view.kind === 'invite-only' ? t('auth.inviteOnlyHelp') : t('auth.workspaceHelp')}</p><Button type="button" onClick={async () => { await api.logout(); localStorage.removeItem('weknora_token'); localStorage.removeItem('weknora_refresh_token'); navigate(navigation, '/login'); }}>{t('auth.logout')}</Button></Card></main>;
}

function AuthShell({ children }: { children: ReactNode }) { return <main className="auth-page"><div className="auth-glow" aria-hidden="true" /><div className="auth-showcase"><p>WeKnora</p><h2>Knowledge, connected.</h2><p>RAG · Agent · Wiki · Hybrid Search</p></div>{children}</main>; }

export function AuthRoutes({ client, navigation }: { client: WeKnoraClient; navigation?: AuthNavigation }) { const api = useMemo(() => createAuthApi(client), [client]); const path = window.location.pathname; if (path === '/register') return <RegisterPage api={api} navigation={navigation} />; if (path === '/onboarding/workspace') return <WorkspaceOnboardingPage api={api} navigation={navigation} />; return <LoginPage api={api} navigation={navigation} />; }
