import { useState } from 'react';
import { View, Text } from '@tarojs/components';
import type { NativeFileSource } from '@weknora/api-client';
import { Screen, Card, Action, Field, Notice, Section, ListRow, Badge, Empty, useData, DataBoundary, useAction } from '../../components/ui.tsx';
import { client, auth } from '../../services/runtime.ts';
import { navigate, routeParam } from '../../platform/navigation.ts';
import { rows, identifier, text, record } from '../../services/views.ts';
import { chooseDocument, openProtectedDocument } from '../../platform/files.ts';
import { formatBytes } from '../../core/format.ts';
const name=(r:Record<string,unknown>)=>text(r.title,text(r.file_name,text(r.name,'未命名文档')));
const status=(r:Record<string,unknown>)=>text(r.parse_status,'状态待确认');
export function KnowledgePage(){
 const [search,setSearch]=useState('');const query=useData('knowledge-bases',()=>client.knowledgeBases.list());
 return <Screen title='知识' tab><Text className='wk-display'>让每一次提问，{ '\n' }都有来源可循。</Text><Field label='搜索知识库' value={search} onChange={setSearch} placeholder='名称或说明'/><DataBoundary state={query}>{data=>{const items=rows(data).filter(r=>`${text(r.name)} ${text(r.description)}`.includes(search));return <>{items.map(kb=><Card key={identifier(kb.id)} tone='mint'><ListRow title={text(kb.name,'知识库')} subtitle={text(kb.description,'查看资料与来源')} onClick={()=>void navigate('kb',{id:identifier(kb.id)})}/></Card>)}{!items.length&&<Empty title='暂无可见知识库' body='没有可见资料不代表服务未开通；权限仍由服务端决定。'/>}</>}}</DataBoundary></Screen>;
}
export function KnowledgeDetailPage(){
 const id=routeParam('id');const [page,setPage]=useState(1);const query=useData(`kb:${id}:${page}`,()=>client.knowledge.documents.list(id,{page,page_size:20}));
 return <Screen title='知识库详情'><Card tone='mint'><Text className='wk-eyebrow'>KNOWLEDGE COLLECTION</Text><Text className='wk-display'>团队知识，随时可用。</Text><Text className='wk-muted'>当前知识库 ID：{id}</Text></Card><View className='wk-grid'><Action onClick={()=>void navigate('chat',{kb:id})}>基于此库提问</Action><Action secondary onClick={()=>void navigate('upload',{kb:id})}>添加知识</Action></View><Section title='库内文档'/><DataBoundary state={query}>{data=><Card>{rows(data).map(doc=><ListRow key={identifier(doc.id)} title={name(doc)} subtitle={status(doc)} onClick={()=>void navigate('document',{id:identifier(doc.id),kb:id})} suffix={<Badge tone={status(doc)==='completed'?'success':'neutral'}>{status(doc)}</Badge>}/>)}{!rows(data).length&&<Empty title='此页没有文档'/>}<View className='wk-grid'><Action secondary disabled={page<=1} onClick={()=>setPage(p=>p-1)}>上一页</Action><Action secondary disabled={rows(data).length<20} onClick={()=>setPage(p=>p+1)}>下一页</Action></View></Card>}</DataBoundary><Notice>上传完成不等于解析完成。只有服务端确认就绪的资料才可参与检索。</Notice></Screen>;
}
export function UploadPage(){
 const kb=routeParam('kb');const [mode,setMode]=useState<'file'|'url'>('file'),[file,setFile]=useState<NativeFileSource>(),[url,setUrl]=useState(''),[progress,setProgress]=useState(0),[created,setCreated]=useState('');const action=useAction();
 return <Screen title='添加知识'><Text className='wk-display'>把资料，放进知识库。</Text><View className='wk-grid'><Action secondary={mode!=='file'} onClick={()=>setMode('file')}>上传文件</Action><Action secondary={mode!=='url'} onClick={()=>setMode('url')}>导入链接</Action></View><View className='wk-spacer'/><Card>{mode==='file'?<><Action secondary onClick={()=>void action.run(async()=>{setFile(await chooseDocument())})}>{file?'重新选择文件':'选择一份资料'}</Action>{file&&<ListRow title={file.name} subtitle={`${formatBytes(file.size??0)} · 尚未上传`} suffix={<Badge>已选择</Badge>}/>}<Text className='wk-muted wk-small'>本端单文件最多 20 MiB；服务端还会检查格式、权限与大小。</Text></>:<Field label='网页链接' value={url} onChange={setUrl} placeholder='https://…'/>}</Card><Notice>这是持久知识入库，不是聊天临时附件。请确认你有权将该内容存入当前空间。</Notice>{created?<><Card tone='mint'><Text className='wk-h2'>已提交到后台</Text><Text className='wk-muted'>上传完成，解析状态尚待服务端确认。</Text></Card><Action onClick={()=>void navigate('document',{id:created,kb})}>查看处理状态</Action></>:<Action loading={action.busy} disabled={mode==='file'?!file:!/^https?:\/\//i.test(url)} onClick={()=>void action.run(async()=>{const stamp=auth.scope.capture();const result=mode==='file'?await client.knowledge.documents.upload(kb,{file:file!,onProgress:e=>{if(auth.scope.isCurrent(stamp)&&e.total)setProgress(Math.round(e.loaded/e.total*100))}}):await client.knowledge.documents.createFromUrl(kb,{url});if(auth.scope.isCurrent(stamp))setCreated(identifier(record(result).id))})}>确认添加{action.busy&&mode==='file'?` ${progress}%`:''}</Action>}{action.error&&<Notice tone='danger'>{action.error}</Notice>}</Screen>;
}
export function DocumentPage(){
 const id=routeParam('id'),kb=routeParam('kb');const action=useAction();const query=useData(`document:${id}`,()=>client.knowledge.documents.get(id));const chunks=useData(`document-chunks:${id}`,()=>client.knowledge.documents.chunks(id,1,20));
 return <Screen title='文档与引用'><DataBoundary state={query}>{data=>{const doc=record(data);return <Card tone='mint'><Text className='wk-eyebrow'>KNOWLEDGE / SOURCE</Text><Text className='wk-display'>{name(doc)}</Text><Badge>{status(doc)}</Badge><Text className='wk-muted'>文档 ID：{id}</Text><Action secondary loading={action.busy} onClick={()=>void action.run(()=>openProtectedDocument(client.knowledge.documents.downloadPath(id),name(doc)))}>查看受保护原文</Action></Card>}}</DataBoundary><Section title='已授权的内容片段'/><DataBoundary state={chunks}>{page=><>{page.data.map(chunk=><Card key={chunk.id}><Text className='wk-prose' selectable>{chunk.content??'暂无文本内容'}</Text></Card>)}{!page.data.length&&<Empty title='内容尚未就绪' body='解析未完成、无文本内容或权限变化时，请刷新文档状态。'/>}</>}</DataBoundary><Notice>这里只显示服务端返回的真实片段，不补造页码，不执行文档中的 HTML 或脚本。</Notice><Action onClick={()=>void navigate('chat',{kb,document:id})}>基于当前资料继续提问</Action>{action.error&&<Notice tone='danger'>{action.error}</Notice>}</Screen>;
}
