from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];d=json.loads((R/'design/resolved-tokens.json').read_text())
css=(R/'design/tokens.css').read_text()+'''*{box-sizing:border-box}body{margin:0;padding:0;background:var(--color-bg-page);color:var(--color-text-primary);font-family:var(--font-family);font-size:14px;line-height:1.65}header{background:#103D32;color:white;padding:52px max(24px,calc((100vw - 1100px)/2));}header h1{font-size:38px;letter-spacing:-1px;margin:12px 0}header p{color:#DCEEE3;margin:0}main{max-width:1160px;margin:0 auto;padding:28px}section{margin:28px 0 48px}h2{font-size:24px;margin-bottom:18px}.meta{font-size:12px;letter-spacing:2px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px}.swatch{background:white;border:1px solid #DBE4DD;border-radius:20px;overflow:hidden}.swatch .chip{height:90px}.swatch .desc{padding:14px}.swatch code{font-size:11px;word-break:break-all}.muted{color:#566B63}.card{padding:24px;background:white;border:1px solid #DBE4DD;border-radius:20px}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.button{font:600 14px var(--font-family);padding:12px 18px;min-height:48px;border:1px solid #DBE4DD;border-radius:14px;background:white;color:#172B27;cursor:pointer}.button.primary{background:#176B52;color:white;border-color:#176B52}.button.danger{background:#FFF0EE;color:#AF4039;border-color:#E5C9C2}.button:disabled{opacity:.48;cursor:not-allowed}.button:focus-visible{outline:3px solid #176B52;outline-offset:3px}.badge{font-size:12px;padding:5px 10px;border-radius:999px}.space-row{display:flex;align-items:center;gap:14px;margin:9px 0}.space-row i{background:#176B52;display:block;height:12px;border-radius:3px}.radius{width:90px;height:66px;background:#DCEEE3;border:1px solid #ABC6B1;display:flex;align-items:center;justify-content:center;color:#176B52;font-size:12px}.label{display:block;font-size:13px;margin:14px 0 7px}.input{width:100%;font:15px var(--font-family);padding:14px;border:1px solid #8EABA0;border-radius:14px;min-height:48px}.hint{font-size:12px;color:#566B63}.error{color:#AF4039}.dark{background:#103D32;color:white;border:none}.dark .muted{color:#DCEEE3}.mini{max-width:350px}.num{font-size:42px;font-weight:600;line-height:1.2;margin:20px 0}.notice{background:#FBF0DC;color:#84520C;padding:14px;border-radius:14px;font-size:13px;margin-top:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #DBE4DD}code{font-family:var(--font-mono);font-size:12px}.footer{padding:25px 0;border-top:1px solid #DBE4DD;color:#566B63;font-size:12px}@media(max-width:600px){header{padding:30px 24px}header h1{font-size:30px}main{padding:20px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.component-grid{grid-template-columns:1fr}}'''
colors=['color.bg.page','color.bg.surface','color.text.primary','color.text.secondary','color.action.primary','color.bg.brand','color.primitive.mint100','color.primitive.lime','color.status.warningBg','color.status.warningFg','color.status.dangerBg','color.status.dangerFg']
sw=''.join(f'<div class="swatch"><div class="chip" style="background:{d[k]}"></div><div class="desc"><b>{d[k]}</b><br><code>{k}</code></div></div>' for k in colors)
font=''.join(f'<div style="font-size:{d["font.size."+k]}px;line-height:1.5;margin:15px 0"><span class="muted" style="font-size:12px;display:inline-block;width:105px">{k} · {d["font.size."+k]}px</span>把知识，变成下一步</div>' for k in ['display','hero','title','section','lead','body','small','label'])
spaces=''.join(f'<div class="space-row"><code style="width:65px">space.{i}</code><i style="width:{i*4}px"></i><span class="hint">{i}px</span></div>' for i in [4,8,12,16,20,24,32])
radii=''.join(f'<div class="radius" style="border-radius:{d["radius."+k]}px">{k} / {d["radius."+k]}</div>' for k in ['sm','md','lg','xl','hero'])
badges=''.join(f'<span class="badge" style="color:{d["color.status."+k+"Fg"]};background:{d["color.status."+k+"Bg"]}">{t}</span>' for k,t in [('success','✓ 已完成'),('warning','! 待确认'),('info','◷ 解析中'),('danger','× 失败')])
html=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WeKnora · Quiet Work 设计系统</title><style>{css}</style><body><header><div class="meta">WEKNORA / MINIAPP DESIGN SYSTEM</div><h1>安静有序，行动清晰。</h1><p>Quiet Work · 浅色主题 v1.0.0 · 106 个源令牌 · 375 逻辑像素基准</p></header><main><section><div class="meta muted">01 / COLOR</div><h2>色彩是一种秩序，不是装饰。</h2><div class="grid">{sw}</div></section><section><div class="meta muted">02 / TYPOGRAPHY</div><h2>让信息有轻重，让阅读有呼吸。</h2><div class="card">{font}</div><p class="hint">系统中文无衬线；主要正文14px/1.65；标题32px/1.24。未分发字体文件。</p></section><section><div class="meta muted">03 / GEOMETRY</div><h2>一致的间距与圆角</h2><div class="grid"><div class="card">{spaces}</div><div class="card"><div class="row">{radii}</div><p class="hint">按钮14；普通卡20；重点卡24/28；标签pill。不是所有组件都用同一个大圆角。</p><div class="notice">逻辑16px → Taro750设计输入32px → 编译32rpx。真实胶囊、安全区和窗口坐标不乘2。</div></div></div></section><section><div class="meta muted">04 / COMPONENTS</div><h2>组件的状态也是设计的一部分。</h2><div class="card"><div class="row"><button class="button primary">发起任务</button><button class="button">返回任务</button><button class="button danger">取消任务</button><button class="button primary" disabled>暂不可购买</button></div><p class="hint">此页按钮仅展示样式，不触发业务；交互请使用20页高保真原型。</p><div class="row" style="margin-top:20px">{badges}</div></div><div class="grid component-grid" style="margin-top:16px"><div class="card"><b>任务描述</b><label class="label" for="sample">你希望助手完成什么？</label><input class="input" id="sample" placeholder="整理本周项目进展…"><p class="hint">填写目标、范围与希望的输出格式。</p><label class="label" for="sample-error">预算上限（错误状态示例）</label><input id="sample-error" class="input" style="border-color:#AF4039" aria-describedby="sample-message" aria-invalid="true" value="-10"><p id="sample-message" class="hint error">请填写服务端允许范围内的预算。</p></div><div class="card dark"><div class="row" style="justify-content:space-between"><span class="muted">当前可用额度</span><span class="badge" style="background:#FFFFFF20">团队协作版</span></div><div class="num">8,640 <small style="font-size:13px;font-weight:400">积分 · 示例</small></div><p class="muted">已预占 160 / 退款冻结 0</p><hr style="border:0;border-top:1px solid #FFFFFF30"><p class="muted">统计时点 09:41 · 付款和权益状态以服务端为准。</p></div></div></section><section><div class="meta muted">05 / IMPLEMENTATION</div><h2>从令牌到真实小程序</h2><table><tr><th>输出</th><th>用途</th></tr><tr><td><code>tokens.json</code></td><td>项目自有源格式，106个token与别名</td></tr><tr><td><code>tokens.css</code></td><td>HTML逻辑px变量</td></tr><tr><td><code>_tokens.taro.scss</code></td><td>750设计输入，尺寸仅乘2一次</td></tr><tr><td><code>tokens.ts</code></td><td>类型化原始逻辑值</td></tr></table></section><div class="footer">所有账号、余额、订单、时间与价格均为虚构演示。组件展示页和HTML原型不代表Taro编译、微信实机或后端验收通过。</div></main></body></html>'''
(R/'design/components.html').write_text(html)
print('Standalone component/token gallery generated')
