import { useState } from 'react';
import { View, Text } from '@tarojs/components';
import { Screen, Card, Action, Field, Notice, Section, ListRow, Badge, Empty, useData, DataBoundary, useAction, useSession, confirmAction } from '../../components/ui.tsx';
import { auth, client, logout } from '../../services/runtime.ts';
import { navigate, routeParam } from '../../platform/navigation.ts';
import { formatCredits, formatMoney, formatTime } from '../../core/format.ts';
const paymentLabels:Record<string,string>={pending:'待确认',paid:'已付款',closed:'已关闭'};
const fulfillmentLabels:Record<string,string>={pending:'等待履约',processing:'处理中',fulfilled:'已开通',attention:'需要处理'};
export function MePage(){
 const session=useSession(),action=useAction();const usage=useData('me-summary',signal=>client.commercial.summary(signal));
 return <Screen title='我的' tab><View className='wk-profile'><View className='wk-profile-avatar'>{session.userName.slice(0,1)||'我'}</View><View><Text className='wk-display'>{session.userName||'我的账号'}</Text><Text className='wk-muted'>平台账号 · {session.tenantName}</Text></View></View><Card><ListRow title={session.tenantName||'选择工作空间'} subtitle='知识、任务与计费相互隔离' icon='user' onClick={()=>void navigate('workspace')}/></Card><DataBoundary state={usage}>{s=><Card tone='dark'><Text className='wk-h2'>用量与权益</Text><Text className='wk-muted'>当前可用 · Credits</Text><Text className='wk-number'>{formatCredits(s.available)}</Text><View className='wk-between'><Text>预占 {formatCredits(s.held)}</Text><Text>退款冻结 {formatCredits(s.refund_locked)}</Text></View><Text className='wk-footnote'>{s.stale?'数据待更新 · ':''}{formatTime(s.as_of)}</Text></Card>}</DataBoundary><Card><ListRow title='套餐与用量' subtitle='查看当前空间的额度和统计时点' onClick={()=>void navigate('usage')}/><ListRow title='订单与履约' subtitle='分别追踪付款与权益发放' icon='tasks' onClick={()=>void navigate('order')}/><ListRow title='空间邀请' subtitle='验证邀请后再加入空间' icon='user' onClick={()=>void navigate('invitations')}/><ListRow title='隐私与数据' subtitle='了解上传、模型与数据处理' icon='shield' onClick={()=>void navigate('states',{kind:'privacy'})}/></Card><Action secondary loading={action.busy} onClick={()=>void action.run(async()=>{if(!await confirmAction('退出登录？','将清理本机登录态与私有缓存。已启动的后台任务不会被取消。'))return;await logout();await navigate('login')})}>退出登录</Action>{action.error&&<Notice tone='danger'>{action.error}</Notice>}</Screen>;
}
export function UsagePage(){
 const query=useData('summary',signal=>client.commercial.summary(signal));
 return <Screen title='用量与套餐'><DataBoundary state={query}>{s=><><Card tone='dark'><Text className='wk-h2'>{s.plan_name}</Text><Text className='wk-muted'>当前可用 · Credits</Text><Text className='wk-number'>{formatCredits(s.available)}</Text><View className='wk-grid'><View><Text className='wk-small'>预占</Text><Text className='wk-h2'>{formatCredits(s.held)}</Text></View><View><Text className='wk-small'>退款冻结</Text><Text className='wk-h2'>{formatCredits(s.refund_locked)}</Text></View></View><Text className='wk-footnote'>统计时点 {formatTime(s.as_of)}</Text></Card>{s.stale&&<Notice tone='warning'>统计结果已过期，不能将此显示值作为新任务的准入依据。</Notice>}<Card><Text className='wk-h3'>额度怎么看？</Text><Text className='wk-prose'>可用额度与预占额度由后端分别返回，不在前端再次相减。Credits 不是人民币，也不直接等于模型 token 数量。</Text><Text className='wk-muted'>权益到期：{s.paid_until?formatTime(s.paid_until):'服务端未设置'}</Text></Card></>}</DataBoundary><Action secondary onClick={()=>void navigate('checkout')}>查看购买能力</Action><Action secondary onClick={()=>void navigate('order')}>查询已有订单</Action></Screen>;
}
export function CheckoutPage(){return <Screen title='确认订单'><Card tone='mint'><Text className='wk-eyebrow'>BILLING / CURRENT WORKSPACE</Text><Text className='wk-display'>让权益，清楚透明。</Text><Badge tone='warning'>小程序支付通道未接入</Badge></Card><Notice tone='warning'>当前 WeChat Provider 是 Native 二维码支付，不能直接作为小程序支付参数。本版本不生成虚构报价，不尝试跳转外部绕过渠道。</Notice><Card><Text className='wk-h2'>开放购买之前</Text><Text className='wk-prose'>需完成商品分类与渠道核验、服务端报价、类型化 checkout、回调验签和幂等履约。购买权限由账单管理员授权决定，而不是按“空间管理员”称谓推断。</Text></Card><Action disabled>暂不可购买</Action><Action secondary onClick={()=>void navigate('order')}>已有订单，查看状态</Action></Screen>}
export function OrderPage(){
 const [draft,setDraft]=useState(routeParam('id')),[id,setId]=useState(routeParam('id'));const query=useData(`order:${id}`,signal=>client.commercial.getOrder(id,signal),!!id);
 return <Screen title='订单与履约'><Text className='wk-display'>付款与权益，{ '\n' }分开核对。</Text><Card><Field label='已有订单号' value={draft} onChange={setDraft}/><Action disabled={!draft.trim()} onClick={()=>setId(draft.trim())}>查询原订单</Action></Card><DataBoundary state={query}>{order=><><Card tone={order.fulfillment==='fulfilled'?'mint':'white'}><Text className='wk-h2'>¥{formatMoney(order.amount_fen)}</Text><Text className='wk-mono'>{order.id}</Text><View className='wk-step'><Text className='wk-h3'>1 · 付款状态</Text><Badge tone={order.payment==='paid'?'success':'warning'}>{paymentLabels[order.payment]??order.payment}</Badge></View><View className='wk-step'><Text className='wk-h3'>2 · 权益发放</Text><Badge tone={order.fulfillment==='fulfilled'?'success':'warning'}>{fulfillmentLabels[order.fulfillment]??order.fulfillment}</Badge></View></Card><Notice>{order.payment==='paid'&&order.fulfillment!=='fulfilled'?'付款已确认，权益尚在处理。请查询原订单，不要重复购买。':'状态由后端订单服务确认，客户端不能自行发放权益。'}</Notice><Action secondary onClick={query.reload}>刷新原订单状态</Action></>}</DataBoundary></Screen>;
}
export function InvitationsPage(){
 const [token,setToken]=useState(''),[done,setDone]=useState('');const action=useAction();
 return <Screen title='空间邀请'><Text className='wk-display'>加入协作，{ '\n' }也保留清晰边界。</Text><Card><Field label='邀请凭证' value={token} onChange={setToken} password placeholder='粘贴受邀获得的凭证'/><Notice>凭证只发送到平台后端验证，不保存在本机。加入邀请不等于立即切换当前空间。</Notice><Action disabled={!token.trim()} loading={action.busy} onClick={()=>void action.run(async()=>{if(!await confirmAction('接受此邀请？','后端将核验受邀账号、邀请有效期与成员关系。'))return;const result=await client.auth.acceptInvitationByToken(token.trim());setToken('');setDone(result.tenantName||'已接受邀请');await auth.bootstrap()})}>验证并接受邀请</Action>{done&&<Notice>{done}</Notice>}{action.error&&<Notice tone='danger'>{action.error}</Notice>}</Card><Action secondary onClick={()=>void navigate('workspace')}>选择工作空间</Action></Screen>;
}
export function StatesPage(){const kind=routeParam('kind');return <Screen title={kind==='privacy'?'隐私与数据':'状态说明'} publicPage><Text className='wk-display'>{kind==='privacy'?'知道数据，去了哪里。':'每一种状态，都有下一步。'}</Text>{kind==='privacy'?<><Card><Text className='wk-h2'>本版本的数据处理说明</Text><Text className='wk-prose'>账号由现有平台验证；问题和用户主动上传的资料会发送到平台后端，并按空间配置由模型及工具处理。小程序不保存模型密钥，不默认读取通讯录或申请手机号。退出登录会清理本机登录态与应用缓存。</Text></Card><Notice tone='warning'>这是开发版本的功能说明，不是可直接用于公开运营的法律文件。发布前须接入实际运营主体的隐私政策、服务协议、数据删除与反馈入口。</Notice></>:<><Card><Text className='wk-h2'>网络断开</Text><Text className='wk-prose'>暂停订阅，恢复后先读取服务端快照；不要重新启动同一任务。</Text></Card><Card><Text className='wk-h2'>没有访问权限</Text><Text className='wk-prose'>检查当前账号和空间。知道资源 ID 并不构成授权。</Text></Card><Card><Text className='wk-h2'>能力尚未开放</Text><Text className='wk-prose'>明确展示部署缺口，不用“暂无任务”掩盖 404、501 或 503。</Text></Card><Card><Text className='wk-h2'>支付与审批冲突</Text><Text className='wk-prose'>读取原订单或原审批状态，保留原幂等 ID，不自动重复提交。</Text></Card></>}</Screen>}
