"""Docker-free behavioral tests for the measurement helpers and the pure
parts of the phase runner.

Latency and throughput numbers are derived from recorded timestamps only;
these tests pin the derivations: nearest-rank percentiles, window and
per-second throughput, unresolved-task exclusion from latency statistics,
the p95-vs-60 s verdict, ISO timestamp deltas, and the idempotent .env
rewriting used by the setup phase.
"""

import unittest

import measure
from run_phase import patch_env_text


class PercentileTests(unittest.TestCase):
    def test_odd_sample_count(self):
        stats = measure.percentiles([1.0, 2.0, 3.0, 4.0, 5.0])
        self.assertEqual(stats["p50"], 3.0)
        self.assertEqual(stats["p95"], 5.0)
        self.assertEqual(stats["max"], 5.0)
        self.assertEqual(stats["count"], 5)

    def test_even_sample_count(self):
        stats = measure.percentiles([10.0, 20.0, 30.0, 40.0])
        self.assertEqual(stats["p50"], 20.0)
        self.assertEqual(stats["p95"], 40.0)
        self.assertEqual(stats["max"], 40.0)

    def test_single_sample(self):
        stats = measure.percentiles([7.5])
        self.assertEqual(stats["p50"], 7.5)
        self.assertEqual(stats["p95"], 7.5)
        self.assertEqual(stats["max"], 7.5)

    def test_input_order_does_not_matter(self):
        self.assertEqual(measure.percentiles([5, 1, 4, 2, 3]), measure.percentiles([1, 2, 3, 4, 5]))

    def test_empty_samples_are_rejected(self):
        with self.assertRaises(ValueError):
            measure.percentiles([])


class ThroughputTests(unittest.TestCase):
    def test_window_throughput_is_accepted_events_over_window(self):
        self.assertEqual(measure.throughput(1280, 16.0), 80.0)

    def test_zero_or_negative_window_is_rejected(self):
        with self.assertRaises(ValueError):
            measure.throughput(10, 0.0)
        with self.assertRaises(ValueError):
            measure.throughput(10, -1.0)

    def test_peak_events_per_second_buckets_by_wall_second(self):
        stamps = [0.0, 0.5, 0.9, 1.0, 1.2, 1.4, 2.5]
        self.assertEqual(measure.peak_events_per_second(stamps), 3)
        self.assertEqual(measure.peak_events_per_second([]), 0)


class LatencySummaryTests(unittest.TestCase):
    def _tasks(self):
        return [
            {"key": "task-1", "latency_seconds": 6.0},
            {"key": "task-2", "latency_seconds": 2.0},
            {"key": "task-3", "latency_seconds": None},   # unresolved
            {"key": "task-4", "latency_seconds": 4.0},
            {"key": "task-5", "latency_seconds": None},   # unresolved
        ]

    def test_unresolved_tasks_are_excluded_from_percentiles_but_counted(self):
        summary = measure.latency_summary(self._tasks())
        self.assertEqual(summary["resolved"]["p50"], 4.0)
        self.assertEqual(summary["resolved"]["p95"], 6.0)
        self.assertEqual(summary["resolved"]["max"], 6.0)
        self.assertEqual(summary["resolved_count"], 3)
        self.assertEqual(summary["unresolved_count"], 2)
        self.assertEqual(summary["unresolved_keys"], ["task-3", "task-5"])

    def test_all_unresolved_yields_none_percentiles(self):
        summary = measure.latency_summary(
            [{"key": "task-1", "latency_seconds": None}]
        )
        self.assertIsNone(summary["resolved"]["p50"])
        self.assertEqual(summary["resolved_count"], 0)
        self.assertEqual(summary["unresolved_count"], 1)

    def test_empty_input_is_rejected(self):
        with self.assertRaises(ValueError):
            measure.latency_summary([])


class VerdictTests(unittest.TestCase):
    def test_p95_at_or_below_sixty_seconds_passes(self):
        self.assertEqual(measure.p95_verdict(59.9)["verdict"], "pass")
        self.assertEqual(measure.p95_verdict(60.0)["verdict"], "pass")

    def test_p95_above_sixty_seconds_fails(self):
        verdict = measure.p95_verdict(60.1)
        self.assertEqual(verdict["verdict"], "fail")
        self.assertEqual(verdict["target_seconds"], 60.0)

    def test_missing_p95_is_a_failure_not_a_pass(self):
        self.assertEqual(measure.p95_verdict(None)["verdict"], "fail")


class IsoDeltaTests(unittest.TestCase):
    def test_delta_between_iso_timestamps(self):
        delta = measure.iso_delta_seconds(
            "2026-09-21T12:00:05.500000+00:00", "2026-09-21T12:00:02.000000+00:00"
        )
        self.assertEqual(delta, 3.5)


class EnvPatchTests(unittest.TestCase):
    ORIGINAL = (
        "# Generated by lago.sh init -- local secrets, never commit.\n"
        "COMPOSE_PROJECT_NAME=weknora-lago\n"
        "LAGO_API_PORT=48889\n"
        "LAGO_FRONT_PORT=48890\n"
        "LAGO_API_URL=http://127.0.0.1:48889\n"
        "LAGO_FRONT_URL=http://127.0.0.1:48890\n"
        "POSTGRES_PASSWORD=generated-secret\n"
        'LAGO_RSA_PRIVATE_KEY="abc123"\n'
    )

    OVERRIDES = {
        "COMPOSE_PROJECT_NAME": "weknora-lago-76",
        "LAGO_API_PORT": "48895",
        "LAGO_FRONT_PORT": "48896",
        "LAGO_API_URL": "http://127.0.0.1:48895",
        "LAGO_FRONT_URL": "http://127.0.0.1:48896",
        "LAGO_CREATE_ORG": "true",
    }

    def test_patch_rewrites_isolation_values_and_appends_new_ones(self):
        patched = patch_env_text(self.ORIGINAL, self.OVERRIDES)
        self.assertIn("COMPOSE_PROJECT_NAME=weknora-lago-76", patched)
        self.assertIn("LAGO_API_PORT=48895", patched)
        self.assertIn("LAGO_FRONT_PORT=48896", patched)
        self.assertIn("LAGO_API_URL=http://127.0.0.1:48895", patched)
        self.assertIn("LAGO_FRONT_URL=http://127.0.0.1:48896", patched)
        self.assertIn("LAGO_CREATE_ORG=true", patched)
        self.assertNotIn("COMPOSE_PROJECT_NAME=weknora-lago\n", patched)
        # secrets survive untouched
        self.assertIn("POSTGRES_PASSWORD=generated-secret", patched)
        self.assertIn('LAGO_RSA_PRIVATE_KEY="abc123"', patched)

    def test_patch_is_idempotent(self):
        once = patch_env_text(self.ORIGINAL, self.OVERRIDES)
        twice = patch_env_text(once, self.OVERRIDES)
        self.assertEqual(once, twice)


if __name__ == "__main__":
    unittest.main()


class PlanPayloadTests(unittest.TestCase):
    def test_plan_charges_reference_metrics_by_lago_id_with_decimal_string_amounts(self):
        import fixture
        from run_phase import _plan_payload

        run = fixture.build_run("weknora-t04-planpayload", task_count=1)
        lago_ids = {
            run.metrics[0].code: "11111111-1111-1111-1111-111111111111",
            run.metrics[1].code: "22222222-2222-2222-2222-222222222222",
        }
        payload = _plan_payload(run, lago_ids)
        plan = payload["plan"]
        self.assertEqual(plan["amount_cents"], 0)
        self.assertEqual(plan["amount_currency"], "CNY")
        charges = plan["charges"]
        self.assertEqual(charges[0]["billable_metric_id"], lago_ids[run.metrics[0].code])
        self.assertEqual(charges[0]["charge_model"], "standard")
        self.assertEqual(charges[0]["properties"]["amount"], "7")  # decimal string
        self.assertEqual(charges[1]["billable_metric_id"], lago_ids[run.metrics[1].code])
        self.assertEqual(charges[1]["properties"]["amount"], "1500")
        self.assertEqual(charges[1]["properties"]["package_size"], 100)
        self.assertEqual(charges[1]["properties"]["free_units"], 0)
        # the v1.53.0 live-verified 404 trap: never reference metrics by code
        for charge in charges:
            self.assertNotIn("billable_metric_code", charge)
