package craft

import (
	"context"
	"fmt"
	"strings"
	"time"
	"unicode"
)

// RunViewKey is the exact server-owned identity of one admitted execution
// view. In particular, RunID is selected from the admitted run and is not a
// caller-supplied directory or filesystem path.
type RunViewKey struct {
	TenantID  uint64
	OwnerID   string
	SessionID string
	RunID     string
}

// RunViewRuntime contains runtime identities only. It intentionally has no
// path field: persisting this binding does not grant filesystem authority.
type RunViewRuntime struct {
	RuntimeID         string
	ContainerID       string
	OpenCodeSessionID string
}

type RunViewState string

const (
	// RunViewStateAllocating means runtime creation is unresolved. Recovery
	// must reuse this generation and must not silently create a replacement.
	RunViewStateAllocating RunViewState = "allocating"
	RunViewStateBound      RunViewState = "bound"
)

// RunView is the durable identity and current runtime binding for one Run.
// Generation is generated by the server and remains stable across retries.
type RunView struct {
	Key        RunViewKey
	Generation string
	Runtime    RunViewRuntime
	State      RunViewState
	// SessionCreateIntentAt marks the durable one-shot permission to issue an
	// external, non-idempotent OpenCode CreateSession request. A non-nil value
	// means the outcome may be unknown; callers must reconcile and never resend.
	SessionCreateIntentAt *time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

// RunViewStore allocates and recovers the execution view attached to one
// admitted Run. Implementations compare the complete tenant/owner/session/run
// identity and make runtime binding immutable once resolved.
type RunViewStore interface {
	Allocate(ctx context.Context, key RunViewKey) (RunView, error)
	Load(ctx context.Context, key RunViewKey) (RunView, error)
	BeginSessionCreate(ctx context.Context, key RunViewKey, generation string) (RunView, bool, error)
	BindRuntime(ctx context.Context, key RunViewKey, generation string, runtime RunViewRuntime) (RunView, error)
}

// ValidateRunViewKey rejects incomplete or path-like execution identity.
func ValidateRunViewKey(key RunViewKey) error {
	if key.TenantID == 0 || !validRunViewToken(key.OwnerID, 512, false) ||
		!validRunViewToken(key.SessionID, 36, false) || !validRunViewToken(key.RunID, 64, true) {
		return fmt.Errorf("%w: incomplete or invalid RunView identity", ErrInvalidInput)
	}
	return nil
}

// ValidateRunViewRuntime requires all three concrete identities together and
// refuses filesystem-like values that could be mistaken for host paths.
func ValidateRunViewRuntime(runtime RunViewRuntime) error {
	if !validRunViewToken(runtime.RuntimeID, 255, true) ||
		!validRunViewToken(runtime.ContainerID, 255, true) ||
		!validRunViewToken(runtime.OpenCodeSessionID, 255, true) {
		return fmt.Errorf("%w: incomplete or invalid RunView runtime identity", ErrInvalidInput)
	}
	return nil
}

// ValidateRunView verifies that unresolved state has no partial runtime and a
// bound state has a complete identity. Timestamps are persistence facts and
// are not required by callers constructing a value for validation.
func ValidateRunView(view RunView) error {
	if err := ValidateRunViewKey(view.Key); err != nil {
		return err
	}
	if !validRunViewToken(view.Generation, 64, true) {
		return fmt.Errorf("%w: invalid RunView generation", ErrInvalidInput)
	}
	switch view.State {
	case RunViewStateAllocating:
		if view.Runtime != (RunViewRuntime{}) {
			return fmt.Errorf("%w: unresolved RunView cannot carry a partial runtime", ErrInvalidInput)
		}
	case RunViewStateBound:
		if view.SessionCreateIntentAt == nil || view.SessionCreateIntentAt.IsZero() {
			return fmt.Errorf("%w: bound RunView requires a session-create intent", ErrInvalidInput)
		}
		if err := ValidateRunViewRuntime(view.Runtime); err != nil {
			return err
		}
	default:
		return fmt.Errorf("%w: unknown RunView state %q", ErrInvalidInput, view.State)
	}
	if view.SessionCreateIntentAt != nil && view.SessionCreateIntentAt.IsZero() {
		return fmt.Errorf("%w: zero RunView session-create intent", ErrInvalidInput)
	}
	return nil
}

func validRunViewToken(value string, maxBytes int, rejectSeparators bool) bool {
	if value == "" || len(value) > maxBytes || strings.TrimSpace(value) != value {
		return false
	}
	for _, char := range value {
		if unicode.IsControl(char) || (rejectSeparators && (char == '/' || char == '\\')) {
			return false
		}
	}
	return true
}
