// WeKnora Semantica wire contract - the ONLY schema shared between the Go
// business system and the Python semantic service (spec section 7).
//
// Tag discipline (C01): field numbers are immutable once released; deleted
// fields must be reserved, never renumbered. Optional scalars distinguish
// "absent" from zero values (spans, manifest_ref, timestamps, error codes).
// 64-bit integers stay uint64 on the wire; JSON public boundaries encode
// them as decimal strings.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: semantic.proto

package semanticpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Semantic_GetCapabilities_FullMethodName       = "/weknora.semantic.v1.Semantic/GetCapabilities"
	Semantic_ApplyDocumentRevision_FullMethodName = "/weknora.semantic.v1.Semantic/ApplyDocumentRevision"
	Semantic_DeleteDocument_FullMethodName        = "/weknora.semantic.v1.Semantic/DeleteDocument"
	Semantic_GetOperation_FullMethodName          = "/weknora.semantic.v1.Semantic/GetOperation"
	Semantic_CancelOperation_FullMethodName       = "/weknora.semantic.v1.Semantic/CancelOperation"
	Semantic_Search_FullMethodName                = "/weknora.semantic.v1.Semantic/Search"
	Semantic_Reason_FullMethodName                = "/weknora.semantic.v1.Semantic/Reason"
)

// SemanticClient is the client API for Semantic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemanticClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	ApplyDocumentRevision(ctx context.Context, in *ApplyDocumentRevisionRequest, opts ...grpc.CallOption) (*Operation, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*Operation, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	CancelOperation(ctx context.Context, in *CancelOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*ReasonResponse, error)
}

type semanticClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticClient(cc grpc.ClientConnInterface) SemanticClient {
	return &semanticClient{cc}
}

func (c *semanticClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, Semantic_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClient) ApplyDocumentRevision(ctx context.Context, in *ApplyDocumentRevisionRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, Semantic_ApplyDocumentRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, Semantic_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, Semantic_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClient) CancelOperation(ctx context.Context, in *CancelOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, Semantic_CancelOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Semantic_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClient) Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*ReasonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReasonResponse)
	err := c.cc.Invoke(ctx, Semantic_Reason_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticServer is the server API for Semantic service.
// All implementations must embed UnimplementedSemanticServer
// for forward compatibility.
type SemanticServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	ApplyDocumentRevision(context.Context, *ApplyDocumentRevisionRequest) (*Operation, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*Operation, error)
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	CancelOperation(context.Context, *CancelOperationRequest) (*Operation, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Reason(context.Context, *ReasonRequest) (*ReasonResponse, error)
	mustEmbedUnimplementedSemanticServer()
}

// UnimplementedSemanticServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticServer struct{}

func (UnimplementedSemanticServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedSemanticServer) ApplyDocumentRevision(context.Context, *ApplyDocumentRevisionRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDocumentRevision not implemented")
}
func (UnimplementedSemanticServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedSemanticServer) GetOperation(context.Context, *GetOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedSemanticServer) CancelOperation(context.Context, *CancelOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOperation not implemented")
}
func (UnimplementedSemanticServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSemanticServer) Reason(context.Context, *ReasonRequest) (*ReasonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reason not implemented")
}
func (UnimplementedSemanticServer) mustEmbedUnimplementedSemanticServer() {}
func (UnimplementedSemanticServer) testEmbeddedByValue()                  {}

// UnsafeSemanticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticServer will
// result in compilation errors.
type UnsafeSemanticServer interface {
	mustEmbedUnimplementedSemanticServer()
}

func RegisterSemanticServer(s grpc.ServiceRegistrar, srv SemanticServer) {
	// If the following call pancis, it indicates UnimplementedSemanticServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Semantic_ServiceDesc, srv)
}

func _Semantic_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantic_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantic_ApplyDocumentRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDocumentRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServer).ApplyDocumentRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantic_ApplyDocumentRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServer).ApplyDocumentRevision(ctx, req.(*ApplyDocumentRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantic_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantic_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantic_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantic_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantic_CancelOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServer).CancelOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantic_CancelOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServer).CancelOperation(ctx, req.(*CancelOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantic_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantic_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Semantic_Reason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReasonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServer).Reason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Semantic_Reason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServer).Reason(ctx, req.(*ReasonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Semantic_ServiceDesc is the grpc.ServiceDesc for Semantic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Semantic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.semantic.v1.Semantic",
	HandlerType: (*SemanticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _Semantic_GetCapabilities_Handler,
		},
		{
			MethodName: "ApplyDocumentRevision",
			Handler:    _Semantic_ApplyDocumentRevision_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Semantic_DeleteDocument_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _Semantic_GetOperation_Handler,
		},
		{
			MethodName: "CancelOperation",
			Handler:    _Semantic_CancelOperation_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Semantic_Search_Handler,
		},
		{
			MethodName: "Reason",
			Handler:    _Semantic_Reason_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic.proto",
}
