// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: semantic.proto

package semanticpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationState int32

const (
	OperationState_OPERATION_STATE_UNSPECIFIED OperationState = 0
	OperationState_OPERATION_STATE_PENDING     OperationState = 1
	OperationState_OPERATION_STATE_RUNNING     OperationState = 2
	OperationState_OPERATION_STATE_SUCCEEDED   OperationState = 3
	OperationState_OPERATION_STATE_FAILED      OperationState = 4
	OperationState_OPERATION_STATE_CANCELLED   OperationState = 5
)

// Enum value maps for OperationState.
var (
	OperationState_name = map[int32]string{
		0: "OPERATION_STATE_UNSPECIFIED",
		1: "OPERATION_STATE_PENDING",
		2: "OPERATION_STATE_RUNNING",
		3: "OPERATION_STATE_SUCCEEDED",
		4: "OPERATION_STATE_FAILED",
		5: "OPERATION_STATE_CANCELLED",
	}
	OperationState_value = map[string]int32{
		"OPERATION_STATE_UNSPECIFIED": 0,
		"OPERATION_STATE_PENDING":     1,
		"OPERATION_STATE_RUNNING":     2,
		"OPERATION_STATE_SUCCEEDED":   3,
		"OPERATION_STATE_FAILED":      4,
		"OPERATION_STATE_CANCELLED":   5,
	}
)

func (x OperationState) Enum() *OperationState {
	p := new(OperationState)
	*p = x
	return p
}

func (x OperationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationState) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[0].Descriptor()
}

func (OperationState) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[0]
}

func (x OperationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationState.Descriptor instead.
func (OperationState) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{0}
}

type Purpose int32

const (
	Purpose_PURPOSE_UNSPECIFIED Purpose = 0
	Purpose_PURPOSE_SEARCH      Purpose = 1
	Purpose_PURPOSE_REASON      Purpose = 2
	Purpose_PURPOSE_INDEX       Purpose = 3
)

// Enum value maps for Purpose.
var (
	Purpose_name = map[int32]string{
		0: "PURPOSE_UNSPECIFIED",
		1: "PURPOSE_SEARCH",
		2: "PURPOSE_REASON",
		3: "PURPOSE_INDEX",
	}
	Purpose_value = map[string]int32{
		"PURPOSE_UNSPECIFIED": 0,
		"PURPOSE_SEARCH":      1,
		"PURPOSE_REASON":      2,
		"PURPOSE_INDEX":       3,
	}
)

func (x Purpose) Enum() *Purpose {
	p := new(Purpose)
	*p = x
	return p
}

func (x Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[1].Descriptor()
}

func (Purpose) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[1]
}

func (x Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Purpose.Descriptor instead.
func (Purpose) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{1}
}

type RetrievalMode int32

const (
	RetrievalMode_RETRIEVAL_MODE_UNSPECIFIED RetrievalMode = 0
	RetrievalMode_RETRIEVAL_MODE_GRAPH_RAG   RetrievalMode = 1
	RetrievalMode_RETRIEVAL_MODE_REASON      RetrievalMode = 2
)

// Enum value maps for RetrievalMode.
var (
	RetrievalMode_name = map[int32]string{
		0: "RETRIEVAL_MODE_UNSPECIFIED",
		1: "RETRIEVAL_MODE_GRAPH_RAG",
		2: "RETRIEVAL_MODE_REASON",
	}
	RetrievalMode_value = map[string]int32{
		"RETRIEVAL_MODE_UNSPECIFIED": 0,
		"RETRIEVAL_MODE_GRAPH_RAG":   1,
		"RETRIEVAL_MODE_REASON":      2,
	}
)

func (x RetrievalMode) Enum() *RetrievalMode {
	p := new(RetrievalMode)
	*p = x
	return p
}

func (x RetrievalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetrievalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[2].Descriptor()
}

func (RetrievalMode) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[2]
}

func (x RetrievalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetrievalMode.Descriptor instead.
func (RetrievalMode) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{2}
}

type ReasoningMode int32

const (
	ReasoningMode_REASONING_MODE_UNSPECIFIED ReasoningMode = 0
	ReasoningMode_REASONING_MODE_RULES       ReasoningMode = 1
	ReasoningMode_REASONING_MODE_MODEL       ReasoningMode = 2
)

// Enum value maps for ReasoningMode.
var (
	ReasoningMode_name = map[int32]string{
		0: "REASONING_MODE_UNSPECIFIED",
		1: "REASONING_MODE_RULES",
		2: "REASONING_MODE_MODEL",
	}
	ReasoningMode_value = map[string]int32{
		"REASONING_MODE_UNSPECIFIED": 0,
		"REASONING_MODE_RULES":       1,
		"REASONING_MODE_MODEL":       2,
	}
)

func (x ReasoningMode) Enum() *ReasoningMode {
	p := new(ReasoningMode)
	*p = x
	return p
}

func (x ReasoningMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasoningMode) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[3].Descriptor()
}

func (ReasoningMode) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[3]
}

func (x ReasoningMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasoningMode.Descriptor instead.
func (ReasoningMode) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{3}
}

type ReasonStatus int32

const (
	ReasonStatus_REASON_STATUS_UNSPECIFIED           ReasonStatus = 0
	ReasonStatus_REASON_STATUS_DERIVED               ReasonStatus = 1
	ReasonStatus_REASON_STATUS_INSUFFICIENT_EVIDENCE ReasonStatus = 2
	ReasonStatus_REASON_STATUS_CONFLICT              ReasonStatus = 3
	ReasonStatus_REASON_STATUS_UNAVAILABLE           ReasonStatus = 4
)

// Enum value maps for ReasonStatus.
var (
	ReasonStatus_name = map[int32]string{
		0: "REASON_STATUS_UNSPECIFIED",
		1: "REASON_STATUS_DERIVED",
		2: "REASON_STATUS_INSUFFICIENT_EVIDENCE",
		3: "REASON_STATUS_CONFLICT",
		4: "REASON_STATUS_UNAVAILABLE",
	}
	ReasonStatus_value = map[string]int32{
		"REASON_STATUS_UNSPECIFIED":           0,
		"REASON_STATUS_DERIVED":               1,
		"REASON_STATUS_INSUFFICIENT_EVIDENCE": 2,
		"REASON_STATUS_CONFLICT":              3,
		"REASON_STATUS_UNAVAILABLE":           4,
	}
)

func (x ReasonStatus) Enum() *ReasonStatus {
	p := new(ReasonStatus)
	*p = x
	return p
}

func (x ReasonStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasonStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[4].Descriptor()
}

func (ReasonStatus) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[4]
}

func (x ReasonStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasonStatus.Descriptor instead.
func (ReasonStatus) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{4}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_semantic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{0}
}

type ScopeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	KbId          string                 `protobuf:"bytes,2,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeKey) Reset() {
	*x = ScopeKey{}
	mi := &file_semantic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeKey) ProtoMessage() {}

func (x *ScopeKey) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeKey.ProtoReflect.Descriptor instead.
func (*ScopeKey) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{1}
}

func (x *ScopeKey) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ScopeKey) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

type DocumentRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeKey              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRevision) Reset() {
	*x = DocumentRevision{}
	mi := &file_semantic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRevision) ProtoMessage() {}

func (x *DocumentRevision) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRevision.ProtoReflect.Descriptor instead.
func (*DocumentRevision) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentRevision) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *DocumentRevision) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentRevision) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DocumentRevision) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *DocumentRevision) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ChunkSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSnapshot) Reset() {
	*x = ChunkSnapshot{}
	mi := &file_semantic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSnapshot) ProtoMessage() {}

func (x *ChunkSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSnapshot.ProtoReflect.Descriptor instead.
func (*ChunkSnapshot) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkSnapshot) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkSnapshot) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChunkSnapshot) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type IndexConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest    string                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	EngineVersion   string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	ModelProfileRef string                 `protobuf:"bytes,3,opt,name=model_profile_ref,json=modelProfileRef,proto3" json:"model_profile_ref,omitempty"`
	PromptVersion   string                 `protobuf:"bytes,4,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`
	RuleSetVersion  string                 `protobuf:"bytes,5,opt,name=rule_set_version,json=ruleSetVersion,proto3" json:"rule_set_version,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IndexConfig) Reset() {
	*x = IndexConfig{}
	mi := &file_semantic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexConfig) ProtoMessage() {}

func (x *IndexConfig) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexConfig.ProtoReflect.Descriptor instead.
func (*IndexConfig) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{4}
}

func (x *IndexConfig) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *IndexConfig) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *IndexConfig) GetModelProfileRef() string {
	if x != nil {
		return x.ModelProfileRef
	}
	return ""
}

func (x *IndexConfig) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

func (x *IndexConfig) GetRuleSetVersion() string {
	if x != nil {
		return x.RuleSetVersion
	}
	return ""
}

func (x *IndexConfig) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type ApplyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Document       *DocumentRevision      `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Chunks         []*ChunkSnapshot       `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	ManifestRef    *string                `protobuf:"bytes,3,opt,name=manifest_ref,json=manifestRef,proto3,oneof" json:"manifest_ref,omitempty"`
	Config         *IndexConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	PayloadHash    string                 `protobuf:"bytes,6,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_semantic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyRequest) GetDocument() *DocumentRevision {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ApplyRequest) GetChunks() []*ChunkSnapshot {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ApplyRequest) GetManifestRef() string {
	if x != nil && x.ManifestRef != nil {
		return *x.ManifestRef
	}
	return ""
}

func (x *ApplyRequest) GetConfig() *IndexConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ApplyRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ApplyRequest) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

type OperationRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeKey              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRef) Reset() {
	*x = OperationRef{}
	mi := &file_semantic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRef) ProtoMessage() {}

func (x *OperationRef) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRef.ProtoReflect.Descriptor instead.
func (*OperationRef) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{6}
}

func (x *OperationRef) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *OperationRef) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type Operation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Scope            *ScopeKey              `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	DocumentId       string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Revision         uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	State            OperationState         `protobuf:"varint,5,opt,name=state,proto3,enum=weknora.semantic.v1.OperationState" json:"state,omitempty"`
	Stage            string                 `protobuf:"bytes,6,opt,name=stage,proto3" json:"stage,omitempty"`
	LeaseToken       uint64                 `protobuf:"varint,7,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	ResultGeneration *string                `protobuf:"bytes,8,opt,name=result_generation,json=resultGeneration,proto3,oneof" json:"result_generation,omitempty"`
	ErrorCode        *string                `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_semantic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{7}
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Operation) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Operation) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Operation) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_UNSPECIFIED
}

func (x *Operation) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Operation) GetLeaseToken() uint64 {
	if x != nil {
		return x.LeaseToken
	}
	return 0
}

func (x *Operation) GetResultGeneration() string {
	if x != nil && x.ResultGeneration != nil {
		return *x.ResultGeneration
	}
	return ""
}

func (x *Operation) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId    string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	ChunkId       string                 `protobuf:"bytes,4,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ContentHash   string                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Quote         string                 `protobuf:"bytes,6,opt,name=quote,proto3" json:"quote,omitempty"`
	StartChar     *uint32                `protobuf:"varint,7,opt,name=start_char,json=startChar,proto3,oneof" json:"start_char,omitempty"`
	EndChar       *uint32                `protobuf:"varint,8,opt,name=end_char,json=endChar,proto3,oneof" json:"end_char,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_semantic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{8}
}

func (x *Evidence) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *Evidence) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Evidence) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Evidence) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Evidence) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Evidence) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Evidence) GetStartChar() uint32 {
	if x != nil && x.StartChar != nil {
		return *x.StartChar
	}
	return 0
}

func (x *Evidence) GetEndChar() uint32 {
	if x != nil && x.EndChar != nil {
		return *x.EndChar
	}
	return 0
}

type AccessScope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scope           *ScopeKey              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ScopeRef        string                 `protobuf:"bytes,3,opt,name=scope_ref,json=scopeRef,proto3" json:"scope_ref,omitempty"`
	ScopeHash       string                 `protobuf:"bytes,4,opt,name=scope_hash,json=scopeHash,proto3" json:"scope_hash,omitempty"`
	PermissionEpoch uint64                 `protobuf:"varint,5,opt,name=permission_epoch,json=permissionEpoch,proto3" json:"permission_epoch,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Audience        string                 `protobuf:"bytes,7,opt,name=audience,proto3" json:"audience,omitempty"`
	Purpose         Purpose                `protobuf:"varint,8,opt,name=purpose,proto3,enum=weknora.semantic.v1.Purpose" json:"purpose,omitempty"`
	BudgetRef       string                 `protobuf:"bytes,9,opt,name=budget_ref,json=budgetRef,proto3" json:"budget_ref,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessScope) Reset() {
	*x = AccessScope{}
	mi := &file_semantic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessScope) ProtoMessage() {}

func (x *AccessScope) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessScope.ProtoReflect.Descriptor instead.
func (*AccessScope) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{9}
}

func (x *AccessScope) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AccessScope) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AccessScope) GetScopeRef() string {
	if x != nil {
		return x.ScopeRef
	}
	return ""
}

func (x *AccessScope) GetScopeHash() string {
	if x != nil {
		return x.ScopeHash
	}
	return ""
}

func (x *AccessScope) GetPermissionEpoch() uint64 {
	if x != nil {
		return x.PermissionEpoch
	}
	return 0
}

func (x *AccessScope) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AccessScope) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *AccessScope) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_PURPOSE_UNSPECIFIED
}

func (x *AccessScope) GetBudgetRef() string {
	if x != nil {
		return x.BudgetRef
	}
	return ""
}

type QueryLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxHops       uint32                 `protobuf:"varint,1,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	MaxNodes      uint32                 `protobuf:"varint,2,opt,name=max_nodes,json=maxNodes,proto3" json:"max_nodes,omitempty"`
	MaxEdges      uint32                 `protobuf:"varint,3,opt,name=max_edges,json=maxEdges,proto3" json:"max_edges,omitempty"`
	TopK          uint32                 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	DeadlineMs    uint32                 `protobuf:"varint,6,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLimits) Reset() {
	*x = QueryLimits{}
	mi := &file_semantic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLimits) ProtoMessage() {}

func (x *QueryLimits) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLimits.ProtoReflect.Descriptor instead.
func (*QueryLimits) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{10}
}

func (x *QueryLimits) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *QueryLimits) GetMaxNodes() uint32 {
	if x != nil {
		return x.MaxNodes
	}
	return 0
}

func (x *QueryLimits) GetMaxEdges() uint32 {
	if x != nil {
		return x.MaxEdges
	}
	return 0
}

func (x *QueryLimits) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryLimits) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *QueryLimits) GetDeadlineMs() uint32 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	AccessScope   *AccessScope           `protobuf:"bytes,3,opt,name=access_scope,json=accessScope,proto3" json:"access_scope,omitempty"`
	Limits        *QueryLimits           `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	RequestedMode RetrievalMode          `protobuf:"varint,5,opt,name=requested_mode,json=requestedMode,proto3,enum=weknora.semantic.v1.RetrievalMode" json:"requested_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_semantic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetAccessScope() *AccessScope {
	if x != nil {
		return x.AccessScope
	}
	return nil
}

func (x *SearchRequest) GetLimits() *QueryLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SearchRequest) GetRequestedMode() RetrievalMode {
	if x != nil {
		return x.RequestedMode
	}
	return RetrievalMode_RETRIEVAL_MODE_UNSPECIFIED
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Generation    string                 `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	RequestedMode RetrievalMode          `protobuf:"varint,3,opt,name=requested_mode,json=requestedMode,proto3,enum=weknora.semantic.v1.RetrievalMode" json:"requested_mode,omitempty"`
	ActualMode    RetrievalMode          `protobuf:"varint,4,opt,name=actual_mode,json=actualMode,proto3,enum=weknora.semantic.v1.RetrievalMode" json:"actual_mode,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,5,rep,name=evidence,proto3" json:"evidence,omitempty"`
	AssertionIds  []string               `protobuf:"bytes,6,rep,name=assertion_ids,json=assertionIds,proto3" json:"assertion_ids,omitempty"`
	Paths         []*StringPath          `protobuf:"bytes,7,rep,name=paths,proto3" json:"paths,omitempty"`
	Stale         bool                   `protobuf:"varint,8,opt,name=stale,proto3" json:"stale,omitempty"`
	Partial       bool                   `protobuf:"varint,9,opt,name=partial,proto3" json:"partial,omitempty"`
	Truncated     bool                   `protobuf:"varint,10,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_semantic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SearchResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *SearchResponse) GetRequestedMode() RetrievalMode {
	if x != nil {
		return x.RequestedMode
	}
	return RetrievalMode_RETRIEVAL_MODE_UNSPECIFIED
}

func (x *SearchResponse) GetActualMode() RetrievalMode {
	if x != nil {
		return x.ActualMode
	}
	return RetrievalMode_RETRIEVAL_MODE_UNSPECIFIED
}

func (x *SearchResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *SearchResponse) GetAssertionIds() []string {
	if x != nil {
		return x.AssertionIds
	}
	return nil
}

func (x *SearchResponse) GetPaths() []*StringPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *SearchResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *SearchResponse) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *SearchResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type StringPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPath) Reset() {
	*x = StringPath{}
	mi := &file_semantic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPath) ProtoMessage() {}

func (x *StringPath) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPath.ProtoReflect.Descriptor instead.
func (*StringPath) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{13}
}

func (x *StringPath) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReasonRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Search         *SearchRequest         `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	ReasoningMode  ReasoningMode          `protobuf:"varint,2,opt,name=reasoning_mode,json=reasoningMode,proto3,enum=weknora.semantic.v1.ReasoningMode" json:"reasoning_mode,omitempty"`
	RuleSetVersion string                 `protobuf:"bytes,3,opt,name=rule_set_version,json=ruleSetVersion,proto3" json:"rule_set_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReasonRequest) Reset() {
	*x = ReasonRequest{}
	mi := &file_semantic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonRequest) ProtoMessage() {}

func (x *ReasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasonRequest.ProtoReflect.Descriptor instead.
func (*ReasonRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{14}
}

func (x *ReasonRequest) GetSearch() *SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ReasonRequest) GetReasoningMode() ReasoningMode {
	if x != nil {
		return x.ReasoningMode
	}
	return ReasoningMode_REASONING_MODE_UNSPECIFIED
}

func (x *ReasonRequest) GetRuleSetVersion() string {
	if x != nil {
		return x.RuleSetVersion
	}
	return ""
}

type ReasonResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Retrieval      *SearchResponse        `protobuf:"bytes,1,opt,name=retrieval,proto3" json:"retrieval,omitempty"`
	Status         ReasonStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=weknora.semantic.v1.ReasonStatus" json:"status,omitempty"`
	Conclusion     *string                `protobuf:"bytes,3,opt,name=conclusion,proto3,oneof" json:"conclusion,omitempty"`
	ConclusionKind *string                `protobuf:"bytes,4,opt,name=conclusion_kind,json=conclusionKind,proto3,oneof" json:"conclusion_kind,omitempty"`
	PremiseIds     []string               `protobuf:"bytes,5,rep,name=premise_ids,json=premiseIds,proto3" json:"premise_ids,omitempty"`
	RuleIds        []string               `protobuf:"bytes,6,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	ModelVersion   *string                `protobuf:"bytes,7,opt,name=model_version,json=modelVersion,proto3,oneof" json:"model_version,omitempty"`
	PromptVersion  *string                `protobuf:"bytes,8,opt,name=prompt_version,json=promptVersion,proto3,oneof" json:"prompt_version,omitempty"`
	Limitations    []string               `protobuf:"bytes,9,rep,name=limitations,proto3" json:"limitations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReasonResponse) Reset() {
	*x = ReasonResponse{}
	mi := &file_semantic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonResponse) ProtoMessage() {}

func (x *ReasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasonResponse.ProtoReflect.Descriptor instead.
func (*ReasonResponse) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{15}
}

func (x *ReasonResponse) GetRetrieval() *SearchResponse {
	if x != nil {
		return x.Retrieval
	}
	return nil
}

func (x *ReasonResponse) GetStatus() ReasonStatus {
	if x != nil {
		return x.Status
	}
	return ReasonStatus_REASON_STATUS_UNSPECIFIED
}

func (x *ReasonResponse) GetConclusion() string {
	if x != nil && x.Conclusion != nil {
		return *x.Conclusion
	}
	return ""
}

func (x *ReasonResponse) GetConclusionKind() string {
	if x != nil && x.ConclusionKind != nil {
		return *x.ConclusionKind
	}
	return ""
}

func (x *ReasonResponse) GetPremiseIds() []string {
	if x != nil {
		return x.PremiseIds
	}
	return nil
}

func (x *ReasonResponse) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

func (x *ReasonResponse) GetModelVersion() string {
	if x != nil && x.ModelVersion != nil {
		return *x.ModelVersion
	}
	return ""
}

func (x *ReasonResponse) GetPromptVersion() string {
	if x != nil && x.PromptVersion != nil {
		return *x.PromptVersion
	}
	return ""
}

func (x *ReasonResponse) GetLimitations() []string {
	if x != nil {
		return x.Limitations
	}
	return nil
}

type Capabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion   string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EngineVersion     string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	RetrievalModes    []RetrievalMode        `protobuf:"varint,3,rep,packed,name=retrieval_modes,json=retrievalModes,proto3,enum=weknora.semantic.v1.RetrievalMode" json:"retrieval_modes,omitempty"`
	ReasoningModes    []ReasoningMode        `protobuf:"varint,4,rep,packed,name=reasoning_modes,json=reasoningModes,proto3,enum=weknora.semantic.v1.ReasoningMode" json:"reasoning_modes,omitempty"`
	Limits            *QueryLimits           `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	Limitations       []string               `protobuf:"bytes,6,rep,name=limitations,proto3" json:"limitations,omitempty"`
	UnavailableReason *string                `protobuf:"bytes,7,opt,name=unavailable_reason,json=unavailableReason,proto3,oneof" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_semantic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{16}
}

func (x *Capabilities) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Capabilities) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *Capabilities) GetRetrievalModes() []RetrievalMode {
	if x != nil {
		return x.RetrievalModes
	}
	return nil
}

func (x *Capabilities) GetReasoningModes() []ReasoningMode {
	if x != nil {
		return x.ReasoningModes
	}
	return nil
}

func (x *Capabilities) GetLimits() *QueryLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Capabilities) GetLimitations() []string {
	if x != nil {
		return x.Limitations
	}
	return nil
}

func (x *Capabilities) GetUnavailableReason() string {
	if x != nil && x.UnavailableReason != nil {
		return *x.UnavailableReason
	}
	return ""
}

var File_semantic_proto protoreflect.FileDescriptor

const file_semantic_proto_rawDesc = "" +
	"\n" +
	"\x0esemantic.proto\x12\x13weknora.semantic.v1\"\a\n" +
	"\x05Empty\"<\n" +
	"\bScopeKey\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x13\n" +
	"\x05kb_id\x18\x02 \x01(\tR\x04kbId\"\xc1\x01\n" +
	"\x10DocumentRevision\x123\n" +
	"\x05scope\x18\x01 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\"a\n" +
	"\rChunkSnapshot\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\"\xfd\x01\n" +
	"\vIndexConfig\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\tR\fconfigDigest\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\x12*\n" +
	"\x11model_profile_ref\x18\x03 \x01(\tR\x0fmodelProfileRef\x12%\n" +
	"\x0eprompt_version\x18\x04 \x01(\tR\rpromptVersion\x12(\n" +
	"\x10rule_set_version\x18\x05 \x01(\tR\x0eruleSetVersion\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\"\xcc\x02\n" +
	"\fApplyRequest\x12A\n" +
	"\bdocument\x18\x01 \x01(\v2%.weknora.semantic.v1.DocumentRevisionR\bdocument\x12:\n" +
	"\x06chunks\x18\x02 \x03(\v2\".weknora.semantic.v1.ChunkSnapshotR\x06chunks\x12&\n" +
	"\fmanifest_ref\x18\x03 \x01(\tH\x00R\vmanifestRef\x88\x01\x01\x128\n" +
	"\x06config\x18\x04 \x01(\v2 .weknora.semantic.v1.IndexConfigR\x06config\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\fpayload_hash\x18\x06 \x01(\tR\vpayloadHashB\x0f\n" +
	"\r_manifest_ref\"f\n" +
	"\fOperationRef\x123\n" +
	"\x05scope\x18\x01 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"\x8d\x03\n" +
	"\tOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x123\n" +
	"\x05scope\x18\x02 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x129\n" +
	"\x05state\x18\x05 \x01(\x0e2#.weknora.semantic.v1.OperationStateR\x05state\x12\x14\n" +
	"\x05stage\x18\x06 \x01(\tR\x05stage\x12\x1f\n" +
	"\vlease_token\x18\a \x01(\x04R\n" +
	"leaseToken\x120\n" +
	"\x11result_generation\x18\b \x01(\tH\x00R\x10resultGeneration\x88\x01\x01\x12\"\n" +
	"\n" +
	"error_code\x18\t \x01(\tH\x01R\terrorCode\x88\x01\x01B\x14\n" +
	"\x12_result_generationB\r\n" +
	"\v_error_code\"\x9c\x02\n" +
	"\bEvidence\x12\x1f\n" +
	"\vevidence_id\x18\x01 \x01(\tR\n" +
	"evidenceId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x19\n" +
	"\bchunk_id\x18\x04 \x01(\tR\achunkId\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12\x14\n" +
	"\x05quote\x18\x06 \x01(\tR\x05quote\x12\"\n" +
	"\n" +
	"start_char\x18\a \x01(\rH\x00R\tstartChar\x88\x01\x01\x12\x1e\n" +
	"\bend_char\x18\b \x01(\rH\x01R\aendChar\x88\x01\x01B\r\n" +
	"\v_start_charB\v\n" +
	"\t_end_char\"\xda\x02\n" +
	"\vAccessScope\x123\n" +
	"\x05scope\x18\x01 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1b\n" +
	"\tscope_ref\x18\x03 \x01(\tR\bscopeRef\x12\x1d\n" +
	"\n" +
	"scope_hash\x18\x04 \x01(\tR\tscopeHash\x12)\n" +
	"\x10permission_epoch\x18\x05 \x01(\x04R\x0fpermissionEpoch\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12\x1a\n" +
	"\baudience\x18\a \x01(\tR\baudience\x126\n" +
	"\apurpose\x18\b \x01(\x0e2\x1c.weknora.semantic.v1.PurposeR\apurpose\x12\x1d\n" +
	"\n" +
	"budget_ref\x18\t \x01(\tR\tbudgetRef\"\xb7\x01\n" +
	"\vQueryLimits\x12\x19\n" +
	"\bmax_hops\x18\x01 \x01(\rR\amaxHops\x12\x1b\n" +
	"\tmax_nodes\x18\x02 \x01(\rR\bmaxNodes\x12\x1b\n" +
	"\tmax_edges\x18\x03 \x01(\rR\bmaxEdges\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\rR\x04topK\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\rR\tmaxTokens\x12\x1f\n" +
	"\vdeadline_ms\x18\x06 \x01(\rR\n" +
	"deadlineMs\"\x8a\x02\n" +
	"\rSearchRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12C\n" +
	"\faccess_scope\x18\x03 \x01(\v2 .weknora.semantic.v1.AccessScopeR\vaccessScope\x128\n" +
	"\x06limits\x18\x04 \x01(\v2 .weknora.semantic.v1.QueryLimitsR\x06limits\x12I\n" +
	"\x0erequested_mode\x18\x05 \x01(\x0e2\".weknora.semantic.v1.RetrievalModeR\rrequestedMode\"\xc0\x03\n" +
	"\x0eSearchResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\tR\n" +
	"generation\x12I\n" +
	"\x0erequested_mode\x18\x03 \x01(\x0e2\".weknora.semantic.v1.RetrievalModeR\rrequestedMode\x12C\n" +
	"\vactual_mode\x18\x04 \x01(\x0e2\".weknora.semantic.v1.RetrievalModeR\n" +
	"actualMode\x129\n" +
	"\bevidence\x18\x05 \x03(\v2\x1d.weknora.semantic.v1.EvidenceR\bevidence\x12#\n" +
	"\rassertion_ids\x18\x06 \x03(\tR\fassertionIds\x125\n" +
	"\x05paths\x18\a \x03(\v2\x1f.weknora.semantic.v1.StringPathR\x05paths\x12\x14\n" +
	"\x05stale\x18\b \x01(\bR\x05stale\x12\x18\n" +
	"\apartial\x18\t \x01(\bR\apartial\x12\x1c\n" +
	"\ttruncated\x18\n" +
	" \x01(\bR\ttruncated\"\x1e\n" +
	"\n" +
	"StringPath\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xc0\x01\n" +
	"\rReasonRequest\x12:\n" +
	"\x06search\x18\x01 \x01(\v2\".weknora.semantic.v1.SearchRequestR\x06search\x12I\n" +
	"\x0ereasoning_mode\x18\x02 \x01(\x0e2\".weknora.semantic.v1.ReasoningModeR\rreasoningMode\x12(\n" +
	"\x10rule_set_version\x18\x03 \x01(\tR\x0eruleSetVersion\"\xdd\x03\n" +
	"\x0eReasonResponse\x12A\n" +
	"\tretrieval\x18\x01 \x01(\v2#.weknora.semantic.v1.SearchResponseR\tretrieval\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.weknora.semantic.v1.ReasonStatusR\x06status\x12#\n" +
	"\n" +
	"conclusion\x18\x03 \x01(\tH\x00R\n" +
	"conclusion\x88\x01\x01\x12,\n" +
	"\x0fconclusion_kind\x18\x04 \x01(\tH\x01R\x0econclusionKind\x88\x01\x01\x12\x1f\n" +
	"\vpremise_ids\x18\x05 \x03(\tR\n" +
	"premiseIds\x12\x19\n" +
	"\brule_ids\x18\x06 \x03(\tR\aruleIds\x12(\n" +
	"\rmodel_version\x18\a \x01(\tH\x02R\fmodelVersion\x88\x01\x01\x12*\n" +
	"\x0eprompt_version\x18\b \x01(\tH\x03R\rpromptVersion\x88\x01\x01\x12 \n" +
	"\vlimitations\x18\t \x03(\tR\vlimitationsB\r\n" +
	"\v_conclusionB\x12\n" +
	"\x10_conclusion_kindB\x10\n" +
	"\x0e_model_versionB\x11\n" +
	"\x0f_prompt_version\"\xa1\x03\n" +
	"\fCapabilities\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\x12K\n" +
	"\x0fretrieval_modes\x18\x03 \x03(\x0e2\".weknora.semantic.v1.RetrievalModeR\x0eretrievalModes\x12K\n" +
	"\x0freasoning_modes\x18\x04 \x03(\x0e2\".weknora.semantic.v1.ReasoningModeR\x0ereasoningModes\x128\n" +
	"\x06limits\x18\x05 \x01(\v2 .weknora.semantic.v1.QueryLimitsR\x06limits\x12 \n" +
	"\vlimitations\x18\x06 \x03(\tR\vlimitations\x122\n" +
	"\x12unavailable_reason\x18\a \x01(\tH\x00R\x11unavailableReason\x88\x01\x01B\x15\n" +
	"\x13_unavailable_reason*\xc5\x01\n" +
	"\x0eOperationState\x12\x1f\n" +
	"\x1bOPERATION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATION_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17OPERATION_STATE_RUNNING\x10\x02\x12\x1d\n" +
	"\x19OPERATION_STATE_SUCCEEDED\x10\x03\x12\x1a\n" +
	"\x16OPERATION_STATE_FAILED\x10\x04\x12\x1d\n" +
	"\x19OPERATION_STATE_CANCELLED\x10\x05*]\n" +
	"\aPurpose\x12\x17\n" +
	"\x13PURPOSE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePURPOSE_SEARCH\x10\x01\x12\x12\n" +
	"\x0ePURPOSE_REASON\x10\x02\x12\x11\n" +
	"\rPURPOSE_INDEX\x10\x03*h\n" +
	"\rRetrievalMode\x12\x1e\n" +
	"\x1aRETRIEVAL_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RETRIEVAL_MODE_GRAPH_RAG\x10\x01\x12\x19\n" +
	"\x15RETRIEVAL_MODE_REASON\x10\x02*c\n" +
	"\rReasoningMode\x12\x1e\n" +
	"\x1aREASONING_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REASONING_MODE_RULES\x10\x01\x12\x18\n" +
	"\x14REASONING_MODE_MODEL\x10\x02*\xac\x01\n" +
	"\fReasonStatus\x12\x1d\n" +
	"\x19REASON_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REASON_STATUS_DERIVED\x10\x01\x12'\n" +
	"#REASON_STATUS_INSUFFICIENT_EVIDENCE\x10\x02\x12\x1a\n" +
	"\x16REASON_STATUS_CONFLICT\x10\x03\x12\x1d\n" +
	"\x19REASON_STATUS_UNAVAILABLE\x10\x042\xe7\x04\n" +
	"\x0fSemanticService\x12P\n" +
	"\x0fGetCapabilities\x12\x1a.weknora.semantic.v1.Empty\x1a!.weknora.semantic.v1.Capabilities\x12Z\n" +
	"\x15ApplyDocumentRevision\x12!.weknora.semantic.v1.ApplyRequest\x1a\x1e.weknora.semantic.v1.Operation\x12W\n" +
	"\x0eDeleteDocument\x12%.weknora.semantic.v1.DocumentRevision\x1a\x1e.weknora.semantic.v1.Operation\x12Q\n" +
	"\fGetOperation\x12!.weknora.semantic.v1.OperationRef\x1a\x1e.weknora.semantic.v1.Operation\x12T\n" +
	"\x0fCancelOperation\x12!.weknora.semantic.v1.OperationRef\x1a\x1e.weknora.semantic.v1.Operation\x12Q\n" +
	"\x06Search\x12\".weknora.semantic.v1.SearchRequest\x1a#.weknora.semantic.v1.SearchResponse\x12Q\n" +
	"\x06Reason\x12\".weknora.semantic.v1.ReasonRequest\x1a#.weknora.semantic.v1.ReasonResponseB6Z4github.com/Tencent/WeKnora/semantic/proto;semanticpbb\x06proto3"

var (
	file_semantic_proto_rawDescOnce sync.Once
	file_semantic_proto_rawDescData []byte
)

func file_semantic_proto_rawDescGZIP() []byte {
	file_semantic_proto_rawDescOnce.Do(func() {
		file_semantic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_semantic_proto_rawDesc), len(file_semantic_proto_rawDesc)))
	})
	return file_semantic_proto_rawDescData
}

var file_semantic_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_semantic_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_semantic_proto_goTypes = []any{
	(OperationState)(0),      // 0: weknora.semantic.v1.OperationState
	(Purpose)(0),             // 1: weknora.semantic.v1.Purpose
	(RetrievalMode)(0),       // 2: weknora.semantic.v1.RetrievalMode
	(ReasoningMode)(0),       // 3: weknora.semantic.v1.ReasoningMode
	(ReasonStatus)(0),        // 4: weknora.semantic.v1.ReasonStatus
	(*Empty)(nil),            // 5: weknora.semantic.v1.Empty
	(*ScopeKey)(nil),         // 6: weknora.semantic.v1.ScopeKey
	(*DocumentRevision)(nil), // 7: weknora.semantic.v1.DocumentRevision
	(*ChunkSnapshot)(nil),    // 8: weknora.semantic.v1.ChunkSnapshot
	(*IndexConfig)(nil),      // 9: weknora.semantic.v1.IndexConfig
	(*ApplyRequest)(nil),     // 10: weknora.semantic.v1.ApplyRequest
	(*OperationRef)(nil),     // 11: weknora.semantic.v1.OperationRef
	(*Operation)(nil),        // 12: weknora.semantic.v1.Operation
	(*Evidence)(nil),         // 13: weknora.semantic.v1.Evidence
	(*AccessScope)(nil),      // 14: weknora.semantic.v1.AccessScope
	(*QueryLimits)(nil),      // 15: weknora.semantic.v1.QueryLimits
	(*SearchRequest)(nil),    // 16: weknora.semantic.v1.SearchRequest
	(*SearchResponse)(nil),   // 17: weknora.semantic.v1.SearchResponse
	(*StringPath)(nil),       // 18: weknora.semantic.v1.StringPath
	(*ReasonRequest)(nil),    // 19: weknora.semantic.v1.ReasonRequest
	(*ReasonResponse)(nil),   // 20: weknora.semantic.v1.ReasonResponse
	(*Capabilities)(nil),     // 21: weknora.semantic.v1.Capabilities
}
var file_semantic_proto_depIdxs = []int32{
	6,  // 0: weknora.semantic.v1.DocumentRevision.scope:type_name -> weknora.semantic.v1.ScopeKey
	7,  // 1: weknora.semantic.v1.ApplyRequest.document:type_name -> weknora.semantic.v1.DocumentRevision
	8,  // 2: weknora.semantic.v1.ApplyRequest.chunks:type_name -> weknora.semantic.v1.ChunkSnapshot
	9,  // 3: weknora.semantic.v1.ApplyRequest.config:type_name -> weknora.semantic.v1.IndexConfig
	6,  // 4: weknora.semantic.v1.OperationRef.scope:type_name -> weknora.semantic.v1.ScopeKey
	6,  // 5: weknora.semantic.v1.Operation.scope:type_name -> weknora.semantic.v1.ScopeKey
	0,  // 6: weknora.semantic.v1.Operation.state:type_name -> weknora.semantic.v1.OperationState
	6,  // 7: weknora.semantic.v1.AccessScope.scope:type_name -> weknora.semantic.v1.ScopeKey
	1,  // 8: weknora.semantic.v1.AccessScope.purpose:type_name -> weknora.semantic.v1.Purpose
	14, // 9: weknora.semantic.v1.SearchRequest.access_scope:type_name -> weknora.semantic.v1.AccessScope
	15, // 10: weknora.semantic.v1.SearchRequest.limits:type_name -> weknora.semantic.v1.QueryLimits
	2,  // 11: weknora.semantic.v1.SearchRequest.requested_mode:type_name -> weknora.semantic.v1.RetrievalMode
	2,  // 12: weknora.semantic.v1.SearchResponse.requested_mode:type_name -> weknora.semantic.v1.RetrievalMode
	2,  // 13: weknora.semantic.v1.SearchResponse.actual_mode:type_name -> weknora.semantic.v1.RetrievalMode
	13, // 14: weknora.semantic.v1.SearchResponse.evidence:type_name -> weknora.semantic.v1.Evidence
	18, // 15: weknora.semantic.v1.SearchResponse.paths:type_name -> weknora.semantic.v1.StringPath
	16, // 16: weknora.semantic.v1.ReasonRequest.search:type_name -> weknora.semantic.v1.SearchRequest
	3,  // 17: weknora.semantic.v1.ReasonRequest.reasoning_mode:type_name -> weknora.semantic.v1.ReasoningMode
	17, // 18: weknora.semantic.v1.ReasonResponse.retrieval:type_name -> weknora.semantic.v1.SearchResponse
	4,  // 19: weknora.semantic.v1.ReasonResponse.status:type_name -> weknora.semantic.v1.ReasonStatus
	2,  // 20: weknora.semantic.v1.Capabilities.retrieval_modes:type_name -> weknora.semantic.v1.RetrievalMode
	3,  // 21: weknora.semantic.v1.Capabilities.reasoning_modes:type_name -> weknora.semantic.v1.ReasoningMode
	15, // 22: weknora.semantic.v1.Capabilities.limits:type_name -> weknora.semantic.v1.QueryLimits
	5,  // 23: weknora.semantic.v1.SemanticService.GetCapabilities:input_type -> weknora.semantic.v1.Empty
	10, // 24: weknora.semantic.v1.SemanticService.ApplyDocumentRevision:input_type -> weknora.semantic.v1.ApplyRequest
	7,  // 25: weknora.semantic.v1.SemanticService.DeleteDocument:input_type -> weknora.semantic.v1.DocumentRevision
	11, // 26: weknora.semantic.v1.SemanticService.GetOperation:input_type -> weknora.semantic.v1.OperationRef
	11, // 27: weknora.semantic.v1.SemanticService.CancelOperation:input_type -> weknora.semantic.v1.OperationRef
	16, // 28: weknora.semantic.v1.SemanticService.Search:input_type -> weknora.semantic.v1.SearchRequest
	19, // 29: weknora.semantic.v1.SemanticService.Reason:input_type -> weknora.semantic.v1.ReasonRequest
	21, // 30: weknora.semantic.v1.SemanticService.GetCapabilities:output_type -> weknora.semantic.v1.Capabilities
	12, // 31: weknora.semantic.v1.SemanticService.ApplyDocumentRevision:output_type -> weknora.semantic.v1.Operation
	12, // 32: weknora.semantic.v1.SemanticService.DeleteDocument:output_type -> weknora.semantic.v1.Operation
	12, // 33: weknora.semantic.v1.SemanticService.GetOperation:output_type -> weknora.semantic.v1.Operation
	12, // 34: weknora.semantic.v1.SemanticService.CancelOperation:output_type -> weknora.semantic.v1.Operation
	17, // 35: weknora.semantic.v1.SemanticService.Search:output_type -> weknora.semantic.v1.SearchResponse
	20, // 36: weknora.semantic.v1.SemanticService.Reason:output_type -> weknora.semantic.v1.ReasonResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_semantic_proto_init() }
func file_semantic_proto_init() {
	if File_semantic_proto != nil {
		return
	}
	file_semantic_proto_msgTypes[5].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[7].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[8].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[15].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_semantic_proto_rawDesc), len(file_semantic_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_semantic_proto_goTypes,
		DependencyIndexes: file_semantic_proto_depIdxs,
		EnumInfos:         file_semantic_proto_enumTypes,
		MessageInfos:      file_semantic_proto_msgTypes,
	}.Build()
	File_semantic_proto = out.File
	file_semantic_proto_goTypes = nil
	file_semantic_proto_depIdxs = nil
}
