// WeKnora Semantica wire contract - the ONLY schema shared between the Go
// business system and the Python semantic service (spec section 7).
//
// Tag discipline (C01): field numbers are immutable once released; deleted
// fields must be reserved, never renumbered. Optional scalars distinguish
// "absent" from zero values (spans, manifest_ref, timestamps, error codes).
// 64-bit integers stay uint64 on the wire; JSON public boundaries encode
// them as decimal strings.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: semantic.proto

package semanticpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation_State int32

const (
	Operation_OPERATION_STATE_UNSPECIFIED Operation_State = 0
	Operation_OPERATION_STATE_ACCEPTED    Operation_State = 1
	Operation_OPERATION_STATE_RUNNING     Operation_State = 2
	Operation_OPERATION_STATE_STAGED      Operation_State = 3
	Operation_OPERATION_STATE_PUBLISHING  Operation_State = 4
	Operation_OPERATION_STATE_SUCCEEDED   Operation_State = 5
	Operation_OPERATION_STATE_FAILED      Operation_State = 6
	Operation_OPERATION_STATE_CANCELLED   Operation_State = 7
	Operation_OPERATION_STATE_SUPERSEDED  Operation_State = 8
)

// Enum value maps for Operation_State.
var (
	Operation_State_name = map[int32]string{
		0: "OPERATION_STATE_UNSPECIFIED",
		1: "OPERATION_STATE_ACCEPTED",
		2: "OPERATION_STATE_RUNNING",
		3: "OPERATION_STATE_STAGED",
		4: "OPERATION_STATE_PUBLISHING",
		5: "OPERATION_STATE_SUCCEEDED",
		6: "OPERATION_STATE_FAILED",
		7: "OPERATION_STATE_CANCELLED",
		8: "OPERATION_STATE_SUPERSEDED",
	}
	Operation_State_value = map[string]int32{
		"OPERATION_STATE_UNSPECIFIED": 0,
		"OPERATION_STATE_ACCEPTED":    1,
		"OPERATION_STATE_RUNNING":     2,
		"OPERATION_STATE_STAGED":      3,
		"OPERATION_STATE_PUBLISHING":  4,
		"OPERATION_STATE_SUCCEEDED":   5,
		"OPERATION_STATE_FAILED":      6,
		"OPERATION_STATE_CANCELLED":   7,
		"OPERATION_STATE_SUPERSEDED":  8,
	}
)

func (x Operation_State) Enum() *Operation_State {
	p := new(Operation_State)
	*p = x
	return p
}

func (x Operation_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation_State) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[0].Descriptor()
}

func (Operation_State) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[0]
}

func (x Operation_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation_State.Descriptor instead.
func (Operation_State) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{6, 0}
}

type Assertion_Kind int32

const (
	Assertion_KIND_UNSPECIFIED Assertion_Kind = 0
	Assertion_KIND_SOURCE      Assertion_Kind = 1
	Assertion_KIND_RULE        Assertion_Kind = 2
	Assertion_KIND_MODEL       Assertion_Kind = 3
)

// Enum value maps for Assertion_Kind.
var (
	Assertion_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SOURCE",
		2: "KIND_RULE",
		3: "KIND_MODEL",
	}
	Assertion_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_SOURCE":      1,
		"KIND_RULE":        2,
		"KIND_MODEL":       3,
	}
)

func (x Assertion_Kind) Enum() *Assertion_Kind {
	p := new(Assertion_Kind)
	*p = x
	return p
}

func (x Assertion_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Assertion_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[1].Descriptor()
}

func (Assertion_Kind) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[1]
}

func (x Assertion_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Assertion_Kind.Descriptor instead.
func (Assertion_Kind) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{8, 0}
}

type AccessScope_Purpose int32

const (
	AccessScope_PURPOSE_UNSPECIFIED AccessScope_Purpose = 0
	AccessScope_PURPOSE_SEARCH      AccessScope_Purpose = 1
	AccessScope_PURPOSE_REASON      AccessScope_Purpose = 2
	AccessScope_PURPOSE_INDEX       AccessScope_Purpose = 3
)

// Enum value maps for AccessScope_Purpose.
var (
	AccessScope_Purpose_name = map[int32]string{
		0: "PURPOSE_UNSPECIFIED",
		1: "PURPOSE_SEARCH",
		2: "PURPOSE_REASON",
		3: "PURPOSE_INDEX",
	}
	AccessScope_Purpose_value = map[string]int32{
		"PURPOSE_UNSPECIFIED": 0,
		"PURPOSE_SEARCH":      1,
		"PURPOSE_REASON":      2,
		"PURPOSE_INDEX":       3,
	}
)

func (x AccessScope_Purpose) Enum() *AccessScope_Purpose {
	p := new(AccessScope_Purpose)
	*p = x
	return p
}

func (x AccessScope_Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessScope_Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[2].Descriptor()
}

func (AccessScope_Purpose) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[2]
}

func (x AccessScope_Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessScope_Purpose.Descriptor instead.
func (AccessScope_Purpose) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{9, 0}
}

type ReasonRequest_ReasoningMode int32

const (
	ReasonRequest_REASONING_MODE_UNSPECIFIED ReasonRequest_ReasoningMode = 0
	ReasonRequest_REASONING_MODE_RULES       ReasonRequest_ReasoningMode = 1
	ReasonRequest_REASONING_MODE_MODEL       ReasonRequest_ReasoningMode = 2
)

// Enum value maps for ReasonRequest_ReasoningMode.
var (
	ReasonRequest_ReasoningMode_name = map[int32]string{
		0: "REASONING_MODE_UNSPECIFIED",
		1: "REASONING_MODE_RULES",
		2: "REASONING_MODE_MODEL",
	}
	ReasonRequest_ReasoningMode_value = map[string]int32{
		"REASONING_MODE_UNSPECIFIED": 0,
		"REASONING_MODE_RULES":       1,
		"REASONING_MODE_MODEL":       2,
	}
)

func (x ReasonRequest_ReasoningMode) Enum() *ReasonRequest_ReasoningMode {
	p := new(ReasonRequest_ReasoningMode)
	*p = x
	return p
}

func (x ReasonRequest_ReasoningMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasonRequest_ReasoningMode) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[3].Descriptor()
}

func (ReasonRequest_ReasoningMode) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[3]
}

func (x ReasonRequest_ReasoningMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasonRequest_ReasoningMode.Descriptor instead.
func (ReasonRequest_ReasoningMode) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{13, 0}
}

type ReasonResponse_ConclusionKind int32

const (
	ReasonResponse_CONCLUSION_KIND_UNSPECIFIED ReasonResponse_ConclusionKind = 0
	ReasonResponse_CONCLUSION_KIND_RULE        ReasonResponse_ConclusionKind = 1
	ReasonResponse_CONCLUSION_KIND_MODEL       ReasonResponse_ConclusionKind = 2
)

// Enum value maps for ReasonResponse_ConclusionKind.
var (
	ReasonResponse_ConclusionKind_name = map[int32]string{
		0: "CONCLUSION_KIND_UNSPECIFIED",
		1: "CONCLUSION_KIND_RULE",
		2: "CONCLUSION_KIND_MODEL",
	}
	ReasonResponse_ConclusionKind_value = map[string]int32{
		"CONCLUSION_KIND_UNSPECIFIED": 0,
		"CONCLUSION_KIND_RULE":        1,
		"CONCLUSION_KIND_MODEL":       2,
	}
)

func (x ReasonResponse_ConclusionKind) Enum() *ReasonResponse_ConclusionKind {
	p := new(ReasonResponse_ConclusionKind)
	*p = x
	return p
}

func (x ReasonResponse_ConclusionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasonResponse_ConclusionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_proto_enumTypes[4].Descriptor()
}

func (ReasonResponse_ConclusionKind) Type() protoreflect.EnumType {
	return &file_semantic_proto_enumTypes[4]
}

func (x ReasonResponse_ConclusionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasonResponse_ConclusionKind.Descriptor instead.
func (ReasonResponse_ConclusionKind) EnumDescriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{14, 0}
}

type RequestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_semantic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeader) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestHeader) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ScopeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	KbId          string                 `protobuf:"bytes,2,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeKey) Reset() {
	*x = ScopeKey{}
	mi := &file_semantic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeKey) ProtoMessage() {}

func (x *ScopeKey) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeKey.ProtoReflect.Descriptor instead.
func (*ScopeKey) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{1}
}

func (x *ScopeKey) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ScopeKey) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

type DocumentRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeKey              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRevision) Reset() {
	*x = DocumentRevision{}
	mi := &file_semantic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRevision) ProtoMessage() {}

func (x *DocumentRevision) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRevision.ProtoReflect.Descriptor instead.
func (*DocumentRevision) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentRevision) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *DocumentRevision) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentRevision) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DocumentRevision) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *DocumentRevision) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ChunkSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSnapshot) Reset() {
	*x = ChunkSnapshot{}
	mi := &file_semantic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSnapshot) ProtoMessage() {}

func (x *ChunkSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSnapshot.ProtoReflect.Descriptor instead.
func (*ChunkSnapshot) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkSnapshot) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkSnapshot) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChunkSnapshot) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type IndexConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest    string                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	EngineVersion   string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	ModelProfileRef string                 `protobuf:"bytes,3,opt,name=model_profile_ref,json=modelProfileRef,proto3" json:"model_profile_ref,omitempty"`
	PromptVersion   string                 `protobuf:"bytes,4,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`
	RuleSetVersion  string                 `protobuf:"bytes,5,opt,name=rule_set_version,json=ruleSetVersion,proto3" json:"rule_set_version,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IndexConfig) Reset() {
	*x = IndexConfig{}
	mi := &file_semantic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexConfig) ProtoMessage() {}

func (x *IndexConfig) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexConfig.ProtoReflect.Descriptor instead.
func (*IndexConfig) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{4}
}

func (x *IndexConfig) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *IndexConfig) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *IndexConfig) GetModelProfileRef() string {
	if x != nil {
		return x.ModelProfileRef
	}
	return ""
}

func (x *IndexConfig) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

func (x *IndexConfig) GetRuleSetVersion() string {
	if x != nil {
		return x.RuleSetVersion
	}
	return ""
}

func (x *IndexConfig) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type ApplyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Document       *DocumentRevision      `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Chunks         []*ChunkSnapshot       `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	ManifestRef    *string                `protobuf:"bytes,3,opt,name=manifest_ref,json=manifestRef,proto3,oneof" json:"manifest_ref,omitempty"`
	Config         *IndexConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	PayloadHash    string                 `protobuf:"bytes,6,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_semantic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyRequest) GetDocument() *DocumentRevision {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ApplyRequest) GetChunks() []*ChunkSnapshot {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ApplyRequest) GetManifestRef() string {
	if x != nil && x.ManifestRef != nil {
		return *x.ManifestRef
	}
	return ""
}

func (x *ApplyRequest) GetConfig() *IndexConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ApplyRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ApplyRequest) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

type Operation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Scope            *ScopeKey              `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	DocumentId       string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Revision         uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	State            Operation_State        `protobuf:"varint,5,opt,name=state,proto3,enum=weknora.semantic.v1.Operation_State" json:"state,omitempty"`
	Stage            string                 `protobuf:"bytes,6,opt,name=stage,proto3" json:"stage,omitempty"`
	LeaseToken       uint64                 `protobuf:"varint,7,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	ResultGeneration *string                `protobuf:"bytes,8,opt,name=result_generation,json=resultGeneration,proto3,oneof" json:"result_generation,omitempty"`
	ErrorCode        *string                `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_semantic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{6}
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Operation) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Operation) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Operation) GetState() Operation_State {
	if x != nil {
		return x.State
	}
	return Operation_OPERATION_STATE_UNSPECIFIED
}

func (x *Operation) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Operation) GetLeaseToken() uint64 {
	if x != nil {
		return x.LeaseToken
	}
	return 0
}

func (x *Operation) GetResultGeneration() string {
	if x != nil && x.ResultGeneration != nil {
		return *x.ResultGeneration
	}
	return ""
}

func (x *Operation) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

type Evidence struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId  string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	DocumentId  string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Revision    uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	ChunkId     string                 `protobuf:"bytes,4,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ContentHash string                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Quote       string                 `protobuf:"bytes,6,opt,name=quote,proto3" json:"quote,omitempty"`
	StartChar   *uint32                `protobuf:"varint,7,opt,name=start_char,json=startChar,proto3,oneof" json:"start_char,omitempty"`
	EndChar     *uint32                `protobuf:"varint,8,opt,name=end_char,json=endChar,proto3,oneof" json:"end_char,omitempty"`
	// Q01: assertions this evidence item supports (source protocol).
	AssertionIds  []string `protobuf:"bytes,9,rep,name=assertion_ids,json=assertionIds,proto3" json:"assertion_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_semantic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{7}
}

func (x *Evidence) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *Evidence) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Evidence) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Evidence) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Evidence) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Evidence) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Evidence) GetStartChar() uint32 {
	if x != nil && x.StartChar != nil {
		return *x.StartChar
	}
	return 0
}

func (x *Evidence) GetEndChar() uint32 {
	if x != nil && x.EndChar != nil {
		return *x.EndChar
	}
	return 0
}

func (x *Evidence) GetAssertionIds() []string {
	if x != nil {
		return x.AssertionIds
	}
	return nil
}

type Assertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssertionId   string                 `protobuf:"bytes,1,opt,name=assertion_id,json=assertionId,proto3" json:"assertion_id,omitempty"`
	Scope         *ScopeKey              `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Predicate     string                 `protobuf:"bytes,4,opt,name=predicate,proto3" json:"predicate,omitempty"`
	ObjectId      *string                `protobuf:"bytes,5,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	Value         *string                `protobuf:"bytes,6,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Kind          Assertion_Kind         `protobuf:"varint,7,opt,name=kind,proto3,enum=weknora.semantic.v1.Assertion_Kind" json:"kind,omitempty"`
	EvidenceIds   []string               `protobuf:"bytes,8,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	PremiseIds    []string               `protobuf:"bytes,9,rep,name=premise_ids,json=premiseIds,proto3" json:"premise_ids,omitempty"`
	ValidFrom     *string                `protobuf:"bytes,10,opt,name=valid_from,json=validFrom,proto3,oneof" json:"valid_from,omitempty"`
	ValidUntil    *string                `protobuf:"bytes,11,opt,name=valid_until,json=validUntil,proto3,oneof" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_semantic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{8}
}

func (x *Assertion) GetAssertionId() string {
	if x != nil {
		return x.AssertionId
	}
	return ""
}

func (x *Assertion) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Assertion) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Assertion) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *Assertion) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *Assertion) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *Assertion) GetKind() Assertion_Kind {
	if x != nil {
		return x.Kind
	}
	return Assertion_KIND_UNSPECIFIED
}

func (x *Assertion) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

func (x *Assertion) GetPremiseIds() []string {
	if x != nil {
		return x.PremiseIds
	}
	return nil
}

func (x *Assertion) GetValidFrom() string {
	if x != nil && x.ValidFrom != nil {
		return *x.ValidFrom
	}
	return ""
}

func (x *Assertion) GetValidUntil() string {
	if x != nil && x.ValidUntil != nil {
		return *x.ValidUntil
	}
	return ""
}

type AccessScope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scope           *ScopeKey              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ScopeRef        string                 `protobuf:"bytes,3,opt,name=scope_ref,json=scopeRef,proto3" json:"scope_ref,omitempty"`
	ScopeHash       string                 `protobuf:"bytes,4,opt,name=scope_hash,json=scopeHash,proto3" json:"scope_hash,omitempty"`
	PermissionEpoch uint64                 `protobuf:"varint,5,opt,name=permission_epoch,json=permissionEpoch,proto3" json:"permission_epoch,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Audience        string                 `protobuf:"bytes,7,opt,name=audience,proto3" json:"audience,omitempty"`
	Purpose         AccessScope_Purpose    `protobuf:"varint,8,opt,name=purpose,proto3,enum=weknora.semantic.v1.AccessScope_Purpose" json:"purpose,omitempty"`
	BudgetRef       string                 `protobuf:"bytes,9,opt,name=budget_ref,json=budgetRef,proto3" json:"budget_ref,omitempty"`
	// Q01: the resolved allowed document set for this search. The business
	// side (Go) resolves the A01 scope snapshot and forwards it; the
	// service never expands the set on its own.
	AllowedDocumentIds []string `protobuf:"bytes,10,rep,name=allowed_document_ids,json=allowedDocumentIds,proto3" json:"allowed_document_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessScope) Reset() {
	*x = AccessScope{}
	mi := &file_semantic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessScope) ProtoMessage() {}

func (x *AccessScope) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessScope.ProtoReflect.Descriptor instead.
func (*AccessScope) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{9}
}

func (x *AccessScope) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AccessScope) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AccessScope) GetScopeRef() string {
	if x != nil {
		return x.ScopeRef
	}
	return ""
}

func (x *AccessScope) GetScopeHash() string {
	if x != nil {
		return x.ScopeHash
	}
	return ""
}

func (x *AccessScope) GetPermissionEpoch() uint64 {
	if x != nil {
		return x.PermissionEpoch
	}
	return 0
}

func (x *AccessScope) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AccessScope) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *AccessScope) GetPurpose() AccessScope_Purpose {
	if x != nil {
		return x.Purpose
	}
	return AccessScope_PURPOSE_UNSPECIFIED
}

func (x *AccessScope) GetBudgetRef() string {
	if x != nil {
		return x.BudgetRef
	}
	return ""
}

func (x *AccessScope) GetAllowedDocumentIds() []string {
	if x != nil {
		return x.AllowedDocumentIds
	}
	return nil
}

type QueryLimits struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MaxHops    uint32                 `protobuf:"varint,1,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	MaxNodes   uint32                 `protobuf:"varint,2,opt,name=max_nodes,json=maxNodes,proto3" json:"max_nodes,omitempty"`
	MaxEdges   uint32                 `protobuf:"varint,3,opt,name=max_edges,json=maxEdges,proto3" json:"max_edges,omitempty"`
	TopK       uint32                 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxTokens  uint32                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	DeadlineMs uint32                 `protobuf:"varint,6,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	// Q01 addition: appended AFTER the released fields - never renumber.
	MaxEvidence   uint32 `protobuf:"varint,7,opt,name=max_evidence,json=maxEvidence,proto3" json:"max_evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLimits) Reset() {
	*x = QueryLimits{}
	mi := &file_semantic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLimits) ProtoMessage() {}

func (x *QueryLimits) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLimits.ProtoReflect.Descriptor instead.
func (*QueryLimits) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{10}
}

func (x *QueryLimits) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *QueryLimits) GetMaxNodes() uint32 {
	if x != nil {
		return x.MaxNodes
	}
	return 0
}

func (x *QueryLimits) GetMaxEdges() uint32 {
	if x != nil {
		return x.MaxEdges
	}
	return 0
}

func (x *QueryLimits) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryLimits) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *QueryLimits) GetDeadlineMs() uint32 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *QueryLimits) GetMaxEvidence() uint32 {
	if x != nil {
		return x.MaxEvidence
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	QueryId       string                 `protobuf:"bytes,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	AccessScope   *AccessScope           `protobuf:"bytes,4,opt,name=access_scope,json=accessScope,proto3" json:"access_scope,omitempty"`
	Limits        *QueryLimits           `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_semantic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SearchRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetAccessScope() *AccessScope {
	if x != nil {
		return x.AccessScope
	}
	return nil
}

func (x *SearchRequest) GetLimits() *QueryLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SearchRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Generation    string                 `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	AssertionIds  []string               `protobuf:"bytes,5,rep,name=assertion_ids,json=assertionIds,proto3" json:"assertion_ids,omitempty"`
	Paths         []*SearchResponse_Path `protobuf:"bytes,6,rep,name=paths,proto3" json:"paths,omitempty"`
	Stale         bool                   `protobuf:"varint,7,opt,name=stale,proto3" json:"stale,omitempty"`
	Partial       bool                   `protobuf:"varint,8,opt,name=partial,proto3" json:"partial,omitempty"`
	Truncated     bool                   `protobuf:"varint,9,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_semantic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SearchResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *SearchResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SearchResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *SearchResponse) GetAssertionIds() []string {
	if x != nil {
		return x.AssertionIds
	}
	return nil
}

func (x *SearchResponse) GetPaths() []*SearchResponse_Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *SearchResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *SearchResponse) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *SearchResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// Header precedence: on ReasonRequest the OUTER header is authoritative;
// the nested search.header must stay unset (the mapping layer never sets
// both). Receivers that observe both MUST use the outer one and reject on
// conflicting values.
type ReasonRequest struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Header         *RequestHeader              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Search         *SearchRequest              `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	ReasoningMode  ReasonRequest_ReasoningMode `protobuf:"varint,3,opt,name=reasoning_mode,json=reasoningMode,proto3,enum=weknora.semantic.v1.ReasonRequest_ReasoningMode" json:"reasoning_mode,omitempty"`
	RuleSetVersion string                      `protobuf:"bytes,4,opt,name=rule_set_version,json=ruleSetVersion,proto3" json:"rule_set_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReasonRequest) Reset() {
	*x = ReasonRequest{}
	mi := &file_semantic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonRequest) ProtoMessage() {}

func (x *ReasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasonRequest.ProtoReflect.Descriptor instead.
func (*ReasonRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{13}
}

func (x *ReasonRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReasonRequest) GetSearch() *SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ReasonRequest) GetReasoningMode() ReasonRequest_ReasoningMode {
	if x != nil {
		return x.ReasoningMode
	}
	return ReasonRequest_REASONING_MODE_UNSPECIFIED
}

func (x *ReasonRequest) GetRuleSetVersion() string {
	if x != nil {
		return x.RuleSetVersion
	}
	return ""
}

type ReasonResponse struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Retrieval      *SearchResponse               `protobuf:"bytes,1,opt,name=retrieval,proto3" json:"retrieval,omitempty"`
	Status         string                        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Conclusion     string                        `protobuf:"bytes,3,opt,name=conclusion,proto3" json:"conclusion,omitempty"`
	ConclusionKind ReasonResponse_ConclusionKind `protobuf:"varint,4,opt,name=conclusion_kind,json=conclusionKind,proto3,enum=weknora.semantic.v1.ReasonResponse_ConclusionKind" json:"conclusion_kind,omitempty"`
	PremiseIds     []string                      `protobuf:"bytes,5,rep,name=premise_ids,json=premiseIds,proto3" json:"premise_ids,omitempty"`
	RuleIds        []string                      `protobuf:"bytes,6,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	ModelVersion   *string                       `protobuf:"bytes,7,opt,name=model_version,json=modelVersion,proto3,oneof" json:"model_version,omitempty"`
	PromptVersion  *string                       `protobuf:"bytes,8,opt,name=prompt_version,json=promptVersion,proto3,oneof" json:"prompt_version,omitempty"`
	Limitations    []string                      `protobuf:"bytes,9,rep,name=limitations,proto3" json:"limitations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReasonResponse) Reset() {
	*x = ReasonResponse{}
	mi := &file_semantic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonResponse) ProtoMessage() {}

func (x *ReasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasonResponse.ProtoReflect.Descriptor instead.
func (*ReasonResponse) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{14}
}

func (x *ReasonResponse) GetRetrieval() *SearchResponse {
	if x != nil {
		return x.Retrieval
	}
	return nil
}

func (x *ReasonResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReasonResponse) GetConclusion() string {
	if x != nil {
		return x.Conclusion
	}
	return ""
}

func (x *ReasonResponse) GetConclusionKind() ReasonResponse_ConclusionKind {
	if x != nil {
		return x.ConclusionKind
	}
	return ReasonResponse_CONCLUSION_KIND_UNSPECIFIED
}

func (x *ReasonResponse) GetPremiseIds() []string {
	if x != nil {
		return x.PremiseIds
	}
	return nil
}

func (x *ReasonResponse) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

func (x *ReasonResponse) GetModelVersion() string {
	if x != nil && x.ModelVersion != nil {
		return *x.ModelVersion
	}
	return ""
}

func (x *ReasonResponse) GetPromptVersion() string {
	if x != nil && x.PromptVersion != nil {
		return *x.PromptVersion
	}
	return ""
}

func (x *ReasonResponse) GetLimitations() []string {
	if x != nil {
		return x.Limitations
	}
	return nil
}

// Capability negotiation failure behavior (spec section 7): if
// GetCapabilities fails, times out, or reports an unsupported
// protocol_version, callers MUST treat EVERY mode as unavailable (fail
// closed) - never assume success. A mode with available=false carries the
// concrete unavailable_reason; callers must not work around it by widening
// scope or switching backends.
type Capability struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Available         bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	UnavailableReason string                 `protobuf:"bytes,3,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_semantic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{15}
}

func (x *Capability) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Capability) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Capability) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_semantic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{16}
}

func (x *GetCapabilitiesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetCapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EngineVersion   string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	Capabilities    []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	DefaultLimits   *QueryLimits           `protobuf:"bytes,4,opt,name=default_limits,json=defaultLimits,proto3" json:"default_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_semantic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{17}
}

func (x *GetCapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetDefaultLimits() *QueryLimits {
	if x != nil {
		return x.DefaultLimits
	}
	return nil
}

type ApplyDocumentRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Apply         *ApplyRequest          `protobuf:"bytes,2,opt,name=apply,proto3" json:"apply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDocumentRevisionRequest) Reset() {
	*x = ApplyDocumentRevisionRequest{}
	mi := &file_semantic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDocumentRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDocumentRevisionRequest) ProtoMessage() {}

func (x *ApplyDocumentRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDocumentRevisionRequest.ProtoReflect.Descriptor instead.
func (*ApplyDocumentRevisionRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{18}
}

func (x *ApplyDocumentRevisionRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ApplyDocumentRevisionRequest) GetApply() *ApplyRequest {
	if x != nil {
		return x.Apply
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Document      *DocumentRevision      `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_semantic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteDocumentRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteDocumentRequest) GetDocument() *DocumentRevision {
	if x != nil {
		return x.Document
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Scope         *ScopeKey              `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_semantic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{20}
}

func (x *GetOperationRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetOperationRequest) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Scope         *ScopeKey              `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_semantic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{21}
}

func (x *CancelOperationRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelOperationRequest) GetScope() *ScopeKey {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CancelOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type SearchResponse_Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Path) Reset() {
	*x = SearchResponse_Path{}
	mi := &file_semantic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Path) ProtoMessage() {}

func (x *SearchResponse_Path) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Path.ProtoReflect.Descriptor instead.
func (*SearchResponse_Path) Descriptor() ([]byte, []int) {
	return file_semantic_proto_rawDescGZIP(), []int{12, 0}
}

func (x *SearchResponse_Path) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_semantic_proto protoreflect.FileDescriptor

const file_semantic_proto_rawDesc = "" +
	"\n" +
	"\x0esemantic.proto\x12\x13weknora.semantic.v1\"I\n" +
	"\rRequestHeader\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"<\n" +
	"\bScopeKey\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x13\n" +
	"\x05kb_id\x18\x02 \x01(\tR\x04kbId\"\xc1\x01\n" +
	"\x10DocumentRevision\x123\n" +
	"\x05scope\x18\x01 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\"a\n" +
	"\rChunkSnapshot\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\"\xfd\x01\n" +
	"\vIndexConfig\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\tR\fconfigDigest\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\x12*\n" +
	"\x11model_profile_ref\x18\x03 \x01(\tR\x0fmodelProfileRef\x12%\n" +
	"\x0eprompt_version\x18\x04 \x01(\tR\rpromptVersion\x12(\n" +
	"\x10rule_set_version\x18\x05 \x01(\tR\x0eruleSetVersion\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\"\xcc\x02\n" +
	"\fApplyRequest\x12A\n" +
	"\bdocument\x18\x01 \x01(\v2%.weknora.semantic.v1.DocumentRevisionR\bdocument\x12:\n" +
	"\x06chunks\x18\x02 \x03(\v2\".weknora.semantic.v1.ChunkSnapshotR\x06chunks\x12&\n" +
	"\fmanifest_ref\x18\x03 \x01(\tH\x00R\vmanifestRef\x88\x01\x01\x128\n" +
	"\x06config\x18\x04 \x01(\v2 .weknora.semantic.v1.IndexConfigR\x06config\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\fpayload_hash\x18\x06 \x01(\tR\vpayloadHashB\x0f\n" +
	"\r_manifest_ref\"\xaa\x05\n" +
	"\tOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x123\n" +
	"\x05scope\x18\x02 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12:\n" +
	"\x05state\x18\x05 \x01(\x0e2$.weknora.semantic.v1.Operation.StateR\x05state\x12\x14\n" +
	"\x05stage\x18\x06 \x01(\tR\x05stage\x12\x1f\n" +
	"\vlease_token\x18\a \x01(\x04R\n" +
	"leaseToken\x120\n" +
	"\x11result_generation\x18\b \x01(\tH\x00R\x10resultGeneration\x88\x01\x01\x12\"\n" +
	"\n" +
	"error_code\x18\t \x01(\tH\x01R\terrorCode\x88\x01\x01\"\x99\x02\n" +
	"\x05State\x12\x1f\n" +
	"\x1bOPERATION_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATE_ACCEPTED\x10\x01\x12\x1b\n" +
	"\x17OPERATION_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16OPERATION_STATE_STAGED\x10\x03\x12\x1e\n" +
	"\x1aOPERATION_STATE_PUBLISHING\x10\x04\x12\x1d\n" +
	"\x19OPERATION_STATE_SUCCEEDED\x10\x05\x12\x1a\n" +
	"\x16OPERATION_STATE_FAILED\x10\x06\x12\x1d\n" +
	"\x19OPERATION_STATE_CANCELLED\x10\a\x12\x1e\n" +
	"\x1aOPERATION_STATE_SUPERSEDED\x10\bB\x14\n" +
	"\x12_result_generationB\r\n" +
	"\v_error_code\"\xc1\x02\n" +
	"\bEvidence\x12\x1f\n" +
	"\vevidence_id\x18\x01 \x01(\tR\n" +
	"evidenceId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x19\n" +
	"\bchunk_id\x18\x04 \x01(\tR\achunkId\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12\x14\n" +
	"\x05quote\x18\x06 \x01(\tR\x05quote\x12\"\n" +
	"\n" +
	"start_char\x18\a \x01(\rH\x00R\tstartChar\x88\x01\x01\x12\x1e\n" +
	"\bend_char\x18\b \x01(\rH\x01R\aendChar\x88\x01\x01\x12#\n" +
	"\rassertion_ids\x18\t \x03(\tR\fassertionIdsB\r\n" +
	"\v_start_charB\v\n" +
	"\t_end_char\"\xa9\x04\n" +
	"\tAssertion\x12!\n" +
	"\fassertion_id\x18\x01 \x01(\tR\vassertionId\x123\n" +
	"\x05scope\x18\x02 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1c\n" +
	"\tpredicate\x18\x04 \x01(\tR\tpredicate\x12 \n" +
	"\tobject_id\x18\x05 \x01(\tH\x00R\bobjectId\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x06 \x01(\tH\x01R\x05value\x88\x01\x01\x127\n" +
	"\x04kind\x18\a \x01(\x0e2#.weknora.semantic.v1.Assertion.KindR\x04kind\x12!\n" +
	"\fevidence_ids\x18\b \x03(\tR\vevidenceIds\x12\x1f\n" +
	"\vpremise_ids\x18\t \x03(\tR\n" +
	"premiseIds\x12\"\n" +
	"\n" +
	"valid_from\x18\n" +
	" \x01(\tH\x02R\tvalidFrom\x88\x01\x01\x12$\n" +
	"\vvalid_until\x18\v \x01(\tH\x03R\n" +
	"validUntil\x88\x01\x01\"L\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vKIND_SOURCE\x10\x01\x12\r\n" +
	"\tKIND_RULE\x10\x02\x12\x0e\n" +
	"\n" +
	"KIND_MODEL\x10\x03B\f\n" +
	"\n" +
	"_object_idB\b\n" +
	"\x06_valueB\r\n" +
	"\v_valid_fromB\x0e\n" +
	"\f_valid_until\"\xf7\x03\n" +
	"\vAccessScope\x123\n" +
	"\x05scope\x18\x01 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1b\n" +
	"\tscope_ref\x18\x03 \x01(\tR\bscopeRef\x12\x1d\n" +
	"\n" +
	"scope_hash\x18\x04 \x01(\tR\tscopeHash\x12)\n" +
	"\x10permission_epoch\x18\x05 \x01(\x04R\x0fpermissionEpoch\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12\x1a\n" +
	"\baudience\x18\a \x01(\tR\baudience\x12B\n" +
	"\apurpose\x18\b \x01(\x0e2(.weknora.semantic.v1.AccessScope.PurposeR\apurpose\x12\x1d\n" +
	"\n" +
	"budget_ref\x18\t \x01(\tR\tbudgetRef\x120\n" +
	"\x14allowed_document_ids\x18\n" +
	" \x03(\tR\x12allowedDocumentIds\"]\n" +
	"\aPurpose\x12\x17\n" +
	"\x13PURPOSE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePURPOSE_SEARCH\x10\x01\x12\x12\n" +
	"\x0ePURPOSE_REASON\x10\x02\x12\x11\n" +
	"\rPURPOSE_INDEX\x10\x03\"\xda\x01\n" +
	"\vQueryLimits\x12\x19\n" +
	"\bmax_hops\x18\x01 \x01(\rR\amaxHops\x12\x1b\n" +
	"\tmax_nodes\x18\x02 \x01(\rR\bmaxNodes\x12\x1b\n" +
	"\tmax_edges\x18\x03 \x01(\rR\bmaxEdges\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\rR\x04topK\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\rR\tmaxTokens\x12\x1f\n" +
	"\vdeadline_ms\x18\x06 \x01(\rR\n" +
	"deadlineMs\x12!\n" +
	"\fmax_evidence\x18\a \x01(\rR\vmaxEvidence\"\x8f\x02\n" +
	"\rSearchRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".weknora.semantic.v1.RequestHeaderR\x06header\x12\x19\n" +
	"\bquery_id\x18\x02 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12C\n" +
	"\faccess_scope\x18\x04 \x01(\v2 .weknora.semantic.v1.AccessScopeR\vaccessScope\x128\n" +
	"\x06limits\x18\x05 \x01(\v2 .weknora.semantic.v1.QueryLimitsR\x06limits\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\"\xeb\x02\n" +
	"\x0eSearchResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\tR\n" +
	"generation\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x129\n" +
	"\bevidence\x18\x04 \x03(\v2\x1d.weknora.semantic.v1.EvidenceR\bevidence\x12#\n" +
	"\rassertion_ids\x18\x05 \x03(\tR\fassertionIds\x12>\n" +
	"\x05paths\x18\x06 \x03(\v2(.weknora.semantic.v1.SearchResponse.PathR\x05paths\x12\x14\n" +
	"\x05stale\x18\a \x01(\bR\x05stale\x12\x18\n" +
	"\apartial\x18\b \x01(\bR\apartial\x12\x1c\n" +
	"\ttruncated\x18\t \x01(\bR\ttruncated\x1a\x1c\n" +
	"\x04Path\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\"\xef\x02\n" +
	"\rReasonRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".weknora.semantic.v1.RequestHeaderR\x06header\x12:\n" +
	"\x06search\x18\x02 \x01(\v2\".weknora.semantic.v1.SearchRequestR\x06search\x12W\n" +
	"\x0ereasoning_mode\x18\x03 \x01(\x0e20.weknora.semantic.v1.ReasonRequest.ReasoningModeR\rreasoningMode\x12(\n" +
	"\x10rule_set_version\x18\x04 \x01(\tR\x0eruleSetVersion\"c\n" +
	"\rReasoningMode\x12\x1e\n" +
	"\x1aREASONING_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REASONING_MODE_RULES\x10\x01\x12\x18\n" +
	"\x14REASONING_MODE_MODEL\x10\x02\"\xa9\x04\n" +
	"\x0eReasonResponse\x12A\n" +
	"\tretrieval\x18\x01 \x01(\v2#.weknora.semantic.v1.SearchResponseR\tretrieval\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"conclusion\x18\x03 \x01(\tR\n" +
	"conclusion\x12[\n" +
	"\x0fconclusion_kind\x18\x04 \x01(\x0e22.weknora.semantic.v1.ReasonResponse.ConclusionKindR\x0econclusionKind\x12\x1f\n" +
	"\vpremise_ids\x18\x05 \x03(\tR\n" +
	"premiseIds\x12\x19\n" +
	"\brule_ids\x18\x06 \x03(\tR\aruleIds\x12(\n" +
	"\rmodel_version\x18\a \x01(\tH\x00R\fmodelVersion\x88\x01\x01\x12*\n" +
	"\x0eprompt_version\x18\b \x01(\tH\x01R\rpromptVersion\x88\x01\x01\x12 \n" +
	"\vlimitations\x18\t \x03(\tR\vlimitations\"f\n" +
	"\x0eConclusionKind\x12\x1f\n" +
	"\x1bCONCLUSION_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CONCLUSION_KIND_RULE\x10\x01\x12\x19\n" +
	"\x15CONCLUSION_KIND_MODEL\x10\x02B\x10\n" +
	"\x0e_model_versionB\x11\n" +
	"\x0f_prompt_version\"m\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12-\n" +
	"\x12unavailable_reason\x18\x03 \x01(\tR\x11unavailableReason\"T\n" +
	"\x16GetCapabilitiesRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".weknora.semantic.v1.RequestHeaderR\x06header\"\xf9\x01\n" +
	"\x17GetCapabilitiesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\x12C\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1f.weknora.semantic.v1.CapabilityR\fcapabilities\x12G\n" +
	"\x0edefault_limits\x18\x04 \x01(\v2 .weknora.semantic.v1.QueryLimitsR\rdefaultLimits\"\x93\x01\n" +
	"\x1cApplyDocumentRevisionRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".weknora.semantic.v1.RequestHeaderR\x06header\x127\n" +
	"\x05apply\x18\x02 \x01(\v2!.weknora.semantic.v1.ApplyRequestR\x05apply\"\x96\x01\n" +
	"\x15DeleteDocumentRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".weknora.semantic.v1.RequestHeaderR\x06header\x12A\n" +
	"\bdocument\x18\x02 \x01(\v2%.weknora.semantic.v1.DocumentRevisionR\bdocument\"\xa9\x01\n" +
	"\x13GetOperationRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".weknora.semantic.v1.RequestHeaderR\x06header\x123\n" +
	"\x05scope\x18\x02 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\"\xac\x01\n" +
	"\x16CancelOperationRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2\".weknora.semantic.v1.RequestHeaderR\x06header\x123\n" +
	"\x05scope\x18\x02 \x01(\v2\x1d.weknora.semantic.v1.ScopeKeyR\x05scope\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId2\xa2\x05\n" +
	"\bSemantic\x12l\n" +
	"\x0fGetCapabilities\x12+.weknora.semantic.v1.GetCapabilitiesRequest\x1a,.weknora.semantic.v1.GetCapabilitiesResponse\x12j\n" +
	"\x15ApplyDocumentRevision\x121.weknora.semantic.v1.ApplyDocumentRevisionRequest\x1a\x1e.weknora.semantic.v1.Operation\x12\\\n" +
	"\x0eDeleteDocument\x12*.weknora.semantic.v1.DeleteDocumentRequest\x1a\x1e.weknora.semantic.v1.Operation\x12X\n" +
	"\fGetOperation\x12(.weknora.semantic.v1.GetOperationRequest\x1a\x1e.weknora.semantic.v1.Operation\x12^\n" +
	"\x0fCancelOperation\x12+.weknora.semantic.v1.CancelOperationRequest\x1a\x1e.weknora.semantic.v1.Operation\x12Q\n" +
	"\x06Search\x12\".weknora.semantic.v1.SearchRequest\x1a#.weknora.semantic.v1.SearchResponse\x12Q\n" +
	"\x06Reason\x12\".weknora.semantic.v1.ReasonRequest\x1a#.weknora.semantic.v1.ReasonResponseB6Z4github.com/Tencent/WeKnora/semantic/proto;semanticpbb\x06proto3"

var (
	file_semantic_proto_rawDescOnce sync.Once
	file_semantic_proto_rawDescData []byte
)

func file_semantic_proto_rawDescGZIP() []byte {
	file_semantic_proto_rawDescOnce.Do(func() {
		file_semantic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_semantic_proto_rawDesc), len(file_semantic_proto_rawDesc)))
	})
	return file_semantic_proto_rawDescData
}

var file_semantic_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_semantic_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_semantic_proto_goTypes = []any{
	(Operation_State)(0),                 // 0: weknora.semantic.v1.Operation.State
	(Assertion_Kind)(0),                  // 1: weknora.semantic.v1.Assertion.Kind
	(AccessScope_Purpose)(0),             // 2: weknora.semantic.v1.AccessScope.Purpose
	(ReasonRequest_ReasoningMode)(0),     // 3: weknora.semantic.v1.ReasonRequest.ReasoningMode
	(ReasonResponse_ConclusionKind)(0),   // 4: weknora.semantic.v1.ReasonResponse.ConclusionKind
	(*RequestHeader)(nil),                // 5: weknora.semantic.v1.RequestHeader
	(*ScopeKey)(nil),                     // 6: weknora.semantic.v1.ScopeKey
	(*DocumentRevision)(nil),             // 7: weknora.semantic.v1.DocumentRevision
	(*ChunkSnapshot)(nil),                // 8: weknora.semantic.v1.ChunkSnapshot
	(*IndexConfig)(nil),                  // 9: weknora.semantic.v1.IndexConfig
	(*ApplyRequest)(nil),                 // 10: weknora.semantic.v1.ApplyRequest
	(*Operation)(nil),                    // 11: weknora.semantic.v1.Operation
	(*Evidence)(nil),                     // 12: weknora.semantic.v1.Evidence
	(*Assertion)(nil),                    // 13: weknora.semantic.v1.Assertion
	(*AccessScope)(nil),                  // 14: weknora.semantic.v1.AccessScope
	(*QueryLimits)(nil),                  // 15: weknora.semantic.v1.QueryLimits
	(*SearchRequest)(nil),                // 16: weknora.semantic.v1.SearchRequest
	(*SearchResponse)(nil),               // 17: weknora.semantic.v1.SearchResponse
	(*ReasonRequest)(nil),                // 18: weknora.semantic.v1.ReasonRequest
	(*ReasonResponse)(nil),               // 19: weknora.semantic.v1.ReasonResponse
	(*Capability)(nil),                   // 20: weknora.semantic.v1.Capability
	(*GetCapabilitiesRequest)(nil),       // 21: weknora.semantic.v1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),      // 22: weknora.semantic.v1.GetCapabilitiesResponse
	(*ApplyDocumentRevisionRequest)(nil), // 23: weknora.semantic.v1.ApplyDocumentRevisionRequest
	(*DeleteDocumentRequest)(nil),        // 24: weknora.semantic.v1.DeleteDocumentRequest
	(*GetOperationRequest)(nil),          // 25: weknora.semantic.v1.GetOperationRequest
	(*CancelOperationRequest)(nil),       // 26: weknora.semantic.v1.CancelOperationRequest
	(*SearchResponse_Path)(nil),          // 27: weknora.semantic.v1.SearchResponse.Path
}
var file_semantic_proto_depIdxs = []int32{
	6,  // 0: weknora.semantic.v1.DocumentRevision.scope:type_name -> weknora.semantic.v1.ScopeKey
	7,  // 1: weknora.semantic.v1.ApplyRequest.document:type_name -> weknora.semantic.v1.DocumentRevision
	8,  // 2: weknora.semantic.v1.ApplyRequest.chunks:type_name -> weknora.semantic.v1.ChunkSnapshot
	9,  // 3: weknora.semantic.v1.ApplyRequest.config:type_name -> weknora.semantic.v1.IndexConfig
	6,  // 4: weknora.semantic.v1.Operation.scope:type_name -> weknora.semantic.v1.ScopeKey
	0,  // 5: weknora.semantic.v1.Operation.state:type_name -> weknora.semantic.v1.Operation.State
	6,  // 6: weknora.semantic.v1.Assertion.scope:type_name -> weknora.semantic.v1.ScopeKey
	1,  // 7: weknora.semantic.v1.Assertion.kind:type_name -> weknora.semantic.v1.Assertion.Kind
	6,  // 8: weknora.semantic.v1.AccessScope.scope:type_name -> weknora.semantic.v1.ScopeKey
	2,  // 9: weknora.semantic.v1.AccessScope.purpose:type_name -> weknora.semantic.v1.AccessScope.Purpose
	5,  // 10: weknora.semantic.v1.SearchRequest.header:type_name -> weknora.semantic.v1.RequestHeader
	14, // 11: weknora.semantic.v1.SearchRequest.access_scope:type_name -> weknora.semantic.v1.AccessScope
	15, // 12: weknora.semantic.v1.SearchRequest.limits:type_name -> weknora.semantic.v1.QueryLimits
	12, // 13: weknora.semantic.v1.SearchResponse.evidence:type_name -> weknora.semantic.v1.Evidence
	27, // 14: weknora.semantic.v1.SearchResponse.paths:type_name -> weknora.semantic.v1.SearchResponse.Path
	5,  // 15: weknora.semantic.v1.ReasonRequest.header:type_name -> weknora.semantic.v1.RequestHeader
	16, // 16: weknora.semantic.v1.ReasonRequest.search:type_name -> weknora.semantic.v1.SearchRequest
	3,  // 17: weknora.semantic.v1.ReasonRequest.reasoning_mode:type_name -> weknora.semantic.v1.ReasonRequest.ReasoningMode
	17, // 18: weknora.semantic.v1.ReasonResponse.retrieval:type_name -> weknora.semantic.v1.SearchResponse
	4,  // 19: weknora.semantic.v1.ReasonResponse.conclusion_kind:type_name -> weknora.semantic.v1.ReasonResponse.ConclusionKind
	5,  // 20: weknora.semantic.v1.GetCapabilitiesRequest.header:type_name -> weknora.semantic.v1.RequestHeader
	20, // 21: weknora.semantic.v1.GetCapabilitiesResponse.capabilities:type_name -> weknora.semantic.v1.Capability
	15, // 22: weknora.semantic.v1.GetCapabilitiesResponse.default_limits:type_name -> weknora.semantic.v1.QueryLimits
	5,  // 23: weknora.semantic.v1.ApplyDocumentRevisionRequest.header:type_name -> weknora.semantic.v1.RequestHeader
	10, // 24: weknora.semantic.v1.ApplyDocumentRevisionRequest.apply:type_name -> weknora.semantic.v1.ApplyRequest
	5,  // 25: weknora.semantic.v1.DeleteDocumentRequest.header:type_name -> weknora.semantic.v1.RequestHeader
	7,  // 26: weknora.semantic.v1.DeleteDocumentRequest.document:type_name -> weknora.semantic.v1.DocumentRevision
	5,  // 27: weknora.semantic.v1.GetOperationRequest.header:type_name -> weknora.semantic.v1.RequestHeader
	6,  // 28: weknora.semantic.v1.GetOperationRequest.scope:type_name -> weknora.semantic.v1.ScopeKey
	5,  // 29: weknora.semantic.v1.CancelOperationRequest.header:type_name -> weknora.semantic.v1.RequestHeader
	6,  // 30: weknora.semantic.v1.CancelOperationRequest.scope:type_name -> weknora.semantic.v1.ScopeKey
	21, // 31: weknora.semantic.v1.Semantic.GetCapabilities:input_type -> weknora.semantic.v1.GetCapabilitiesRequest
	23, // 32: weknora.semantic.v1.Semantic.ApplyDocumentRevision:input_type -> weknora.semantic.v1.ApplyDocumentRevisionRequest
	24, // 33: weknora.semantic.v1.Semantic.DeleteDocument:input_type -> weknora.semantic.v1.DeleteDocumentRequest
	25, // 34: weknora.semantic.v1.Semantic.GetOperation:input_type -> weknora.semantic.v1.GetOperationRequest
	26, // 35: weknora.semantic.v1.Semantic.CancelOperation:input_type -> weknora.semantic.v1.CancelOperationRequest
	16, // 36: weknora.semantic.v1.Semantic.Search:input_type -> weknora.semantic.v1.SearchRequest
	18, // 37: weknora.semantic.v1.Semantic.Reason:input_type -> weknora.semantic.v1.ReasonRequest
	22, // 38: weknora.semantic.v1.Semantic.GetCapabilities:output_type -> weknora.semantic.v1.GetCapabilitiesResponse
	11, // 39: weknora.semantic.v1.Semantic.ApplyDocumentRevision:output_type -> weknora.semantic.v1.Operation
	11, // 40: weknora.semantic.v1.Semantic.DeleteDocument:output_type -> weknora.semantic.v1.Operation
	11, // 41: weknora.semantic.v1.Semantic.GetOperation:output_type -> weknora.semantic.v1.Operation
	11, // 42: weknora.semantic.v1.Semantic.CancelOperation:output_type -> weknora.semantic.v1.Operation
	17, // 43: weknora.semantic.v1.Semantic.Search:output_type -> weknora.semantic.v1.SearchResponse
	19, // 44: weknora.semantic.v1.Semantic.Reason:output_type -> weknora.semantic.v1.ReasonResponse
	38, // [38:45] is the sub-list for method output_type
	31, // [31:38] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_semantic_proto_init() }
func file_semantic_proto_init() {
	if File_semantic_proto != nil {
		return
	}
	file_semantic_proto_msgTypes[5].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[6].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[7].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[8].OneofWrappers = []any{}
	file_semantic_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_semantic_proto_rawDesc), len(file_semantic_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_semantic_proto_goTypes,
		DependencyIndexes: file_semantic_proto_depIdxs,
		EnumInfos:         file_semantic_proto_enumTypes,
		MessageInfos:      file_semantic_proto_msgTypes,
	}.Build()
	File_semantic_proto = out.File
	file_semantic_proto_goTypes = nil
	file_semantic_proto_depIdxs = nil
}
