// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: semantic.proto

package semanticpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticService_GetCapabilities_FullMethodName       = "/weknora.semantic.v1.SemanticService/GetCapabilities"
	SemanticService_ApplyDocumentRevision_FullMethodName = "/weknora.semantic.v1.SemanticService/ApplyDocumentRevision"
	SemanticService_DeleteDocument_FullMethodName        = "/weknora.semantic.v1.SemanticService/DeleteDocument"
	SemanticService_GetOperation_FullMethodName          = "/weknora.semantic.v1.SemanticService/GetOperation"
	SemanticService_CancelOperation_FullMethodName       = "/weknora.semantic.v1.SemanticService/CancelOperation"
	SemanticService_Search_FullMethodName                = "/weknora.semantic.v1.SemanticService/Search"
	SemanticService_Reason_FullMethodName                = "/weknora.semantic.v1.SemanticService/Reason"
)

// SemanticServiceClient is the client API for SemanticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemanticServiceClient interface {
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
	ApplyDocumentRevision(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Operation, error)
	DeleteDocument(ctx context.Context, in *DocumentRevision, opts ...grpc.CallOption) (*Operation, error)
	GetOperation(ctx context.Context, in *OperationRef, opts ...grpc.CallOption) (*Operation, error)
	CancelOperation(ctx context.Context, in *OperationRef, opts ...grpc.CallOption) (*Operation, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*ReasonResponse, error)
}

type semanticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticServiceClient(cc grpc.ClientConnInterface) SemanticServiceClient {
	return &semanticServiceClient{cc}
}

func (c *semanticServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, SemanticService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticServiceClient) ApplyDocumentRevision(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, SemanticService_ApplyDocumentRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticServiceClient) DeleteDocument(ctx context.Context, in *DocumentRevision, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, SemanticService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticServiceClient) GetOperation(ctx context.Context, in *OperationRef, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, SemanticService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticServiceClient) CancelOperation(ctx context.Context, in *OperationRef, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, SemanticService_CancelOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SemanticService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticServiceClient) Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*ReasonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReasonResponse)
	err := c.cc.Invoke(ctx, SemanticService_Reason_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticServiceServer is the server API for SemanticService service.
// All implementations must embed UnimplementedSemanticServiceServer
// for forward compatibility.
type SemanticServiceServer interface {
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	ApplyDocumentRevision(context.Context, *ApplyRequest) (*Operation, error)
	DeleteDocument(context.Context, *DocumentRevision) (*Operation, error)
	GetOperation(context.Context, *OperationRef) (*Operation, error)
	CancelOperation(context.Context, *OperationRef) (*Operation, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Reason(context.Context, *ReasonRequest) (*ReasonResponse, error)
	mustEmbedUnimplementedSemanticServiceServer()
}

// UnimplementedSemanticServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticServiceServer struct{}

func (UnimplementedSemanticServiceServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedSemanticServiceServer) ApplyDocumentRevision(context.Context, *ApplyRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDocumentRevision not implemented")
}
func (UnimplementedSemanticServiceServer) DeleteDocument(context.Context, *DocumentRevision) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedSemanticServiceServer) GetOperation(context.Context, *OperationRef) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedSemanticServiceServer) CancelOperation(context.Context, *OperationRef) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOperation not implemented")
}
func (UnimplementedSemanticServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSemanticServiceServer) Reason(context.Context, *ReasonRequest) (*ReasonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reason not implemented")
}
func (UnimplementedSemanticServiceServer) mustEmbedUnimplementedSemanticServiceServer() {}
func (UnimplementedSemanticServiceServer) testEmbeddedByValue()                         {}

// UnsafeSemanticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticServiceServer will
// result in compilation errors.
type UnsafeSemanticServiceServer interface {
	mustEmbedUnimplementedSemanticServiceServer()
}

func RegisterSemanticServiceServer(s grpc.ServiceRegistrar, srv SemanticServiceServer) {
	// If the following call pancis, it indicates UnimplementedSemanticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticService_ServiceDesc, srv)
}

func _SemanticService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticService_ApplyDocumentRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServiceServer).ApplyDocumentRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticService_ApplyDocumentRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServiceServer).ApplyDocumentRevision(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentRevision)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServiceServer).DeleteDocument(ctx, req.(*DocumentRevision))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServiceServer).GetOperation(ctx, req.(*OperationRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticService_CancelOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServiceServer).CancelOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticService_CancelOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServiceServer).CancelOperation(ctx, req.(*OperationRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticService_Reason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReasonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticServiceServer).Reason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticService_Reason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticServiceServer).Reason(ctx, req.(*ReasonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticService_ServiceDesc is the grpc.ServiceDesc for SemanticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.semantic.v1.SemanticService",
	HandlerType: (*SemanticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _SemanticService_GetCapabilities_Handler,
		},
		{
			MethodName: "ApplyDocumentRevision",
			Handler:    _SemanticService_ApplyDocumentRevision_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _SemanticService_DeleteDocument_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _SemanticService_GetOperation_Handler,
		},
		{
			MethodName: "CancelOperation",
			Handler:    _SemanticService_CancelOperation_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _SemanticService_Search_Handler,
		},
		{
			MethodName: "Reason",
			Handler:    _SemanticService_Reason_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic.proto",
}
