#!/usr/bin/env bash
# Operator lifecycle for the pinned local Lago Community v1.53.0 stack.
#
# Usage: ./deploy/lago/lago.sh init|up|down|status|config|contract-probe|backup|restore
#
#   init           generate deploy/lago/.env with random secrets (mode 600)
#   up             validate secrets, then docker compose up -d --wait
#   down           stop the stack (named data volumes are preserved)
#   status         print the Task 1 health snapshot JSON
#   config         print the resolved Compose config with secrets redacted
#   contract-probe run the real Customer create/delete contract probe (API key comes from the caller environment)
#   backup         dump the authority (pg_dump -Fc), object storage (tar) and
#                  pending work (redis RDB) into deploy/lago/backups/<utcstamp>
#   restore        destroy the stack data volumes and reinstate a backup (#104)

set -euo pipefail

LAGO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$LAGO_DIR/.env"

# Official Lago sample defaults that generated secrets must never equal.
readonly SAMPLE_POSTGRES_PASSWORD="changeme"
readonly SAMPLE_SECRET_KEY_BASE="your-secret-key-base-hex-64"
readonly SAMPLE_ENCRYPTION_PRIMARY_KEY="your-encryption-primary-key"
readonly SAMPLE_ENCRYPTION_DETERMINISTIC_KEY="your-encryption-deterministic-key"
readonly SAMPLE_ENCRYPTION_KEY_DERIVATION_SALT="your-encryption-derivation-salt"

die() {
  echo "lago.sh: $*" >&2
  exit 1
}

usage() {
  sed -n '2,14p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 2
}

compose() {
  (cd "$LAGO_DIR" && docker compose "$@")
}

env_value() {
  local key="$1" file="${2:-$ENV_FILE}" line
  line="$(grep -E "^${key}=" "$file" | tail -n 1 || true)"
  line="${line#*=}"
  line="${line#\"}"
  printf '%s' "${line%\"}"
}

check_port_url_consistency() {
  # The frontend's browser-side API URL is baked from the ports at init time;
  # reject an .env where a port was changed without updating its URL.
  local env_file="${1:-$ENV_FILE}"
  local name port url url_port
  for name in LAGO_API LAGO_FRONT; do
    port="$(env_value "${name}_PORT" "$env_file")"
    url="$(env_value "${name}_URL" "$env_file")"
    [[ -n "$port" && -n "$url" ]] || continue
    url_port="${url##*:}"
    if [[ "$url_port" != "$port" ]]; then
      die "${name}_URL '${url}' does not point at the configured ${name}_PORT '${port}' -- fix .env or delete it and re-run ./deploy/lago/lago.sh init"
    fi
  done
}

ensure_env() {
  [[ -f "$ENV_FILE" ]] || die "missing $ENV_FILE -- run ./deploy/lago/lago.sh init first"
}

check_secret_differs() {
  local key="$1" sample="$2" value
  value="$(env_value "$key")"
  [[ -n "$value" ]] || die "$key is empty -- run ./deploy/lago/lago.sh init"
  [[ "$value" != "$sample" ]] || die "$key still equals the official Lago sample default -- run ./deploy/lago/lago.sh init"
}

check_secrets() {
  ensure_env
  check_secret_differs POSTGRES_PASSWORD "$SAMPLE_POSTGRES_PASSWORD"
  check_secret_differs SECRET_KEY_BASE "$SAMPLE_SECRET_KEY_BASE"
  check_secret_differs LAGO_ENCRYPTION_PRIMARY_KEY "$SAMPLE_ENCRYPTION_PRIMARY_KEY"
  check_secret_differs LAGO_ENCRYPTION_DETERMINISTIC_KEY "$SAMPLE_ENCRYPTION_DETERMINISTIC_KEY"
  check_secret_differs LAGO_ENCRYPTION_KEY_DERIVATION_SALT "$SAMPLE_ENCRYPTION_KEY_DERIVATION_SALT"
  check_secret_differs LAGO_RSA_PRIVATE_KEY ""
}

random_secret() {
  python3 -c "import secrets; print(secrets.token_urlsafe($1))"
}

random_hex_secret() {
  python3 -c "import secrets; print(secrets.token_hex($1))"
}

cmd_init() {
  if [[ -e "$ENV_FILE" ]]; then
    die "refusing to overwrite existing $ENV_FILE (delete it first to regenerate)"
  fi
  local api_port=48889 front_port=48890 rsa_key
  rsa_key="$(openssl genrsa 2048 2>/dev/null | openssl base64 -A)"
  [[ -n "$rsa_key" ]] || die "openssl failed to generate the Lago RSA private key"

  umask 077
  {
    echo "# Generated by lago.sh init -- local secrets, never commit."
    echo "COMPOSE_PROJECT_NAME=weknora-lago"
    echo "LAGO_API_PORT=${api_port}"
    echo "LAGO_FRONT_PORT=${front_port}"
    echo "LAGO_API_URL=http://127.0.0.1:${api_port}"
    echo "LAGO_FRONT_URL=http://127.0.0.1:${front_port}"
    echo "POSTGRES_PASSWORD=$(random_secret 24)"
    echo "SECRET_KEY_BASE=$(random_hex_secret 32)"
    echo "LAGO_ENCRYPTION_PRIMARY_KEY=$(random_secret 32)"
    echo "LAGO_ENCRYPTION_DETERMINISTIC_KEY=$(random_secret 32)"
    echo "LAGO_ENCRYPTION_KEY_DERIVATION_SALT=$(random_secret 16)"
    echo "LAGO_RSA_PRIVATE_KEY=\"${rsa_key}\""
  } > "$ENV_FILE"
  echo "wrote $ENV_FILE (mode 600) -- secrets are local-only"
}

cmd_up() {
  check_secrets
  check_port_url_consistency
  compose up -d --wait
}

cmd_down() {
  ensure_env
  compose down
}

cmd_status() {
  ensure_env
  local port
  port="$(env_value LAGO_API_PORT)"
  [[ -n "$port" ]] && export LAGO_API_PORT="$port"
  if [[ $# -eq 0 ]]; then
    set -- --json
  fi
  exec python3 "$LAGO_DIR/health.py" "$@"
}

cmd_config() {
  check_secrets
  python3 - "$ENV_FILE" "$LAGO_DIR" <<'PY'
import subprocess
import sys
from pathlib import Path

env_file, lago_dir = sys.argv[1], sys.argv[2]
result = subprocess.run(
    ["docker", "compose", "config"],
    cwd=lago_dir,
    check=True,
    capture_output=True,
    text=True,
)
sys.stderr.write(result.stderr)

text = result.stdout
for line in Path(env_file).read_text(encoding="utf-8").splitlines():
    line = line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    key, _, value = line.partition("=")
    value = value.strip().strip('"')
    if not value:
        continue
    if any(marker in key for marker in ("PASSWORD", "SECRET", "KEY", "SALT", "TOKEN")):
        text = text.replace(value, "***REDACTED***")
sys.stdout.write(text)
PY
}

cmd_contract_probe() {
  ensure_env
  local port
  port="$(env_value LAGO_API_PORT)"
  [[ -n "$port" ]] && export LAGO_API_PORT="$port"
  # The API key is operator input: only inherited from the caller
  # environment, never read from .env, logged, or written to reports.
  exec python3 "$LAGO_DIR/contract_probe.py" "$@"
}

# --- #104 [Lago 32]: backup / restore -----------------------------------
# A backup is three artifacts under one directory (gitignored):
#   lago.dump    pg_dump custom format -- the billing authority
#   storage.tar  the object-storage volume (generated PDFs, CSV exports)
#   redis.rdb    an RDB snapshot of the pending-work (Sidekiq) state
# RPO is a method property, not a command property: locally it is the
# backup cadence the operator chooses; the production design (WAL
# archiving, RPO <= 5 min) is documented in
# docs/upstream-parity/lago-production-observability.md.

# The RDB for this stack is tiny, so BGSAVE can finish before the first
# poll -- baseline LASTSAVE is taken BEFORE issuing BGSAVE.
wait_redis_bgsave() {
  local before="$1" now i
  for i in $(seq 1 40); do
    now="$(compose exec -T redis redis-cli -p "${REDIS_PORT:-6379}" LASTSAVE | tr -d '\r')"
    [[ "$now" != "$before" ]] && return 0
    sleep 0.5
  done
  die "redis BGSAVE did not finish within 20s"
}

cmd_backup() {
  check_secrets
  local out="${1:-$LAGO_DIR/backups/$(date -u +%Y%m%dT%H%M%SZ)}"
  [[ -e "$out" ]] && die "backup target $out already exists"
  mkdir -p "$out" && chmod 700 "$out"
  local lastsave
  lastsave="$(compose exec -T redis redis-cli -p "${REDIS_PORT:-6379}" LASTSAVE | tr -d '\r')"
  compose exec -T db pg_dump -U "${POSTGRES_USER:-lago}" -d "${POSTGRES_DB:-lago}" -Fc > "$out/lago.dump"
  compose exec -T redis redis-cli -p "${REDIS_PORT:-6379}" BGSAVE > /dev/null
  wait_redis_bgsave "$lastsave"
  compose run --rm --no-deps --entrypoint tar -v "$out":/backup api -cf /backup/storage.tar -C /app/storage .
  compose run --rm --no-deps --entrypoint sh -v "$out":/backup redis -c 'cp /data/dump.rdb /backup/redis.rdb'
  printf '{"created_at":"%s","release":"v1.53.0","contents":["lago.dump","storage.tar","redis.rdb"]}\n' \
    "$(date -u +%FT%TZ)" > "$out/backup.json"
  echo "backup written to $out"
}

# restore DESTROYS the current stack data (down -v) and reinstates a
# backup taken by cmd_backup. This is the #104 recovery path: the RTO drill
# (deploy/lago/restore_drill.py) times exactly this command.
cmd_restore() {
  check_secrets
  local src="${1:-}"
  [[ -n "$src" ]] || die "usage: lago.sh restore <backup-dir>"
  [[ -f "$src/lago.dump" ]] || die "$src/lago.dump missing -- not a lago.sh backup"
  echo "lago.sh: restore will DESTROY the current stack data and reinstate $src"
  sleep 3
  compose down -v
  compose up -d db --wait
  compose exec -T db pg_restore -U "${POSTGRES_USER:-lago}" -d "${POSTGRES_DB:-lago}" --no-owner < "$src/lago.dump"
  compose run --rm --no-deps --entrypoint tar -v "$src":/backup api -xf /backup/storage.tar -C /app/storage
  if [[ -f "$src/redis.rdb" ]]; then
    compose run --rm --no-deps --entrypoint sh -v "$src":/backup redis -c 'cp /backup/redis.rdb /data/dump.rdb'
  fi
  compose up -d --wait
  echo "lago.sh: restore complete -- stack reports healthy"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-}" in
    init) shift; cmd_init "$@" ;;
    up) shift; cmd_up "$@" ;;
    down) shift; cmd_down "$@" ;;
    status) shift; cmd_status "$@" ;;
    config) shift; cmd_config "$@" ;;
    contract-probe) shift; cmd_contract_probe "$@" ;;
    backup) shift; cmd_backup "$@" ;;
    restore) shift; cmd_restore "$@" ;;
    -h|--help|help) usage ;;
    *) usage ;;
  esac
fi
