#!/usr/bin/env bash
# Operator lifecycle for the pinned local Lago Community v1.53.0 stack.
#
# Usage: ./deploy/lago/lago.sh init|up|down|status|config|contract-probe
#
#   init           generate deploy/lago/.env with random secrets (mode 600)
#   up             validate secrets, then docker compose up -d --wait
#   down           stop the stack (named data volumes are preserved)
#   status         print the Task 1 health snapshot JSON
#   config         print the resolved Compose config with secrets redacted
#   contract-probe reserved for Task 3

set -euo pipefail

LAGO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$LAGO_DIR/.env"

# Official Lago sample defaults that generated secrets must never equal.
readonly SAMPLE_POSTGRES_PASSWORD="changeme"
readonly SAMPLE_SECRET_KEY_BASE="your-secret-key-base-hex-64"
readonly SAMPLE_ENCRYPTION_PRIMARY_KEY="your-encryption-primary-key"
readonly SAMPLE_ENCRYPTION_DETERMINISTIC_KEY="your-encryption-deterministic-key"
readonly SAMPLE_ENCRYPTION_KEY_DERIVATION_SALT="your-encryption-derivation-salt"

die() {
  echo "lago.sh: $*" >&2
  exit 1
}

usage() {
  sed -n '2,11p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 2
}

compose() {
  (cd "$LAGO_DIR" && docker compose "$@")
}

env_value() {
  local key="$1" file="${2:-$ENV_FILE}" line
  line="$(grep -E "^${key}=" "$file" | tail -n 1 || true)"
  line="${line#*=}"
  line="${line#\"}"
  printf '%s' "${line%\"}"
}

check_port_url_consistency() {
  # The frontend's browser-side API URL is baked from the ports at init time;
  # reject an .env where a port was changed without updating its URL.
  local env_file="${1:-$ENV_FILE}"
  local name port url url_port
  for name in LAGO_API LAGO_FRONT; do
    port="$(env_value "${name}_PORT" "$env_file")"
    url="$(env_value "${name}_URL" "$env_file")"
    [[ -n "$port" && -n "$url" ]] || continue
    url_port="${url##*:}"
    if [[ "$url_port" != "$port" ]]; then
      die "${name}_URL '${url}' does not point at the configured ${name}_PORT '${port}' -- fix .env or delete it and re-run ./deploy/lago/lago.sh init"
    fi
  done
}

ensure_env() {
  [[ -f "$ENV_FILE" ]] || die "missing $ENV_FILE -- run ./deploy/lago/lago.sh init first"
}

check_secret_differs() {
  local key="$1" sample="$2" value
  value="$(env_value "$key")"
  [[ -n "$value" ]] || die "$key is empty -- run ./deploy/lago/lago.sh init"
  [[ "$value" != "$sample" ]] || die "$key still equals the official Lago sample default -- run ./deploy/lago/lago.sh init"
}

check_secrets() {
  ensure_env
  check_secret_differs POSTGRES_PASSWORD "$SAMPLE_POSTGRES_PASSWORD"
  check_secret_differs SECRET_KEY_BASE "$SAMPLE_SECRET_KEY_BASE"
  check_secret_differs LAGO_ENCRYPTION_PRIMARY_KEY "$SAMPLE_ENCRYPTION_PRIMARY_KEY"
  check_secret_differs LAGO_ENCRYPTION_DETERMINISTIC_KEY "$SAMPLE_ENCRYPTION_DETERMINISTIC_KEY"
  check_secret_differs LAGO_ENCRYPTION_KEY_DERIVATION_SALT "$SAMPLE_ENCRYPTION_KEY_DERIVATION_SALT"
  check_secret_differs LAGO_RSA_PRIVATE_KEY ""
}

random_secret() {
  python3 -c "import secrets; print(secrets.token_urlsafe($1))"
}

random_hex_secret() {
  python3 -c "import secrets; print(secrets.token_hex($1))"
}

cmd_init() {
  if [[ -e "$ENV_FILE" ]]; then
    die "refusing to overwrite existing $ENV_FILE (delete it first to regenerate)"
  fi
  local api_port=48889 front_port=48890 rsa_key
  rsa_key="$(openssl genrsa 2048 2>/dev/null | openssl base64 -A)"
  [[ -n "$rsa_key" ]] || die "openssl failed to generate the Lago RSA private key"

  umask 077
  {
    echo "# Generated by lago.sh init -- local secrets, never commit."
    echo "COMPOSE_PROJECT_NAME=weknora-lago"
    echo "LAGO_API_PORT=${api_port}"
    echo "LAGO_FRONT_PORT=${front_port}"
    echo "LAGO_API_URL=http://127.0.0.1:${api_port}"
    echo "LAGO_FRONT_URL=http://127.0.0.1:${front_port}"
    echo "POSTGRES_PASSWORD=$(random_secret 24)"
    echo "SECRET_KEY_BASE=$(random_hex_secret 32)"
    echo "LAGO_ENCRYPTION_PRIMARY_KEY=$(random_secret 32)"
    echo "LAGO_ENCRYPTION_DETERMINISTIC_KEY=$(random_secret 32)"
    echo "LAGO_ENCRYPTION_KEY_DERIVATION_SALT=$(random_secret 16)"
    echo "LAGO_RSA_PRIVATE_KEY=\"${rsa_key}\""
  } > "$ENV_FILE"
  echo "wrote $ENV_FILE (mode 600) -- secrets are local-only"
}

cmd_up() {
  check_secrets
  check_port_url_consistency
  compose up -d --wait
}

cmd_down() {
  ensure_env
  compose down
}

cmd_status() {
  ensure_env
  local port
  port="$(env_value LAGO_API_PORT)"
  [[ -n "$port" ]] && export LAGO_API_PORT="$port"
  if [[ $# -eq 0 ]]; then
    set -- --json
  fi
  exec python3 "$LAGO_DIR/health.py" "$@"
}

cmd_config() {
  check_secrets
  python3 - "$ENV_FILE" "$LAGO_DIR" <<'PY'
import subprocess
import sys
from pathlib import Path

env_file, lago_dir = sys.argv[1], sys.argv[2]
result = subprocess.run(
    ["docker", "compose", "config"],
    cwd=lago_dir,
    check=True,
    capture_output=True,
    text=True,
)
sys.stderr.write(result.stderr)

text = result.stdout
for line in Path(env_file).read_text(encoding="utf-8").splitlines():
    line = line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    key, _, value = line.partition("=")
    value = value.strip().strip('"')
    if not value:
        continue
    if any(marker in key for marker in ("PASSWORD", "SECRET", "KEY", "SALT", "TOKEN")):
        text = text.replace(value, "***REDACTED***")
sys.stdout.write(text)
PY
}

cmd_contract_probe() {
  echo "contract-probe: not implemented yet (arrives with Task 3)" >&2
  exit 1
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-}" in
    init) shift; cmd_init "$@" ;;
    up) shift; cmd_up "$@" ;;
    down) shift; cmd_down "$@" ;;
    status) shift; cmd_status "$@" ;;
    config) shift; cmd_config "$@" ;;
    contract-probe) shift; cmd_contract_probe "$@" ;;
    -h|--help|help) usage ;;
    *) usage ;;
  esac
fi
