# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from semantic_service.proto import semantic_pb2 as semantic__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in semantic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/weknora.semantic.v1.SemanticService/GetCapabilities',
                request_serializer=semantic__pb2.Empty.SerializeToString,
                response_deserializer=semantic__pb2.Capabilities.FromString,
                _registered_method=True)
        self.ApplyDocumentRevision = channel.unary_unary(
                '/weknora.semantic.v1.SemanticService/ApplyDocumentRevision',
                request_serializer=semantic__pb2.ApplyRequest.SerializeToString,
                response_deserializer=semantic__pb2.Operation.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/weknora.semantic.v1.SemanticService/DeleteDocument',
                request_serializer=semantic__pb2.DocumentRevision.SerializeToString,
                response_deserializer=semantic__pb2.Operation.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/weknora.semantic.v1.SemanticService/GetOperation',
                request_serializer=semantic__pb2.OperationRef.SerializeToString,
                response_deserializer=semantic__pb2.Operation.FromString,
                _registered_method=True)
        self.CancelOperation = channel.unary_unary(
                '/weknora.semantic.v1.SemanticService/CancelOperation',
                request_serializer=semantic__pb2.OperationRef.SerializeToString,
                response_deserializer=semantic__pb2.Operation.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/weknora.semantic.v1.SemanticService/Search',
                request_serializer=semantic__pb2.SearchRequest.SerializeToString,
                response_deserializer=semantic__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Reason = channel.unary_unary(
                '/weknora.semantic.v1.SemanticService/Reason',
                request_serializer=semantic__pb2.ReasonRequest.SerializeToString,
                response_deserializer=semantic__pb2.ReasonResponse.FromString,
                _registered_method=True)


class SemanticServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyDocumentRevision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reason(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=semantic__pb2.Empty.FromString,
                    response_serializer=semantic__pb2.Capabilities.SerializeToString,
            ),
            'ApplyDocumentRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyDocumentRevision,
                    request_deserializer=semantic__pb2.ApplyRequest.FromString,
                    response_serializer=semantic__pb2.Operation.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=semantic__pb2.DocumentRevision.FromString,
                    response_serializer=semantic__pb2.Operation.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=semantic__pb2.OperationRef.FromString,
                    response_serializer=semantic__pb2.Operation.SerializeToString,
            ),
            'CancelOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOperation,
                    request_deserializer=semantic__pb2.OperationRef.FromString,
                    response_serializer=semantic__pb2.Operation.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=semantic__pb2.SearchRequest.FromString,
                    response_serializer=semantic__pb2.SearchResponse.SerializeToString,
            ),
            'Reason': grpc.unary_unary_rpc_method_handler(
                    servicer.Reason,
                    request_deserializer=semantic__pb2.ReasonRequest.FromString,
                    response_serializer=semantic__pb2.ReasonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weknora.semantic.v1.SemanticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weknora.semantic.v1.SemanticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weknora.semantic.v1.SemanticService/GetCapabilities',
            semantic__pb2.Empty.SerializeToString,
            semantic__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyDocumentRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weknora.semantic.v1.SemanticService/ApplyDocumentRevision',
            semantic__pb2.ApplyRequest.SerializeToString,
            semantic__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weknora.semantic.v1.SemanticService/DeleteDocument',
            semantic__pb2.DocumentRevision.SerializeToString,
            semantic__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weknora.semantic.v1.SemanticService/GetOperation',
            semantic__pb2.OperationRef.SerializeToString,
            semantic__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weknora.semantic.v1.SemanticService/CancelOperation',
            semantic__pb2.OperationRef.SerializeToString,
            semantic__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weknora.semantic.v1.SemanticService/Search',
            semantic__pb2.SearchRequest.SerializeToString,
            semantic__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reason(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weknora.semantic.v1.SemanticService/Reason',
            semantic__pb2.ReasonRequest.SerializeToString,
            semantic__pb2.ReasonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
