// Package domain holds the Query History module's pure domain model: the
// workspace visibility policy, the async export job aggregate, and the export
// filter/payload value objects. Everything here depends only on the Go
// standard library — persistence behavior (driver.Valuer / sql.Scanner,
// TableName, JSON and GORM struct tags) rides along as plain methods and tag
// strings without importing any framework.
package domain

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"strings"
	"time"
)

// Mode is the workspace-level query-history visibility mode, stored on
// tenants.query_history_config and enforced at READ time on the query-history
// audit surfaces (the "source=all" admin listing, the admin snapshot, and the
// CSV export): what is recorded never changes — switching modes changes what
// audit reads return, not what was stored.
//
// It is deliberately a string alias rather than a defined type: the Wave 1
// legacy aliases in internal/types/query_history.go must keep every existing
// string-typed call site compiling unchanged. Wave 5 (legacy seam removal)
// may tighten it into a defined type.
type Mode = string

// Query history visibility modes (see Mode).
const (
	// Normal serves audit reads with full owner identities.
	Normal = "normal"
	// Anonymized serves audit reads with owner identities masked at read
	// time (user ids replaced by "anonymous", the list rows' IM principal id
	// dropped); stored rows keep their identities, so switching back to
	// normal restores them retroactively.
	Anonymized = "anonymized"
	// Disabled rejects audit reads with 403. Recording itself still writes,
	// so re-enabling serves everything that was recorded while the mode was
	// active.
	Disabled = "disabled"
)

// ExportStatus is the lifecycle status of a query-history export job. A
// string alias for the same Wave 1 compatibility reason as Mode.
type ExportStatus = string

// Query history export job lifecycle statuses.
const (
	ExportPending = "pending"
	ExportRunning = "running"
	ExportDone    = "done"
	ExportFailed  = "failed"
)

// NormalizeMode returns the supported mode for the raw value, falling back
// to Normal for empty/unknown input so a corrupt row can never silently
// disable or de-identify workspace history.
func NormalizeMode(mode Mode) Mode {
	switch strings.TrimSpace(mode) {
	case Normal, Anonymized, Disabled:
		return strings.TrimSpace(mode)
	default:
		return Normal
	}
}

// Config is the workspace-level query history policy, stored in the
// tenants.query_history_config JSONB column. Nil means "not configured";
// callers normalizing a config they are about to enforce get Mode=normal.
type Config struct {
	// Mode is one of the mode constants. Empty or unrecognized values
	// normalize to Normal so a corrupt row can never silently disable or
	// de-identify workspace history.
	Mode Mode `json:"mode" yaml:"mode"`
}

// Normalize canonicalizes the config's Mode in place. The nil receiver is a
// no-op so a nil config stays "unconfigured" rather than gaining a default.
func (c *Config) Normalize() {
	if c == nil {
		return
	}
	c.Mode = NormalizeMode(c.Mode)
}

// Value implements the driver.Valuer interface, used to convert
// Config to database value.
func (c *Config) Value() (driver.Value, error) {
	if c == nil {
		return nil, nil
	}
	return json.Marshal(c)
}

// Scan implements the sql.Scanner interface, used to convert database value
// to Config.
func (c *Config) Scan(value interface{}) error {
	if value == nil {
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		return nil
	}
	return json.Unmarshal(b, c)
}

// ExportJob tracks one asynchronous query-history export. The worker claims
// pending jobs, streams the archive to FilePath, and leaves either done or
// failed with ErrorMessage set.
type ExportJob struct {
	// ID is generated by the database.
	ID uint64 `json:"id" gorm:"primaryKey;autoIncrement"`
	// TenantID scopes the export to one workspace.
	TenantID uint64 `json:"tenant_id" gorm:"index"`
	// RequestedBy is the principal that asked for the export.
	RequestedBy string `json:"requested_by" gorm:"type:varchar(512)"`
	// Status is one of the Export* lifecycle constants.
	Status ExportStatus `json:"status" gorm:"type:varchar(16);not null;default:'pending'"`
	// FilePath is where the finished archive lives; empty until it exists.
	FilePath string `json:"file_path" gorm:"type:varchar(512);not null;default:''"`
	// ErrorMessage explains a failed export; empty otherwise.
	ErrorMessage string    `json:"error_message" gorm:"type:text;not null;default:''"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// TableName pins the GORM table name.
func (ExportJob) TableName() string { return "query_history_export_jobs" }

// ExportRow is one aggregated per-session row of an async export CSV: the
// session header fields plus its message and like/dislike tallies. Source
// reuses the audit listing's origin classification (IM platform / embed /
// api / web).
type ExportRow struct {
	SessionID    string    `json:"session_id"    gorm:"column:session_id"`
	Title        string    `json:"title"         gorm:"column:title"`
	UserID       string    `json:"user_id"       gorm:"column:user_id"`
	Source       string    `json:"source"        gorm:"column:source"`
	EngineType   string    `json:"engine_type"   gorm:"column:engine_type"`
	CreatedAt    time.Time `json:"created_at"    gorm:"column:created_at"`
	UpdatedAt    time.Time `json:"updated_at"    gorm:"column:updated_at"`
	MessageCount int64     `json:"message_count" gorm:"column:message_count"`
	LikeCount    int64     `json:"like_count"    gorm:"column:like_count"`
	DislikeCount int64     `json:"dislike_count" gorm:"column:dislike_count"`
}

// ExportFilter narrows an export to the audit window the admin saw when
// requesting it. It mirrors the subset of the audit listing's query that the
// export flow honors: the export always spans the Admin+ source=all view
// with no keyword, agent, or paging, so only these fields ride along.
//
// StartTime / EndTime bound created_at as a half-open range
// [StartTime, EndTime); zero values leave that side of the range open.
// FeedbackRating, when "like" or "dislike", keeps only sessions carrying a
// matching feedback row; empty means no feedback filter. UserID empty means
// the whole tenant.
type ExportFilter struct {
	UserID         string
	StartTime      time.Time
	EndTime        time.Time
	FeedbackRating string
}

// ErrPermanentPayload marks an export-task payload that can never succeed on
// retry (malformed JSON, or missing job/tenant scope). The application worker
// answers it — wrapped, so context travels along — without touching a job;
// the module's queue adapter translates it into the task framework's
// skip-retry signal, keeping the application layer framework-independent.
var ErrPermanentPayload = errors.New("query history export: payload is not retryable")

// ExportPayload carries one async query-history CSV export across the task
// queue. The JSON keys, their order, and the omitempty behavior are
// byte-identical to the legacy types.QueryHistoryExportPayload (whose
// embedded TracingContext serialized to the same flat "lf_" fields) so
// payloads enqueued before the module migration keep parsing.
//
// Timestamps travel as unix milliseconds because time.Time cannot round-trip
// its zero value through JSON (a zero "0001-01-01" would masquerade as a
// real lower bound).
type ExportPayload struct {
	// Langfuse fields mirror types.TracingContext (the domain cannot embed
	// the legacy type); the queue adapter injects them at enqueue time.
	LangfuseTraceID             string `json:"lf_trace_id,omitempty"`
	LangfuseParentObservationID string `json:"lf_parent_obs_id,omitempty"`
	LangfuseTraceparent         string `json:"lf_traceparent,omitempty"`
	LangfuseUserID              string `json:"lf_user_id,omitempty"`
	LangfuseSessionID           string `json:"lf_session_id,omitempty"`

	JobID    uint64 `json:"job_id"`
	TenantID uint64 `json:"tenant_id"`
	// RequestedBy is the principal that asked for the export (audit trail on
	// the job row; the payload copy keeps worker logs self-describing).
	RequestedBy string `json:"requested_by,omitempty"`
	// UserID narrows the export to one principal; empty means the whole
	// tenant.
	UserID string `json:"user_id,omitempty"`
	// StartTimeMs / EndTimeMs bound created_at as [start, end); 0 leaves the
	// corresponding side open.
	StartTimeMs int64 `json:"start_time_ms,omitempty"`
	EndTimeMs   int64 `json:"end_time_ms,omitempty"`
	// FeedbackRating, when "like" or "dislike", keeps only sessions carrying
	// a matching feedback row; empty means no feedback filter.
	FeedbackRating string `json:"feedback_rating,omitempty"`
}
