// AUTO-PORTED from frontend/src/i18n/locales/*.ts top-level menu block
import type { Locale } from './index.ts';

export const menuMessages: Record<Locale, Record<string, string>> = {
  "zh-CN": {"menu.sessionInProgress":"会话进行中","menu.knowledgeBase":"知识库","menu.agents":"智能体","menu.organizations":"共享空间","menu.analytics":"数据分析","menu.newChat":"新对话","menu.settings":"系统设置","menu.logout":"退出登录","menu.clearMessages":"清空消息","menu.clearMessagesSuccess":"消息已清空","menu.clearMessagesFailed":"清空消息失败，请稍后再试","menu.renameSession":"修改标题","menu.renameSessionSuccess":"标题已更新","menu.renameSessionFailed":"修改标题失败，请稍后再试","menu.batchManage":"批量管理","menu.newSession":"新会话","menu.pin":"置顶","menu.unpin":"取消置顶","menu.pinFailed":"置顶失败，请稍后再试","menu.unpinFailed":"取消置顶失败，请稍后再试","menu.search":"搜索","menu.collapseSidebar":"收起侧边栏","menu.expandSidebar":"展开侧边栏","menu.logoutSuccess":"已退出登录","menu.myChats":"我的对话","menu.apiChats":"API 会话","menu.noSessions":"暂无对话",
  },
  "en-US": {"menu.sessionInProgress":"Conversation in progress","menu.knowledgeBase":"Knowledge Base","menu.agents":"Agents","menu.organizations":"Shared Spaces","menu.analytics":"Analytics","menu.newChat":"New Chat","menu.settings":"System Settings","menu.logout":"Logout","menu.clearMessages":"Clear Messages","menu.clearMessagesSuccess":"Messages cleared","menu.clearMessagesFailed":"Failed to clear messages, please try again later","menu.renameSession":"Rename","menu.renameSessionSuccess":"Title updated","menu.renameSessionFailed":"Failed to update title, please try again later","menu.batchManage":"Batch Manage","menu.newSession":"New Chat","menu.pin":"Pin","menu.unpin":"Unpin","menu.pinFailed":"Failed to pin, please try again later","menu.unpinFailed":"Failed to unpin, please try again later","menu.search":"Search","menu.collapseSidebar":"Collapse Sidebar","menu.expandSidebar":"Expand Sidebar","menu.logoutSuccess":"Logged out successfully","menu.myChats":"My chats","menu.apiChats":"API sessions","menu.noSessions":"No conversations yet",
  },
  "ja-JP": {"menu.sessionInProgress":"会話中","menu.knowledgeBase":"ナレッジベース","menu.agents":"エージェント","menu.organizations":"共有スペース","menu.analytics":"データ分析","menu.newChat":"新しいチャット","menu.settings":"システム設定","menu.logout":"ログアウト","menu.clearMessages":"メッセージをクリア","menu.clearMessagesSuccess":"メッセージをクリアしました","menu.clearMessagesFailed":"メッセージのクリアに失敗しました。しばらくしてから再試行してください","menu.renameSession":"タイトルを変更","menu.renameSessionSuccess":"タイトルを更新しました","menu.renameSessionFailed":"タイトルの更新に失敗しました。しばらくしてから再試行してください","menu.batchManage":"一括管理","menu.newSession":"新しいチャット","menu.pin":"ピン留め","menu.unpin":"ピン留めを解除","menu.pinFailed":"ピン留めに失敗しました。しばらくしてから再試行してください","menu.unpinFailed":"ピン留めの解除に失敗しました。しばらくしてから再試行してください","menu.search":"検索","menu.collapseSidebar":"サイドバーを折りたたむ","menu.expandSidebar":"サイドバーを展開","menu.logoutSuccess":"ログアウトしました","menu.myChats":"マイチャット","menu.apiChats":"APIセッション","menu.noSessions":"会話はまだありません",
  },
  "ko-KR": {"menu.sessionInProgress":"대화 진행 중","menu.knowledgeBase":"지식베이스","menu.agents":"에이전트","menu.organizations":"공유 공간","menu.analytics":"데이터 분석","menu.newChat":"새 대화","menu.settings":"시스템 설정","menu.logout":"로그아웃","menu.clearMessages":"메시지 지우기","menu.clearMessagesSuccess":"메시지가 지워졌습니다","menu.clearMessagesFailed":"메시지 지우기 실패, 나중에 다시 시도해 주세요","menu.renameSession":"제목 수정","menu.renameSessionSuccess":"제목이 업데이트되었습니다","menu.renameSessionFailed":"제목 수정 실패, 나중에 다시 시도해 주세요","menu.batchManage":"일괄 관리","menu.newSession":"새 세션","menu.pin":"고정","menu.unpin":"고정 해제","menu.pinFailed":"고정 실패, 나중에 다시 시도해 주세요","menu.unpinFailed":"고정 해제 실패, 나중에 다시 시도해 주세요","menu.search":"검색","menu.collapseSidebar":"사이드바 접기","menu.expandSidebar":"사이드바 펼치기","menu.logoutSuccess":"로그아웃되었습니다","menu.myChats":"내 대화","menu.apiChats":"API 세션","menu.noSessions":"대화가 없습니다",
  },
  "ru-RU": {"menu.sessionInProgress":"Диалог выполняется","menu.knowledgeBase":"База знаний","menu.agents":"Агенты","menu.organizations":"Общие пространства","menu.analytics":"Аналитика","menu.newChat":"Новый диалог","menu.settings":"Настройки системы","menu.logout":"Выход","menu.clearMessages":"Очистить сообщения","menu.clearMessagesSuccess":"Сообщения очищены","menu.clearMessagesFailed":"Не удалось очистить сообщения, попробуйте позже","menu.renameSession":"Переименовать","menu.renameSessionSuccess":"Название обновлено","menu.renameSessionFailed":"Не удалось обновить название, попробуйте позже","menu.batchManage":"Пакетное управление","menu.newSession":"Новый диалог","menu.pin":"Закрепить","menu.unpin":"Открепить","menu.pinFailed":"Не удалось закрепить, попробуйте позже","menu.unpinFailed":"Не удалось открепить, попробуйте позже","menu.search":"Поиск","menu.collapseSidebar":"Свернуть боковую панель","menu.expandSidebar":"Развернуть боковую панель","menu.logoutSuccess":"Вы вышли из системы","menu.myChats":"Мои чаты","menu.apiChats":"Сессии API","menu.noSessions":"Пока нет диалогов",
  },
};
