package router

import (
	"github.com/Tencent/WeKnora/internal/career"
	"github.com/gin-gonic/gin"
)

func RegisterCareerRoutes(r *gin.RouterGroup, h *career.Handler) {
	if h == nil {
		return
	}
	g := r.Group("/career")
	g.GET("/open", h.Open)
	g.GET("/list", h.List)
	g.GET("/changes", h.Changes)
	g.GET("/receipt", h.Receipt)
	g.GET("/sources", h.Sources)
	g.POST("/sources/upload", h.Upload)
	g.POST("/act", h.Act)
	g.POST("/opportunities/import", h.ImportJD)
	g.POST("/opportunities/import-url", h.ImportURL)
	g.GET("/opportunities/receipt", h.OpportunityReceipt)
	g.GET("/opportunities/:opportunityId", h.OpportunityEvidence)
	g.GET("/opportunities/:opportunityId/observations", h.OpportunityObservations)
	g.GET("/opportunities/:opportunityId/status", h.OpportunityStatus)
	g.GET("/opportunities/:opportunityId/reconciliations", h.OpportunityReconciliationsHandler)
	g.POST("/opportunities/reconcile", h.ReconcileOpportunities)
	g.GET("/reconciliations/receipt", h.ReconciliationReceipt)
	g.GET("/coverage", h.SourceCoverage)
	g.POST("/evaluations", h.EvaluateOpportunity)
	g.GET("/evaluations/receipt", h.EvaluationReceipt)
	g.GET("/evaluations/:evaluationId", h.Evaluation)
	g.POST("/applications", h.CreateApplication)
	g.GET("/applications/receipt", h.ApplicationReceipt)
	g.GET("/applications/:applicationId", h.GetApplication)
	g.POST("/applications/link/reconcile", h.ReconcileApplicationLink)
	g.POST("/searches", h.SearchOnce)
	g.GET("/searches/receipt", h.SearchReceipt)
	g.GET("/searches/:searchId", h.GetSearch)
	g.GET("/usage/estimate", h.UsageEstimate)
	g.POST("/rules", h.SetRule)
	g.GET("/rules", h.ListRules)
	g.GET("/rules/receipt", h.RuleReceipt)
	g.GET("/rules/:ruleId", h.GetRule)
	g.POST("/materials", h.EditMaterial)
	g.POST("/materials/confirm", h.ConfirmMaterialBody)
	g.GET("/materials/receipt", h.MaterialReceiptHandler)
	g.GET("/materials/:materialId", h.GetMaterial)
	g.GET("/materials/:materialId/versions", h.ListMaterialVersions)
	g.GET("/materials/:materialId/versions/:versionId", h.GetMaterialVersion)
	g.GET("/materials/:materialId/versions/:versionId/compare", h.CompareMaterialVersions)
	g.POST("/materials/:materialId/exports", h.PublishMaterialHandler)
	g.GET("/materials/:materialId/exports", h.ListMaterialExports)
	g.POST("/materials/:materialId/exports/:exportId/signed-url", h.MaterialExportSignedURL)
	g.GET("/materials/:materialId/exports/:exportId/download", h.DownloadMaterialExport)
	g.DELETE("/materials/:materialId/exports/:exportId", h.RevokeMaterialExport)
	g.POST("/applications/:applicationId/progress", h.AppendProgress)
	g.POST("/applications/:applicationId/progress/correct", h.CorrectProgress)
	g.GET("/applications/:applicationId/progress", h.ApplicationProgress)
	g.GET("/progress/receipt", h.ProgressReceiptHandler)
	g.POST("/applications/:applicationId/submissions", h.RecordSubmission)
	g.GET("/applications/:applicationId/submissions", h.ApplicationSubmissions)
	g.GET("/submissions/receipt", h.SubmissionReceiptHandler)
	g.POST("/applications/:applicationId/preparations", h.GeneratePreparationHandler)
	g.GET("/applications/:applicationId/preparations", h.ApplicationPreparations)
	g.GET("/preparations/receipt", h.PreparationReceiptHandler)
	g.POST("/reminders", h.SetReminderHandler)
	g.GET("/reminders", h.ListRemindersHandler)
	g.GET("/reminders/receipt", h.ReminderReceiptHandler)
	g.POST("/exports", h.ExportCareerHandler)
	g.GET("/exports/receipt", h.ExportCareerReceiptHandler)
	g.GET("/deletions/boundary", h.CareerDeletionBoundaryHandler)
	g.POST("/deletions", h.DeleteCareerHandler)
	g.GET("/deletions/receipt", h.CareerDeletionReceiptHandler)
}
